### ISSUE TITLE
Add msg_id to pylint output

### ISSUE THREAD

**Issue by benbarbour** [scrooloose/syntastic#1002]
Currently syntastic puts the human readable name only in the output, like this:

`path/to/file.py|12 col 10| [no-member] Module 'my.module' has no 'M' member`

That's fine and all, but what if I need to ignore that error inline with a `pylint: disable=???` message? Right now I have to google the [no-member] thing to look up what _???_ should be. I'd love to add the error code back in there somewhere.

I short, I'd like to change (or be able to customize) the msg-template argument to pylint from `--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"` to something like `--msg-template="{path}:{line}:{column}:{C}: {msg_id}[{symbol}] {msg}"`

**Comment by pitchforks** [comment]
> Then put the format spec in post_args:
> let g:syntastic_python_pylint_post_args = '--msg-template="{path}:{line}:{column}:{C}: {msg_id}[{symbol}] {msg}"'

@lcd047 please, please put this into the documentation file. I have wasted a few hours reading the docs of pylint, syntastic and digging syntastic issues on github till I found this one.

**Comment by lcd047** [comment]
@pitchforks Sure, [done](https://github.com/scrooloose/syntastic/wiki/Python%3A---pylint).
