### ISSUE TITLE
Add option to disable syntastic in general (for all filetypes) by default

### ISSUE THREAD

**Issue by blueyed** [scrooloose/syntastic#101]
I think that it can be useful to disable syntastic by default, and enable it when you want to use it (via `SyntasticEnable`).

Currently you can only disable it using `g:syntastic_disabled_filetypes`, which expects a list of filetypes to exclude.

I see two options:
1. allow "*" (for "all") in the list of filetypes to disable (and remove it once one of them gets enabled)
2. add a new option to disable syntastic altogether (and which `SyntasticEnable` would toggle).

**Comment by taromero** [comment]
Putting the following in my `.vimrc` worked for me (as a workaround):

`autocmd VimEnter * SyntasticToggleMode " disable syntastic by default`

It runs `:SyntasticToggleMode` when opening Vim.

**Comment by lcd047** [comment]
@taromero I strongly recommend you to invest a few minutes in reading the manual.

**Comment by taromero** [comment]
@lcd047 why would that be?

**Comment by LandonSchropp** [comment]
:+1: I'd love an easy way to disable Syntastic if Neomake is installed.

**Comment by lcd047** [comment]
@LandonSchropp As I said above: if you switch to passive mode, the files are not checked unless you explicitly request it:
```vim
let g:syntastic_mode_map = { 'mode': 'passive' }
```
How to detect Neomake is installed and / or active is a question for Neomake authors.

**Comment by andbar-ru** [comment]
`command ToggleSyntastic if !exists('g:syntastic_mode_map_bak') | let g:syntastic_mode_map_bak = g:syntastic_mode_map | let g:syntastic_mode_map = {'mode':'passive'} | else | let g:syntastic_mode_map = g:syntastic_mode_map_bak | unlet g:syntastic_mode_map_bak | endif`

`map <C-F7> :ToggleSyntastic<CR>`
`imap <C-F7> <C-o>:ToggleSyntastic<CR>`

**Comment by lcd047** [comment]
@andbar-ru This is exactly what `:SyntasticToggleMode` does.
