### ISSUE TITLE
Checker javascript/jshint returned abnormal status

### ISSUE THREAD

**Issue by weiying-chen** [scrooloose/syntastic#1029]
I have JSHint installed (I'm on Ubuntu):

alex@alex-K43U:~$ which jshint
/home/alex/nvm/v0.8.8/bin/jshint
'/home/alex/.vim/bundle/syntastic' 
And I'm pointing to it on my .vimrc:

" Syntastic
let g:syntastic_check_on_open=1
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_jshint_exec='/home/alex/nvm/v0.8.8/bin/jshint'
Vim seems to be detecting it:

Syntastic: active mode enabled
Syntastic info for filetype: javascript
Available checker(s): jshint
Currently enabled checker(s): jshint
But when I open a .js file I get stuff like this:

checker javascript/jshint returned abnormal status

Debug:

"~/www/coffeescript/js/script.js" 11L, 193C
syntastic: 8.443991: g:syntastic_version = '3.4.0'
syntastic: 8.455821: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shellt
emp = 1, &shellxquote = ''
syntastic: 8.508374: g:syntastic_aggregate_errors = 0
syntastic: 8.528577: getcwd() = /home/alex
syntastic: 8.567175: CacheErrors: Invoking checker: javascript/jshint
syntastic: 8.625888: SyntasticMake: called with options: {'errorformat': '%E%f: line %l\, col %v\, %m', 'defaults': {'bufnr': 1}, 'makeprg': '/home/alex/nvm/v0
.8.8/bin/jshint --config ~/.jshintrc /home/alex/www/coffeescript/js/script.js', 'returns': [0, 2]}
syntastic: 8.688247: checker output: ['/usr/bin/env: node: No such file or directory', '']
syntastic: 8.707693: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/usr/bin/env: node: N
o such file or directory'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]

My $PATH:

alex@alex-K43U:~$ echo $PATH
/home/alex/sbt/bin:/home/alex/.pythonbrew/bin:/home/alex/nvm/v0.8.8/bin:/home/alex/.rvm/gems/ruby-2.0.0-p247@railstutorial_rails_4_0/bin:/home/alex/.rvm/gems/ruby-2.0.0-p247@global/bin:/home/alex/.rvm/rubies/ruby-2.0.0-p247/bin:/home/alex/.rvm/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/alex/play20/:/home/alex/grails-2.1.2/bin/:/home/alex/.rvm/bin

What could be the problem?

**Comment by AdamBrodzinski** [comment]
FWIW, I was getting this error when I had a trailing comma in my .jshintrc located in the project root.

**Comment by kosz** [comment]
@AdamBrodzinski thanks, your message solved my problem :) . This message does appear on trailing commas in .jshintrc

**Comment by tthew** [comment]
@AD7six @kosz can confirm this was also the case for me.

**Comment by ryneeverett** [comment]
This error seems to result from *any* syntax error in `.jshintrc`.

**Comment by lcd047** [comment]
Guys, "checker X/Y returned abnormal status" means there is a problem outside syntastic, and checker "X/Y" has just hit it.  It's an abnormal condition, and it isn't syntastic's job to decide whether the problem is survivable or not.  Fix the cause (again, outside syntastic), and syntastic will be happy.

**Comment by bluemsn** [comment]
@lcd047  I got  `syntastic error`  too in my MacVim;
can you help me , how to fix it ?

the error msg is

"systastic:error :checker javascript/jscs returned abnormal status 1 " 

I don't know why ?

**Comment by lcd047** [comment]
@bluemsn Please open a new issue.  Explain what you did, what did you expect to happen, and what happened instead.  Open your test file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and include the output in your report.

**Comment by Jimones** [comment]
It’s a wonderful experience to learn Chinese here. I found their website www.hanbridgemandarin.com on Google. I wanted to have an audition of the course. So they gave me a lesson, one teacher for one student, based on your Chinese level, they will give you the specific lesson and practice.
