### ISSUE TITLE
[FIXED] Cpp inheritance bug with wxWidgets (YCM issue)

### ISSUE THREAD

**Issue by naumazeredo** [scrooloose/syntastic#1086]
I have a syntastic configured to compile C++ with wxWidgets (the same flags I use to compile with clang are passed to syntastic), but syntastic keeps giving me the error "base class has incomplete type" when I inherit the class wxFrame.
I compile fine with clang++ and g++ using the same flags I configured syntastic.

The important lines in my .vimrc are:
    let g:syntastic_cpp_include_dirs = ['/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0/', '/usr/include/wx-3.0/']
    let g:syntastic_cpp_remove_include_errors = 1
    let g:syntastic_cpp_compiler = 'clang++'
    let g:syntastic_cpp_compiler_options = '-std=c++11 -stdlib=libstdc++ `wx-config --cppflags` `wx-config --libs`'

Also, I have YouCompleteMe and will test to see if ycm is overriding syntastic.

**Comment by jpleau** [comment]
Sorry to necro this. I am having the same issue, and this page is the only relevant result I could find on Google.

How did you fix this problem? Using vim + YCM + syntastic, and copy/pasting the "tutorial" from this page: http://docs.wxwidgets.org/stable/overview_helloworld.html, I am also getting "base class has incomplete type" errors

Cheers

**Comment by lcd047** [comment]
@jpleau Assuming YCM didn't disable your syntastic, please set `g:syntastic_debug` to 3, run the checker, and post the output of `:mes`.

**Comment by jpleau** [comment]
@lcd047 Thanks for the answer, of course YCM was disabling syntastic, sorry for the noise. Using syntastic alone with the right CXXFLAGS and all works as expected

Cheers.

**Comment by jpleau** [comment]
For anyone coming here from Google, please make sure you have the fight CXXFLAGS set for this.

I was missing this one from wx-config --cxxflags: -D__WXGTK__

**Comment by lcd047** [comment]
For what it's worth: recent versions of syntastic tell you about that when you run `:SyntasticInfo`.
