### ISSUE TITLE
eslint validator not working 

### ISSUE THREAD

**Issue by fortes** [scrooloose/syntastic#1110]
I'm not a vim expert, so I don't quite know how to debug this issue. I've set the `g:syntastic_javascript_eslint_conf` property per the documentation, however there is still no validation happening.

If I install `jshint` everything works automatically without even changing configuration.

**Comment by tnguyen14** [comment]
I ran into this issue as well, where I have to set `g:syntastic_javascript_checkers = ['eslint']`. But how would it affect me to set this globally (in .vimrc) if some projects use eslint while others jshint?

**Comment by lcd047** [comment]
> I ran into this issue as well

It isn't an "issue", this is how syntastic is supposed to work: you have to tell it what checkers you want to run.

> But how would it affect me to set this globally (in .vimrc) if some projects use eslint while others jshint?

You'd use `autocmd`s to set the checkers for each of your projects.  Something like this:
```vim
autocmd BufNewFile,BufReadPre *.js   let b:syntastic_checkers = 
    \ expand('<amatch>') =~# '^/path/to/project1/' ? ['eslint'] :
    \ expand('<amatch>') =~# '^/path/to/project2/' ? ['jshint'] :
    \     ['standard']
```
Alternatively:
```vim
let g:syntastic_javascript_checkers = ['eslint']
autocmd BufNewFile,BufReadPre /path/to/project2/**/*.js  let b:syntastic_checkers = ['jshint']
```

**Comment by tnguyen14** [comment]
Thanks. Sorry I didn't mean to characterize it as an "issue", more like a question on how it's supposed to work.

The suggestion on using `autocmd` is interesting. However, it requires references to project paths in the .vimrc, which I don't think is maintainable. It will also not work for new projects. Is there any way to turn them on based on detection of the respective config file, i.e. `.eslintrc` and `.jshintrc`?

**Comment by lcd047** [comment]
This is a little more involved to implement correctly, but sure, it can be done:
```vim
function! HasConfig(file, dir)
    return findfile(a:file, escape(a:dir, ' ') . ';') !=# ''
endfunction

autocmd BufNewFile,BufReadPre *.js  let b:syntastic_checkers =
    \ HasConfig('.eslintrc', expand('<amatch>:h')) ? ['eslint'] :
    \ HasConfig('.jshintrc', expand('<amatch>:h')) ? ['jshint'] :
    \     ['standard']
```

**Comment by tnguyen14** [comment]
This is great. Thank you.

Just so I understand correctly, this will use `eslint` if `.eslintrc` exists, `jshint` if `.jshintrc` exists, and default to `standard`, is that correct?

**Comment by lcd047** [comment]
Correct.

**Comment by tnguyen14** [comment]
@lcd047 another question for you again.. this might be overly complicating things, but..

if I have a project that use both jshint and jscs, and the use of those should be triggered by `.jshintrc` and `.jscsrc`, could you update the script you had to append `jscs` as an addition checker?

**Comment by lcd047** [comment]
Yes, you can do that, the `? :` operator is associative.

**Comment by tnguyen14** [comment]
Ok thanks. So it would be something like this?

```
autocmd BufNewFile,BufReadPre *.js  let b:syntastic_checkers =
    \ HasConfig('.eslintrc', expand('<amatch>:h')) ? ['eslint'] :
    \ HasConfig('.jshintrc', expand('<amatch>:h')) ? ['jshint'] :
    \ HasConfig('.jscsrc', expand('<amatch>:h')) ? ['jscs'] :
```

Also, for the default checker, instead of `standard`, could I use something different, such as `happiness` https://github.com/JedWatson/happiness?

**Comment by lcd047** [comment]
> Ok thanks. So it would be something like this?

Have you tried it?  Did it work the way you expect?

> Also, for the default checker, instead of `standard`, could I use something different, such as `happiness` https://github.com/JedWatson/happiness?

If `hapiness` produces error messages in the same format as `standard` you can just point `g:syntastic_javascript_standard_exec` to it, and syntastic's checker `standard` will run the `hapiness` executable:
```vim
let g:syntastic_javascript_standard_exec = 'happiness'
```

**Comment by tnguyen14** [comment]
I did, but it's not really working. The `:SyntasticInfo` looks like this:

```
Syntastic version: 3.6.0-176 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: eslint jscs jshint
Currently enabled checker: jshint
```

Also for a folder that doesn't have either `.jshintrc` or `.jscsrc`, I get this (no standard)

```
Syntastic version: 3.6.0-176 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checker: eslint
Currently enabled checkers: -
```

**Comment by lcd047** [comment]
This would be an excellent time to get familiar with the manual.

**Comment by adamski** [comment]
I am also having this problem, after having used jshint previously.

My output is:
```
Syntastic version: 3.6.0-47 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
Available checkers: -
Currently enabled checkers: -
```

I have tried both a global `.eslintrc` and in the local folder.

**Comment by lcd047** [comment]
@adamski Do you have `eslint` installed?  Did you read the [first item](https://github.com/scrooloose/syntastic#faqinfo) in the FAQ?

**Comment by adamski** [comment]
Yes I’ve run `npm install -g eslint`

Also added the extra suggested lines to my `~/.vimrc`

Same output from `:SyntasticInfo javascript`

To be clear I’ve been using jshint with syntastic fine.

**Comment by lcd047** [comment]
> To be clear I’ve been using jshint with syntastic fine.

Well, the output of `:SyntasticInfo` above says `jshint` won't work now either.  Did you actually _read_ the section I pointed you to, about `$PATH`?

**Comment by adamski** [comment]
Thanks for the hint about $PATH. So to get it fully working I ended up adding 
```
let g:syntastic_javascript_eslint_exec = '<full/path/to>/bin/eslint'
```
I also did
```
ln -s ~/.zshrc ~/.zprofile
```
Which seemed to get it picking up other checkers - there seems to be an issue with zsh and vim $PATH being different from terminal.

**Comment by lcd047** [comment]
> there seems to be an issue with zsh and vim $PATH being different from terminal.

Yes, this is a [well known](https://github.com/scrooloose/syntastic/issues/1407#issuecomment-99174796) issue with zsh and Vim.
