### ISSUE TITLE
Matlab 'mlint' syntax checker not working

### ISSUE THREAD

**Issue by awelkie** [scrooloose/syntastic#1125]
When I open a matlab file and run SyntasticInfo, it correctly identifies the file as a matlab file, but there are no available checkers. I installed the mlint checker through Fedora's repos (syntastic-matlab), and mlint.vim seems to be installed in the right place. 

Looking in mlint.vim, I assume it's trying to call 'mlint', which is a MATLAB internal function, so I'm not even sure how the syntax checker expects to be able to call that function. Does it depend on another external executable named 'mlint'? Has anybody had success running this mlint syntax checker?

**Comment by asoplata** [comment]
I just wanted to say, it only worked for me when set to `g:syntastic_matlab_mlint_exec`, NOT `g:syntax_matlab_mlint_exec`. That got it working, and it's awesome, thanks!!!

**Comment by lcd047** [comment]
@asoplata Yeah, typos happen.  Thank you for the correction.
