### ISSUE TITLE
Python checking not working on saving ?

### ISSUE THREAD

**Issue by nishantvarma** [scrooloose/syntastic#1133]
All of a sudden my python files are not getting checked for errors . Did any of the recent updates change that feature for Python ? I can see JavaScript works as expected and :SyntasticCheck <linter> in a Python Buffer also works fine . I  made the let g:syntastic_check_on_wq = 1 forceful but still doesn't help . 
I currently fixed it by adding a  au BufWritePost *.py SyntasticCheck but let me know if you are aware of any possible cause of ways to troubleshoot this ?

**Comment by naught101** [comment]
Along the lines of what Simon suggested, I forgot that I only had flake8 installed in a conda env, and was getting confused when vim wasn't working. Re-activating that env made flake8 available again, and everything works.
