### ISSUE TITLE
False-positive error on variables defined in indirectly imported files

### ISSUE THREAD

**Issue by stansidel** [scrooloose/syntastic#1140]
In my project, SASS files are `@import`ed into a single `styles.scss` file. The file structure is like this:

```
/scss
|-styles/
  |-layout.scss
  |-welcome.scss
|-style.scss
|-variables.scss
```

`style.scss` file content:

```
# style.scss
@import "variables.scss";
@import "styles/layout.scss";
@import "styles/welcome.scss";
```

So all variables are declared in the `variables.scss` file and are used in other `styles/*.scss` files. Eg:

```
# variables.scss
$main-color: blue;
```

Those other files, in accordance, don't import the `variables.scss` file as this is already done in the main `style.scss` file. When I try to use any variable Syntastic reports an error 'Undefined variable', although the files compiles smoothly into a single css file. Eg:

```
# styles/layout.scss
body {
  color: $main-color; # <---- An error here 'Undefined variable'
}
```

Is it possible to avoid this error by other means than importing the `variables.scss` file into each `styles/*` file?

VIM Version: 7.4 (2013 Aug 10, compiled Nov 18 2013 23:18:36)
MacOS X (unix) version

SyntasticInfo output:

```
Syntastic: active mode enabled
Syntastic info for filetype: scss
Available checker(s): sass
Currently enabled checker(s): sass
```

**Comment by erichonkanen** [comment]
what was the solution to this? Im getting same issue

**Comment by lcd047** [comment]
@erichonkanen The solution is to do what I described above: see how syntastic calls `sass`, then set `g:syntastic_scss_sass_args` so that `sass` gets to see all your imports.  There is no "find my imports" switch in syntastic.

**Comment by erichonkanen** [comment]
@lcd047 when I type ":g:syntastic_debug" I get an error, how do I type that into the console?

**Comment by lcd047** [comment]
@erichonkanen `:let g:syntastic_debug = 1`

**Comment by erichonkanen** [comment]
@lcd047 ok I did that and then saved the file and I see some stuff for a split second then it just shows
```syntastic: 1961.381616: getLocList: checker scss/sass returned 65
syntastic: 1961.381807: getLocList: checker scss/sass run in 0.258697s```

what do I do from here? I tried `let g:syntastic_scss_sass_args` but it says `E121: Undefined variable: g:syntastic_scss_sass_args`

thanks!

**Comment by lcd047** [comment]
@erichonkanen Please read `:h syntastic-debug`.

**Comment by erichonkanen** [comment]
@lcd047 ok here is the output

```syntastic: 3207.520501: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape
= ''
syntastic: 3207.520786: UpdateErrors (auto): default checkers
syntastic: 3207.521009: CacheErrors: default checkers
syntastic: 3207.521517: g:syntastic_aggregate_errors = 0
syntastic: 3207.521682: getcwd() = '/Users/eric/Projects/toast/overlord/build/client-web'
syntastic: 3207.521973: CacheErrors: Invoking checker: scss/sass
syntastic: 3207.522435: SyntasticMake: called with options: {'postprocess': ['compressWhitespace'], 'errorformat': '%E%\m%\%%(Syntax %\)%\?%trror: %m,%+C              %.%#,%C        on line %l of %f\, %.%
#,%C        on line %l of %f,%-G %\+from line %.%#,%-G %\+Use --trace for backtrace.,%W%>DEPRECATION WARNING on line %l of %f:,%+C%>  %.%#,%W%>WARNING: on line %l of %f:,%+C%>  %.%#,%W%>WARNING on line %l
 of %f: %m,%+C%>  %.%#,%W%>WARNING on line %l of %f:,%Z%m,%W%>WARNING: %m,%C         on line %l of %f\, %.%#,%C         on line %l of %f,%-G %\+from line %.%#,Syntax %trror on line %l: %m,%-G%.%#', 'makep
rg': 'sass --cache-location /var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T//vim-syntastic-27113-lsrpsYi4 --compass --check app/styles/components/split-panel.scss'}
syntastic: 3207.794084: system: command run in 0.271330s
syntastic: 3207.796936: getLocList: checker scss/sass returned 65
syntastic: 3207.797127: getLocList: checker scss/sass run in 0.275071s```

**Comment by lcd047** [comment]
@erichonkanen Now read my first post above.

**Comment by erichonkanen** [comment]
@lcd047 sorry Im so newb, I see where it is calling `sass --cache-location /var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T//vim-syntastic-27113-lsrpsYi4 --compass --check app/styles/components/split-panel.scss'`

but how do I pass in another arg? is that what you're suggesting?

**Comment by lcd047** [comment]
@erichonkanen Like I said: you can add arguments to `g:syntastic_scss_sass_args`:
```vim
let g:syntastic_scss_sass_args = '--some --args'
```
You probably want to add this to your vimrc.

**Comment by erichonkanen** [comment]
I see, so I need to basically add an import arg to import the root sass file?
