### ISSUE TITLE
Rubocop not working

### ISSUE THREAD

**Issue by klautcomputing** [scrooloose/syntastic#1145]
I am trying to get rubocop to work:
SyntasticInfo:
Syntastic version: 3.4.0-109
Info for filetype: ruby
Mode: active
Filetype ruby is active
Available checkers: mri rubylint
Currently enabled checkers: mri rubylint

from my vimrc:
let g:syntastic_ruby_checkers = ['mri', 'rubocop', 'rubylint']
(I installed ruby-lint just to double check it's a rubocop issue)

I use RVM to install my gems and ruby-lint / rubocop are here:
/home/leex/.rvm/gems/ruby-head/bin/ruby-lint
/home/leex/.rvm/gems/ruby-head/bin/rubocop

rubocop works fine when executed from my shell
test.rb 2::1: C: 1 trailing blank lines detected.

some other info from syntastic
syntastic: 300.564263: g:syntastic_version = '3.4.0-109'
syntastic: 300.564573: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1
| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1,
 &shellxquote = '', &shellxescape = ''
syntastic: 300.564953: g:syntastic_aggregate_errors = 0
syntastic: 300.565220: getcwd() = /home/leex
syntastic: 300.565833: CacheErrors: Checker ruby/rubocop is not available
syntastic: warning: checker rubocop is not available

the syntax checker exists:
~/.vim/bundle/syntastic/syntax_checkers/ruby/rubocop.vim

my path: 
/home/leex/.rvm/gems/ruby-head/bin:/home/leex/.rvm/gems/ruby-head@global/bin:/home/leex/.rvm/rubies/ruby-head/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin:/home/leex/dotfiles/generated/scripts:/home/leex/.rvm/bin

rvm 1.25.26
rubocop 0.24.1
Syntastic: 3.4.0-109

So why does it work fine with rubylint but not with rubocop? ... No, idea yet :)

**Comment by skyksandr** [comment]
@klautcomputing Thanks a bunch for emphatic solution :)

**Comment by phantomwhale** [comment]
@skyksandr / others who come to this issue now - `bundle update robocop` should fix the root cause of the issue, now that ruby 2.2 is live and the parser gem + rubocop dependencies have been updated to match.

**Comment by johndkraft** [comment]
the patch has to go into a different file now.
~/.vim/bundle/syntastic/plugin/syntastic/checker.vim

-        let command = a:0 ? a:1 : self.getExecEscaped() . ' --version'
+        let command = a:0 ? a:1 : self.getExecEscaped() . ' --version 2>/dev/null'

**Comment by lcd047** [comment]
> the patch has to go into a different file now.

... which would then break all checkers that print their version to `stderr`, but would fix your use case...

**Comment by johndkraft** [comment]
First, I'm pretty sure that editing syntastic/plugin/syntastic/checker.vim will not impact any checker other than syntastic, unless they're somehow relying on files inside the syntastic/ repo... which I hope would be unsupported.

Second, I think that ideals are awesome, but in the real world sometimes I need to get work done. I've wasted enough time trying to have a ruby installation dedicated to running vim, which caused enough other problems with my development. The version managers do not play well with chefdk for one thing. I suppose I could 'bundle exec vim' but that hurts my soul.

Any time you run bundle, you risk bringing in a new version of parser. Unless you're dedicated to upgrading ruby at the same time, syntastic is then broken. I understand that there is some slim chance that the syntax changed, and I choose to accept that risk.

How about you guys realize that a lot of people appreciate your plugin and want to use it but are having real issues?

I suppose the right answer is to use something less insane than ruby to do development, but I don't have that option today.

**Comment by johndkraft** [comment]
Bah, I was wrong about the checker.vim -- it would break as you say. I'm just tired of ruby version hell and this is part of it.

**Comment by lcd047** [comment]
> I think that ideals are awesome, but in the real world sometimes I need to get work done.

For the same reason, I don't care about spending my time cleaning up somebody else's mess.  Sorry about that.  If `rbenv` and `rvm` don't work for you, you still have the option to use the wrapper script I mentioned in the wiki.
