### ISSUE TITLE
Reports "invalid syntax for "yield from" in python file

### ISSUE THREAD

**Issue by joristork** [scrooloose/syntastic#1148]
I get an invalid syntax warning (E901) for `yield from` (which is valid syntax since python 3.3). 

I've added `let g:syntastic_python_python_exec = 'python3'` to .vimrc, but still get the warnings.

**Comment by qzio** [comment]
I have This same issue.

lcd047 How do I check which checker is reporting the problem?

I've tried what joristork said
`let g:syntastic_python_python_exec = '/usr/bin/python3.4'`
but that doesn't seem to help

**Comment by lcd047** [comment]
> How do I check which checker is reporting the problem?

Unless you're running some plugin (such as powerline) that obliterates `w:quickfix_title`, the name of the checker that found the errors is shown on the status line of the error window:
![2015-03-14-174000_492x189](https://cloud.githubusercontent.com/assets/1281736/6654787/d699e47a-cae3-11e4-8c76-59cc9a2645c7.png)
If you're running powerline I suppose you're left with enabling debugging and trying to figure it out from there.  Of course, if you're really determined you could also spend a few minutes reading powerline manual and find out how to re-enable `w:quickfix_title`.  You could then add a note to syntastic's manual and send a PR. :)

**Comment by tobinvanpelt** [comment]
I had the same issues. I discovered in my case that I had not yet installed flake8 for python3.  I fixed it with `pip3 install flake8` and my E901 for `yield from` went away.
