### ISSUE TITLE
No available checkers for TCL

### ISSUE THREAD

**Issue by phanhaiquang** [scrooloose/syntastic#1181]
Hi,

Syntastic works fine with Perl, Ruby, Javascript but TCL.
I tried to enable TCL but it does not work.

I downloaded nagelfar at
http://sourceforge.net/projects/nagelfar/files/nagelfar1112.tar.gz/download
& put to /home/<<username>>/bin/nagelfar1112/nagelfar.tcl
It could work by command line. But it could not be called from VIM.

Below is result of :SyntasticInfo

Syntastic: active mode enabled
Syntastic info for filetype: tcl
Available checker(s):
Currently enabled checker(s):

With perl, it is

Syntastic: active mode enabled
Syntastic info for filetype: perl
Available checker(s): perl podchecker
Currently enabled checker(s): perl

**Comment by FisherDao** [comment]
Download nagelfar130 and add below line to .vimrc, but it's still not working.
let g:syntastic_tcl_nagelfar_exec = '/user/bin/my.git/vim.plugin/syntastic/tcl/nagelfar130/nagelfar.tcl'
![image](https://user-images.githubusercontent.com/52155822/60008720-767c4200-966c-11e9-9b45-fec948bd2a64.png)

**Comment by FisherDao** [comment]
Download nagelfar.linux; save to /user/bin/; add let g:syntastic_tcl_checkers = ['nagelfar.linux'] to .vimrc. Still not working.

**Comment by FisherDao** [comment]
Finally nagelfar is detected.
1. Download and save binary nagelfar.linux to your local $PATH. 
2. Add below lines to .vimrc
let g:syntastic_tcl_nagelfar_exec = '/user/bin/nagelfar.linux'
let g:syntastic_tcl_checkers = ['nagelfar'] 

![image](https://user-images.githubusercontent.com/52155822/60009988-c78d3580-966e-11e9-81fa-d819f3335ea8.png)

**Comment by lcd047** [comment]
@FisherDao Please avoid screenshots in your reports, as they can't be indexed for searching.

**Comment by FisherDao** [comment]
@lcd047 Thanks for the suggestion, but I think screenshots I added it's better for other user to understand the case.
