### ISSUE TITLE
reStructedText Check Error

### ISSUE THREAD

**Issue by DelightRun** [scrooloose/syntastic#1195]
I was editing [a .rst file in Hitchhiker's Guide to Python](https://github.com/kennethreitz/python-guide/blob/master/docs/starting/pip-virtualenv.rst)，and after I save the file, I got many error like `docs/starting/pip-virtualenv.rst|19 error| Unknown interpreted text role "file"`，so why this happened? and how should I fix it ?

**Comment by westurner** [comment]
> Sphinx too sits on top of docutils, it just adds a huge list of extensions to the standard rst syntax. I suppose the clean way to handle all this would be to add a null backend to Sphinx, that would just print any errors it finds and produce no output file. 

```
def filename_to_sphinxname(conf, filename):
      filename{.rest, .rst, .md, .markdown} -> sphinxname
```

* the verbose log file (from a complete ``sphinx-build`` run contains line numbers, but is not segmented by filename)

> It should be easy then to add a corresponding syntastic checker. I haven't looked at Sphinx sources, but I'd expect that could be done with an extension.

**Comment by lcd047** [comment]
@westurner Syntastic has a Sphinx checker now.
