### ISSUE TITLE
cannot enable scss-lint checker

### ISSUE THREAD

**Issue by fgarcia** [scrooloose/syntastic#1196]
I have been trying without success to enable scss-lint. These is how I have been trying:

```
let g:syntastic_scss_lint_exec='/opt/bin/my-scss-lint'
let g:syntastic_scss_scss_lint_exec='/opt/bin/my-scss-lint'
let g:syntastic_scss_checkers = ['scss_lint']
```

The `exec` variables are repeated because I was not sure which syntax was right. The custom binary was just a wrapper that wraps scss with `bundle exec` and also makes sure that syntastic has a stable binary path

After loading a scss file, verifying that the variables are set and running `:SyntasticInfo` i see the scss filetype was properly detected, but the list of available and enabled checkers is empty

**Comment by clindsey** [comment]
I also had a similar issue with `stylelint`, but it turned out I was using a pretty old version of `syntastic` (I have dropbox sync my `.vim/` folder) and the function `syntastic#util#getVersion` was missing.  A simple `cd ~/.vim/bundle/syntastic && git pull` fixed it

**Comment by rvodden** [comment]
I got this working by doing:

    let g:syntastic_scss_checkers = ['scss_lint']
    let g:syntastic_scss_scss_lint_exec = 'bundle'
    let g:syntastic_scss_scss_lint_args = 'exec scss-lint'
