### ISSUE TITLE
Support multiple filetypes in one file

### ISSUE THREAD

**Issue by rafi** [scrooloose/syntastic#1198]
Using [Shougo/context-filetype.vim](https://github.com/Shougo/context_filetype.vim) you can run `:echo context_filetype#get_filetype()` with the cursor on a line of html or javascript (just an example), and `:echo context_filetype#get_range()` for the line/column range information.

Would it be possible for checkers like `html.mustache` (or `html.handlers`) to send partial code to the exec's stdin? or let the user decide if a nested filetype (e.g. mustache) should be ignore/stripped and sent to checker's exec... ?

This would enable multiple syntax inspection on a single file.

**Comment by zanona** [comment]
I am not sure if that's fit within this same issue but I currently have enabled `eslint` for `javascript` files, however `eslint` has also a [plugin](https://www.npmjs.com/package/eslint-plugin-html) for analysing javascript within `script` tags on `html` files. Considering this, I would like to be able to add `eslint` for html files as well.

So far I have tried on my `~/.vimrc` file:

```viml
let g:syntastic_html_checkers       = ['tidy', 'aslant']
```

or trying to edit `syntastic/syntax_checkers/javascript/eslint.vim`
```viml
call g:SyntasticRegistry.CreateAndRegisterChecker({
    \ 'filetype': ['javascript', 'html'],
    \ 'name': 'eslint'})
```

but none seem to work and when checking the file with `:SyntasticInfo` I only get:
```
Syntastic version: 3.7.0-93 (Vim 704, Darwin)
Info for filetype: html
Global mode: active
Filetype html is active
The current file will be checked automatically
Available checkers: tidy validator w3
Currently enabled checker: tidy
```

Is there any way to achieve this currently?

**Comment by lcd047** [comment]
@zanona You can't just make up commands and expect syntastic to understand them.  Mapping `html` to `javascript` works, but then you won't be able to use HTML checkers.  Something else that works is to temporarily set `filetype` to `javascript`, and run the JavaScript checkers:
```vim
setf javascript
```
But normally there is no way to run checkers intended for a filetype against files of a different filetype.  There are good reasons for that, and code has to be written to allow using a checker for a new filetype.  In this particular case I added an `eslint` checker for `html`: commit 30fa9be.

**Comment by zanona** [comment]
Thanks @lcd047, yeah. I've just noticed it has disabled that as now :/

I have also used `:set filetype=html.javascript` however that messes up with indentation following the latter options and ignoring html's which is the main thing.

Thanks for adding ESLint to HTML now though.
