### ISSUE TITLE
Unable to load syntastic with master

### ISSUE THREAD

**Issue by lzap** [scrooloose/syntastic#1213]
I was trying to git blame and find what is wrong, but this could be also due to misconfiguration after I upgraded today?

```
syntastic: warning: variable g:syntastic_quiet_warnings is deprecated, please use let g:syntastic_quiet_messages = {'level': 'warnings'} instead
Error detected while processing /home/lzap/.vim/bundle/syntastic/plugin/syntastic.vim:
line  105:
E741: Value is locked: g:syntastic_quiet_messages['type'] = s:quiet_warnings
```

My config:

```
" SYNTASTIC PLUGIN
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_auto_loc_list=2
let g:syntastic_quiet_warnings=1
"let g:syntastic_python_checker = 'pyflakes'
let g:syntastic_python_checker = 'pylint'
let g:syntastic_python_checker_args = '--rcfile=/etc/spacewalk-pylint.rc --additional-builtins=_'
let g:syntastic_stl_format = '[%E{Err: %fe #%e}%B{, }%W{Warn: %fw #%w}]'
```

**Comment by robmcelvenny** [comment]
adding `let g:syntastic_quiet_messages = {'level' : 'warnings'}` does nothing at all either.

**Comment by lcd047** [comment]
@robmcelvenny Please don't add something to a 5 years old thread and expect it to still make sense today.  Please open a new issue, and explain what did you do, what did you expect to happen, and what happened instead.  Try to post minimal test files that illustrate the problem if at all relevant.
