### ISSUE TITLE
Why cpp checker can't choose "make" ?

### ISSUE THREAD

**Issue by cs86661** [scrooloose/syntastic#1228]
1. open a.cpp, and then run command "SyntasticInfo". There is no "make" checker ?
   
   > Syntastic version: 3.5.0-72
   > Info for filetype: cpp
   > Mode: active
   > Filetype cpp is active
   > Available checkers: cppcheck gcc
   > Currently enabled checker: gcc
2. set filetype to c, then run "SyntasticCheck" again. Yes! "make" is there.
   
   > Syntastic version: 3.5.0-72
   > Info for filetype: c
   > Mode: active
   > Filetype c is active
   > Available checkers: cppcheck gcc make

so~why don't add "make" checker into cpp ?

**Comment by SrsBusiness** [comment]
Is there any chance you guys can keep make as a checker for C? We have a large project and it's a real pain for us if we have to maintain our compiler flags (of which there are many) in 2 different places.

**Comment by lcd047** [comment]
> Is there any chance you guys can keep make as a checker for C?

@SrsBusiness It's 2016, and the `make` checker is still here.

> We have a large project and it's a real pain for us if we have to maintain our compiler flags (of which there are many) in 2 different places.

Why do you have to maintain them in two different places?  Put this in your vimrc:
```vim
let g:syntastic_c_config_file = '.config'
```
Then put this in your `Makefile`:
```vim
CFLAGS!=cat .config
```
