### ISSUE TITLE
Pylint fails in Vim/Syntastic, runs fine in shell

### ISSUE THREAD

**Issue by seanh** [scrooloose/syntastic#1236]
Activate my virtualenv, run vim (in terminal), Syntastic is giving me: `syntastic: error: checker python/pylint: can't parse version string (abnormal termination?)`.

If I run `:echo system('pylint --version')` in Vim I get:

```
Traceback (most recent call last):                                                                                                                                                  
  File "/home/seanh/.virtualenvs/ckan/bin/pylint", line 5, in <module>                                                                                                              
    from pkg_resources import load_entry_point                                                                                                                                      
  File "/home/seanh/.virtualenvs/ckan/lib/python2.7/site-packages/pkg_resources.py", line 2736, in <module>                                                                         
    add_activation_listener(lambda dist: dist.activate())                                                                                                                           
  File "/home/seanh/.virtualenvs/ckan/lib/python2.7/site-packages/pkg_resources.py", line 698, in subscribe                                                                         
    callback(dist)                                                                                                                                                                  
  File "/home/seanh/.virtualenvs/ckan/lib/python2.7/site-packages/pkg_resources.py", line 2736, in <lambda>                                                                         
    add_activation_listener(lambda dist: dist.activate())                                                                                                                           
  File "/home/seanh/.virtualenvs/ckan/lib/python2.7/site-packages/pkg_resources.py", line 2274, in activate                                                                         
    list(map(declare_namespace, self._get_metadata('namespace_packages.txt')))                                                                                                      
  File "/home/seanh/.virtualenvs/ckan/lib/python2.7/site-packages/pkg_resources.py", line 1870, in declare_namespace                                                                
    path = sys.modules[parent].__path__                                                                                                                                             
KeyError: 'repoze.who'
```

No idea why. But if i quit vim and run `pylint --version` in a shell in the same terminal (same virtualenv activated) it's fine:

```
pylint 1.3.1, 
astroid 1.2.1, common 0.62.1
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
```

I can also actually get pylint to check a python package and it works fine.

**Comment by philbert** [comment]
For anyone else who stumbles across this error, the correct approach is probably use the [python-mode](https://github.com/klen/python-mode) plugin and disable syntastic with the following so that the two do not conflict on python files:

```let g:pymode_lint_on_write = 0```

python-mode supports multiple virtualenv and includes pylint and a bunch of other stuff you probably want.

**Comment by lcd047** [comment]
@philbert Well "this error" was actually triggered by [repoze.who](https://github.com/repoze/repoze.who).  Perhps `repoze.who` has evolved in the mean time.  If you have a problem that isn't related to `repoze.who`, please open a new issue and explain what you did, what did you expect to happen, and what happened instead.

As for `python-mode`, turning off `pymode_lint_on_write` actually disables lint checks by `python-mode`, not syntastic (cf. `:h syntastic-pymode`).  You can use `syntastic_mode_map` to disable syntastic checks, or any of the other mechanisms documented in the manual.  However, `python-mode` uses the Python interpreter embedded in Vim, and doesn't necessarily makes your life easier if you need to deal with multiple versions of Python. _shrug_

**Comment by philbert** [comment]
Thanks for the clarification @lcd047. I appreciate that you are so fast to respond on issues.

Getting my setup to do what I want has been a long journey with a lot of small errors along the way, but I had a similar symptom described above, being that pylint worked from the terminal but not inside syntastic but only when I was working in a virtualenv. (But I don't use repoze.who)

I think I may have been misled in your comments here leading me to believe syntastic did not handle virtualenv properly so I figured I'd drop a note to help put others on the right path. But maybe my good intentions were misguided...

**Comment by lcd047** [comment]
@philbert Syntastic relies on Vim being able to run external checkers without crashing them.  There are many moving parts (Vim itself, the shell, the OS, external interpreters such as Python, etc.) and getting them to play nice together is not always trivial.  What the above says is that syntastic won't work if all these parts are not __already__ playing well together.  Syntastic is a Vim plugin, you can't expect it to fix your setup. _shrug_
