### ISSUE TITLE
Disable syntastic when using diff mode (vimdiff)

### ISSUE THREAD

**Issue by ashikase** [scrooloose/syntastic#125]
Below is a patch that prevents syntastic from interfering with diff mode (vimdiff) (which I personally use for 'git diff').

As I mentioned in a previous issue, I have little experience with vimscript, so I doubt that this is the best/proper way to implement this.

(The below code is based on git commit: d14b53e903...)

``` vim
if getwinvar(0, '&diff')
    finish
endif

if exists("g:loaded_syntastic_plugin")
    finish
endif
let g:loaded_syntastic_plugin = 1
```

**Comment by Undeterminant** [comment]
I seem to have this problem on master; is there something that I'm doing incorrectly?

**Comment by lcd047** [comment]
@Undeterminant: Please open a new issue, and explain what you did, what did you expect to happen, and what happened instead.
