### ISSUE TITLE
Configuration file ignored

### ISSUE THREAD

**Issue by BigfootN** [scrooloose/syntastic#1276]
Hello,

I don't know why but it seems that the config file just stopped  being checked.

Here is my <code>.vimrc</code> config:

```
let g:syntastic_cpp_checkers = ['gcc']
let g:syntastic_cpp_check_header = 1
let g:syntastic_cpp_auto_refresh_includes = 1
let b:syntastic_cpp_includes = 1
let g:syntastic_cpp_config_file = '.config_cpp'
let g:syntastic_cpp_compiler = 'g++'
```

and when I check a file after having written the `.config_cpp` file (for example):

```
-Wall
-Werror
-Wextra
```

and I do a `let g:syntastic_debug=1` it doesn't add the desired flags, only the default ones that are present.

Thank you in advance for any help :)

**Comment by lcd047** [comment]
Ok, as of 79b04bd you can trace reading config files by setting `g:syntastic_debug` to 33.
