### ISSUE TITLE
Differing calls to pathogen in instructions

### ISSUE THREAD

**Issue by uusijani** [scrooloose/syntastic#1279]
In README, 2.2.1. Step 1 says I need to add "execute pathogen#infect()" to .vimrc, while the second point in the checklist at the end of 2.2.2. Step 2 says it should have been "call pathogen#infect()". I'm guessing both work, but it should probably be consistently the same in the instructions.

**Comment by lcd047** [comment]
Thank you.  The official pathogen docs have changed from recommending `call` to recommending `exec`.  Syntastic instructions have changed accordingly, but I missed the second reference.  Fixed in 50f6b47.
