### ISSUE TITLE
javac is clearing the classpath

### ISSUE THREAD

**Issue by jszakmeister** [scrooloose/syntastic#1281]
This took a little while to track down, but I discovered that my classpath is being filtered (accidentally) by the javac checker.

The problem seems to stem from the fact that Vim isn't actually implementing `glob()` according to the docs.  The javac plugin is calling something like: `glob(path, 1)`, where the `1` is supposed to indicate that glob should ignore suffixes and wildignore, but that doesn't appear to be happening.  In my case, I have `*.jar` is my wildignore setting, ,and it's still getting applied, which results in the path coming back as empty.  Even if that wasn't a problem though, later there is a call to `syntastic#util#shexpand()`, which calls `expand()` and it can apply the wildignore setting.  So if you're unfortunate enough to have your classpath end with ".jar", then you may see you classpath wiped clean.

I applied this patch, which fixes the issue for me, but there might be a better way to go:

```diff
diff --git a/bundle/syntastic/syntax_checkers/java/javac.vim b/bundle/syntastic/syntax_checkers/java/javac.vim
index 2e138be..70e4373 100644
--- a/bundle/syntastic/syntax_checkers/java/javac.vim
+++ b/bundle/syntastic/syntax_checkers/java/javac.vim
@@ -352,6 +352,9 @@ function! SyntaxCheckers_java_javac_GetLocList() dict
     let javac_classpath = ''
 
     " add classpathes to javac_classpath
+    let save_wildignore = &wildignore
+    set wildignore-=*.jar
+
     for path in split(g:syntastic_java_javac_classpath, s:ClassSep())
         if path != ''
             try
@@ -390,6 +393,7 @@ function! SyntaxCheckers_java_javac_GetLocList() dict
     if javac_classpath != ''
         let javac_opts .= ' -cp ' . syntastic#util#shexpand(javac_classpath)
     endif
+    let &wildignore = save_wildignore
 
     let fname = expand('%:p:h') . syntastic#util#Slash() . expand ('%:t')
 
```

**Comment by lcd047** [comment]
Oh, this is pretty nasty.  The `wildignore` thing affects `glob()`, `globpath()`, and `expand()`, and there are 81 occurrences of those in syntastic that had to be fixed.  I think  is my new favourite misfeature of Vim. :) Thank you for uncovering it.

Ok, please try d1b4016.

**Comment by jszakmeister** [comment]
@lcd047 It appears to be working now, thanks!  I'm a bit surprised you didn't have to save off `wildignore`, because I tried calling `glob()` manually and it appeared to be filtering off `wildignore` files despite the presence of the flag telling it not to.  But, I apparently didn't do something right because it does appear to be working correctly now that I try it again.

Thanks!

**Comment by lcd047** [comment]
Actually, `glob()` works fine, but your initial reading of the code was wrong: the [code](https://github.com/scrooloose/syntastic/commit/d1b401609bcdcbd5e834f84c7a8d8f1193323864#diff-3c44f2f1999397816acc71d07a9a4b03L338) used to call `glob(path, 0)`, rather than `glob(path, 1)`.

**Comment by jszakmeister** [comment]
Sorry, I had explored it locally as a way to fix the issue--I generally like to post something helpful when reporting a bug. :-)  When I had tried it before, I thought `glob()` was ignoring the flag which is why I went with the save wildignore approach.  But I'm glad to see that glob works correctly with the flag set. :-)
