### ISSUE TITLE
Error list window cause terminal VIM to freeze

### ISSUE THREAD

**Issue by ianks** [scrooloose/syntastic#1284]
1. After editing a file with errors in it
2. If I do not fix the errors and quit out of the file
3. Then VIM is rendered unresponsive to input commands.

This issue exists with multiple file types (reproduced on Ruby and C).

Here's what I mean when the error list is rendered unresponsive:
![example](https://www.dropbox.com/s/m3zegvvsxhtl195/Screenshot%202014-12-31%2004.18.57.png?dl=1)

I am using:
* Most recent Homebrew version 7.4.560
* OSX 10.10.1
* Master branch of Syntastic

**Comment by lcd047** [comment]
I'm afraid I don't have OSX here, and I can't reproduce the problem.

What exactly did you do to run into the problem?  Does the problem persists if you disable all other Vim plugins?

**Comment by ianks** [comment]
I have confirmed that this issue does *not* happen with other plugins installed. So it is most likely something on my part.

Also, I have found this issue only happens with this set:
```viml
let g:syntastic_auto_loc_list=1
```

**Comment by lcd047** [comment]
On a side note: unless you have very specific reasons to keep syntastic from using loclists, `g:syntastic_auto_loc_list` always be set to 1.  The only reason why this option exists in the first place is to avoid compatibility problems with other (seldom used) plugins, and the fact that it defaults to 0 is a historic accident.  Sadly it's way too late to change it now.

**Comment by lcd047** [comment]
Please post if / when you identify the conflicting plugin / situation.  It might be interesting enough for either a workaround, or a note in the manual.

**Comment by ianks** [comment]
Closing as this seems to be a personal problem.
