### ISSUE TITLE
'shellredir=>' causes no errors always

### ISSUE THREAD

**Issue by lilydjwg** [scrooloose/syntastic#1285]
What about temporarily change it when running checkers? I set it to include only stdout because I want curl to show its processbar when editing a HTTP URL (there are some other programs that works like filters but are tending to print warnings to stderr too).

**Comment by lcd047** [comment]
> What about temporarily change it when running checkers?

This is not really feasible.  Setting `shellredir` to something meaningful depends on the shell in use; there is no single setting that makes sense for all shells.  If you leave it alone Vim will usually make a sensible choice, but the details of the decision process itself are not trivial.  For this reason syntastic doesn't try to mess with `shellredir`, and merely assumes the user has set it to something appropriate.  Basically it's up to you to make sure your setting of `shellredir` doesn't cut off the output of the checkers you use.

> I set it to include only stdout because I want curl to show its processbar when editing a HTTP URL

Then how about _you_ save and restore the `shellredir` before running syntastic.

**Comment by lilydjwg** [comment]
I've just checked the code, and find that I can't automatically save and restore options before running syntastic from outside, or I'll lose some functions.  E.g. I won't get autocompletion if I override the `SyntasticCheck` command because the completer is private. I won't be able to use `SyntasticToggleMode` because I can't call `s:BufWritePostHook()` etc (and I can't arrange my hook to run just before and after syntastic's ones).

How about a user provided variable specifying what should `shellredir` be set to when running syntastic?

**Comment by lcd047** [comment]
> How about a user provided variable specifying what should `shellredir` be set to when running syntastic?

Like I said: syntastic won't mess with `shellredir`.  Syntastic assumes a working `system()`, and your configuration breaks that assumption.  This is not supported; sorry about that.
