### ISSUE TITLE
Add support for go errcheck

### ISSUE THREAD

**Issue by oryband** [scrooloose/syntastic#1286]
https://github.com/kisielk/errcheck

This checker checks for unchecked errors (ha ha), an idiom in go.

**Comment by lcd047** [comment]
I think I looked at errcheck some time ago, and decided there is no reasonable way to make it run from syntastic.  Please feel free to prove me wrong by posting a (working) PR though. *shrug*

**Comment by oryband** [comment]
Currently ErrCheck is a bit slow to be able to run on ever save (which triggers `:SyntasticCheck`). Please keep this issue open until we resolve this.

**Comment by oryband** [comment]
Update: ErrCheck has become quite fast (see kisielk/errcheck/#56). Might be worth adding support for it now.

**Comment by lcd047** [comment]
As far as syntastic is concerned, the speed of ErrCheck has never been the main issue.  The main problem was, and still is, how to make it run from syntastic.  Like I said: please feel free to post a working PR if you can figure out how to solve it.

**Comment by oryband** [comment]
will do

**Comment by lcd047** [comment]
As of commit 8bb535b, the `gometalinter` checker can be used to run `errcheck`.

**Comment by oryband** [comment]
@lcd047 awesome, thanks for keeping up with this issue! :+1:
