### ISSUE TITLE
Go files with build tags are not checked

### ISSUE THREAD

**Issue by oryband** [scrooloose/syntastic#1287]
I have a file called `package_integration_test.go` which looks something like this:
```go
// +build integration

package bla

// code
```
In order to test this in the terminal, I need to use `go test -tags=integration`, otherwise `go build` (which is executed behind `go test` I think) will ignore this file.

This also means that syntastic won't show errors generated by `go build`, even when explicitly calling `:SyntasticCheck`.

We should find a way to handle build tags.

**NOTE**: The file does have to be a `_test.go` file, it can also be a normal one, and behaviour will stay the same. `go test` calls `go build` behind the scenes.

**Comment by lcd047** [comment]
> In order to test this in the terminal, I need to use `go test -tags=integration`, otherwise `go build` (which is executed behind `go test` I think) will ignore this file.

Try this:
```vim
let g:syntastic_go_go_args = '-tags=integration'
```

**Comment by lcd047** [comment]
Ah, I see: the `go build` stage ignores `*_args`.

**Comment by oryband** [comment]
@lcd047 I didn't understand your second comment, what do you mean?

**Comment by lcd047** [comment]
I mean changing `g:syntastic_go_go_args` has no effect on running `go test`, you need a new (set of) option(s) just for `go test`.  It will happen eventually, once I decide on the least annoying way of adding them.

**Comment by lcd047** [comment]
Please try a18ccb4.  It adds two new options, `g:syntastic_go_go_build_args` and `g:syntastic_go_go_test_args`.

**Comment by lcd047** [comment]
Any feedback on this?

**Comment by oryband** [comment]
Sorry for taking so long to answer.
After settings:
```vim
let g:syntastic_go_go_build_args = [ "tag1", "tag2" ]
let g:syntastic_go_go_test_args = g:syntastic_go_go_build_args
```
Openin a `_test.go` file and `:SyntasticCheck` in any `.go` file, I get the following error:
```vim
Error detected while processing function SyntasticCheck..<SNR>68_UpdateErrors..<SNR>68_CacheErrors..241..240..SyntaxCheckers_go_go_GetLocList:
line   25:
E691: Can only compare List with List
E15: Invalid expression: opts != '' ? syntastic#util#shescape(opts) : ''
Error detected while processing function SyntasticCheck..<SNR>68_UpdateErrors..<SNR>68_CacheErrors:
line   34:
E170: Missing :endfor
Error detected while processing function SyntasticCheck..<SNR>68_UpdateErrors:
line   13:
E171: Missing :endif
```

```

**Comment by lcd047** [comment]
... Which is exactly why I'd expect this to be annoying: `g:syntastic_go_go_build_args` and `g:syntastic_go_go_test_args` can only be strings for now, not lists.

**Comment by oryband** [comment]
ok, so how can I enter multiple trags in string form? `"tag1,tag2"`?

**Comment by oryband** [comment]
just tried, same error

**Comment by lcd047** [comment]
No.  You can now enter what you asked for in your first message:
```vim
let g:syntastic_go_go_test_args = "-tags=integration"
```

**Comment by oryband** [comment]
ok I tested it, and it works when using a single tag, but not for multiple tags. I've set:
```go
// +build ttt
package main
// code ...
```
```go
// +build integration
package main
// More code, this is a different file
```
And in `.vimrc`:
```vim
let g:syntastic_go_go_build_args = '-tags="ttt integration"'
```
And `:SyntasticCheck` returns syntax errors which show that these files weren't built i.e. the build tags arg was ignored.
If I do this from the terminal it works:
```sh
$ go build -tags="ttt integration"
# All ok
```

**Comment by lcd047** [comment]
Ok, `g:syntastic_go_go_build_args` and `g:syntastic_go_go_test_args` should now behave like the standard variables.  Commit 4d1f2e2.

**Comment by oryband** [comment]
Yup. That did the trick. Feel free to merge + close.
