### ISSUE TITLE
Syntastic and scalastyle

### ISSUE THREAD

**Issue by ianks** [scrooloose/syntastic#1289]
Currently I have scalastyle installed via Homebrew. However, when I add:

```viml
" ~/.vimrc
let g:syntastic_scala_checkers=['scalastyle']
```

Syntastic does pick up any of my Scala style errors. I can confirm that scalastyle runs correctly, and such. What am I doing wrong?

cc: @lcd047

**Comment by lcd047** [comment]
You need to point `g:syntastic_scala_scalastyle_jar` and `g:syntastic_scala_scalastyle_config_file` to the corresponding files.

**Comment by xanderdunn** [comment]
@lcd047 Thanks!  This was helpful!
