### ISSUE TITLE
If coffeelint is being run, coffee doesn't need to run.

### ISSUE THREAD

**Issue by AsaAyers** [scrooloose/syntastic#1292]
CoffeeLint does the same syntax check that `coffee -cp` does. Speed isn't really an issue, but recently I added the ability to have CoffeeLint handle alternate Syntaxes like [`cjx`](https://github.com/clutchski/coffeelint/blob/master/doc/user.md#how-do-i-use-jsx-reactjs). Since Syntastic runs both checkers, there's no way to get around the syntax error.

In my opinion Syntastic should prefer coffeelint and only run coffee if coffeelint is missing.

**Comment by lcd047** [comment]
```vim
let g:syntastic_coffee_checkers = ['coffeelint']
```
