### ISSUE TITLE
E54 on some php files

### ISSUE THREAD

**Issue by greg0ire** [scrooloose/syntastic#1293]
When I write some php files with errors, I sometimes get this message : 

> E54 : Unmatched \(

I did some profiling, here is what I got : http://hastebin.com/ugoculaxaj.coffee

The detected phpmd errors is : 

> The class User has 50 public methods and attributes. Consider to reduce the number of public items under 45

**Comment by lcd047** [comment]
Do you have a test file that can be used to reproduce the problem reliably?  Does the problem still occur if you disable the other Vim plugins?

**Comment by greg0ire** [comment]
Here is [a test file](http://hastebin.com/axazuhopew.php). The problem still occurs after disabling other vim plugins that appeared in another profiling file I did before. It disappears when I disable syntastic.

**Comment by lcd047** [comment]
I take that as an "yes" to my first question, and a "maybe" to the second. :)

Ok, now please explain what you did, what did you expect to happen, and what happened instead.  Also please explain how does profiling fit into this picture.

**Comment by lcd047** [comment]
Never mind, I can reproduce the problem.

**Comment by greg0ire** [comment]
Good interpretation on my answers :)
What I did : saving this file by typing `:w`
What I expecting : seeing syntactic errors in the margin, not getting the… ah great you reproduced it.

I profiled so that maybe you could see the calls and narrow the faulty execution path.

**Comment by lcd047** [comment]
Ok, please try 5429d24.

**Comment by greg0ire** [comment]
Sorry, but it does not seem to fix the problem, I get the exact same message on the exact same file.

**Comment by lcd047** [comment]
The problem solved by the patch is "E54 : Unmatched (".  The error "The class User has 50 public methods and attributes." comes from phpmd, and doesn't have anything to do with syntastic. *shrug*

**Comment by greg0ire** [comment]
The message I'm talking about is "E54 : Unmatched \("

**Comment by greg0ire** [comment]
Oh sorry, my mistake, i failed to upgrade to 5429d24

**Comment by greg0ire** [comment]
I fetched instead of pulling. I can confirm the patch works. Thank you very much for fixing this so quickly! :)
