### ISSUE TITLE
Merge phpcs + phpmd results when chaining

### ISSUE THREAD

**Issue by PVince81** [scrooloose/syntastic#1295]
```vim
let g:syntastic_php_checkers = ['php', 'phpcs', 'phpmd']
```

Currently syntastic (3.5.0) stops at the first with an error.
This means that even if there is a a minor style error, the developer will not get any results from phpmd.

It would be good if the results of every checker are merged so they can be all displayed in the editor.

**Comment by lcd047** [comment]
`:help syntastic_aggregate_errors`

**Comment by PVince81** [comment]
Wow, I missed it because I was googling for "group error messages".
Thanks!

Syntastic indeed is very tastic :smile:
