### ISSUE TITLE
Setting syntastic_FILETYPE_checkers for the current buffer

### ISSUE THREAD

**Issue by rodrigoaguilera** [scrooloose/syntastic#1299]
I'm contributing to a vim plugin

https://www.drupal.org/node/2405125#comment-9520877
and another contributor suggested that we should set syntastic_javascript_checkers only for the current buffer so we don't mess with the user preferences in the vimrc file. But the checker only work if is set as a global variable.

is this the expected behaviour?

**Comment by lcd047** [comment]
Reading the manual (syntastic's manual, that is) might be a good place to start for both of you:

1. you can set the list of checkers for the current buffer: `:help b:syntastic_checkers`
2. adding an executable path to `g:syntastic_javascript_checkers` is less than useful
3. it's safe to enable a checker even if the corresponding binary is not installed.

And yes, I'd suggest not overriding `g:syntastic_javascript_checkers` if set by user.

**Comment by rodrigoaguilera** [comment]
Thank you! 

all clear now
