### ISSUE TITLE
Error in eslint checker

### ISSUE THREAD

**Issue by brettof86** [scrooloose/syntastic#1302]
```
Error detected while processing function <SNR>75_BufWritePostHook..<SNR>75_UpdateErrors..<SNR>75_CacheErrors..239..SyntaxCheckers_javascript_eslint_GetLocList:

line   12:
E714: List required
Error detected while processing function <SNR>75_BufWritePostHook..<SNR>75_UpdateErrors..<SNR>75_CacheErrors:
line   25:
E170: Missing :endfor
Error detected while processing function <SNR>75_BufWritePostHook..<SNR>75_UpdateErrors:
line   11:
E171: Missing :endif
```

I noticed that similar errors come up with incorrect syntastic variables but I've checked mine and I don't see anything wrong with them:

These are the only lines in my vimrc that contain the word 'syntastic'

```
let g:airline_section_warning = airline#section#create(['syntastic'])
let g:syntastic_python_checkers = ["flake8"]
let g:syntastic_javascript_checkers = ["eslint"]
let g:syntastic_html_checkers = []
```

Here is the output for :SyntasticInfo

```
Syntastic: active mode enabled
Syntastic info for filetype: javascript
Available checker(s): eslint
Currently enabled checker(s): eslint
```

**Comment by brettof86** [comment]
Whenever I remove `syntastic_javascript_checkers` from my vimrc SyntasticInfo doesn't default to eslint even though it's available

```
Syntastic: active mode enabled
Syntastic info for filetype: javascript
Available checker(s): eslint
Currently enabled checker(s):   
```

**Comment by lcd047** [comment]
What OS do you have, and what version of syntastic are you using?  Can you reproduce the problem if you disable all other Vim plugins?

> Whenever I remove `syntastic_javascript_checkers` from my vimrc SyntasticInfo doesn't default to eslint even though it's available

Have you considered reading the manual?  At least the "quick start" part?

**Comment by brettof86** [comment]
1. OSX
1. whatever version installs with vundle
1. I haven't tried to disable other plugins
1. I read the manual when I installed this plugin (years ago) but since you brought it up I read just went over it again and I don't see anything having to do with what I said.

**Comment by lcd047** [comment]
1. I don't have OSX, and I can't reproduce your problem.
2. Please upgrade to syntastic 3.6.0.  Remote debugging of unknown versions of syntastic is not supported.  Remote debugging of Vundle is not supported either. :)
3. Please try disabling all other plugins, and report back if you can still reproduce the problem.
4. Let's try the first paragraph of "Quick start", in particular the second sentence:

> Syntastic comes preconfigured with a default list of enabled checkers per filetype. This list is kept reasonably short to prevent slowing down Vim or trying to use conflicting checkers.

**Comment by brettof86** [comment]
I'll try disabling other plugins in the morning and I'll try on a Windows machine at work. Vundle simply clones the repo so it's whatever is in master. I'll downgrade(?) to 3.6.0 and see if that helps. I'll report back in the morning. Thanks for the help.

**Comment by lcd047** [comment]
Syntastic 3.6.0 is the current master HEAD, and the output of `:SyntasticInfo` in 3.6.0 is different from what you have shown above. *shrug*

**Comment by brettof86** [comment]
I just realized I switched to [Syntastic-Async](https://github.com/stgpetrovic/syntastic-async) a while back and that's why it's not on the latest version. I just changed it back to this repo and it works fine. Sorry about that.
