### ISSUE TITLE
Issue with ghost characters when exiting insert mode

### ISSUE THREAD

**Issue by gwintrob** [scrooloose/syntastic#1303]
When I exit insert mode and then go to save with `:wq`, I often see a ghost ":" or "w" character, which isn't actually saved to the file on disk.  This seems to only affect file types that have syntastic checking.  Here's a screencast of editing the file "testfile.js":

https://www.dropbox.com/s/0cm9131a9ovfz3v/syntastic_trim.mov?dl=0

If I rename the file to "testfile.txt" to disable syntax checking, then I don't see these ghost characters.  I turned on the following settings in my .vimrc:

```
let g:syntastic_full_redraws=0
let g:syntastic_check_on_wq=0
```

Really appreciate your help!

**Comment by lcd047** [comment]
Contrary to the popular belief, syntastic has exactly zero control on low level redraws.  Please see #822 for more details.

> `let g:syntastic_full_redraws=0`

This is not related to your problem.
