### ISSUE TITLE
how to use robucop.vim?

### ISSUE THREAD

**Issue by magicalbanana** [scrooloose/syntastic#1304]
Noob in Vim here.

How do I exactly incorporate that to an existing vimrc?

**Comment by lcd047** [comment]
1. Get a basic understanding of how Vim works
2. Get a basic understanding of how Vim plugins work
3. [Install syntastic](https://github.com/scrooloose/syntastic#installation)
4. Read the [manual](https://github.com/scrooloose/syntastic/blob/master/doc/syntastic.txt)
5. Add the [recommended settings](https://github.com/scrooloose/syntastic#settings) to your vimrc
6. Configure syntastic to run rubocop (you should have found out how to do that at step 4.) :)
7. Start checking your code.

If you need help beyond the above, this is probably not the right place to start.  Sorry about that.
