### ISSUE TITLE
Rubucop file open slow (g:SyntasticRegistry.CreateAndRegisterChecker)

### ISSUE THREAD

**Issue by kballenegger** [scrooloose/syntastic#1305]
Syntastic is extremely slow loading any ruby files (no matter how small), and the hang up seems to be in the `g:SyntasticRegistry.CreateAndRegisterChecker` call in `rubocop.vim`.

Note: I have rubocop checking disabled by default:

```vim
let g:syntastic_ruby_checkers = ['mri']
command! Syn call CustomSyn()
function! CustomSyn()
  let g:syntastic_ruby_checkers = ['mri']
  let g:syntastic_quiet_messages = {'type': 'style'}
  :SyntasticCheck
endfunction
command! SynS call CustomSynS()
function! CustomSynS()
  let g:syntastic_ruby_checkers = ['mri', 'rubocop']
  let g:syntastic_quiet_messages = {}
  :SyntasticCheck
endfunction
```

/cc @roktas 

Here's the relevant section from the profile:

```
SCRIPT  /Users/kenneth/.vim/bundle/syntastic/syntax_checkers/ruby/rubocop.vim
Sourced 1 time
Total time:   0.500709
 Self time:   0.000236

count  total (s)   self (s)
                            "============================================================================
                            "File:        rubocop.vim
                            "Description: Syntax checking plugin for syntastic.vim
                            "Maintainer:  Recai Oktaş <roktas@bil.omu.edu.tr>
                            "License:     This program is free software. It comes without any warranty,
                            "             to the extent permitted by applicable law. You can redistribute
                            "             it and/or modify it under the terms of the Do What The Fuck You
                            "             Want To Public License, Version 2, as published by Sam Hocevar.
                            "             See http://sam.zoy.org/wtfpl/COPYING for more details.
                            "
                            "============================================================================
                            "
                            " In order to use rubocop with the default ruby checker (mri):
                            "     let g:syntastic_ruby_checkers = ['mri', 'rubocop']
                            
    1              0.000007 if exists("g:loaded_syntastic_ruby_rubocop_checker")
                                finish
                            endif
    1              0.000007 let g:loaded_syntastic_ruby_rubocop_checker = 1
                            
    1              0.000018 let s:save_cpo = &cpo
    1              0.000009 set cpo&vim
                            
    1              0.000005 function! SyntaxCheckers_ruby_rubocop_IsAvailable() dict
                                return
                                    \ executable(self.getExec()) &&
                                    \ syntastic#util#versionIsAtLeast(syntastic#util#getVersion(self.getExecEscaped() . ' --version'), [0, 9, 0])
                            endfunction
                            
    1              0.000004 function! SyntaxCheckers_ruby_rubocop_GetLocList() dict
                                let makeprg = self.makeprgBuild({ 'args_after': '--format emacs --silent' })
                            
                                let errorformat = '%f:%l:%c: %t: %m'
                            
                                let loclist = SyntasticMake({
                                    \ 'makeprg': makeprg,
                                    \ 'errorformat': errorformat,
                                    \ 'subtype': 'Style'})
                            
                                " convert rubocop severities to error types recognized by syntastic
                                for e in loclist
                                    if e['type'] ==# 'F'
                                        let e['type'] = 'E'
                                    elseif e['type'] !=# 'W' && e['type'] !=# 'E'
                                        let e['type'] = 'W'
                                    endif
                                endfor
                            
                                return loclist
                            endfunction
                            
    1   0.500511   0.000038 call g:SyntasticRegistry.CreateAndRegisterChecker({
                                \ 'filetype': 'ruby',
                                \ 'name': 'rubocop'})
                            
    1              0.000015 let &cpo = s:save_cpo
    1              0.000003 unlet s:save_cpo
                            
                            " vim: set et sts=4 sw=4:

```

**Comment by roktas** [comment]
This is probably because rubocop displays version info too slow.

```sh
$ time rubocop --version
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.5-compliant syntax, but you are running 2.1.4.
0.28.0
rubocop -v  0,38s user 0,03s system 99% cpu 0,419 total
```

Slowness is not the only problem, newer rubocop versions might produce warnings (as can be seen above) and that will actually disable rubocop checker.

Let's see how we can fix the issue.  More on this later...

**Comment by lcd047** [comment]
@kballenegger: This was fixed a while back (cf. #885).  Please upgrade to the master HEAD.

@roktas: There is nothing to fix in syntastic.  Getting rid of the warnings is described in the [relevant wiki page](https://github.com/scrooloose/syntastic/wiki/Ruby%3A---rubocop).

**Comment by roktas** [comment]
@lcd047 fair enough.  Before reading your comment, I had made the above change (tested ok).  It's definitely a hack.  Just to note...

**Comment by lcd047** [comment]
There are several different issues here.  My take, for what it's worth:

1. Syntastic used to call `rubocop --version` even when `rubocop` was not part of `g:syntastic_ruby_checkers`.  This is (hopefully) the problem the initial poster had, and it was fixed a few month ago.
2. `rubocop --version` is slow.  Well, boo-hoo. :) This has been known for a long, long time, and if the developers of rubocop are happy to live with it, so is syntastic.  Nowadays syntastic tries to minimise the damage by calling `rubocop --version` only once, the first time the `rubocop` checker is actually used.
3. Trying to speed up `rubocop --version` by calling the module directly.  I'm not fundamentally opposed to this, but then it has to deal with load errors, and things will get exponentially more complex from there.  The official way to get the version is `rubocop --version`, which is simple, and it's guaranteed to work (albeit slowly). :)
4. Ignoring warnings from `rubocop --version`.  That, I _am_ opposed to.  A warning is a symptom of a problem, and syntastic doesn't know how serious the problem might be.  It's up to the user to fix the problem, rather than being up to syntastic to tell if the problem is survivable or not.  Again, if rubocop developers are happy to live with that, so is syntastic.

**Comment by kballenegger** [comment]
For what it's worth, the code in the `vimrc` snippet I pasted disables rubocop by default, and only enables it when the command `SynS` is executed. Shouldn't that defer the calling of `rubocop --version` until it's first used?

(Or could that be because I was somewhat behind master.)

**Comment by lcd047** [comment]
@kballenegger Like I said: this was fixed a few month ago.  Please try again with the current master HEAD.

**Comment by roktas** [comment]
@lcd047: yep, especially the last one.  The warnings are there for a reason.  Although disabling the rubocop checker seems to be a side effect at the first sight, it says something about a problem.  My main concern was the slowness of rubocop, i.e, the slow codepath from launching to the version dumping :-)  But thinking more on the issue, I concluded that the problem doesn't deserve an ugly hack and we could live with a (one time) slow boot process.

**Comment by lcd047** [comment]
The annoying part at handling warnings from `rubocop --version` is the checker is disabled silently.  As of cb64516 this is no longer the case, syntastil will complain it can't parse the version string.
