### ISSUE TITLE
Syntastic displays jscs & jshint errors/warnings exclusively. 

### ISSUE THREAD

**Issue by kennykaye** [scrooloose/syntastic#1307]
First off, thank you very much for all the hard work you do on this plugin, it is really wonderful!

It seems this is probably an issue with jscs and jshint, however I've had this configuration working with other linters, so I thought to raise the issue here.

**The Issue:** When running `jscs` and `jshint` together, if there is an error from jscs then no jshint warnings display. When there are no warnings, errors display properly.

Here are my javascript linters:
```vimscript
let g:syntastic_javascript_checkers=['jshint', 'jscs']
```
---

**jscs error:**
![screen shot 2015-01-23 at 11 48 17 pm](https://cloud.githubusercontent.com/assets/3267574/5886574/4c0a0682-a35b-11e4-9bc6-270b8b29185e.png)

**jshint error:**
![screen shot 2015-01-23 at 11 47 56 pm](https://cloud.githubusercontent.com/assets/3267574/5886573/4c07f248-a35b-11e4-8696-31bf25c2a12f.png)

**Comment by lcd047** [comment]
Does this answer your question: `:help syntastic-aggregating-errors`?

**Comment by kennykaye** [comment]
That does, thank you!
