### ISSUE TITLE
Call vim function instead of exe?

### ISSUE THREAD

**Issue by venantius** [scrooloose/syntastic#1308]
Is there a way for me to call a vim function instead of shelling out to an executable on $PATH? 

I ask because I'm working on a Clojure linter for Syntastic that would rely on Tim Pope's excellent [vim-fireplace](https://github.com/tpope/vim-fireplace). If I have to write some sort of bash or vim standalone executable that wouldn't be the end of the world, but it'd be nice if I could just call the function directly.

Thanks!

**Comment by lcd047** [comment]
Sure, just build a `loclist` and return it from `GetLocList()`, that's exactly the `vimlint` checker works. Syntastic only needs a `loclist`, it doesn't really care how that is obrtained.  In particular, the `SyntasticMake()` function is just a convenience that runs an external program and transforms its output in a `loclist`.

**Comment by venantius** [comment]
That's incredibly helpful, thanks.
