### ISSUE TITLE
puppet checker reports error

### ISSUE THREAD

**Issue by jby** [scrooloose/syntastic#1310]
I've seen that others have reported this for other checkers, but I can't find a solution related to syntastic. This probably means that the problem is probably not within syntastic, but I can't find the problem.

 ```
syntastic: error: checker puppet/puppet: can't parse version string (abnormal termination?)
```

**Comment by lcd047** [comment]
Please run this in a terminal and post the output:
```sh
puppet --version
```

**Comment by jby** [comment]
```
puppet --version
3.7.3
```

**Comment by lcd047** [comment]
Ok, please run this in Vim and post the output:
```vim
:echo system('puppet --version 2>/dev/null')
```

**Comment by jby** [comment]
```
:echo system('puppet --version 2>/dev/null')
Command terminated

Press ENTER or type command to continue
```

**Comment by lcd047** [comment]
This looks like a Vim configuration problem.  What OS do you have, and what version of Vim?  Please open a puppet file, set `g:syntastic_debug` to 33, run `:SyntasticInfo` and post the output.  Then without quitting Vim run `:SyntasticCheck puppet`, run `:mes`, and post the output.

**Comment by jby** [comment]
```vim
:SyntasticInfo
Syntastic version: 3.6.0-4
Info for filetype: puppet
Global mode: active
Filetype puppet is active
The current file will be checked automatically
syntastic: 15.252223: puppet/puppetlint: executable('puppet') = 1, executable('puppet-lint') = 1
syntastic: 15.816585: puppet/puppetlint: puppet-lint version = [1, 1, 0]
Available checkers: puppet puppetlint
Currently enabled checkers: puppet puppetlint
```
And
```vim
:SyntasticCheck puppet
Syntastic version: 3.6.0-4
Info for filetype: puppet
Global mode: active
Filetype puppet is active
The current file will be checked automatically
syntastic: 15.252223: puppet/puppetlint: executable('puppet') = 1, executable('puppet-lint') = 1
syntastic: 15.816585: puppet/puppetlint: puppet-lint version = [1, 1, 0]
Available checkers: puppet puppetlint
Currently enabled checkers: puppet puppetlint
syntastic: 75.344556: &shell = '/usr/local/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 75.344947: UpdateErrors: puppet
syntastic: 75.345597: CacheErrors: puppet
syntastic: 75.347049: g:syntastic_aggregate_errors = 0
syntastic: 75.347397: getcwd() = /Users/jonasb/src/puppet/modules/terminatorv2/manifests
syntastic: 75.348009: CacheErrors: Invoking checker: puppet/puppet
syntastic: error: checker puppet/puppet: can't parse version string (abnormal termination?)
syntastic: 76.577378: SyntasticMake: called with options: {'errorformat': '%-Gerr: Try ''puppet help parser validate'' for usage,%-GError: Try ''puppet help parser validate'' for usage,%A%t%*[a-zA-Z]: %m at %f:%l:%c,%A%t%*[a-zA-Z]: %m at
%f:%l', 'makeprg': 'puppet --color=false --parseonly init.pp'}
syntastic: 77.003766: getLocList: checker puppet/puppet returned -1
```

**Comment by lcd047** [comment]
I take it your OS is Mac OS.  What version of Vim do you have.  Does any other checker run with syntastic.  Doesn anything change if you set shell to `/bin/sh`:
```vim
set shell=/bin/sh
```

**Comment by lcd047** [comment]
In particular, does `:echo system('puppet --version 2>/dev/null')` still dies with "Command terminated" if you set your (Vim) `shell` to `/bin/sh`.

**Comment by jby** [comment]
Yes, sorry, I'm on OS X.

I use zsh, but setting the shell like you suggested doesn't change the problem.

I still get:
```
syntastic: error: checker puppet/puppet: can't parse version string (abnormal termination?)
```

**Comment by jby** [comment]
Hmm, set shell apparently didn't do what you (and I) thought it would.

However after
```sh
export SHELL=/bin/sh
 ```
the
```vim
:echo system('puppet --version 2>/dev/null')
```
does work, and prints the current puppet version.

This has however changed recently, I've been using this setup for over a year without a problem. This seem to have started in the new year.

**Comment by lcd047** [comment]
Well, "Command terminated" is an unusual condition, and I have no idea what it _actually_ means on your OS.  Also, the environment variable `SHELL` is not supposed to take precedence over Vim's option `shell`.  Both of these point to problems in your Vim.

Now, the code in syntastic handling versions did change recently, but not in ways relevant to your problem (at least as far as I can tell).  Syntastic relies heavily on `system()` working properly, and should (re-)start working once `system()` does.  I'm not sure what else I can tell you. _shrug_

**Comment by jby** [comment]
Ok, after some troubleshooting I can say that the ```Command terminated``` is unrelated to the ```abnormal termination``` message.

Regardless of which commit I check out since Jan 1 I get the ```Command terminated```.
The ```abnormal termination``` issue came in cb64516d4d6786e63071c313fce074f690bc17be
Or, rather, it was absent in bcaf7cbcc9c21f3d70f1d699e84397cb5a5812dc and in 1ba96436c1b00ed6c5d6c1eac030b49fc6ae8e9a there was a load of other errors - but I guess you know that... ;-)

**Comment by jby** [comment]
Oh, one more thing - syntastic seems to be working despite the error messages!

**Comment by lcd047** [comment]
> Ok, after some troubleshooting I can say that the `Command terminated` is unrelated to the `abnormal termination` message.

But it is.  It's just that old versions used to fail silently.  The effect was the same: the wrong flags were passed to puppet.

> Regardless of which commit I check out since Jan 1 I get the `Command terminated`.

Well, you get "Command terminated" outside syntastic, `system()` is a Vim internal, not a syntastic function.  Now, if the result of `:echo system('puppet --version 2>/dev/null')` itself depends on which version of syntastic is installed (which is my understanding from your description), then your Vim is badly broken.  I won't attempt to debug problems that ultimately resolve to Vim not behaving as advertised. _shrug_

> The `abnormal termination` issue came in cb64516d4d6786e63071c313fce074f690bc17be
Or, rather, it was absent in bcaf7cbcc9c21f3d70f1d699e84397cb5a5812dc and in 1ba96436c1b00ed6c5d6c1eac030b49fc6ae8e9a there was a load of other errors - but I guess you know that... ;-)

The point of 1ba9643 was exactly to let people know of problems when running `stuff --version` rather than failing silently.  In the vast majority of cases, these are problems outside syntastic that people need to take care of before hoping to use the corresponding checkers.  The point of cb64516 is to fix a logic bug in 1ba9643, which, on a side note, you wouldn't have run into if your `system()` was behaving properly. :)

**Comment by lcd047** [comment]
Now, where to go from here: I'd strongly suggest you should get the "Command terminated" thing fixed.  As far as I can tell it's about a process going away before Vim gets a chance to `wait(2)` for it, or something like that.  Perhaps ask on a forum related to your particular flavour of Vim (which, BTW, you haven't disclosed :)).

In the mean time, you could just replace [these lines](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/puppet/puppet.vim#L22-L25) with `let s:puppet_new = 1`, to avoid trying to detect the version.  But, if your `system()` is broken you'll soon run into other problems.

**Comment by jby** [comment]
I've asked in other forums after your excellent explanation. I didn't realize that I hadn't disclosed my Vim-version.

So, for reference:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 17 2014 20:55:26)
MacOS X (unix) version
Included patches: 1-258
Compiled by Homebrew
Huge version with MacVim GUI.
```

**Comment by lcd047** [comment]
On second thought, a simpler explanation would be that `2>/dev/null` might be hiding a crash in puppet.  Then "Command terminated" might actually be legitimate, and the problem would be between vim, zsh, and ruby.  Since MacVim is known to do weird things with the environment, the crash could be related to something like a missing environment variable.  So you might want to take a look at `:echo system('puppet --version')`, without the `2>/dev/null` part.  Just speculating really.

**Comment by jby** [comment]
Yes, it seems to be rvm-related:

```vim
:echo system('puppet --version')
Command terminated
dyld: lazy symbol binding failed: Symbol not found: _rb_ary_new_from_values
  Referenced from: /Users/jonasb/.rvm/gems/ruby-2.1.1/gems/psych-2.0.6/lib/psych.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_ary_new_from_values
  Referenced from: /Users/jonasb/.rvm/gems/ruby-2.1.1/gems/psych-2.0.6/lib/psych.bundle
  Expected in: flat namespace


Press ENTER or type command to continue
```
I'll investigate further.

**Comment by jby** [comment]
Uninstalling the complaining gem, psych-2.0.6 did solve all problems. Both the ```command terminated``` and the ```abnormal termination```

Sorry for taking your time with a problem I had locally, and thanks for the pointers making me able to solve it!

**Comment by lcd047** [comment]
Yes, but that still doesn't explain why you didn't get the same problem in a terminal.  Anyway, redirecting `stderr` was a bad idea.  Commit 6b76c26.
