### ISSUE TITLE
Syntastic not detecting checkers in gvim

### ISSUE THREAD

**Issue by person808** [scrooloose/syntastic#1315]
Syntastic is not detecting any checker besides `python` in gvim.

Output of `:SyntasticInfo` in gvim:
```
Syntastic version: 3.6.0-15
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
Available checkers: python
Currently enabled checker: -
```

In terminal vim:
```
Syntastic version: 3.6.0-15
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
Available checkers: flake8 pep257 pep8 prospector pyflakes pylint python
Currently enabled checker: prospector
```

Syntastic settings
```
let g:syntastic_aggregate_errors = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_python_python_exec = '/usr/bin/python3'
let g:syntastic_python_checkers = ['prospector']
let g:syntastic_python_prospector_args = "-F --max-line-length 99"
```

With `g:syntastic_debug=1`:
```
syntastic: 174.257324: &shell = 'bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 174.260453: UpdateErrors (auto): default checkers
syntastic: 174.264991: CacheErrors: default checkers
syntastic: 174.266752: g:syntastic_aggregate_errors = 1
syntastic: 174.267649: getcwd() = /home/kainalu
syntastic: 174.268816: CacheErrors: Checker python/prospector is not available
syntastic: 174.269813: CacheErrors: no checkers available for python
```
Other debug levels described in the documentation do not contain errors. All of the checkers are in my PATH.

**Comment by lcd047** [comment]
> syntastic: 174.257324: &shell = 'bash'

`shell` must be a full path:
```vim
set shell=/path/to/bash
```

**Comment by person808** [comment]
Unfortunately, that has no effect. I'm still getting the same error.

**Comment by lcd047** [comment]
> Unfortunately, that has no effect.

Then you're adding it to the wrong file.  At least the `&shell` output above should change. :)

**Comment by person808** [comment]
What I meant was the `&shell` output did change to `/usr/bin/bash`, but everything else remained the same.

**Comment by lcd047** [comment]
Please open a Python file (in gvim), set `g:syntastic_debug` to 33, run `:SyntasticInfo` and `:SyntasticCheck prospector`, then run `:mes` and post the output.

**Comment by person808** [comment]
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"test.py" 2L, 25C
Syntastic version: 3.6.0-15
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
syntastic: 20.831088: python/python: getVersion: 'python --version': ['Python 3.4.2', '']
syntastic: 20.832687: python/python: python version = [3, 4, 2]
Available checker: python
Currently enabled checkers: -
syntastic: 52.563243: &shell = '/usr/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 52.569879: UpdateErrors: prospector
syntastic: 52.571686: CacheErrors: prospector
syntastic: 52.573917: g:syntastic_aggregate_errors = 1
syntastic: 52.574982: getcwd() = /home/kainalu
syntastic: 52.576402: CacheErrors: Checker python/prospector is not available
syntastic: warning: checker prospector is not available
```

**Comment by lcd047** [comment]
Right.  Please run `echo $PATH` in a terminal, then open the same file as above in gvim and run `:echo $PATH`.  Compare the results.

**Comment by person808** [comment]
Here's the problem!

In terminal:
```
/home/kainalu/.dotfiles/bin:/home/kainalu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```
In gvim:
```
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

The prospector executable is in /home/kainalu/.local/bin which is where pip installs it.

**Comment by lcd047** [comment]
> The prospector executable is in /home/kainalu/.local/bin which is where pip installs it.

... Which is why gvim can't find it.

A little understood fact about the way X works is that `$PATH` as seen by applications run directly from the window manager has little in common to `$PATH` in a login shell.  The proper way to fix that depends on your OS, on your window manager / desktop manager / whatever it's called these days, and on a few other things.  You can however cheat, and set Vim's `$PATH` to the same value it has in your shell:
```vim
let $PATH='/home/kainalu/.dotfiles/bin:/home/kainalu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'
```
For best results you should do that before any plugins are loaded.

Alternatively, you can set `g:syntastic_python_prospector_exec` (and all other similar variables) to a full path, but that would only have an effect for syntastic.

**Comment by person808** [comment]
That worked. Thanks for the help!
