### ISSUE TITLE
statusline errors with powerline

### ISSUE THREAD

**Issue by markogresak** [scrooloose/syntastic#1318]
Hi!

I am trying to add syntastic in vim (macvim 7.4 - via homebrew), but I'm having problems when I set statusline and it seems to me they're caused by mixing it with powerline. I was searching issues here but I couldn't find anything that would fix it.

When I open up gvim, it starts w/o errors, but when I try to evaluate vimrc (`:source $MYVIMRC`), I get these errors and they don't end until I reopen vim.

```
E121: Undefined variable: #warningmsg#
E15: Invalid expression: pyeval('powerline.new_window()')%#warningmsg#%{SyntasticStatuslineFlag()}%* 
```

[This is my .vimrc](https://github.com/markogresak/dotfiles/blob/master/vim/.vimrc#L96) (I apologise for bad structuring).

If i comment out lines starting with `set statusline`, the errors go away. I'm new to vim so I was just following the instructions in readme, I'm not sure statusline settings are required at all.

**Comment by lcd047** [comment]
> I'm having problems when I set statusline and it seems to me they're caused by mixing it with powerline.

Yes, changing the status line in a way that makes sense to powerline has everything to do with powerline, and it has nothing to do with syntastic. _shrug_

> I'm not sure statusline settings are required at all.

Well, it's a notification mechanism, it gives you information.  As any other notification mechanism, it isn't mandatory.  Syntastic will happily run without showing you any results if you tell it to do that.  It's up to you if you to decide if you care about showing error counts on the status line badly enough to read the powerline manual. :)
