### ISSUE TITLE
Error detected while processing BufRead Auto commands for "*"

### ISSUE THREAD

**Issue by myint** [scrooloose/syntastic#1319]
I get the error the following error message when I use `:Errors`:

```
Error detected while processing BufRead Auto commands for "*":
E492: Not an editor command: [Errno 2] No such file or directory: ''^@
```

This happens only if I have `au BufRead * execute stuff` in my Vim configuration. I intend this to match all filenames with the `*`. I know next to nothing about Vim syntax so I'm probably doing something wrong.

If I replace it with `au BufRead *.* execute stuff`, `:Errors` no longer triggers the above error. But this causes files that do not have `.` in them to not be matched. Should I be using something else instead of `*`?

Thanks

**Comment by lcd047** [comment]
I can't reproduce this, and I don't really see how it could be related to syntastic.  My guess would be it's either a problem in the way you wrote `stuff`, or a bug in Vim.  What is your complete configuration?

**Comment by myint** [comment]
To reproduce it, use [`indent-finder`](https://github.com/myint/indent-finder):

```
$ cd ~/.vim/bundle
$ git clone https://github.com/myint/indent-finder
```

And [here](https://github.com/myint/indent-finder/commit/92b0338f6cf294cf86b1ffb10ad6803bfd13cdad) is my temporarily workaround. 

Thanks

**Comment by myint** [comment]
Here is a relevant screenshot.
![screen shot 2015-02-10 at 08 19 48](https://cloud.githubusercontent.com/assets/1235108/6130945/99ba2d1c-b0fd-11e4-827a-bee03018260f.png)

If I press `enter`, the location list will then properly show up.

**Comment by myint** [comment]
Oh, I figured out what the problem was. I'm doing a `system()` call with the `au BufRead *` first and then get the results. The problem is this gets passed an empty string as argument to the system call. This results in an error message from the system call `[Errno 2] No such file or directory: ''` to be executed in the next line, which is `au BufRead * execute`.

https://github.com/myint/indent-finder/blob/7f6a2c17a7d725f5e22f5818d6f7934e2d3b25ca/plugin/indent_finder.vim
