### ISSUE TITLE
Setting $PYTHONHOME breaks Syntastic's Python checking

### ISSUE THREAD

**Issue by abdarraafi** [scrooloose/syntastic#1321]
Once upon a time, I used to use [spf13-vim](https://github.com/spf13/spf13-vim), and on Mac OS X, that required the following in `.vimrc` because I had a `brew`-installed version of Python:

```
" Thanks https://github.com/spf13/spf13-vim/issues/176#issuecomment-12710485
let $PYTHONHOME='/System/Library/Frameworks/Python.framework/Versions/Current'
```

On removing spf13-vim in favor of Syntastic and friends, I discovered Syntastic's Python checking completely breaks as a result (used `let g:syntastic_debug = 3` to see debug logs):

```
"core.py" 793L, 20786C
syntastic: 0.176509: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquot
e = '', &shellxescape = ''
syntastic: 0.176686: UpdateErrors (auto): default checkers
syntastic: 0.176903: CacheErrors: default checkers
syntastic: 0.177396: g:syntastic_aggregate_errors = 0
syntastic: 0.177563: getcwd() = '/Users/abdarraafi/workspace/libnl/python/netlink'
syntastic: 0.193694: CacheErrors: Invoking checker: python/python
syntastic: 0.194542: SyntasticMake: called with options: {'errorformat': '%E%f:%l:%c: %m', 'makeprg': 'python /Users/abdarraafi/.vim/bundle/syntastic/syntax_checkers/python/compil
e.py core.py', 'env': {'TERM': 'dumb'}, 'returns': [0]}
syntastic: 0.228114: checker output: ['Traceback (most recent call last):', '  File "/Users/abdarraafi/.vim/bundle/syntastic/syntax_checkers/python/compile.py", line 3, in <module
>', '    from __future__ import print_function', 'ImportError: No module named __future__', '']
syntastic: error: checker python/python returned abnormal status 1
syntastic: 0.228984: python/python raw: []
syntastic: 0.229237: quiet_messages filter: {}
syntastic: 0.229819: CacheErrors: Invoking checker: python/flake8
syntastic: 0.230757: SyntasticMake: called with options: {'errorformat': '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %t%n %m,%A%f:%l: %t%n %m,%-G%.%#', 'makeprg': 'flake8 core.
py', 'env': {'TERM': 'dumb'}}
syntastic: 0.263712: checker output: ['Traceback (most recent call last):', '  File "/usr/bin/flake8", line 7, in <module>', '    from flake8.main import main', '  File "/
opt/twitter/lib/python2.7/site-packages/flake8/main.py", line 5, in <module>', '    import setuptools', 'zipimport.ZipImportError: can''t decompress data; zlib not available', '']

syntastic: 0.264429: raw loclist: []
syntastic: 0.264644: getLocList: checker python/flake8 returned 1
syntastic: 0.264759: python/flake8 raw: []
syntastic: 0.264956: quiet_messages filter: {}
syntastic: error: checker python/pylint: can't parse version string (abnormal termination?)
syntastic: 0.298420: CacheErrors: Checker python/pylint is not available
syntastic: 0.298605: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
```

Once I removed that line, Syntastic worked great. I'm marking this as a bug because other Vim plugins worked fine, but if this is expected behavior, perhaps someone else may derive benefit by discovering this while Googling.

**Comment by lcd047** [comment]
Can you please stop for a moment and take your time to _understand_ what you're doing, rather than follow blindly whatever random advice you happen to find out there?  According to the thread you mention, the problem with spf13-vim came from the python-mode plugin.  The python-mode plugin uses the Python interpreter embedded in Vim.  Syntastic runs whatever Python interpreter it finds in your `$PATH`.  If the two conflict, you're mixing the interpreter from a Python installation with the runtime from another.  So either remove the reference to `$PYTHONHOME`, or point `g:syntastic_python_python_exec` to the `python` binary of your `brew`-installed Python.  That's all there is to it, nothing to do with syntastic in particular.

**Comment by abdarraafi** [comment]
Wow, @lcd047, I did not realize the significance of that. #til that Vim with Python embeds a Python interpreter, among other things. Thanks!

**Comment by lcd047** [comment]
The full story is, of course, more involved than "Vim with Python embeds a Python interpreter", but that's the basic idea.  Try `:help python` for more details.
