### ISSUE TITLE
Argument --quiet to the reek checker

### ISSUE THREAD

**Issue by cartolari** [scrooloose/syntastic#1324]
Apparently the reek checker for the ruby language in it's last version does not support the --quiet flag, and when it's present the checker doesn't work.
Maybe the reek checker could conditionally pass this flag if the reek version is lower than 2.

Edit:
I've removed the --quiet flag from the code of the checker and it works fine.

**Comment by lcd047** [comment]
Ok, done in 372daff.

There's a deeper problem related to reek and checking versions (and I don't have any reasonable solution to it for now), but you won't run into it for the time being.  Oh well.

**Comment by cartolari** [comment]
That's great, thanks.
