### ISSUE TITLE
Losing code syntax highlighting when changing buffer

### ISSUE THREAD

**Issue by sim590** [scrooloose/syntastic#1325]
Let's say I have syntastic enabled and that I open these two files in the same window :
![sshot1](https://cloud.githubusercontent.com/assets/4147254/6211641/3f96f9e4-b5aa-11e4-8223-eff833893bef.png)
![sshot3](https://cloud.githubusercontent.com/assets/4147254/6211644/43659e04-b5aa-11e4-847c-f88f6e7c7863.png)

I jump from a file to another by changing the buffer in the window. Sometimes, when syntastic notifies me about syntax errors and after changing the buffer inside the window (I haven't noticed anything else that would trigger that), I lose code syntax highlighting :

![sshot2](https://cloud.githubusercontent.com/assets/4147254/6211642/41ea3ecc-b5aa-11e4-9c9c-0652cab3c9f0.png)

When I change the buffer from the `.cpp` file to the `.hpp` file, syntastic's window disappears (as if it wouldn't do any syntax check inside `.hpp` file). Does changing back and forth the buffer inside the same window would kind of confuse syntastic ?

I know that after the bug has appeared, it keeps coming back (after having `:set syntax=cpp`) each time I go back and forth changing buffers. I've also noticed that disabling syntastic (`:SyntasticToggleMode`) does solve the issue. However, until I restart vim, reenabling syntastic will make the bug come back. That's a bit odd.

What's happening?

**Comment by lcd047** [comment]
Syntastic has nothing to do with enabling or disabling syntax highlighting (not intentionally anyway).  Does the problem still occurs if you disable all other plugins?  What OS do you have, what version of Vim, and what version of syntastic?

`:SyntasticToggleMode` doesn't "disable syntastic", it just toggles checking mode between active and passive.  What exactly did you do to run into the problem you're accusing?  Do you have a minimal set of files that can be used to reproduce the problem?  When the problem occurs, is the `filetype` of the file in cause still correct?

**Comment by lcd047** [comment]
One more thing: do you have `autocmd`s that get triggered when you switch buffers?  If yes, does the problem still occur if you disable them?

**Comment by sim590** [comment]
- OS : Archlinux
- Vim version : latest (it's archlinux), Vim 7.4.617
- Syntastic version : 3.6.0-14
- I have some autocommands

Here's a small [video](http://www.dailymotion.com/video/x2hbqp0_debugging-syntastic-bug_tech) showing the bug.

The bug doesn't happen systematically. While the bug occured more than one time, I haven't been able to reproduce it with or without my other plugins enabled yet just after your posts. I'll give more information after testing more.

**Comment by lcd047** [comment]
> Here's a small [video](http://www.dailymotion.com/video/x2hbqp0_debugging-syntastic-bug_tech) showing the bug.

Please try to answer my questions above.  The point is not to convince me you're seeing a problem (I do take your word for it), but to find out what's going on.

**Comment by lcd047** [comment]
Ping.

**Comment by sim590** [comment]
I haven't work on this yet. I was busy doing something else. I have work to do using. I'll be able to give more detail in a week or two.

**Comment by lcd047** [comment]
For what it's worth: I took a look at your [vimrc](https://github.com/sim590/dotfiles/blob/master/.vimrc).  Your problem might be related to [these lines](https://github.com/sim590/dotfiles/blob/2d1af9d53ec74b548617ccb0a085d20470031938/.vimrc#L72-L73).  `autocmd`s are fragile and non-deterministic.  A complete explanation of why these might lead to the behaviour you're seeing is beyond the scope of this tracker, but you can take my word for it that it's a bad idea to mix them with other `BufWrite`s.

**Comment by sim590** [comment]
I'm sorry, but this vimrc file is *really* old. I've changed it alot and the `BufWrite` commands aren't there anymore.

**Comment by lcd047** [comment]
Whatever.  My point still stands: the more `autocmd`s you have (either yours or brought in by plugins), the more trouble you're asking for. :) Setting things like `filetype` and `tabstop` doesn't count, but anything more complex than that does.

**Comment by Battlingtoads** [comment]
Any update on this? I'm having the same issue. I'll try disabling the other plugins and see if that fixes the issue. Also, it only happens when I switch to a specific buffer using ":b foo.cpp". I'm running Ubuntu 14.04, vim 7.4.273, syntastic 3.5.0 - 72.

**Comment by lcd047** [comment]
Still waiting for answers to the questions above:

* Does the problem still occur if you disable all other plugins?
* What exactly did you do to run into the problem you're accusing?
* Do you have a minimal set of files that can be used to reproduce the problem?
* When the problem occurs, is the `filetype` of the file in cause still correct?
* When the problem occurs, what is the output of `:syntax`?
* Do you have `autocmd`s that get triggered when you switch buffers?
* If yyou do have `autocmd`s that get triggered when you switch buffers, does the problem still occur if you disable them?

**Comment by lcd047** [comment]
Ok, please feel free to reopen this when you feel ready to answer the questions above.

**Comment by AnwarShah** [comment]
I was experiencing this problem and disabling minibufexplorer plugin seems to have resolved this. Sorry for bumping old thread
