### ISSUE TITLE
feature request: stylus support

### ISSUE THREAD

**Issue by gre** [scrooloose/syntastic#1328]
syntastic is awesome!

Would be great to have stylus support too

**Comment by lcd047** [comment]
From a quick look, I think stylus would make an awkward syntastic checker at best.  Syntax checking seems to be almost an afterthought for stylus, error reporting is less than great (for various reasons), and simulating a parse-only mode would be problematic (again, for various reasons).  I'd say handling included files is likely to be problematic too. _shrug_

That said however, working pull requests are welcome.  There's also a [guide](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide) for doing it.

**Comment by faceleg** [comment]
Does this make it easier?

https://github.com/rossPatton/stylint

**Comment by lcd047** [comment]
@faceleg Much better, yes.  Please see edde4c5.

**Comment by faceleg** [comment]
PHEW! I was hoping you'd twiddle your fingers with some of your Syntastic magic, otherwise I was going to have to hack and slash a solution together...
