### ISSUE TITLE
:Explore - E464: Ambiguous use of user-defined command

### ISSUE THREAD

**Issue by sime** [scrooloose/syntastic#1330]
Since installing syntastic I am unable to use <code>:Explore</code>. I get the following message:

E464: Ambiguous use of user-defined command

**Comment by lcd047** [comment]
This has nothing to do with syntastic.
```sh
$ cd syntastic
$ fgrep -ir explore | wc -l
0
```

**Comment by lcd047** [comment]
`:Explore` is part of `netrw`.  You should consider reporting this to the `vim-dev` list; the author of `netrw` is subscribed, and might help you.

**Comment by sime** [comment]
Hrm, though when I remove syntastic from ~/.vim/bundle/ it works.

**Comment by sime** [comment]
Ahh, the problem is the shortform. <code>:E</code> fails. <code>:Ex</code> works.

**Comment by 3den** [comment]
For me both fail.

**Comment by 3den** [comment]
but doing `:Explore` works.

**Comment by lcd047** [comment]
... and both are still unrelated to syntastic.
