### ISSUE TITLE
R file syntax checking with lint doesn't work

### ISSUE THREAD

**Issue by tinyheero** [scrooloose/syntastic#1332]
Hi,

I am trying to get syntastic working with R files. I've installed syntastic through Vundle. Then I got the lint R package installed (https://github.com/scrooloose/syntastic/wiki/R:---lint)

Added the following to my ~/.vimrc:

```
let g:syntastic_r_lint_styles = 'list(spacing.indentation.notabs, spacing.indentation.evenindent)'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
set tabstop=8
```

When I start a test.R file, I ran : SyntasticInfo

```
Syntastic version: 3.6.0-32 (Vim 704, Darwin)
Info for filetype: r
Global mode: active
Filetype r is active
The current file will be checked automatically
Available checker: lint
Currently enabled checkers: -
```

It doesn't seem to recognize the lint checker? Is there something I missed in enabling? No checking seems to be working.  

I am running vim version 7.4.488, syntastic version 3.6.0-32

Thanks in advance for my any help.

**Comment by lcd047** [comment]
The checker is available but not enabled.  Try something like this:
```vim
let g:syntastic_r_checkers = ['lint']
```
You also probably don't want to check only formatting, so you might leave `g:syntastic_r_lint_styles` to the default (the example in the manual is there to illustrate the syntax, not to be copied as it is).

**Comment by tinyheero** [comment]
Ah that worked. Thanks!
