### ISSUE TITLE
feature request: apiary blueprint markdown files

### ISSUE THREAD

**Issue by catesandrew** [scrooloose/syntastic#1335]
This will depend on snowcrash.

```
$ snowcrash apiary.apib -l

OK.
warning: (10)  headers asset is expected to be a pre-formatted code block, every of its line indented by exactly 12 spaces or 3 tabs :13012:63
```

**Comment by lcd047** [comment]
Can you please explain for the uninitiated, preferably in full sentences:

* what is apiary
* what is snowcrash
* what am I supposed to see above
* what Vim filetype you want to check
* what application is supposed to run the checks
* what is the typical workflow for the files you want to check
* where can I find the relevant applications
* where can I find sample files that produce the errors you want to detect.

**Comment by catesandrew** [comment]
[apiary](http://apiary.io/) is the company behind [api blueprint](http://apiblueprint.org/). They open source the latter. If you choose to you can pay them to host your files, etc, otherwise you're on your own to build APIs. They extend markdown simple markdown to give meaning to request, response, routes, parameters, body, and headers.

- API Blueprint is the specification of markdown for writing API documentation.
- [Snowcrash](https://github.com/apiaryio/snowcrash) is the parser.
- `apiblueprint` is the vim filetype from [vim-apiblueprint](https://github.com/kylef/apiblueprint.vim).
- `snowcrash` is the application you would run against the markdown files for the checks. Typically they end with `.apib`.
- Typical workflow is open, edit, save, run `snowcrash -l <input file>` to get a list of errors/warnings. Fix errors, warnings, retry.
- I'll look into generating some sample files to hit the error conditions.

Thanks!

**Comment by lcd047** [comment]
Good summary, thank you.  I think I can figure out the error format from the sources, but a few sample files would still come in handy.

**Comment by lcd047** [comment]
Ok, done in 5214f00.
