### ISSUE TITLE
Syntastic fail in check C language errors [SOLVED]

### ISSUE THREAD

**Issue by iasj** [scrooloose/syntastic#1338]
I installed syntastic with pathogen today (24/feb/2015). I've been testing it with this C code
```c
#include<stdio.h>                                            
 int main()
{
    printf("\n")
    return 0;
}
```
clearly there is an error syntax (missing ';' after printf call). But syntastic din't show error messages.
I puted this in my ~/.vimrc
```vim
let g:syntastic_c_checkers = ["gcc"]
```
and yet, getting nothing.
The solution was:
EDIT the file ~/.vim/bundle/syntastic/syntax_checkers/c/gcc.vim. Find this piece of code
```vim
call g:SyntasticRegistry.CreateAndRegisterChecker({
    \'filetype': 'c', 
    \'name': 'gcc' })
```
and change it to this
```vim
call g:SyntasticRegistry.CreateAndRegisterChecker({ 'filetype': 'c', 'name': 'gcc' })
```
And that's it!
And sorry for my poor english!

**Comment by lcd047** [comment]
I'm afraid you're confused.  Your change doesn't accomplish anything useful.

**Comment by iasj** [comment]
Yeah, i realised this too. I did this because i saw the ')' character in
red. So i thought that was a vim's error sign. I changed and syntastic
started to work. But today is not working any more. So i have no idea what
is going on.
And yet, sorry for that mistake, my bad!

**Comment by iasj** [comment]
It did work quite well with [neocomplete](https://github.com/Shougo/neocomplete.vim).
I was using it with [YouCompleteMe](https://github.com/Valloric/YouCompleteMe}, and, somehow they wasn't woking well together, but only for C-Family, once i have tested it with python too. So, i think i'll use neocomplete, instead!

**Comment by lcd047** [comment]
You might save yourself a lot of time by spending a few minutes to read the manuals of the tools you're using.  YCM disables syntastic by default (but there is a way to [re-enable](https://github.com/Valloric/YouCompleteMe#user-content-the-gycm_show_diagnostics_ui-option) it).  `:SyntasticInfo` in recent versions of syntastic would have also told you this.

**Comment by iasj** [comment]
Yeah. I do read the manuals, but it just happened of i do not read YCM's manual this time.
But now i'm confused. I didn't change any thing in YCM configuration, and yet syntastic worked well for python syntax check.

**Comment by lcd047** [comment]
> But now i'm confused. I didn't change any thing in YCM configuration, and yet syntastic worked well for python syntax check.

This would be a good time to read YCM's manual (or at least the section I pointed you to).
