### ISSUE TITLE
cpp `-isystem` fails to include, while `-I` works

### ISSUE THREAD

**Issue by scraimer** [scrooloose/syntastic#1340]
I have a header file that syntastic reports that GCC cannot find. I suspect this is because I specified the include directory with `-isystem` instead of with `-I`. And IIRC, syntastic has special handling for `-I` in `.syntastic_cpp_config`.

I set my .syntastic_cpp_config to have this line:

    -isystem ../../env/rfa6.4.1.L1.linux/setup/Include

And although there is a file `../env/rfa7.2.1.L1.linux/Setup/Include/SessionLayer/OMMItemEvent.h`, syntastic would tell me that GCC reports an error including it, since the file was not found.

Once I changed from `-isystem` to `-I`, it worked.

Note: If you're not familiar with `-isystem`, it is a GCC flag that says "here's an include path to files that are part of the system". Functionally, it means that GCC won't report warnings about files included from that directory. It's useful when working with 3rd party software headers, since we can't change them anyway.

I suspect that the second cause of the issue is that the path to the include directory is relative. And without the special handling used for `-I`, it isn't being resolved correctly.

With that being said, I did a cursory look in the repository, but couldn't find where the "special handling" for `-I` was located in the code. Maybe I just imagined reading about it, then.

Thanks,
Shalom

**Comment by lcd047** [comment]
You need to put `-isystem` and `../../env/rfa6.4.1.L1.linux/setup/Include` on separate lines.  Syntastic doesn't try to keep track of options with arguments, with the exception of `-I`.  This is [documented](https://github.com/scrooloose/syntastic/wiki/Configuration-Files#format), and the corresponding file is linked from the relevant [wiki page](https://github.com/scrooloose/syntastic/wiki/C--%3A---gcc).

**Comment by scraimer** [comment]
Oh. Thanks!
