### ISSUE TITLE
Unable to lower verbosity with Ruby MRI checker

### ISSUE THREAD

**Issue by Carpetsmoker** [scrooloose/syntastic#1346]
I am unable to lower the verbosity of the Ruby MRI checker, I would like to get rid of these messages:

    a.rb|4 warning| statement not reached                                                                                            
    a.rb|2 warning| assigned but unused variable - a

I need to pass `-W1` to `ruby` (default is `-W2`), so I added:

    let g:syntastic_ruby_mri_args = "-W1"

to my vimrc;  but this doesn't work because `syntax_checkers/ruby/mri.vim` does:

    let makeprg = self.makeprgBuild({ 'args_after': '-w -T1 -c' })

The `-w` flag seems to be the same as `-W2`, and takes precedence over my `-W1`.

... I'm not sure what's the best way to solve this? I can't seem to override the `args_after` as far as I can figure out. Perhaps setting `g:syntastic_ruby_mri_args` to the default of `-w` so it can be overridden?

**Comment by lcd047** [comment]
Right, these should be configurable.  Please try fe3a48f.

**Comment by Carpetsmoker** [comment]
Thanks @lcd047  , this works as expected ;-)
