### ISSUE TITLE
eslint not working?

### ISSUE THREAD

**Issue by jasonkuhrt** [scrooloose/syntastic#1347]
I'm using the new release of `eslint 0.16.1` but not information is coming through in vim...

I'm actually also unable to get `eslint` working with `atom` right now https://github.com/AtomLinter/linter-eslint/issues/39 for what its worth...

How would I go about getting more debug info about what syntactic is doing? I have exactly zero feedback right now.

**Comment by lcd047** [comment]
> I'm using the new release of `eslint 0.6.1` but not information is coming through in vim...

I presume you mean 0.16.1.  Seems to work fine here.

> How would I go about getting more debug info about what syntactic is doing?

* Active / enabled checkers: `:SyntasticInfo`
* Debugging information: `let g:syntastic_debug = 1`, run the checker, run `:mes`
* Debugging information with checker's output: `let g:syntastic_debug = 3`, then same as above

More information:

* Syntastic manual: `:help syntastic`
* [FAQ](https://github.com/scrooloose/syntastic#faq)
* [ESLint checker](https://github.com/scrooloose/syntastic/wiki/JavaScript%3A---eslint)
* [Checker Guide](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide)

**Comment by jasonkuhrt** [comment]
> I presume you mean 0.16.1. Seems to work fine here.
 
Yes

**Comment by jasonkuhrt** [comment]
I ran those three commands but it seems very vague:

![1](https://cloud.githubusercontent.com/assets/284476/6548822/26482782-c5dc-11e4-83b0-b9a5648a88a8.png)
![2](https://cloud.githubusercontent.com/assets/284476/6548823/264b432c-c5dc-11e4-8350-724a76cfe983.png)
![3](https://cloud.githubusercontent.com/assets/284476/6548824/264bd526-c5dc-11e4-99c7-d626012c8fd2.png)

**Comment by jasonkuhrt** [comment]
Ok I seem to have gotten something working now:

![screen shot 2015-03-08 at 9 48 20 pm](https://cloud.githubusercontent.com/assets/284476/6548849/ec210c08-c5dc-11e4-87f4-3a31a36a9403.png)

I'll close this issue soon probably.

**Comment by schmittyjd** [comment]
@jasonkuhrt what was your solution to this? I am running into a similar problem

**Comment by jasonkuhrt** [comment]
Can't remember, I'm using `spacemacs` now.

**Comment by lcd047** [comment]
@schmittyjd My first post above gives instructions for debugging.  Please post a new issue if you can't get it working.

**Comment by schmittyjd** [comment]
@lcd047 I did the same and got very similar output to jason. I will probably make an issue soon
