### ISSUE TITLE
Moving cursor to error highlighting resets cursor position.

### ISSUE THREAD

**Issue by jordwalke** [scrooloose/syntastic#1352]
Suppose you have the following:

![cursor](https://cloud.githubusercontent.com/assets/977348/6605425/340ceb6a-c7ed-11e4-8828-94bdf0d10f69.png)

With Vim, when you move up and down the cursor position is either the last horizontal place that a horizontal movement occured (the last horizontal position that was explicitly moved left/right to) or the maximum length of the current line (whichever is smaller.

So in this screenshot, if I move down, the cursor should move to the end of true. Then when I move back up, the cursor should be exactly where it is in this picture.

The problem is that if there's a syntastic highlighted error (underline), moving down to the error line, then back up does not re-place the cursor back to where it is in the picture. The cursor position is "reset" to be at the last o of Function.

Vim's cursor behavior is very specific in this respect - it's what gives it that "authentic Vim feel", that is almost impossible to recreate.

I reported the issue on another plugin that uses Syntastic.

https://github.com/the-lambda-church/merlin/issues/229

**Comment by lcd047** [comment]
Sorry to disappoint you, but this is not related to syntastic either.  Syntastic has exactly zero control over cursor position in the context you describe.  It does sound like a bug in Vim though; please report it to vim-dev.

**Comment by lcd047** [comment]
Right, I can reproduce the problem outside syntastic.  From the position above:

* move down
* run `:set noshowcmd`
* move up

Feel free to report this to vim-dev.

**Comment by lcd047** [comment]
For what it's worth, my report at vim-dev: [Minor w_curswant bug](https://groups.google.com/forum/#!topic/vim_dev/XX6VVJq_miA).

**Comment by lcd047** [comment]
This is [fixed in Vim 7.4.659](https://code.google.com/p/vim/source/detail?r=5a12a68613670ddb7d3be0c693738400c61ef24b).
