### ISSUE TITLE
Run syntastic on unsaved buffers.

### ISSUE THREAD

**Issue by jordwalke** [scrooloose/syntastic#1354]
How can we have Syntastic run on unsaved buffers, with programs that find errors (at least parse errors), without saving them to disk. My use case is that I want to run a formatting program, and then refresh Syntastic so that the line locations reflect the new formatting, but that will only work if I save the file to disk. Usually users don't want to necessarily save just because they formatted.

**Comment by jordwalke** [comment]
For the sake of simplicity, suppose I have a string in my script that is the standard output of my error checking program. How can I give this to Syntastic and say "Here's the results you would have received had I saved the program".

**Comment by lcd047** [comment]
> How can we have Syntastic run on unsaved buffers, with programs that find errors (at least parse errors), without saving them to disk.

The short answer is you can't.

Think of it for a moment.  You want to pass a structure in memory to an external program that doesn't know anything about Vim and doesn't expect any kind of IPC.  How would that be accomplished?

Actually, it can be done for _some_ checkers that run entirely inside Vim, using one of the embedded interpreters (provided that Vim has been compiled with support for them).  An experiment with that is described in #1351, for perl and python; ruby and lua might be possible too.  But that trick works only for a few very special checkers, and it's still an experiment (which doesn't seem to attract any interest so far anyway).  It isn't possible in general.

**Comment by jordwalke** [comment]
>> Think of it for a moment. You want to pass a structure in memory to an external program that doesn't know anything about Vim and doesn't expect any kind of IPC. How would that be accomplished?

Standard input?

**Comment by lcd047** [comment]
> Standard input?

The vast majority of checkers want a real file.  And no, saving the buffer to a temporary file and checking that instead won't work either, but the reasons for that are more involved (it has been discussed in the past, search the archives if you're curious).

**Comment by jordwalke** [comment]
Why not optionally support checkers that *do* support standard input?

**Comment by lcd047** [comment]
Because it would be a huge pain in the rear for very little return?
