### ISSUE TITLE
CoffeeScript checker says "can't parse version string" due to the shell being set to tcsh

### ISSUE THREAD

**Issue by Carpetsmoker** [scrooloose/syntastic#1355]
Since about a week or 2, I get this error whenever I open a `.coffee` file:

	syntastic: error: checker coffee/coffee: can't parse version string (abnormal termination?)

The problem seems to be this line in `syntax_checkers/coffee/coffee.vim`:

    let ver = self.getVersion(self.getExecEscaped() . ' --version 2>' .  syntastic#util#DevNull())

`2>` doesn't work because my shell is set to `/bin/tcsh`. I could set the `shell` in my vimrc, but this has some side-effects such as my tcsh aliases no longer working.

I'm not sure why it used to work before, it could be I was running a very outdated Syntactic version (it's been like this since June 2013).

In any case, in `g:SyntasticChecker.getVersion` the command is executed as:

    let version_output = system(command)

This would perhaps be better as:

	let version_output = s:system(command)

Where `s:system()` is:

	fun! s:system(command)
		try 
			let sh = &shell
			if !(has('win32') || has('win64'))
				set shell=sh
			endif
			return system(command)
		finally
			let &shell = sh
		endtry
	endfun

Or maybe even as:

	fun! s:system(command)
		try
			let sh = &shell
			if !(has('win32') || has('win64'))
				set shell=sh
			endif
			if type() == 3 " List
				return system(join(map(a:command, 'syntastic#util#shescape(v:val)'), ' '))
			else
				return system(a:command)
			endif
		finally
			let &shell = sh
		endtry
	endfun

for auto-escaping ease of use.

This will make sure you're always using a Bourne shell.  This might also fix some issues for `fish` users.

Also see [the fix in vim-plug](https://github.com/junegunn/vim-plug/commit/79da5b2654c8148774eb8a07dd551a63f3eebe5d)

I can make a pull request for this by the way :-)

**Comment by lcd047** [comment]
> `2>` doesn't work because my shell is set to `/bin/tcsh`.

Right: syntastic pretty much assumes Bourne shell syntax for redirections.

> I could set the `shell` in my vimrc, but this has some side-effects such as my tcsh aliases no longer working.

I'm not sure I follow.  What does Vim's shell has to do with your aliases?

> I'm not sure why it used to work before, it could be I was running a very outdated Syntactic version (it's been like this since June 2013).

As far as I can tell, the `coffee` checker always did that.  I don't recall why `2>/dev/null` is needed though.

> This will make sure you're always using a Bourne shell.

Sadly, many people are running Zsh and have it configured differently than the stock sh.  Forcing syntastic to use sh would break many configurations.

> Also see [the fix in vim-plug](https://github.com/junegunn/vim-plug/commit/79da5b2654c8148774eb8a07dd551a63f3eebe5d)

I suppose the author has never run this on BSD. :)

**Comment by Carpetsmoker** [comment]
> I'm not sure I follow. What does Vim's shell have to do with your aliases?

What I meant was, if I use `set shell=/bin/sh` in my vimrc, my aliases that I defined in `tcsh` no longer work when using `:!...` (since those are `tcsh` aliases, and not `sh` aliases)... So while this fixes this issue, it also causes some side-effects...

> Sadly, many people are running Zsh and have it configured differently than the stock sh. Forcing syntastic to use sh would break many configurations.

We just set it temporarily before executing `system()`, and reset it to what-ever it was afterwards. I'm not sure if I understand how this will break anything for anyone (and `zsh` users in particular)? It would really be the same as using `sh -c cmd`, except with less quoting issues.

We could add a new `syntastic_shell` option, if it's undefined we do nothing (so nothing changes in the default behaviour), and if it's set we use the value for (temporarily) setting the shell.

**Comment by lcd047** [comment]
> We just set it temporarily before executing `system()`, and reset it to what-ever it was afterwards. I'm not sure if I understand how this will break anything for anyone (and `zsh` users in particular)?

Once upon a time syntastic would look for bash, and point shell to it if it found it (don't ask me why it did that; it was way before my time with syntastic). :) Then some day somebody complained that his checkers were not detected.  As it turns out, people do things like install unreleased versions of ruby in their `$HOME`, and set up a shitload of variables to make them work.  But they do this for their shell, which may or may not read the same profile files as bash.  So there you have it: config schizophrenia. :)

> We could add a new `syntastic_shell` option, if it's undefined we do nothing (so nothing changes in the default behaviour), and if it's set we use the value for (temporarily) setting the shell.

Yeah, that's more or less what I had in mind too.  I'll think of a patch.

**Comment by lcd047** [comment]
On a side note, this is likely to be the explanation for why you could use the coffee checker with older versions of syntastic: you were actually running it with under bash.

**Comment by lcd047** [comment]
Ok, please try 47eabae.

**Comment by Carpetsmoker** [comment]
Thanks, that works :-)

I also noticed just not there's already a `:help syntastic-fish`, `:help  syntastic-powershell`,  and `:help syntastic-fizsh`, all of which recommend setting `shell`, so these should probably be updated.

Also, the error message:

> syntastic: error: checker coffee/coffee: can't parse version string (abnormal termination?)

Isn't very useful ... I had to dig in the code to figure out it was my shell. Perhaps it could be updated to something like:

> syntastic: error: checker coffee/coffee: can't parse version string (abnormal termination? See :help  syntastic_shell`)

Or some such ...

**Comment by lcd047** [comment]
In the vast majority of cases, "can't parse version string" happens for one of two reasons: the external checker is broken, or the format of the version printed by the checker has changed.  The shell is really the last thing to to suspect when looking for the root cause...
