### ISSUE TITLE
I have no idea, so I have to ask you for help.

### ISSUE THREAD

**Issue by NixusCN** [scrooloose/syntastic#1356]
![1](https://cloud.githubusercontent.com/assets/4592706/6648230/503dc85a-ca12-11e4-9c80-0ce83a32bf67.png)
It's very perfect when I installed syntastic first,but now, something is wrong.
I don't know that the info is right in the pic, and syntastic is not work.
After I checked a lot of info, I have to ask you for help.
Please help me, I'm looking forward to your reply.
Thank you very much.

**Comment by lcd047** [comment]
This is explained in the [FAQ](https://github.com/scrooloose/syntastic#faqinfo).

**Comment by NixusCN** [comment]
@lcd047 I have again and again,read the FAQ and #780 #989,but the problem still exists. I have not any ideas.

let g:syntastic_enable_php_checker = 1
let g:syntastic_php_checkers = ['php', 'phpcs', 'phpmd']
I have added 2 lines in the _vimrc above, 
then enter :SyntasticInfo, show some info in the command:
Syntastic version:3.6.0-57 (Vim 704,Windows)
Info for filetype:php
Global mode:passive
Filetype php is passive
The current file will not be checked automatically.
Available checkers:-
Current enabled checkers:-

**Comment by lcd047** [comment]
You need to have php, phpcs, and phpmd available in your `$PATH`.  Install them and fix your `$PATH`, that's all there is to it.  Once you do that you'll see them as available in the output of `:SyntasticInfo`.

**Comment by NixusCN** [comment]
@lcd047 Thank you very much. It's my mistake. Thanks.

**Comment by NixusCN** [comment]
@lcd047  It's okey now.
