### ISSUE TITLE
Syntactic checking on file save despite setting that option to 0

### ISSUE THREAD

**Issue by drewverlee** [scrooloose/syntastic#1357]
So the probem is that from within gvim or vim 

when i'm in a fie like test.py
"
def foo(): return "foo"
"
and i save ":w" i get the syntaticCheck despite having:

let g:syntastic_check_on_wq = 0

when i would expect to get NO syntactic check

my vimrc : https://gist.github.com/drewverlee/882901f9605b3983d66c

the output of a debug log: https://gist.github.com/drewverlee/87596f81b105aabe3d25

I tried a fresh install of the plugin. Update and restarting my comp. I looked over my autocmds and didn't see anything odd. Everything else behaves as it should.

Probably irrelevant: 
At one point i toyed with the idea of setting the syntatic check to happen on every keystroke
something like "autocmd anykeystroke <buffer> * :syntaticCheck" but i disabled it (and its not checking on every keystroke anyway"

**Comment by lcd047** [comment]
The term you're looking for is "passive mode".  Try `:help syntastic_mode_map`.

**Comment by drewverlee** [comment]
Thanks!, Looking at my .vimrc its obvious i knew what at one point :).
