### ISSUE TITLE
Only use flow checker when applicable.

### ISSUE THREAD

**Issue by jordwalke** [scrooloose/syntastic#1358]
I have configured syntastic as follows:

    let g:syntastic_javascript_checkers=['flow'] 

And everything works great when I am in a flow project/file. However, when I open a non-flow JS file I get the following error:

    syntastic: warning: checker javascript/flow: unknown error format
    Press ENTER to continue

It is quite annoying. Can the detection be made more intelligent?

**Comment by lcd047** [comment]
Please see 7b8526b.
