### ISSUE TITLE
validator.nu API HTTPS url

### ISSUE THREAD

**Issue by nickbalestra** [scrooloose/syntastic#1359]
I had problems making the validator.nu working for html. 

After checking the configuarion I was able make it work by setting the api url using https instead of http:

```g:syntastic_html_validator_api = 'https://validator.nu/'```

Can anyone reproduce/confirm this?

**Comment by lcd047** [comment]
Right, the API is now over HTTPS.  The main problem was however that curl didn't allow redirects.  Please try 84add5b.
