### ISSUE TITLE
Errors disappear when centering cursor with nnoremap j jzz on OS X

### ISSUE THREAD

**Issue by msto** [scrooloose/syntastic#1360]

**Comment by msto** [comment]
Hi,

Sorry, I accidentally submitted the bug when filling out the title. I'm encountering a strange issue where the description of the syntax error that should appear in the status bar at the bottom of the screen disappears when I include the following in my ~/.vimrc.

    nnoremap <C-U> 11kzz
    nnoremap <C-D> 11jzz
    nnoremap j jzz
    nnoremap k kzz
    nnoremap # #zz
    nnoremap * *zz
    nnoremap n nzz
    nnoremap N Nzz

It flashes for a brief moment, but is then apparently suppressed or overwritten. Commenting those lines out resolves the issue, and the syntax error messages remain persistent.  

However, this bug is only occurring on my laptop, where I'm using a homebrew installation of vim 7.4 on OS X 10.10.2. It does not occur on a remote cluster I work on, where I'm using vim 7.4 on RHEL 6.2 and an identical vimrc. I've tried uninstalling and re-installing Syntastic and it had no effect. 

I'm not sure if this qualifies as a bug or if I'm missing something on my end, so I apologize if that's the case and I'm wasting your time. For now I'm simply removing those lines from the vimrc, but I really do prefer a centered cursor so I'd appreciate any assistance in resolving the issue. Could you please let me know if this is a known issue or if there's a simple fix?

Thanks!

**Comment by msto** [comment]
Also, this occurs in both Python files being checked by flake8 and LaTeX files being checked by lacheck. The Syntastic symbols in the side column that mark rows with an error remain unaffected.

**Comment by msto** [comment]
Here's a brief screencast of the behavior in question.

https://www.youtube.com/watch?v=UjXrOv_RYxg

(I'm now aware that scikit-learn's `cross_validation.train_test_split()` exists and this code is a nice example of unnecessary redundancy)

**Comment by lcd047** [comment]
This seems to be a bug in Vim.  To reproduce it:

* `:echo 'foo'`
* `zz`

If `zz` causes a scroll, `foo` is erased.  I'll post a bug report to vim-dev.

**Comment by lcd047** [comment]
On a closer look this is the intended behaviour: redraws also clear the status line.  Well, syntastic can't even detect that `zz` in your maps has caused a scroll, let alone do something about it.  Sorry about that.

**Comment by msto** [comment]
Makes sense. No worries, thanks for looking into it. I wasn't sure why this would be OS X specific so I went back and realized the line I was testing on the RHEL server was early enough in the file that it wasn't provoking a scroll, and reproduced the same behavior with a later line. 

Ah well, guess I'll learn to live without the center cursor. Sorry for the trouble!
