### ISSUE TITLE
Can't override 'go vet' executable (can override golint though)

### ISSUE THREAD

**Issue by aktau** [scrooloose/syntastic#1364]
I'm doing some development and want to use an alternate `go vet` to check some things. I do the same for golint, so I do something like this:

```vim
let g:syntastic_go_golint_exec = '~/bin/mygolint'
let g:syntastic_go_govet_exec = '~/bin/mygovet'
```

For golint (`mygolint`) this works fine, but syntastic seems to ignore `mygovet`. I'm not the best viml coder out there, but the salient difference between the two seems to be:

golint.vim:

```vim
    let makeprg = self.makeprgBuild({})
```

govet.vim

```vim
    let makeprg = 'go vet'
```

Said in another way, `go vet` is hardcoded. Can this be changed? If so, what would be the best way to go about it?

Thanks!

**UPDATE**:

I should have, of course, ran `:PluginUpdate` first. I see that the current `govet.vim` code is:

```vim
    let makeprg = self.getExec() . ' vet'
```

I'll try to see if I can get this to work but I'll probably need to do some contortions with an alternate dispatching script.

**Comment by lcd047** [comment]
> For golint (`mygolint`) this works fine, but syntastic seems to ignore `mygovet`.

Yes, this is [documented](https://github.com/scrooloose/syntastic/wiki/Go%3A---govet).

> `let makeprg = self.getExec() . ' vet'`

Yes, you can override the `go` executable.  You can't override the `vet` argument.

> I'll try to see if I can get this to work but I'll probably need to do some contortions with an alternate dispatching script.

What exactly are you trying to do?

**Comment by aktau** [comment]
> What exactly are you trying to do?

Like I said, running a custom `govet` binary. Anyway, I "fixed" it by wrapping it in a shell script which replaces the "vet" argument with `.`. It works fine. Thanks!
