### ISSUE TITLE
Unable to ignore a certain Ruby MRI warning

### ISSUE THREAD

**Issue by tsigo** [scrooloose/syntastic#1366]
I've got this valid RSpec code:

```ruby
describe Foo do
  context "some context" do
    let(:foo) { build(:foo) }

    context "on create" do
      it "does something" do
        expect { foo.save }.to change(foo, :bar).from(nil).to('baz')
      end
    end
  end
end
```

But MRI spits out a warning: `warning: possible reference to past scope - foo` inside the `it` block.

I've tried to ignore these warnings with `let g:syntastic_ruby_mri_ignore_errors=[" possible reference to past scope"]` with no effect. I was able to get syntastic to ignore them with `let g:syntastic_ruby_mri_args = "-W1"` but I'm paranoid and would prefer to ignore just the one specific warning instead.

I'm sure it's a dumb mistake with my configuration for ignoring the specific error and would appreciate some help. Thanks!

**Comment by lcd047** [comment]
> I've tried to silence these warnings with `let g:syntastic_ruby_mri_ignore_errors=[" possible reference to past scope"]` with no effect.

This is the expected behaviour, since `syntastic_*_ignore_errors` exists only for the `tidy` checker. :)

Try `:help 'syntastic_quiet_messages'` for a mechanism that works for all checkers.

**Comment by tsigo** [comment]
Thank you! Fixed it with this:

```
    let g:syntastic_quiet_messages = {
        \ "type":    "style",
        \ "regex":   '\m.*reference to past scope.*',
        \ "file:p":  ['\m_spec\.rb$'] }
```

Also apparently this was only a Ruby 2.2.0 warning; 2.1.5 didn't care.

**Comment by lcd047** [comment]
This is mostly wrong.  `"type": "style"` kills all style messages for all checkers, and `"file:p":  ['\m_spec\.rb$']` kills all messages referring to `_spec.rb`.  I'd suggest something like:
```vim
let g:syntastic_ruby_mri_quiet_messages = { 'regex': 'reference to past scope' }
```

**Comment by tsigo** [comment]
Ah ha. Thanks again.
