### ISSUE TITLE
go "Syntax: line 6" on save

### ISSUE THREAD

**Issue by lloydde** [scrooloose/syntastic#1367]
If I save, ':w', without any changes, https://github.com/cdarwin/go-koans/blob/master/about_basics.go I receive an error in the vim status bar.

ENV
up-to-date tpope/vim-sensible , scrooloose/syntastic ,  fatih/vim-go ,  bling/vim-airline

SCREENSHOT
![go-koans_ _vim](https://cloud.githubusercontent.com/assets/962387/6772495/24a053aa-d0bd-11e4-8ea9-097124ced6fc.png)

**Comment by lcd047** [comment]
When you write the file syntastic runs the `go` checker.  Go doesn't have a syntax checking mode, so the `go` checker is not very smart: it simply runs `go fmt` and `go build` in the base directory of the current file, and shows you the results.  Running `go build` in the `go-koans` directory gives this:
```sh
$ go build
# _/home/lcd047/tmp/go-koans
./about_allocation.go:6: undefined: assert
./about_allocation.go:6: undefined: __int__
./about_allocation.go:13: undefined: assert
./about_allocation.go:13: undefined: __int__
./about_allocation.go:16: undefined: assert
./about_allocation.go:16: undefined: __int__
./about_allocation.go:18: undefined: __positive_int__
./about_allocation.go:19: undefined: assert
./about_allocation.go:22: undefined: assert
./about_allocation.go:22: undefined: __int__
./about_allocation.go:22: too many errors
```
These are your 11 errors.

It doesn't end here though.  Should you have followed the [FAQ](https://github.com/scrooloose/syntastic#settings) and add the recommended settings to your `vimrc`, you would have seen the errors above in a loclist window.  On the other hand, `vim-go` runs its own checks, and shows the results in a quickfix window.  This is not incompatible to syntastic, but having both a loclist and a quickfix window open might get confusing.  I suppose I should add a note about that to the manual.

Also, many people these days seem to prefer powerline or airline to standard status line in Vim.  This does affect the way syntastic works.  Syntastic uses `w:quickfix_title` to show on the status line of the loclist window the name of the checker that returned errors:

![2015-03-14-174000_492x189](https://cloud.githubusercontent.com/assets/1281736/6654787/d699e47a-cae3-11e4-8c76-59cc9a2645c7.png)

Powerline and airline don't show this information.  I suppose I should add a note to the manual about them too.

**Comment by lloydde** [comment]
@lcd047 thanks for looking into this!

I'm new to go, it's not clear to me that running `go build` is always appropriate, as my understanding was that the `build` command is for packaging. During development you might just be running `go test`, or `go run` if you have a main.

Thanks for the additional tips for how to get more out of syntastic. I've added a comment to https://github.com/jez/vim-as-an-ide/commit/144f979 , where I recently learned about syntastic.

**Comment by lcd047** [comment]
Which is why there are other checkers for go to choose from.  You're really _not_ supposed to use syntastic with the default config.  What you're supposed to do is spend a few minutes reading the manual, then enable the features that make sense for you.  The default config is good only to show you that syntastic does _something_.  There is no combination of settings that works reasonably for most people.  You can save a lot of time if you take care to understand what you're doing. _shrug_
