### ISSUE TITLE
jshint not loading to syntastic abnormal termination

### ISSUE THREAD

**Issue by ddaza** [scrooloose/syntastic#1369]
recently I switched to use node with 'nvm', installed jshint  set my vimrc  like this
```
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_jshint_exec = '/home/user/.nvm/versions/node/v0.12.1/bin/jshint'
```
When opening vim now i get this and jshint is never loaded
```
syntastic: error: checker javascript/jshint: can't parse version string (abnormal termination?)
```

**Comment by lcd047** [comment]
Please open a JavaScript file, set `g:syntastic_debug` to 32, run `:SyntasticInfo`, run `:mes`, and post the output.

**Comment by ddaza** [comment]
yeah sorry i found a workaround and now it works. I tried to roll back to where it was before but it is not erroring out anymore. 

The workaround is to install a copy of node's binaries for the nvm system. 
 
i tried to remove the apt copy and just use the nvm one but now is not crashing anymore.

It might be a problem with the way/order i installed thing. 

thanks, anyway

**Comment by lcd047** [comment]
Once again, for people searching the archives: in the vast majority of cases, "abnormal termination" is a symptom of a problem __outside__ syntastic.

**Comment by caneta** [comment]
I had the same problem using nvm and solved adding the following to my .vimrc:
    
    if $PATH !~ "\.nvm"
        let $PATH="/home/services/.nvm/versions/node/v0.12.2/bin:" . $PATH
    endif

**Comment by do3cc** [comment]
I have the same probem. I am running ubuntu and installed npm.
When running jshint without arguments on the console, I get this exception:
```
/usr/bin/env: node: No such file or directory
```
When installing nodejs on ubuntu, the binary gets named `nodejs` not `node`
Locally, I fixed it by creating a node symlink:
```
sudo ln -s /usr/bin/node{js,}
```

I understand that this is not the fault of syntastic, but I did not find this hint anywhere else.

**Comment by hagabaka** [comment]
I also had this problem, and it seems to be because my jshint (version 2.9.2 from npm) outputs `jshint v2.9.2` in response to `--version`. I made a wrapper as a temporary fix (obviously it would be better to actually parse the version than hard-code it).
```
#!/bin/sh

if [ "$1" = '--version' ]
then
  echo 2.9.2
else
  jshint "$@"
fi
```
I can't help but wonder if this is a common problem. Would it be a good idea to have an universal way to not try to parse the version string? Or make the version parser more lenient, and ignore everything except numbers and dots?

**Comment by lcd047** [comment]
@hagabaka No, the output of `v2.9.2` is not a problem for syntastic, I have it working fine here with the exact same version. Trying to run `jshint` not installed globally might be though.  Or it might be something completely unrelated.

Please open a __new__ issue, and state (1) your Vim version, (2) what you did, (3) what did you expect to happen, and (4) what happened instead.  Open a JavaScript file, run `:SyntasticInfo`, and post the output.  Then set `g:syntastic_debug` to 3, run `:SyntasticCheck jshint`, run `:mes`, and post the output.

**Comment by hagabaka** [comment]
@lcd047 The output for me is `jshint v2.9.2`, not just `v2.9.2`.

**Comment by lcd047** [comment]
@hagabaka Syntastic can still parse `jshint v2.9.2`:
```vim
:echo syntastic#util#parseVersion('jshint v2.9.2')
[2, 9, 2]
```
As I said, your problem is elsewhere.

**Comment by mannyhappenings** [comment]
I had the same problem with jsxhint,

Doing this solved my problem:
--- a/syntax_checkers/javascript/jsxhint.vim
+++ b/syntax_checkers/javascript/jsxhint.vim
@@ -23,7 +23,8 @@ function! SyntaxCheckers_javascript_jsxhint_IsAvailable() dict " {{{1
     endif
 
     let version_output = syntastic#util#system(self.getExecEscaped() . ' --version')
-    let parsed_ver = !v:shell_error && (version_output =~# '\m^JSXHint\>') ? syntastic#util#parseVersion(version_output) : []
+"    let parsed_ver = !v:shell_error && (version_output =~# '\m^JSXHint\>') ? syntastic#util#parseVersion(version_output) : []
+    let parsed_ver = [2, 9, 2]
     if len(parsed_ver)
         call self.setVersion(parsed_ver)
     else

Don't know why but bypassing version parsing did solved the problem.

**Comment by lcd047** [comment]
@mannyhappenings That hides the problem rather than solve it. _shrug_
