### ISSUE TITLE
syntastic really slow with pylint

### ISSUE THREAD

**Issue by backupchecker** [scrooloose/syntastic#1370]
Hi,

on a Debian Jessie using vim 7.4.052, using both syntastic and pylint results in a really slow vim. Passing from a line to another one, even switching from one word to another one is really slow, though the hardware for the desktop is brand new.
Removing lines related to syntastic in my ~/.vimrc solves the problem.

 _SYNTASTIC_VERSION = '3.6.0-59' pylint 1.4.3 I was using the recommanded setup in ~/.vimrc:

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

Regards,
Carl Chenet

**Comment by lcd047** [comment]
You can turn on passive mode, and turn off `g:syntastic_check_on_open`.  Turning off echo notifications might help too.  You can also save both of us a lot of time by reading the manual and understanding what syntastic is doing, and how you can tune it to fit your needs.

If, after reading the manual, you still think something is off, you're welcome to explain what you did, what did you expect to happen, and what happened instead.  Post a sample file that illustrates the problem.  Enable debugging and post the logs.  And / or enable profiling (cf. #688) and post the profiling logs.

**Comment by backupchecker** [comment]
You're missing the point. If the syntastic "recommended settings" makes my vim laggy on a brand new computer, it should be improved. Of course I could tune it, but the using the "recommended settings" makes it laggy, that's not a good first feeling.

**Comment by lcd047** [comment]
> You're missing the point.

I may well be.  But you're missing some of it too: there is no such thing as a set of defaults that works reasonably for everybody, or even for a majority of people.  You came with the expectation that syntastic will work fine out of the box.  This is not the case: the default settings are there only to show you syntastic does _something_.  Making it just work for everybody is simply not possible.

> If the syntastic "recommended settings" makes my vim laggy on a brand new computer, "recommended settings" in README should be improved.

I'm open to suggestions.

**Comment by backupchecker** [comment]
Ok so if it's laggy out of the box with the "recommended settings" on a brand new computer and you're ok with it, everything is fine (for you at least). I'm closing the bug report.

Regards,
Carl Chenet

**Comment by farsil** [comment]
I know this is an old topic, but I was able to alleviate most of my grief with pylint by changing:

    let g:syntastic_check_on_open = 0
    let g:syntastic_check_on_wq = 1

so that linters and syntax checkers are only invoked when I write to file.

**Comment by tony** [comment]
Thanks @farsil 

ATM my vim config is crippled performance-wise.

I get serious benefits from this plugin, but we need that smooth, liquid motion in the editor.'

It appears recommneded settings are updated:

ref: https://github.com/vim-syntastic/syntastic/blob/8577c8e/doc/syntastic.txt#L115

(Latest in case you view this years from now: https://github.com/vim-syntastic/syntastic/blob/master/doc/syntastic.txt#L115)

**Comment by lcd047** [comment]
> I get serious benefits from this plugin, but we need that smooth, liquid motion in the editor.

Then you should consider using an async plugin instead of syntastic, such as [ALE][ale].

[ale]: https://github.com/w0rp/ale

**Comment by tony** [comment]
@lcd047 Thanks for letting me know about ALE.

**Comment by tamasgal** [comment]
Thanks, I also switched over to ALE, it's awesome!

**Comment by fabriziobertoglio1987** [comment]
currently `ALE` [is NOT compatible](https://github.com/w0rp/ale/issues/1334#issuecomment-475570430) with `Ubuntu 18.04` and the `apt` package `vim 8.0.14.53` installed with either `vim` or `gnome-vim` package. There is no solution to this problem, installing `vim` from source means loosing `clipboard` compatability so for me `ale` is not an option, even if I tested it and was very **faster** then syntastic.

The bug on Ubuntu 18.04 causes the cursor to disappers on error and makes the plugin unusable
