### ISSUE TITLE
scss-lint doesn't use .scss-lint.yml in subdirectory

### ISSUE THREAD

**Issue by jasonlong** [scrooloose/syntastic#1373]
I'm not sure if this is a symptom of my Vim config, but with the following directory structure

```
myproject
    └── index.html
    └── scss
        └── .scss-lint.yml
        └── styles.scss
```

I open the project at the root (`myproject`) and when I edit `styles.scss` the `.scss-lint.yml` file in that directory is not used. If I copy the `.yml` file to the root level, it does.

Is this by design or is there something I might have configured wrong?

**Comment by lcd047** [comment]
Syntastic doesn't care about `.scss-lint.yml`, only `scss-lint` does.  You can see how syntastic calls `scss-lint` by enabling debug: set `g:syntastic_debug` to 1, run the checker, and run `:mes`.  The relevant fields are `getcwd()` and `makeprg`.  You can pass arguments to `scss-lint` (e.g. `-c config.yml`) by setting `g:syntastic_scss_scss_lint_args`.

**Comment by jasonlong** [comment]
Great, thanks for the info @lcd047. :sparkles:

**Comment by nguyenj** [comment]
@jasonlong Did you figured out how to get syntastic to use `.scss-lint.yml`? 

I added `let g:syntastic_scss_checkers = ['scss_lint']` in my `.vimrc`; however I'm not sure how to make the checker use the `.scss-lint.yml` of the project.

**Comment by nguyenj** [comment]
@jasonlong never mind, I figured it out. My `.scss-lint.yml` wasn't in the correct folder that I opened up vim in. Once I opened vim from the root (`.scss-lint.yml` also at the root level), everything worked. `getcwd()` and `let g:syntastic_debug=1` was key for my discovery :).

**Comment by sblask** [comment]
This made it work for me: https://github.com/sblask/dotfiles/commit/2a171978f048d6a621b78b85bd26240bd731d7db

**Comment by jasonlong** [comment]
Nice, thanks @sblask!
