### ISSUE TITLE
:lnext and :lprevious don't jump to errors

### ISSUE THREAD

**Issue by DelvarWorld** [scrooloose/syntastic#1375]
I have a javascript warning that shows up in my quickfix list when I type `:lopen`. Syntastic also shows me the yellow `// WARNINGS (1)//` in my status line. However, When I type `:lnext` or `:lprev` I get "No more items" (regardless of if I'm on the errored line or not).

**Comment by lcd047** [comment]
`:lnext` and `:lprevious` go to the next / previous issue.  With a single warning in the loclist there 
are no next / previous issues, so `:lnext` and `:lprevious` won't work, try `:lfirst` and `:llast` instead.  This is not particularly intuitive if you ask me, but it's how Vim works, it doesn't have anything to do with syntastic. _shrug_
