### ISSUE TITLE
Error messages when enabling syntastic

### ISSUE THREAD

**Issue by Hellseher** [scrooloose/syntastic#1384]
### Error massages when syntastic enable ###
Hello mb month ago I've got these error massages when enable syntastic plugin.  

__system__

    Fedora 21 workstation  
    x86_64 GNU/Linux 3.19.3-200.fc21.x86_64 #1 SMP  
    Thu Mar 26 21:39:42 UTC 2015  

__Vim --version__

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  3 2015 16:17:48)  
    Included patches: 1-689  
    Compiled by sharlatan@hb  
    Huge version without GUI.  Features included (+) or not (-):  
    +acl             +farsi           +mouse_netterm   +syntax  
    +arabic          +file_in_path    +mouse_sgr       +tag_binary  
    +autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static  
    -balloon_eval    +float           +mouse_urxvt     -tag_any_white  
    -browse          +folding         +mouse_xterm     -tcl  
    ++builtin_terms  -footer          +multi_byte      +terminfo  
    +byte_offset     +fork()          +multi_lang      +termresponse  
    +cindent         +gettext         -mzscheme        +textobjects  
    -clientserver    -hangul_input    +netbeans_intg   +title  
    -clipboard       +iconv           +path_extra      -toolbar  
    +cmdline_compl   +insert_expand   +perl            +user_commands  
    +cmdline_hist    +jumplist        +persistent_undo +vertsplit  
    +cmdline_info    +keymap          +postscript      +virtualedit  
    +comments        +langmap         +printer         +visual  
    +conceal         +libcall         +profile         +visualextra  
    +cryptv          +linebreak       +python          +viminfo  
    +cscope          +lispindent      -python3         +vreplace  
    +cursorbind      +listcmds        +quickfix        +wildignore  
    +cursorshape     +localmap        +reltime         +wildmenu  
    +dialog_con      +lua             +rightleft       +windows  
    +diff            +menu            +ruby            +writebackup  
    +digraphs        +mksession       +scrollbind      -X11  
    -dnd             +modify_fname    +signs           -xfontset  
    -ebcdic          +mouse           +smartindent     -xim  
    +emacs_tags      -mouseshape      -sniff           -xsmp  
    +eval            +mouse_dec       +startuptime     -xterm_clipboard  
    +ex_extra        -mouse_gpm       +statusline      -xterm_save  
    +extra_search    -mouse_jsbterm   -sun_workshop    -xpm  

__SyntasticInfo__

    Syntastic version: 3.6.0-67 (Vim 704, Linux)  
    Info for filetype: python  
    Global mode: active  
    Filetype python is active  
    The current file will be checked automatically  
    Error detected while processing function  SyntasticInfo  
    ..310..309..247..SyntaxCheckers_python_pylint_IsAvailable..syntastic#util#system:  
    Error detected while processing function  
    line  9:  
    E484: Cannot open file /tmp/vnmSZpx/4  
    Error detected while processing function SyntasticInfo..310..309..247:  
    line  3:  
    E171: Missing :endif  
    Error detected while processing function SyntasticInfo..310:  
    line 12:  
    E171: Missing :endif  

__Syntastic varables__

    let g:syntastic_auto_loc_list = 1  
    set statusline+=%#warningmsg#  
    set statusline+=%{SyntasticStatuslineFlag()}  
    set statusline+=%*  
    let g:syntastic_auto_loc_list=1  
    let g:syntastic_always_populate_loc_list = 1  
    let g:syntastic_check_on_open = 1  
    let g:syntastic_check_on_wq = 0  

__when open a *.py file:__

    Error detected while processing function  
    <SNR>70_BufReadPostHook..<SNR>70_UpdateErrors..  
    <SNR>70_CacheErrors..242..241..SyntaxCheckers_python_python_GetLocList..  
    SyntasticMake..  
    syntastic#util#system:  
    line 9:  
    E484: Cannot open file /tmp/vY5Lal7/2  
    Error detected while processing function  
    <SNR>70_BufReadPostHook..<SNR>70_UpdateErrors..  
    <SNR>70_CacheErrors:  
    line 35:  
    E170: Missing :endfor  
    Error detected while processing function  
    <SNR>70_BufReadPostHook..<SNR>70_UpdateErrors:  
    line 13:  
    E171: Missing :endif  
    Error detected while processing function  
    <SNR>70_BufReadPostHook:  
    line 4:  
    E171: Missing :endif

**Comment by lcd047** [comment]
What OS are you running, what version of syntastic, and what variables relevant to syntastic do you have in your vimrc?

**Comment by Hellseher** [comment]
Hi,
added more info about error.

**Comment by lcd047** [comment]
Please set `g:syntastic_check_on_open` to 0 in your vimrc, open a Python file, set `g:syntastic_debug` to 3, run `:SyntasticInfo`, and post the output.  Then (without quitting vim) run `:SyntasticCheck python`, run `:mes`, and again post the output.

**Comment by Hellseher** [comment]
__SyntasticInfo__

    Syntastic version: 3.6.0-67 (Vim 704, Linux)  
    Info for filetype: python  
    Global mode: active  
    Filetype python is active  
    The current file will be checked automatically  
    Available checkers: flake8 pep8 pyflakes pylint python  
    Currently enabled checkers: python flake8 pylint

**Comment by lcd047** [comment]
> `&shellcmdflag = '-ic'`

This is (part of) your problem.  Configurations that mess with shell parameters are not supported.  Leave `shellcmdflag` to the default, and you should be fine (well, hopefully).

**Comment by Hellseher** [comment]
all works...
sorry for "false" apart :)
