### ISSUE TITLE
Is there anywhere I can find a list of all the interpolated strings in the syntastic errorformat

### ISSUE THREAD

**Issue by omni-vi** [scrooloose/syntastic#1386]
I'm trying to write a syntax checker for the Intel Fortran compiler based on the gfortran compiler. 

Problem is, I can't seem to find the place in the wiki where the errorformat string is thoroughly explained. Am I missing something?

**Comment by omni-vi** [comment]
I guess it's the vim errorformat described here
[VIM - Errorformat](http://vimdoc.sourceforge.net/htmldoc/quickfix.html#errorformat)

Maybe the Wiki should have a line explaining that.

**Comment by lcd047** [comment]
Yes, `errorformat` is a standard Vim option.  Realistically, you probably won't be able to figure it out from the manual alone.  If you're fluent in C, I'd recommend reading the sources (`qf_init_ext()` in `src/quickfix.c`).  I also wrote a short blurb a few weeks ago in a [SO post](http://stackoverflow.com/questions/29088436/whats-the-meaning-of-some-advanced-patterns-in-vim-errorformat-s/29102995#29102995), where I try to clarify some points in the manual.
