### ISSUE TITLE
Fortran syntax checker doesn't support Intel Fortran compiler

### ISSUE THREAD

**Issue by omni-vi** [scrooloose/syntastic#1387]
### Hi,

the syntax checker for Fortran is based on gfortran and doesn't work with the Intel Fortran compiler. I'm trying to create a `syntax_checkers/fortran/ifort.vim` file for people relying on ifort. Is there any interest for me to submit a patch?

### What I did
The ifort syntax output generally looks like this
`filename(linenum): severity #error number: message` followed by the problematic code and a marker.  It also comes in different severity levels, e.g.:

```
/tmp$ ifort -syntax-only -stand -warn test.f90
test.f90(4): error #5120: Unterminated character constant
    write(*,*) "Hello
---------------^
test.f90(3): warning #6717: This name has not been given an explicit type.   [I]
  do i = 1,10
-----^
test.f90(2): remark #7712: This variable has not been used.   [A]
  integer :: a
-------------^
```
I did create a new `errorformat` string (using the [VIM - Quickfix](http://vimdoc.sourceforge.net/htmldoc/quickfix.html#errorformat) description).
```
let errorformat =  '%E%f(%l): error #%n: %m,'
let errorformat .= '%W%f(%l): warning #%n: %m,'
let errorformat .= '%I%f(%l): remark #%n: %m,'
let errorformat .= '%-C  %#%.%#,'
let errorformat .= '%-Z%p^'
```

It works for me and I'd create a pull request if anyone is interested.
Sebastian

**Comment by lcd047** [comment]
> Is there any interest for me to submit a patch?

By all means, make a pull request.

**Comment by lcd047** [comment]
As it turns out, this needs to be merged with the existing `gfortran` checker, because of design defficiencies of `syntastic#c#GetLocList()`.  It's uglier than it needs to be, so I went ahead and made the changes myself.  Sorry about that.  The user-visible functionality is reasonable though: set `g:syntastic_fortran_compiler` to `'ifort'` to use Intel Fortran, or set it to `'gfortran'` (which is still the default) for GNU Fortran.  Commit b152ac3.

**Comment by omni-vi** [comment]
It works very well, thanks.

**Comment by snowfed** [comment]
Hi,

Do you by any chance know how to deal with *.i90 files (preprocessed files) produced by ifort syntax checking? It appears that ifort keeps temporary files if two options -fsyntax-only and -fpp appear together. ifort's option -no-save-temps has no effect. May be it could be done through syntastic?

===
**Example:**
-sh-4.1$ mkdir tmp
-sh-4.1$ cd tmp
-sh-4.1$ vi test.f90
-sh-4.1$ ls
test.f90  test.i90 **<-- garbage**

**Comment by lcd047** [comment]
@snowfed Syntastic does very few things on its own: it just runs the checker, and shows you the results in a window.  It's specifically __not__ suppose to mess with files it didn't create.  I'm afraid you'll have to find the right combination of compiler flags to deal with your problem. _shrug_

**Comment by snowfed** [comment]
Thanks for answering, @lcd047 
The right flag is described in "man ifort", but it doesn't help, at least in ifort 14. So for now I guess I'll have to use "rm *.i90" :/

**Comment by lcd047** [comment]
@snowfed I suppose a better way would be something like this:
```sh
find /some/dir -type f -name '*.i90' -print0 | xargs -0 rm -f
```
and perhaps add that as a `clean` rule in a `Makefile`.  But basically, yes, you'll have to deal with it manually.

**Comment by snowfed** [comment]
@lcd047 It's definetely fancier your way, thanks.
