### ISSUE TITLE
Add a way to ignore or filter warnings

### ISSUE THREAD

**Issue by seirl** [scrooloose/syntastic#1388]
I am using clang -fsyntax-only as my c++ syntax checker, but it has this annoying issue: https://llvm.org/bugs/show_bug.cgi?id=16686 that makes syntastic complain whenever I'm syntax-checking a header with #pragma once. Is there a way I could ignore or filter this warning in syntastic? Would that be something useful to add?

**Comment by lcd047** [comment]
Try `:help 'syntastic_quiet_messages'`.
