### ISSUE TITLE
Progress bar?

### ISSUE THREAD

**Issue by mlr-msft** [scrooloose/syntastic#1390]
I'm developing vim plugins for two languages that perform verification, which can take significantly more time than just compilation.

Is there a way to display a spinning bar (i.e. `\|/-`) or a progress bar to show that syntactic is working?

If not, could someone provide some pointers regarding how and where this could be done? I'd be willing to invest some time into it.

Thanks in advance.

**Comment by lcd047** [comment]
> Is there a way to display a spinning bar (i.e. `\|/-`) or a progress bar to show that syntactic is working?

No.  Vim is single-threaded, and while there are a number of hacks that could be used to (almost) work around that, syntastic is in an uniquely bad position for doing it.

> If not, could someone provide some pointers regarding how and where this could be done?

If you can modify the code of the application doing the checks, the cleanest approach would be to make the application's status available on a pipe / socket, then write a client to poll it and show a progress bar.  If you can't modify the application, you could try writing a wrapper that would somehow ping the application once in a while to make sure it's still alive, and show a spinning bar.

Alternatively, you could look into making syntastic run checkers asynchronously.  That would be far more useful than a progress bar, an army of syntastic users would be grateful for it.  See #699 and #1253 for previous discussions.

Last but not least, you could look at [neovim](https://github.com/neovim/neovim), and perhaps [neomake](https://github.com/benekastah/neomake).  Writing a progress bar in that context would be clean and relatively easy, but the end result wouldn't work with plain Vim.

**Comment by mlr-msft** [comment]
Thanks for the excellent advice. :)

I'll weigh my options and act accordingly.
