### ISSUE TITLE
No checkers for arduino files

### ISSUE THREAD

**Issue by benalb** [scrooloose/syntastic#1392]
Syntastic version: 3.6.0-74 (Vim 704, Linux)
Info for filetype: arduino
Global mode: active
Filetype arduino is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -

**Comment by lcd047** [comment]
Yes: currently syntastic doesn't have any checker for Arduino files.  There used to be one in version 3.5.0, but it didn't meet people's standards so it has been removed (cf. #1173).  Sorry about that.
