### ISSUE TITLE
what happend about '-std=c++0x' not allowed with 'C/ObjC' ? 

### ISSUE THREAD

**Issue by hlee13** [scrooloose/syntastic#1409]
when I open a .h header file only, the syntastic plugin give the below error:

invalid argument '-std=c++0x' not allowed with 'C/ObjC' 
'vector' file not found 

other .cpp and .h are work well

please

**Comment by lcd047** [comment]
Syntastic doesn't care about compiler flags or include files, only compilers do.  So, what checker are you using, and what filetype do you want to check?

**Comment by hlee13** [comment]
I use the default ycm_extra_conf.py with below flags:
 '-std=c++11',
 '-x',
'c++',

and my ~/.vimrc
 let g:syntastic_cpp_include_dirs = ['/usr/include/']
let g:syntastic_cpp_remove_include_errors = 1
 let g:syntastic_cpp_check_header = 1
 let g:syntastic_cpp_compiler = 'clang++'
 let g:syntastic_cpp_compiler_options = '-std=c++11 -stdlib=libstdc++' 

Why I have the message, invalid argument '-std=c++0x' not allowed with 'C/ObjC' , and what I do will remove the error message
please give a elegant slove

**Comment by lcd047** [comment]
Please open a C++ file, run `:SyntasticInfo`, and post the output.

> please give a elegant slove

What can I sy, I'll try my best. :)

**Comment by hlee13** [comment]
Syntastic version: 3.6.0-77 (Vim 704, Linux)
Info for filetype: cpp
Global mode: active
Filetype cpp is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
Checkers for filetype cpp possibly disabled by YouCompleteMe

**Comment by hlee13** [comment]
this works well on other.h file

**Comment by hlee13** [comment]
its seem like be a  YCM error message

**Comment by lcd047** [comment]
> Checkers for filetype cpp possibly disabled by YouCompleteMe

You're using YCM to check the files, not syntastic.
