### ISSUE TITLE
b:syntastic_ruby_rubocop_exec to mri bin for a jruby project

### ISSUE THREAD

**Issue by mooreniemi** [scrooloose/syntastic#1410]
I'd like, for speed, to use the MRI ruby executable for some of my syntax checks, though my code will run in jRuby in production. (I'd argue this is ok for the vast majority of cases, but if you disagree or see it as too low a priority and don't want to support this, you can close this issue. I can try exploring nail-gun to run the checks on an on-going process prob.)

What I did:

I set `b:syntastic_ruby_rubocop_exec = '/Users/amooreniemi/.rvm/rubies/ruby-2.1.3/bin/ruby'` for my buffer containing a `.rb` file. I ran `:SyntasticCheck`. (I had only ['rubocop'] set to run during check.)

What I expected:

I expected the rubocop check to return a populated Loc List. If run in jruby this file does have a few, and running `rubocop /Users/amooreniemi/work/core-api/app/controllers/locations_controller.rb` in an MRI set shell returns the same.

What happened:

No loc list populated. This was in the `:mes` return:

"~/work/core-api/app/controllers/locations_controller.rb" 58L, 2166C
syntastic: 107.889129: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&
1', &shellslash = 0, &shelltemp = 1, &shellxquote = ''
syntastic: 107.889347: UpdateErrors: default checkers
syntastic: 107.889560: CacheErrors: default checkers
syntastic: 107.890082: g:syntastic_aggregate_errors = 0
syntastic: 107.890226: getcwd() = '/Users/amooreniemi/work/core-api/app/controllers'
syntastic: 107.890491: CacheErrors: Invoking checker: ruby/rubocop
syntastic: 107.890956: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%f:%l:%c: %t: %m', 'makeprg': '/Users
/amooreniemi/.rvm/rubies/ruby-2.1.3/bin/ruby --format emacs locations_controller.rb'}
syntastic: 107.915640: getLocList: checker ruby/rubocop returned 1

System details:

`:ver`: VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  5 2014 21:00:28)
`:SyntasticInfo`: Syntastic version: 3.6.0-77 (Vim 703, Darwin)

**Comment by lcd047** [comment]
> I set  `b:syntastic_ruby_rubocop_exec = '/Users/amooreniemi/.rvm/rubies/ruby-2.1.3/bin/ruby'`

Out of curiosity, why did you do that?  Syntastic's `rubocop` checker is supposed to run (surprise!) `rubocop`.  It only works if `g:syntastic_ruby_rubocop_exec` points to the `rubocop` binary.  It won't work if you point it to MRI Ruby, to JRuby, to `/bin/ls`, or to `/dev/random`.

If you want to check your file with MRI Ruby set `g:syntastic_ruby_exec` to your modified MRI, then set `g:syntastic_ruby_checkers` to `['mri']`.

If you want to check your file with JRuby set `g:syntastic_ruby_checkers` to `['jruby']` and _leave everything else alone_.

If you want to check your file with rubocop set `g:syntastic_ruby_checkers` to `['rubocop']` and _leave everything else alone_.

**Comment by mooreniemi** [comment]
Oh god, of course. I was just thinking about it as if it were choosing platforms, duh, it is pointing right to the binary. Thanks for your patience with my dumb question!

It might be nice at some point to be able to say "grab all language executables from _this_ bin", ala pointing to `.rvm/gems/ruby-2.1.3/bin/` so that I don't have to set each checker/make it easy to switch platforms.

Thanks for the info on setting platform in the checkers list though, as I just assumed it'd be smart enough to sort out having both in there.
