### ISSUE TITLE
Pylint not working with syntastic

### ISSUE THREAD

**Issue by josefson** [scrooloose/syntastic#1412]
```
let g:syntastic_python_checkers = ['pylint']
```
Nothing is returned from SyntasticCheck. No error message, nothing at all. But, pylint works outside vim.

I have:
    - Vim 7.4.488
    - Syntastic 3.6.0-77
    - Pylint 1.4.3

My syntastic configs are:
```
let g:syntastic_python_checkers = ['python', 'pylint']
let g:syntastic_python_pylint_exec = '/usr/local/bin/pylint'
```
When i have python syntax errors i get syntastic errors, but the same doesn't happen for pylint checks.

**Comment by lcd047** [comment]
Please open your test file, run `:SyntasticInfo` and post the output.  Then set `g:syntastic_debug` to 3, run `:SyntasticCheck pylint`, run `:mes`, and post the output again.

**Comment by josefson** [comment]
@lcd047 Thanks for guiding me into the problem. Now i got errors, whose i could search for and found a workaround in #902 and that did the trick:
Had to add this to my shellrc:
```
export LC_CTYPE=en_US.UTF-8
```
Even tho i already had:
```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```
Which made locale give me:
```LC_CTYPE="en_US.UTF-8"
```
Now locale still gives me:
```LC_CTYPE="en_US.UTF-8"
```
But syntactic works, so im fine with that. I am closing this, since i found a workaround in #902.
Thanks!!

**Comment by phiche** [comment]
Yep I had this exact same problem with zsh and vim trying to run pylint on OSX. 
When I tried to run :SyntasticCheck it returned nothing, put pylint worked from inside my terminal.
I enabled debug and googled what was in :mes and chased it down to this missing shell variable: 
```export LC_CTYPE=en_US.UTF-8```
It's unclear to me whether this is a pylint issue or a syntactic issue?

**Comment by lcd047** [comment]
@phiche This comes up in some form every few months, but it isn't obvious to recognize for what it is, so people keep asking.  Python crashing because of messed up locales when run from Vim is neither pylint's nor syntastic's doing.  It's between (your particular versions of) Python, Vim, and your shell, and it's specific to OS-X.  Perhaps ask on an OS-X forum?

**Comment by phiche** [comment]
Yeah there are a lot of moving pieces here. The only thing that's important is that people can find the solution easily when they search for it. What finally got me on the path to the solution is learning how to enable debug with ```let g:syntastic_debug = 1``` and viewing the log with ```:mes```
