### ISSUE TITLE
synastic rubocop returns "Command Terminated" on macvim

### ISSUE THREAD

**Issue by tthomas7** [scrooloose/syntastic#1417]
This may be my error but my vimrc file works on my linux machine and not on osx so it might not be. Thanks in advance for any help you can give me, and for synastic, it's fantastic.

I'd like syntastic to run the MRI checker and then the rubocop checker and it does that. But the rubocop checker fails and I don't know why. I'm gonna try to put as much of my setup as I can here. 

I'm running macvim 7.4 installed through homebrew and run from the command line.
Rubocop from the command line is on version 0.31.0 and works. It's output is below.
SynasticInfo returns:
Syntastic version: 3.6.0-83 (Vim 704, Darwin)
Info for filetype: ruby
Global mode: active
Filetype ruby is active
The current file will be checked automatically
Available checkers: mri rubocop
Currently enabled checkers: mri rubocop

I extracted the command that it looks like syntactic is trying to run and ran it on the command line. That seems to work fine.
rubocop -R --format emacs spec/models/pdn_importer_spec.rb                                                                                                          
/spec/models/foo_spec.rb:29:7: C: Use snake_case for variable names.
/spec/models/foo_spec.rb:29:17: C: Do not use semicolons to terminate expressions.

SynasticCheck though gives me something like:
```
# syntastic: 682.927458: &shell = '/usr/local/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
# syntastic: 682.927719: UpdateErrors: default checkers
# syntastic: 682.928045: CacheErrors: default checkers
# syntastic: 682.928861: g:syntastic_aggregate_errors = 1
# syntastic: 682.929100: getcwd() = '/rails/root/'
# syntastic: 682.929524: CacheErrors: Invoking checker: ruby/mri
# syntastic: 682.930200: SyntasticMake: called with options: {'errorformat': '%-G%\m%.%#warning: %\%%(possibly %\)%\?useless use of == in void context,%-G%\%.%\%.%\%.%.%#,%-GSyntax OK,%E%f:%l: syntax error\, %m,%Z%p^,%W%f:%l: warning: %m,%Z%p^,%W%f:%l: %m,%-C%.%#', 'makeprg': 'ruby -w -T1 -c spec/models/foo_spec.rb', 'env': {'RUBYOPT': ''}}
# error list 2 of 3; 0 errors
# syntastic: 682.975444: getLocList: checker ruby/mri returned 0
# syntastic: 682.975895: CacheErrors: Invoking checker: ruby/rubocop
# syntastic: 682.976458: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%f:%l:%c: %t: %m', 'makeprg': 'rubocop -R --format emacs spec/models/foo_spec.rb'}
# Command terminated

# error list 2 of 3; 0 errors
# syntastic: 683.683708: getLocList: checker ruby/rubocop returned -1

The syntastic portion of my vimrc file is below.
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_scss_checkers = ['sass', 'scss_lint']
let g:syntastic_ruby_checkers = ['mri', 'rubocop']
let g:syntastic_ruby_rubocop_args = "-R"
"coffeelint needs to be installed through npm, the rest are ruby gems.
let g:syntastic_coffee_checkers = ['coffee', 'coffeelint']
let g:syntastic_haml_checkers = ['haml', 'haml_lint']
let g:syntastic_aggregate_errors = 1
let g:syntastic_html_tidy_ignore_errors=[" proprietary attribute \"ng-"]
```

Thanks for your help and let me know what I can do.
~Thomas

**Comment by lcd047** [comment]
"Command terminated" means the checker has crashed.  [This post](https://github.com/scrooloose/syntastic/issues/1407#issuecomment-99174796) might provide an answer.  If it doesn't, please open your test file, set `g:syntastic_debug` to 3, run `:SyntasticCheck rubocop`, run `:mes`, and post the output.

**Comment by tthomas7** [comment]
That did it!
Thanks. 

I set rvm into my path in .zshenv instead of .zshrc and everything is happy.
