### ISSUE TITLE
Is there a way to ignore rubocop warnings?

### ISSUE THREAD

**Issue by firedev** [scrooloose/syntastic#1418]
Depending on some factors rubocop is showing this line sometimes:

```
$ rubocop                                                                                                                                                                     
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.2.
```

Since I am in a project with other developers and dependencies I can't do shit about it and it blows up Syntastic.

[I was told](https://github.com/bbatsov/rubocop/issues/1819) to run it with `ruby -W0 -S`, okay, fair enough. How can I do that? 

Or is there a better way?

**Comment by firedev** [comment]
In fact `ruby-lint` suffer from the same issue caused by parser:

```
$ ruby-lint                                                                                                                                                                 
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.2.
You must specify at least one file to analyze
```

**Comment by lcd047** [comment]
> Depending on some factors rubocop is showing this line sometimes:

Write a [wrapper](https://gist.github.com/lcd047/96138909015f2f8d2d36) around rubocop and point `g:syntastic_ruby_rubocop_exec` to it.

> Since I am in a project with other developers and dependencies I can't do shit about it and it blows up Syntastic.

And thus I'm supposed to fix it.  How nice.

> Or is there a better way?

Nope, we're arseholes all the way down.

> In fact `ruby-lint` suffer from the same issue caused by parser:

Write another wrapper?

**Comment by firedev** [comment]
Sorry, not sure what ticked you off, I simply removed the warning from parser itself.

Thank you for pointing me to the wrapper thing, couldn't find a way how to do it.

**Comment by lcd047** [comment]
> Sorry, not sure what ticked you off

Not ticked off at all, that was supposed to self irony.  Syntastic maintainer blames rubocop.  Rubocop maintainer blames parser.  Parser maintainer blames ruby.  And the funny thing is, each of us have reasons for doing it (aside from being arseholes, that is). :)

**Comment by lcd047** [comment]
For what it's worth: I added a note to the [wiki](https://github.com/scrooloose/syntastic/wiki/Ruby%3A---rubocop) with the current workarounds.

**Comment by firedev** [comment]
Thank you, this definitely helps.

**Comment by gawbul** [comment]
Another way around this is to uninstall the current version of parser and install an older version that supports the syntax for your version of ruby? Look in https://github.com/whitequark/parser/blob/v2.2.3.0/lib/parser/current.rb, find your ruby version, then go back through the tags until you find the tag that supports your version of ruby? For example for ruby version 2.1.6, I had to install parser 2.2.2.6.

**Comment by firedev** [comment]
I have just edited the local gem and commented the warnings out.
