### ISSUE TITLE
Feature: easy way to ignore certain errors (ideally straight from the error, inline)

### ISSUE THREAD

**Issue by yoaquim** [scrooloose/syntastic#1419]
I've been trying to figure out how to ignore errors, specifically the `Missing "use strict" statement.` for Javascript, and I've gotten as far as `syntastic_quiet_messages` and `syntastic_javascript_checker_args = '--ignore=[ERROR]` (though I still don't know how to use them).

It'd be nice if you could move to the line the error is in, and run a command that lets syntastic ignore the current error, and make it configurable (e.g., current buffer, file, across everything, etc). This could also just be toggling the options mentioned above.

**Comment by lcd047** [comment]
Please read: `:help 'syntastic_quiet_messages'`.

**Comment by lcd047** [comment]
What checker gives you this error?

**Comment by yoaquim** [comment]
JSHint

**Comment by lcd047** [comment]
For `jshint` there are a number of ways to do it.  Edit your `.jshintrc` or `package.json` file and change `"strict": true` to `"strict": false`; see [JSHint docs](http://jshint.com/docs/) for details.  Or set `g:syntastic_javascript_jshint_quiet_messages` to `{ 'regex': '\VMissing "use strict" statement.' }`.  Or set `g:syntastic_quiet_messages` to the same.

As for adding a function to kill error messages interactively: this is a reasonable request.  It could be done, but it would be awkward, and it would involve solving problems I'd rather stay away from.  Among other things, syntastic as it is now doesn't care about key mappings, and making your kill list persist would involve using some king of cache file.  Managing that without race conditions is something I don't want to try to do in Vim. :)

**Comment by yoaquim** [comment]
Fair enough! Thanks!
