### ISSUE TITLE
Moving cursor while performing a check messes status line

### ISSUE THREAD

**Issue by jumski** [scrooloose/syntastic#1423]
I am cursed by this error and finally got time to check and report it.

Steps to reproduce:
- make change to file
- execute `:w<cr>`
- hold any move key while syntastic is perfoming a check

I tested this on latest syntastic and powerline pulled from github, but this is not a new bug for sure.

This is how this looks being messed up:
![1](https://cloud.githubusercontent.com/assets/9126/7754351/3a8aa6a8-ffec-11e4-9e7f-ffc15c4479b2.png)

It seems the status line becomes part of the screen, when i delete some lines, it "climbs":
![2](https://cloud.githubusercontent.com/assets/9126/7754380/74d6d246-ffec-11e4-962d-fba15a9ac29b.png)

I just tested it without powerline and it also breaks status line like this:
![3](https://cloud.githubusercontent.com/assets/9126/7754447/e823bcf0-ffec-11e4-9462-5decb56f9633.png)

Executing `:redraw!` or simply opening and closing a split/tab fixes the status line and "deactivates" this bug - i can reproduce it only after reopening vim.

Any idea what could be wrong?
Thanks

**Comment by lcd047** [comment]
I can't reproduce this.  What OS are you running, what version of Vim, what version of syntastic, and what configuration options did you set for syntastic?

**Comment by jumski** [comment]
Not sure what the cuase is, but i know how to fix it after some twiddling.
It happens only on `slim` files. When i comment out `vim-slim` plugin or set passive mode for `slim` it does not happen anymore.

For brevity, my versions:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 26 2014 22:33:48)
Included patches: 1-488
```

OS: Linux Mint 17 (Ubuntu derivative)

syntastic from latest master
the only option i have enabled is
 
```
let g:syntastic_mode_map = { 'passive_filetypes': ['haml', 'sass'] } 
```
 (which now includes also `slim`)

**Comment by lcd047** [comment]
This looks like a low-level redraw problem in Vim, or possibly in the underlying ncurses library.  Syntastic doesn't have any control there.  Sadly, there is no reasonable way to debug it, either.

Does the problem still happen if you set `slim` to passive and you run `:SyntasticCheck` manually?

**Comment by jumski** [comment]
No, i cannot trigger this bug with manual call.

It's not a big deal, given i narrowed it down to 'slim', I can live with passive mode with ease :)

Thank you!
