### ISSUE TITLE
Performance issues on Windows with ESLint

### ISSUE THREAD

**Issue by AntJanus** [scrooloose/syntastic#1427]
I'm on Windows and currently using JSHint for JS checking and it's super-fast. I save and before I can move the cursor, the linting is done.

However, I decided to switch to ESLint and it freezes up VIM for good 10 seconds. Any idea why that would be?

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 1, run the checker, run `:mes`, and post the output.  Then run `:SyntasticInfo`, and again, post the output.  Don't do anything else;  the order of running these is also important.

**Comment by AntJanus** [comment]
Since I can't seem to be able to directly copy paste, I'll rewrite it:

````
"~\Path\to\my\project\app\app.js" 76L, 2037C
"app.js" 76L, 2037C written
syntastic: 4.166771: g:syntastic_version = '3.5.0-15'
syntastic: 4.169603: &shell = 'C:\Windows\system32\cm.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1',  &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '(', &shellxescape = '"&|<>()@^'
syntastic: 4.170912: UpdateErrors (auto): default checkers
syntastic: 4.173432: g:syntastic_aggregate_errors = 0
syntastic: 4.173819: getcwd() = C:\path\to\my\project\app
syntastic: 5.141627: CacheErrors: Invoking checker: javascript/eslint
syntastic: 5.142711: SyntasticMake: called with options: {'postprocess': ['guards'], 'errorformat': '%E%f: line %\l, col %c\, Error - %m,%W%f: line %l\, col %c\, Warning - %m', 'makeprg': 'eslint -f compact app.js'}
syntastic: 6.022188: getLocList: checker javascript/eslint returned 1
````

SyntasticInfo

````
Syntastic version: 3.5.0-15
Info for filetype: javascript
Mode: active
Filetype javascript is active
Available checkers: eslint jscs jshint
Currently enabled checker: eslint
````

**Comment by lcd047** [comment]
Your syntastic is very old, you might consider upgrading it to the current master HEAD.

Anyway, your problem seem to be outside syntastic.  It takes less than 2 seconds for syntastic to finish the first run (from 4.170912 to 6.022188), and subsequent runs should be ~1 second faster (roughly from 5.141627 to 6.022188).  If you wish to debug this further you might try to get a profile log (cf. #688), upload the results somewhere, and post the link.

**Comment by AntJanus** [comment]
Hmm, updating syntastic made it a little more bearable. The first time around after launching VIM, it takes like 5-10 seconds (depending on file size) and afterward, it doesn't take as long. :/

**Comment by lcd047** [comment]
Like I said: if you feel this is worth investigating further, please get a profiling log (instructions for doing that are now in the [wiki](https://github.com/scrooloose/syntastic/wiki/Profiling-syntastic)), upload it to Google Docs or similar, and post the link.

**Comment by AntJanus** [comment]
Thanks!
