### ISSUE TITLE
Add a way to use relative paths for config options other than -I

### ISSUE THREAD

**Issue by Phyks** [scrooloose/syntastic#1430]
Hi,

I think it could be useful to support relative paths expansion in different kind of options, and not only in `-I` options.

For example, in [this PR](https://github.com/scrooloose/syntastic/pull/1429), I added support for Vera++. Vera++ has an argument, `-r`, to set its root path. In my case, this root path is often committed in the repo (or a submodule), so that anyone can just clone the repo and start working. However, I have to manually set an absolute path in the option file associated with Vera++ checker, and this prevents easy sharing of config files.

Thanks

**Comment by lcd047** [comment]
> I think it could be useful to support relative paths expansion in different kind of options, and not only in `-I` options.

The problem with making more options "magic" in `syntastic#c#ReadConfig()` is that said function is used by [many other checkers](https://github.com/scrooloose/syntastic/wiki/Configuration-Files), and `-I` is the only option common to all of them.  Is this situation ideal?  Of course not, this config file is just a crutch for the bigger problem of passing complex sets of options to checkers.  But it's still better than nothing, and the alternative, namely dealing in a meaningful way with all possible options of all checkers supported by syntastic, across all their versions, is simply out of question. _shrug_

Thus, sorry, but no.

**Comment by Phyks** [comment]
Ok. I understood this. But it may be possible to add a kind of macro replacement in config files, no?

Then, say I have a config file with
```
-r
EXPAND_PATH(some_relative_path)
```

The `some_relative_path` would be expanded to the full path?

**Comment by lcd047** [comment]
It's possible in principle, but then I'll have to add escape rules, quoting, dealing with newlines, and all the similar fun, and write a parser for it.  This is what config files are supposed to save you from, not help proliferate.

You can however do it yourself, with a Makefile and `cpp` or `m4`.  Or just a small shell script that would generate the config file.

**Comment by Phyks** [comment]
Indeed, generating them with a makefile or so might be the best solution if you do not want to implement much stuff in the config handling.
