### ISSUE TITLE
Non verbose errors.

### ISSUE THREAD

**Issue by mckeankylej** [scrooloose/syntastic#1434]
I am trying to check haskell code and when i use cabal sanboxes I get this error with ghc-mod. How do i make this error more verbose so I can troubleshoot?
syntastic: error: checker haskell/ghc_mod returned abnormal status 1

**Comment by lcd047** [comment]
As I said on SO, this is not a syntastic error. :)

Please open a Haskell file, set `g:syntastic_debug` to 3, run the checker, then run `:mes` and post the output.

**Comment by mckeankylej** [comment]
How do you set g:syntastic_debug to 3?

**Comment by lcd047** [comment]
You run `:let g:syntastic_debug=3`.

**Comment by mckeankylej** [comment]
It gives me this very long error:
http://pastebin.com/Us2ufkxJ

**Comment by lcd047** [comment]
Only this line is relevant:
> checker output: ['ghc-mod: /home/kyle/Desktop/haskell/Phalanx/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)', '']

You need to fix this.

**Comment by mckeankylej** [comment]
I have no idea where to go to fix this... do you have any idea?

**Comment by lcd047** [comment]
A search for the above error seems to imply this is a locale problem.  Please run these in a terminal and post the output:
```sh
locale
LC_ALL= LC_MESSAGES= locale
```
Also, do you get the same error if you run the checker in a terminal?  The exact commands are:
```sh
cd /home/kyle/Desktop/haskell/Phalanx
ghc-mod check --boundary="" RegexParser.hs
```

**Comment by mckeankylej** [comment]
locale:
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Next Command:
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES=
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

ghc-mod command:
ghc-mod: /home/kyle/Desktop/haskell/Phalanx/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)

Yes it appears to be a problem with ghc-mod should i open an issue on the ghc-mod github?

**Comment by lcd047** [comment]
I suppose the `ghc-mod` people are the most qualified to help you with it.

Going through your logs again, it looks like `hdevtools` is crashing too:
> checker output: ['cannot satisfy -package-id base-4.8.0.0-1b689eb8d72c4d4cc88f445839c1f01a', '    (use -v for more information)', '']

Again, something that you might want to fix.  The commnand producing that message is:
```sh
hdevtools check /home/kyle/Desktop/haskell/Phalanx/RegexParser.hs
```

**Comment by mckeankylej** [comment]
I think I have figured it out so when i ran -V on hdevtools it showed this
hdevtools: version 0.1.0.6 (ghc-7.6.3-x86_64-linux, cabal-1.16.0)
The important part is the fact that cabal sandboxes are a feature that is new to cabal. 
Thats the reason everything crashes when I use sandboxes.

**Comment by mckeankylej** [comment]
I just updated hdevtools and that didnt help anything :/
