### ISSUE TITLE
let g:syntastic_js_checkers not working

### ISSUE THREAD

**Issue by apostiglioni** [scrooloose/syntastic#1440]
Syntastic is ignoring the option **let g:syntastic_js_checkers = ['jscs']** and running jshint instead:

**Output of SyntasticInfo**
```
Syntastic version: 3.6.0-92 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: jscs jshint
Currently enabled checker: jshint
```
**.vimrc configuration**
```
" Configure syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_js_checkers = ['jscs']
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_error_symbol = "✗"
let g:syntastic_warning_symbol = "⚠"
```

**Comment by apostiglioni** [comment]
It looks like the issue is that syntastic is ignoring the setting *let g:syntastic_js_checkers = ['jscs']* and is running jshint instead.

**Comment by lcd047** [comment]
This is not supposed to work.  The standard filetype is named `javascript`, not `js`.  Try `g:syntastic_javascript_checkers` instead of `g:syntastic_js_checkers`.

**Comment by juanpabloaj** [comment]
when I try to see the variable `g:syntastic_javascript_checkers`, I get

```vim
:echo g:syntastic_javascript_checkers
E121: Undefined variable: g:syntastic_javascript_checkers
```

**Comment by lcd047** [comment]
@juanpabloaj That's because there is no variable `g:syntastic_javascript_checkers` defined by default.  __You__ are supposed to set it to the list of `javascript` checkers you want to run if you plan to use syntastic to check JavaScript files.
