### ISSUE TITLE
ESLint doesn't work

### ISSUE THREAD

**Issue by KolesnichenkoDS** [scrooloose/syntastic#1441]
from **.vimrc**:
```VimL
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_python_python_exec = '/path/to/python3'

let g:syntastic_python_checkers = ['pep8']
let g:syntastic_javascript_checkers = ['eslint']
```

It checks Python with PEP8, but doesn't check JavaScript. When I type **:SyntasticInfo javascript** if prints
```
Syntastic version: 3.6.0-92 (Vim 704, Linux)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
Available checkers: -
Currently enabled checkers: -  
```
it doesn't see eslint

however, eslint works well from the terminal (I've installed it with **npm install -g eslint**)

**P. S.** OS Debian Jessie

**P. P. S.** Excuse me if my English isn't very well

**Comment by lcd047** [comment]
Please open a JavaScript file, set `g:syntastic_debug` to 33, run `:SyntasticInfo`, run `:mes`, and post the output.

**Comment by KolesnichenkoDS** [comment]
@lcd047 I don't now how why, but when I set syntastic_debug to 33 it started to work well
thank you :)

**Comment by netei** [comment]
Hi, I have the same issue : Here is what is in the :mes after doing 

`g:syntastic_debug to 33, `

```
Syntastic version: 3.6.0-93 (Vim 704, Linux)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: eslint jscs
Currently enabled checkers: -
```

The eslint checker is available but not enabled.

However, in my .vimrc, I have `let g:syntastic_js_checkers = ['eslint']`

and if I do `:echo g:syntastic_js_checkers`, I get back ['eslint']

**Comment by netei** [comment]
If I force to use eslint by running : `:SyntasticCheck eslint` , I get back the right errors, strangely. So it seems it's only the "enabling" that doesn't work.

**Comment by netei** [comment]
I've removed jshint and jscs from my system, and now I get : 

```
syntastic: 14.964734: getcwd() = '/home/edi9999/projects/test'
syntastic: 14.965139: CacheErrors: Checker javascript/jshint is not available
syntastic: 14.965331: CacheErrors: Checker javascript/jslint is not available
syntastic: 14.965516: CacheErrors: no checkers available for javascript
```

It seems that syntastic has cached the linters I would like to use, is they some way to clean that cache ?

**Comment by lcd047** [comment]
@netei Please see #1440.

**Comment by netei** [comment]
Great, works !
