### ISSUE TITLE
Syntastic doesn't play well with breakindent

### ISSUE THREAD

**Issue by sugarfrosted** [scrooloose/syntastic#1442]
Vim version 7.4.729 (has been consistently an issue since break indent was included with vim.)

Syntastic misplaces syntax highlighting on lines that are soft broken when breakindent is in enabled as show below

**Comment by sugarfrosted** [comment]
![Uploading breakindentVsyntastic.jpg…]()

**Comment by lcd047** [comment]
This is a bug in Vim, not in syntastic.  Your screenshot above (that is, I suppose it was a screenshot) didn't work; what checkers seem to be affected?

**Comment by lcd047** [comment]
Ping.

**Comment by lcd047** [comment]
Ping.

**Comment by lcd047** [comment]
No fedback, no cry.
