### ISSUE TITLE
    *syntastic_mode_map* variable does not exists?

### ISSUE THREAD

**Issue by FriendOfFatBeagle** [scrooloose/syntastic#1445]
Hello:

The following is from syntastic doc inside Vim:
```
                                                        *'syntastic_mode_map'*
Default: { "mode": "active",
           "active_filetypes": [],
           "passive_filetypes": [] }
Use this option to fine tune when automatic syntax checking is done (or not
done).

The option should be set to something like: >

    let g:syntastic_mode_map = {
        \ "mode": "active",
        \ "active_filetypes": ["ruby", "php"],
        \ "passive_filetypes": ["puppet"] }
<
"mode" can be mapped to one of two values - "active" or "passive". When set
to "active", syntastic does automatic checking whenever a buffer is saved or
initially opened.  When set to "passive" syntastic only checks when the user
calls |:SyntasticCheck|.
```
Questions:
At the moment, syntastic is able to flag syntax errors when I save or open the source file.
The doc indicate there is a default value for  global variable *'syntastic_mode_map'*
I am NOT able to display result of *'syntastic_mode_map'*
When I ran like so:

:echo  syntastic_mode_map,

I get error messages:
 "E121:undefined variable ..."  and "E15: Invalid expression..." .

Since the default for mode for *'syntastic_mode_map'* active, I want to see if active syntax checking is on.

What did I missed?
This is a great plugin. Thanks.

**Comment by lcd047** [comment]
The variable `g:syntastic_mode_map` takes effect as documented if you define it, but the mode thing is not implemented internally as an actual variable `g:syntastic_mode_map` (if you're curious, the main reason for that is to avoid various race confitions that could occur when setting `g:syntastic_mode_map` at the wrong moment).  You can see the current mode by running `:SyntasticInfo`.
