### ISSUE TITLE
Saved sessions reopen with both [Quickfix List] and empty [Location List] window

### ISSUE THREAD

**Issue by tecfu** [scrooloose/syntastic#1449]
### Problem
Sessions saved with populated [Location List] windows restore as a populated [Quickfix List] window and an empty [Location List] window.

This creates and unwanted, empty window in the tab and also changes the tab name to "location list"

The above was determined using 
```
:ls
```
to view the open buffers in the tab.

### Steps to replicate:

[1] Save a session that has at least one <b>open tab</b> and contains:
- a buffer you are editing
- an open Syntastic <b>location list</b> with syntax errors for that buffer

*The location list window with syntax errors should be populated and opened at startup given the .vimrc configuration listed in the "Environment" heading below.

```
:mksession somefile
```

[2] Quit vim

[3]  Restore the session with 

```
vim -S somefile
```

[3] Observe that the previously mentioned tab now contains
- a buffer you are editing
- an open, empty <b>location list window</b>
- an open Syntastic <b>quickfix list window </b> with syntax errors for that buffer

### Environment

- Vim 7.4 / Ubuntu 14.04 

- .vimrc

```
NeoBundle 'scrooloose/syntastic'
"{{{
"Check if plugin loaded
if !empty(glob("~/.vim/bundle/syntastic/plugin/syntastic.vim")) 
	set statusline+=%#warningmsg#
	set statusline+=%{SyntasticStatuslineFlag()}
	set statusline+=%*

	let g:syntastic_always_populate_loc_list = 1
	let g:syntastic_auto_loc_list = 1
	let g:syntastic_check_on_open = 1
	let g:syntastic_check_on_wq = 0
        let g:syntastic_reuse_loc_lists = 1
	let g:syntastic_javascript_checkers = ['jshint']

	" Navigation shortcuts for location window
	map <expr> <C-Down> (empty(getloclist(0))  ? "" : ":lnext")."\n"
	map <expr> <C-Up> (empty(getloclist(0))  ? "" : ":lp")."\n"
endif

" Set location list height to 3 lines
let g:syntastic_loc_list_height=3
"}}}
```

**Comment by lcd047** [comment]
Try this:
```vim
set sessionoptions-=blank
```

**Comment by tecfu** [comment]
Brilliant. That worked. Thank you.
