### ISSUE TITLE
syntastic does not work

### ISSUE THREAD

**Issue by tlanyan** [scrooloose/syntastic#1451]
I did all the steps as the installation guide said, and it turned out that the syntastic did not work. I type :SyntasticInfo in the php file, and I got the following output:

    Syntastic version: 3.6.0-93 (Vim 704, Linux)
    Info for filetype: php
    Global mode: active
    Filetype php is active
    The current file will be checked automatically
    Available checker: php
    Currently enabled checker: php
    The current file will not be checked (file not readable / not local)

And I found that whatever file type I open, the information is always: The current file will not be checked (file not readable / not local). And I could not figure out why it happens.

I'm using vim 7.4. Can anyone be so kind to tell me how to get it work?

**Comment by lcd047** [comment]
The error message is supposed to explain it: you can only check files that live on the local machine.  You won't be able to check files opened over network, with `vim scp://hostname/path/to/file`, or `vim http://hostname/path/to/file`, or the like, even if Vim can open them.

**Comment by tlanyan** [comment]
So it means that syntastic can not be used over ssh?

**Comment by tlanyan** [comment]
The same hint appears even if I open the file in my local machine.

**Comment by lcd047** [comment]
> So it means that syntastic can not be used over ssh?

It can be used over ssh if you ssh to the remote machine and run Vim there.  It can't be used with files opened with `vim scp://...` or `vim sftp://...`.

> The same hint appears even if I open the file in my local machine.

Can you please give an example?  How do you open the file, and what happens?

**Comment by tlanyan** [comment]
I connect to the server via ssh and create a new file: `vim test.php`. Then I type :SyntasticInfo, and get the same output.

**Comment by lcd047** [comment]
Syntastic checks files on the (local) disk.  It can't check buffers in memory.  Write the file first, then try `:SyntasticInfo` on it.

**Comment by tlanyan** [comment]
Yes, it works in that way. Many Thanks!
So syntastic can not do syntax check dynamically? only when you put the buffers to the disk it will perform check?

**Comment by lcd047** [comment]
> So syntastic can not do syntax check dynamically? only when you put the buffers to the disk it will perform check?

That's correct.  I made an experiment some time ago with adding checks for buffers in memory for a few filetypes, but there was little interest for it (cf. #1351).
