### ISSUE TITLE
Possible to override PATH of executable?

### ISSUE THREAD

**Issue by rightaway** [scrooloose/syntastic#1452]
Instead of installing eslint with `npm install -g eslint` for a global install, I did a local install, so the eslint binary gets installed to my project folder's node_modules/.bin directory. Can I override the PATH variable seen by syntastic so that it will use eslint from that location so I don't have to install it globally?

**Comment by lcd047** [comment]
As far as syntastic is concerned it's possible:
```vim
let g:syntastic_javascript_eslint_exec = '/path/to/eslint'
```
However, that have been reports in the past about `node` programs not being able to run when invoked from Vim.  This is unrelated to syntastic. _shrug_

**Comment by patrick91** [comment]
is there a way to automatically figure the path of eslint?

**Comment by patrick91** [comment]
Ok, sorry! I just found this: https://github.com/lencioni/dotfiles/commit/ca2c86d950feb07b2c17947eeff0e1624d865c54

**Comment by lcd047** [comment]
It should be detected automatically if it is in your `$PATH` (provided, of course, that your Vim actually sees the right `$PATH`).
