### ISSUE TITLE
Request: semistandard (javascript)

### ISSUE THREAD

**Issue by rstacruz** [scrooloose/syntastic#1460]
https://github.com/Flet/semistandard

syntastic already has a `standard` reporter. `semistandard` is a drop-in replacement for standard (to enable semicolons).

**Comment by lcd047** [comment]
Good news: you can use it with syntastic without changes:
```vim
let g:syntastic_javascript_standard_exec = 'semistandard'
```

**Comment by fourcolors** [comment]
Just what I needed, thank you!

**Comment by fourcolors** [comment]
Actually... this doesn't seem to work for me...

**Comment by lcd047** [comment]
@fourcolors What did you do, what did you expect to happen, and what happened instead?

**Comment by fourcolors** [comment]
Hi lcd047 !

Ok I figured out what the problem was. It just threw me off that I needed to set my checker to 'standard' and the standard_exec to 'semistandard' but it makes sense now haha. Ok so basically yes your line works BUT you must have this line in your vimrc file as well.

  let g:syntastic_javascript_checkers = ['standard']

So you need both. Thank you for responding so quickly! Sorry about that.

**Comment by lcd047** [comment]
@fourcolors The syntastic checker `standard` handles both, yes.  But you don't need to have both _binaries_ `standard` and `semistandard` installed.

On the other hand, if you do have both binaries installed, you can switch between using them on the fly by pointing `g:syntastic_javascript_standard_exec` alternatively to standard` and `semistandard`, but only with relatively recent versions of syntastic.  With older versions you need to restart Vim if you change `g:syntastic_javascript_standard_exec`.

**Comment by fourcolors** [comment]
Ah, thank you for the clarification.

**Comment by rstacruz** [comment]
btw here's what I do on my vim config:

```vim
command! Standard :call <SID>standard()
command! Semistandard :call <SID>semistandard()

function! s:standard()
  let g:syntastic_javascript_checkers = ['standard']
  let g:syntastic_javascript_standard_exec = 'standard'
  SyntasticCheck
endfunction

function! s:semistandard()
  let g:syntastic_javascript_checkers = ['standard']
  let g:syntastic_javascript_standard_exec = 'semistandard'
  SyntasticCheck
endfunction
```

...I just then run `:Standard` when I need it. Have these set up for other linters as well.
