### ISSUE TITLE
perl: add b:syntastic_enable_perl_checker option

### ISSUE THREAD

**Issue by hvhaugwitz** [scrooloose/syntastic#1464]
Currently it is only possible to enable the perl checker globally via g:syntastic_enable_perl_checker. I would like to disable the perl checker by default but enable it only for specific buffers. Is it possible to add support for b:syntastic_enable_perl_checker variable?

**Comment by lcd047** [comment]
Heh, somebody actually takes this seriously. :)

It's actually an excellent idea.  Done in d75f3e5 for all three checkers that have that problem (`perl/perl`, `elixir/elixir`, and `r/svtools`).

**Comment by hvhaugwitz** [comment]
Thanks. Is it possible to disable the 'checks disabled for security reasons' error message when I explicitly disable the checker globally via 'g:syntastic_enable_perl_checker=0'?

**Comment by lcd047** [comment]
Sure.  Done in commit 4708cdd.
