### ISSUE TITLE
Rubocop warnings/errors not showing up

### ISSUE THREAD

**Issue by rousisk** [scrooloose/syntastic#1466]
Most probably I am doing something wrong but since I upgraded to the latest Ubuntu and with it to the latest janus vim version, my previously working syntastic/rubocop setup works no more.

    ruby -v
    ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

    rubocop -v
    0.32.1

    rubocop
    ...
    89 files inspected, 76 offenses detected

    :SyntasticInfo
    Syntastic version: 3.5.0-72
    Info for filetype: ruby
    Mode: active
    Filetype ruby is active
    Available checkers: mri rubocop
    Currently enabled checkers: mri rubocop

    :RuboCop
    (1 of 1): W: Assignment in condition - you probably meant to use `==`.

Yet :SyntasticCheck yields nothing, nor is saving the file.

I've tried different ruby, rubocop, and syntastic versions without success.

What am I missing?

**Comment by lcd047** [comment]
Try upgrading syntastic, preferably to the current master HEAD.  If that doesn't solve the problem open your test file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output.

**Comment by rousisk** [comment]
Thanks for the prompt response, upgrading to HEAD did the trick.
