### ISSUE TITLE
How to enable checkers in Syntastic

### ISSUE THREAD

**Issue by RanaZubair** [scrooloose/syntastic#1470]
i have a ruby script and my syntastic showing no errors in it. I installed syntastic with Pathogen. 
When i type `:SyntasticInfo` it show like
```
available checkers : mri
Currently Enabled checkers : -
```
i searched a lot of online forums but no told how to enable checkers ... i think if i enabled checkers then Syntastic can show errors ..
I have following settting for syntastic in my .vimrc
```
"syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

"made some changes in syntastic
let g:syntastic_php_checkers = ['php', 'phpcs', 'phpmd']

let g:syntastic_ruby_checkers = ['jruby', 'rubocop', 'reek', 'rubylint']

let g:syntastic_ruby_rubocop_exec = '/Program Files (x86)/vim/vimfiles/bundle/syntastic-master/syntax_checkers/ruby/rubocop'

let g:syntastic_aggregate_errors = 1
let g:syntastic_enable_ruby_checker = 1

autocmd FileType ruby map <F9> :w<CR>:!ruby -c %<CR
```
Please gimme the solution for this...

**Comment by lcd047** [comment]
> `available checkers : mri`

Only the `mri` checker is available.

> `let g:syntastic_ruby_checkers = ['jruby', 'rubocop', 'reek', 'rubylint']`

No point in adding any of these, only `mri` is available.  If you want to run checks with `jruby`, `rubocop`, `reek`, or `rubylint` you need to install the corresponding programs.

> let g:syntastic_ruby_rubocop_exec = '/Program Files (x86)/vim/vimfiles/bundle/syntastic-master/syntax_checkers/ruby/rubocop'

This doesn't make any sense.  If you change `g:syntastic_ruby_rubocop_exec` you need to poiunt it to the `rubocop` script, not to syntastic's own stub.

> Please gimme the solution for this...

Syntastic doesn't do any syntax checking by itself, it just runs third-party programs against your files and shows their results in a window.  In order to be able to run checks you need to install said third-party programs.

**Comment by RanaZubair** [comment]
But these jruby, rubocop, reek and rubylint are available in vimfiles/bundle/syntastic-master/syntax_checkers/ruby/
or you trying to say that i should reinstall them manually as a plugin?

**Comment by lcd047** [comment]
What you have in `vimfiles/bundle/syntastic-master/syntax_checkers/ruby/` are syntastic's functions for interacting with the corresponding programs.  This is nmot enough, you need to install the programs themselves.  For example you need to install [JRuby][jruby] to get the `jruby` checker working.  Please see the [wiki][ruby_checkers] for the other checkers.

[jruby]: http://jruby.org/
[ruby_checkers]: https://github.com/scrooloose/syntastic/wiki/Syntax-Checkers#user-content-ruby

**Comment by RanaZubair** [comment]
Thanks a lot my friend and now i have understand....
i got this link http://jruby.org/  for jruby... is that what you are saying or it is jruby plugin for vim??

**Comment by RanaZubair** [comment]
okay got the answer i'll inform if it will work for me Thanks....
