### ISSUE TITLE
syntax broken

### ISSUE THREAD

**Issue by carlitux** [scrooloose/syntastic#1472]
Syntax is broken when lint/checker fails for filetypes...

Steps:
1.- Editing python file (flake8 fails validations)
2.- Change buffer to another python file (syntax color is gone)
3.- Fix syntax or pep8
4.- run :e to reload file and set syntax on again (I didn't test with set syntax on)

**Comment by lcd047** [comment]
This may come as a surprise to you, but syntastic never calls the `syntax` command.  You don't have to take my word for it, you can run something like this and see for yourself:
```sh
$ egrep -riw 'sy(ntax)?' /path/to/syntastic | \
    egrep -v '/(README\.markdown|CONTRIBUTING\.md|syntastic\.txt):' | \
    egrep -v '^[^:]+: *"'
```
The first command finds `syntax`, the second one eliminates some irrelevant files, and the third one removes the occurrences in comments.  The remaining occurrences are `errorformat` strings, the `statusline` flag, and an error message.  Consequently, the problem might be _triggered_ by syntastic, but it isn't _caused_ by it.

Now, I can't reproduce the problem with your scenario, so I can only speculate on why it's happening for you.  The first candidate for a culprit would be an `autocmd`.  One way to get an idea what's going on that might (or might not) work, is to trigger the problem, then run `:verbose set syntax?` while the syntax highlighting is still off.

**Comment by carlitux** [comment]
![error](https://cloud.githubusercontent.com/assets/40538/8640419/4d91d47c-28c5-11e5-9322-f7844912374d.gif)

Here is the steps... I hope this helps

**Comment by lcd047** [comment]
As I said, I do believe you you're seeing a problem.  Also like I said, the problem is not with syntastic.  I gave you an idea about debugging the problem.  Not sure what else to add.

**Comment by carlitux** [comment]
Ok, thank you

**Comment by lcd047** [comment]
On a side note: you seem to be using neovim.  Syntastic has not been tested with neovim, and makes no promise about working with it.  Not that I'd expect that to be relevant to your problem, but it's something to keep in mind when reporting problems: try to reproduce them with plain Vim first.
