### ISSUE TITLE
clang_check and clang_tidy checkers do not work automatically with compilation databases

### ISSUE THREAD

**Issue by bbannier** [scrooloose/syntastic#1473]
The current implementation assumes that no compilation database is used since it explicitly adds `--`.

While a user could overwrite `post_args` with an empty string to make the plugin work with a compilation database, the settings for `clang_check` would not disable color-diagnostics.

Suggested fix for clang checkers: Move current `post_args` of `clang_check` and `clang_tidy` to `args`, but allow overwriting the `post_args` with a user-set string. For users not using compilation databases a configured `post_arg` of at least `--` would enable the plugins.

Suggested fix for `oclint`: Move to `args` and drop `--`.

**Comment by lcd047** [comment]
Have you considered reading the [docs](https://github.com/scrooloose/syntastic/wiki/C%3A---clang_check) before writing a patch?

**Comment by bbannier** [comment]
@lcd047 Still breaks because it doesn't disable color diagnostics which messes up the the error file display.

**Comment by lcd047** [comment]
Ok, please provide a minimal example of what breaks if you follow the instructions in the wiki.

**Comment by bbannier** [comment]
The issue seems to have gone away on my side and I cannot reproduce my original problem anymore.

**Comment by lcd047** [comment]
There shouldn't be any problem with ANSI colours, all these tools are smart enough to disable printing colours when their output is not a terminal.
