### ISSUE TITLE
cpp  std error checking

### ISSUE THREAD

**Issue by Rmmichael95** [scrooloose/syntastic#1483]
I just setup syntastic to use for my c++ environment but it doesn't seem to recognize objects from the standard library. I have written a small test code to show examples of the errors I am getting and included a screenshot. For example, on the line using name space std it says, "using directive refers to implicitly-defined namespace 'std'" and it marks string and my cout and sto* objects as unknown. Does anyone know what I may be able to do to fix this? It seems to only be happening with objects related to the standard library.  

![screenshot](https://cloud.githubusercontent.com/assets/8621104/8814463/92cb6d52-2fc1-11e5-9df0-14284bbda1db.png)

**Comment by lcd047** [comment]
Skim through the manual to get an idea how all this is supposed to work, copy the [recommended settings](https://github.com/scrooloose/syntastic#settings) to your vimrc, then read the [wiki entries](https://github.com/scrooloose/syntastic/wiki/Syntax-Checkers#user-content-cpp) for the checkers you want to use.  Checking C/C++ is more of a pain in the rear than checking other filetypes.  You'll probably want to create a [config file](https://github.com/scrooloose/syntastic/wiki/Configuration-Files) with the relevant compiler flags, and configure the checkers to use it.  Some checkers can use a [compilation database](http://clang.llvm.org/docs/JSONCompilationDatabase.html), but you'll have to make some special arrangements for that, too.  Sadly, none of this can be done automatically.

**Comment by Rmmichael95** [comment]
I have already copied the recommended settings and enabled some checkers in my .vimrc. Do you mean a config file separate from c.vim in in ~/.vim/bundle/syntastic/autoload/syntastic/c.vim? Also, will you complete me cause any problems? SyntasticInfo gives me-

Syntastic version: 3.6.0-130 (Vim 704, Linux)
Info for filetype: cpp
Global mode: passive
Filetype cpp is passive
The current file will not be checked automatically
Available checkers: clang_check clang_tidy gcc
Currently enabled checkers: -
Checkers for filetype cpp possibly disabled by YouCompleteMe

**Comment by Rmmichael95** [comment]
I got the checkers to enable properly but it still thinks standard library members are errors. Could this be ycm or is it just a mistake on my end?

Syntastic version: 3.6.0-130 (Vim 704, Linux)
Info for filetype: cpp
Global mode: passive
Filetype cpp is passive
The current file will not be checked automatically
Available checkers: clang_check clang_tidy gcc
Currently enabled checker: gcc
Checkers for filetype cpp possibly disabled by YouCompleteMe

**Comment by lcd047** [comment]
> Do you mean a config file separate from c.vim in in ~/.vim/bundle/syntastic/autoload/syntastic/c.vim?

`c.vim` is a source file, not a config file.

> Also, will you complete me cause any problems?

Yes, YCM disables syntastic checks by default.
