### ISSUE TITLE
gcc option to set flags

### ISSUE THREAD

**Issue by ScriptorNY** [scrooloose/syntastic#1492]
Hello,

I would like to know if there could be an option to be able to modify the base flags for at least the gcc checker, to be able to at least remove the *fsyntax-only* flag.

Thank you in advance :)

**Comment by lcd047** [comment]
No, currently `-fsyntax-only` can't be removed.  Sorry about that.

**Comment by ScriptorNY** [comment]
Thank you very much :) But if I manage to write one, would you accept it ?

Thank you again :)

**Comment by lcd047** [comment]
Probably not.  Allowing the removal of `-fsyntax-only` means dealing with object files, and this is something I'd like to avoid.

**Comment by ScriptorNY** [comment]
And if `-c -o /dev/null` was added at the end ? Don't worry this will be my very last question.

Anyway thank you very much for your time :)
