### ISSUE TITLE
Eslint moving to 1-based columns

### ISSUE THREAD

**Issue by gcochard** [scrooloose/syntastic#1494]
ESLint 1.0 will [switch to 1-based columns](http://eslint.org/blog/2015/07/eslint-1.0.0-rc-3-released/#breaking-changes-100-rc-1), so syntastic needs to get rid of the [workaround](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/javascript/eslint.vim#L47), or add a check for ESLint's version and only use the workaround on `v0.x`.

**Comment by lcd047** [comment]
Thank you for letting me know.  Please see bfc5579.

While you are at this: `"semi": [2, "never"]` produces column numbers off by 1.  There might be other similar problems, this is just from a quick look.

**Comment by gcochard** [comment]
Thanks for pointing this out, it's been fixed in ESLint for the semi rule!
