### ISSUE TITLE
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib

### ISSUE THREAD

**Issue by jeanmichelcote** [scrooloose/syntastic#1495]
Now that everything is installed, here is the error popping up when i load in Vim on OSX:

`syntastic: error: checker output:
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /usr/local/bin/shellcheck
  Reason: Incompatible library version: shellcheck requires version 13.0.0 or later, but libgmp.10.dylib provides version 12.0.0
syntastic: error: checker sh/shellcheck returned abnormal status 133`

So I did a `brew update && brew upgrade` and even a `brew upgrade gmp` but it said: `Error: gmp 6.0.0a already installed`

How should i get that version 13.0.0 instead of that 12.0.0 that i've got?

**Comment by lcd047** [comment]
How would I know?  Please note that it's shellcheck that complains, not syntastic.  Syntastic is just delivering you the news.

**Comment by jeanmichelcote** [comment]
I think you are quite prompt to close this issue.

**Comment by lcd047** [comment]
Let me put this in no uncertain terms: the problem has nothing to do with syntastic.  It has to do with shellcheck, and with package management on your system.  Sadly, I know very little about linking Haskell programs, and even less about package management on OSX.  Feel free to seek help for it here if you must (I hope you'll excuse me for not participating), but an _open_ issue with syntastic it isn't. _shrug_

**Comment by jeanmichelcote** [comment]
Fair enough.
