### ISSUE TITLE
syntasitc not popup when NERDTree open 

### ISSUE THREAD

**Issue by mydearxym** [scrooloose/syntastic#1496]
amazing work!
syntasitc works fine in terminal vim but in macVim , when NERDTree is open , it not showing up ..

**Comment by lcd047** [comment]
Please explain what did you do, what did you expect to happen, and what happened instead.

**Comment by lcd047** [comment]
Ping.

**Comment by mydearxym** [comment]
i' am  sorry ~~
### here is a demo( nerdTree  not open ): 
[![Gyazo](https://i.gyazo.com/5a4bfdefc8edd086f6a1954fa6f066dd.gif)](https://gyazo.com/5a4bfdefc8edd086f6a1954fa6f066dd)

### here is another demo( with nerdTree open)
#### the warning msg is not showing up ...
[![Gyazo](https://i.gyazo.com/8cada47f917c4dccdd1966273e18eaad.gif)](https://gyazo.com/8cada47f917c4dccdd1966273e18eaad)

**Comment by lcd047** [comment]
I can't reproduce the problem.  How are you triggering syntastic?  Please don't asume I can understand exactly what you're doing from your screenshot. :)

**Comment by mydearxym** [comment]
here is my config (the default config) , and i use latest macVim in (macOS 10.10.2)

```bash
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


```

**Comment by lcd047** [comment]
Please explain how are you triggering syntastic.  I can't see that in your screenshot.

**Comment by mydearxym** [comment]
sorry i don't know what you mean by triggering,  it's all Automatic ...

**Comment by lcd047** [comment]
You aren't running syntastic with the power of your mind, are you?  Please explain in English sentences what you're doing.  Are you writing the file?  Are you running `:SyntasticChecks`?  Do you have a macro that automates the write?  Is the cursor in the file window (as opposed to the nerdtree window) when you run syntastic?

**Comment by mydearxym** [comment]
you lost me ..
long words in short:  i close NERDTree , the "warning check" works fine , i open NERDTree the "warning check" works bad .

that's the best i can explain .

**Comment by lcd047** [comment]
Please run `:SyntasticInfo` with the NERDTree open, and post the output.

**Comment by mydearxym** [comment]
here comes: 

[![Gyazo](https://i.gyazo.com/f7df7f3648e355b805322d069f87aeeb.png)](https://gyazo.com/f7df7f3648e355b805322d069f87aeeb)

**Comment by lcd047** [comment]
Ok.  What happens if you run `:SyntasticCheck` with NERDTree open?

**Comment by mydearxym** [comment]
Thanks.
if i run :SyntasticCheck manually with NERDTree open it works fine ~ 
i guess "save"  not trigger :SyntasicCheck  with NERDTree open

**Comment by lcd047** [comment]
Please post the output of:
```vim
:verbose autocmd BufWritePost
```

**Comment by mydearxym** [comment]
OK , Without NERDTree : 

[![Gyazo](https://i.gyazo.com/b2f55ca10bac20627e0dbfef6a4aa10a.png)](https://gyazo.com/b2f55ca10bac20627e0dbfef6a4aa10a)

and with it open : 
[![Gyazo](https://i.gyazo.com/0f11fc66bc9e70a34d08162940a50fea.png)](https://gyazo.com/0f11fc66bc9e70a34d08162940a50fea)

**Comment by lcd047** [comment]
Great.  Now please try doing your test with all your plugins disabled, except for syntastic and NERDTree.

**Comment by mydearxym** [comment]
sorry,  but how to ?

**Comment by lcd047** [comment]
Temporarily move them somewhere else.

**Comment by mydearxym** [comment]
@lcd047   ok, then what?

**Comment by lcd047** [comment]
Then you try running syntastic with NERDTree open, as before.

**Comment by mydearxym** [comment]
with or without NERDTree open , it both not work
and when i try ; SyntasticCheck , it shows *Not an editor command: SyntasticCheck*  ...
i guess i could use SyntasticCheck without NERDTree open , it's not big deal

**Comment by lcd047** [comment]
Somehow you also disabled syntastic.  Please run the test with both NERDTree and syntastic left active.

**Comment by lcd047** [comment]
You seem to be using nerdtree-git-plugin.  According to #1391, nerdtree-git-plugin has a bug that prevents syntastic from working.  This doesn't seem to have been fixed to this day.

**Comment by mydearxym** [comment]
yes, i did use the nerdtree-git-plugin,  thanks for point out .

**Comment by NickolasHKraus** [comment]
This [pull request](https://github.com/Xuyuanp/nerdtree-git-plugin/pull/131) provides a solution.
