### ISSUE TITLE
Don't display version compatibility message on startup

### ISSUE THREAD

**Issue by marknsikora** [scrooloose/syntastic#1497]
Commit ffcf625fcb79cf9fc8006ee7cf96b5066c120c65 now displays an error message when an old version of vim is used. This runs against what the majority of other projects are doing. More details can be found in a similar issue I opened here easymotion/vim-easymotion#170.

**Comment by lcd047** [comment]
Your argument seems to be that you want to have the same vimrc on all your machines, therefore people should use their ESP capacities to find out what's going on when syntastic refuses to run.  Well, I happen to disagree.  Dying silently when it's perfectly possible to avoid that is asinine, regardless of what "the majority of other projects" are doing.  You can fix your vimrc to not activate syntastic if you must, f.i. by adding something like this before loading your package manager:
```vim
if v:version < 700 || (v:version == 700 && !has('patch175'))
    let g:loaded_syntastic_plugin = 1
fi
```

**Comment by marknsikora** [comment]
I could have sworn I posted a follow up here already.

Anyways I have a few complaints with your approach
1. Just about everyone running vim is using a very recent version. Only crazy people like me are running old versions and we are more than aware that not everything will work.
2. Adding that code to my vimrc means that I now have to keep on top of the dependencies of the project and update my code when you  do. This may not be a problem for a single project but most users are running dozens of plugins so this quickly becomes a hassle.

I understand where you are coming from. But could we settle in the middle and add something like`g:syntastic_no_warn_on_load`. So that users can disable these messages more easily.

**Comment by lcd047** [comment]
> Adding that code to my vimrc means that I now have to keep on top of the dependencies of the project and update my code when you do.

No.  You only have to update it when and if I ever find that I'm using a function that was added in a version more recent than 7.0.175, and I can't work around that at runtime.

> But could we settle in the middle

I'm afraid you're in a minority of one to need this, and you actually don't _need_ it either, since you have a perfectly good workaround.  Sorry, but no.
