### ISSUE TITLE
Syntastic shouldn't run when exiting with :wq

### ISSUE THREAD

**Issue by skylerberg** [scrooloose/syntastic#1499]
I have a checker that can be slow on large files (pylint). When I use `:wq` I have some lag time while syntastic does its stuff. However, this is pointless because I am just saving a quitting. I don't know how easy/feasible it would be to fix this, but it would be better if syntastic didn't do anything on a save and quit. This would prevent lag while exiting.

**Comment by lcd047** [comment]
Have you considered applying the [recommended settings](https://github.com/scrooloose/syntastic#settings)?

**Comment by skylerberg** [comment]
Thanks for the link. let `g:syntastic_check_on_wq = 0` is what I was looking for. One question before closing this bug. Why is this not on by default?

**Comment by lcd047** [comment]
Because you can add syntax errors in the edit before `:wq`, and they won't be caught.
