### ISSUE TITLE
eslint doesn't work

### ISSUE THREAD

**Issue by hydRAnger** [scrooloose/syntastic#1500]
I have installed eslint and flow, and I can run them in command line.
![image](https://cloud.githubusercontent.com/assets/1228449/9102342/9777edc6-3c23-11e5-8695-a5c544a1b50a.png)

![image](https://cloud.githubusercontent.com/assets/1228449/9102352/af92a464-3c23-11e5-9da3-17af8ebbfff6.png)

In my .vimrc(I use Vundle for plugin install):
" for scrooloose/syntastic
let g:syntastic_check_on_open = 1
" " for javacript
let g:syntastic_javascript_checkers = ['eslint', 'flow']

But if I open my vim, :SyntasticInfo's output:
Syntastic version: 3.6.0-143 (Vim 704, Linux)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
syntastic: error: checker output:
/bin/bash: jsxhint: command not found
syntastic: error: checker javascript/jsxhint: can't parse version string (abnormal termination?)
Available checker: flow
Currently enabled checker: flow

eslint doesn't work (It's used to be ok), and I have not installed jsxhint at all...
if I run :SyntasticInfo again, it's outpuy:
Syntastic version: 3.6.0-143 (Vim 704, Linux)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checker: flow
Currently enabled checker: flow

This time the jsxhint error disappear, but eslint is still available.

It's a bug? or stupid wrong caused by myself? Thx a lot!

**Comment by lcd047** [comment]
> npm run eslint

Try running this in a terminal:
```sh
eslint --version
```
If the output is anything else than a version string, f.i. `v1.0.0`, then syntastic won't consider it.  Fix that, and syntastic will be happy.

> syntastic: error: checker javascript/jsxhint: can't parse version string (abnormal termination?)

Syntastic doesn't run jsxhint out of its own will.  If jsxhint is not mentioned in your vimrc then your Vim reads other startup files than you think it does.  Look at the output of `:ver` to find out where Vim is looking for config files.

**Comment by hydRAnger** [comment]
@lcd047  
Yes, you are right. Thx! My eslint version is 0.24, I upgrade it to latest 1.0.0(npm install -g eslint), it works.
![image](https://cloud.githubusercontent.com/assets/1228449/9104139/c03914c6-3c3a-11e5-9e51-00748389e646.png)

The jsxhint error is still there, I checked all my vim startup files:
![image](https://cloud.githubusercontent.com/assets/1228449/9104151/f227e69c-3c3a-11e5-9730-564efdbb3aea.png)

But I can't find any thing about jsxhint. 
This confused me, but at least both eslint and flow can work correctly now. Thx!

**Comment by lcd047** [comment]
Hmm, right, that jsxhint message is a bug.  Please try 3fb8281.

**Comment by hydRAnger** [comment]
@lcd047  Cool, that's works, THX!
