### ISSUE TITLE
Invalid option g:syntastic_check_on_wq

### ISSUE THREAD

**Issue by sixgame** [scrooloose/syntastic#1501]
function! s:BufWritePostHook() abort " {{{2                                                                                                                                  
    +++ if g:syntastic_check_on_wq                                                                                                                                               
        call syntastic#log#debug(g:_SYNTASTIC_DEBUG_AUTOCOMMANDS,                                                                                                            
            \ 'autocmd: BufWritePost, buffer ' . bufnr('') . ' = ' . string(bufname(str2nr(bufnr('')))))                                                                     
        call s:UpdateErrors(1, [])                                                                                                                                           
    +++ end                                                                                                                                                                      
endfunction " }}}2

**Comment by lcd047** [comment]
Please explain (preferably in full English sentences) what you did, what did you expect to happen, and what happened instead.

**Comment by sixgame** [comment]
g:syntastic_check_on_wq does't work

**Comment by lcd047** [comment]
Please explain (preferably in full English sentences) what you did, what did you expect to happen, and what happened instead.

**Comment by lcd047** [comment]
Please reopen this when you're ready to express your problem in a meaningful post.  Thank you.
