### ISSUE TITLE
javac multi-line errors not rendering properly

### ISSUE THREAD

**Issue by aw1621107** [scrooloose/syntastic#1503]
I'm half sure it's something on my end, but I can't for the life of me figure out how to change the behavior

javac likes to use a carat to point to where exactly in a line an error occurs. Unfortunately, the carat on my system either doesn't render at all (usually for smaller windows), or appears somewhere off to the right, making it somewhat less helpful for debugging.

Is it possible to get multi-line errors to work, or is it a limitation from how errors are displayed?

I'm on OS X 10.11, using either neovim built from git or vim 7.4 (seems to occur on both), and java 1.9.0_b74. 

<img width="922" alt="javac" src="https://cloud.githubusercontent.com/assets/566572/9115057/cbfb81a8-3c22-11e5-8236-27debbd3fef7.png">
<img width="922" alt="vim" src="https://cloud.githubusercontent.com/assets/566572/9115058/cbfd3b88-3c22-11e5-8eb3-ade71c8d0d0c.png">

**Comment by lcd047** [comment]
Right, the `errorformat` seems to have been broken for a long time.  Please try 1ae5589.  Check with the output in terminal and report back if you see any discrepancies.

**Comment by aw1621107** [comment]
Only change I noticed is that the carat is gone:

<img width="922" alt="vim2" src="https://cloud.githubusercontent.com/assets/566572/9116107/34800136-3c28-11e5-8e1d-4cb2ade93a43.png">

**Comment by lcd047** [comment]
Yes, that's what was supposed to happen.  The error message is included, the offending line isn't.  Your screenshot above shows the expected behaviour.  If by "multi-line errors" you mean showing the entire output of javac in the error window, then no, this is not going to happen.

**Comment by aw1621107** [comment]
I suppose that's it then? Thank you for the quick response!
