### ISSUE TITLE
thank you for your work

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1507]
<img src="https://github.com/wsdjeg/wsdjeg.github.io/blob/master/Java/java1.png?raw=true">

**Comment by lcd047** [comment]
What an I supposed to see here?  Please explain (preferably in full English sentences) what you did, what did you expect to happen, and what happened instead.

**Comment by wsdjeg** [comment]
Tips abstract method has not been implemented

**Comment by lcd047** [comment]
Syntastic has nothing to do with code completion.
