### ISSUE TITLE
Ruby MRI, Ruby 2 Keyword Arguments raising errors

### ISSUE THREAD

**Issue by zzk** [scrooloose/syntastic#1510]
While using ruby 2 keywoard arguments syntastic is raising errors
````
def mehod(attribute:, attribute2:)
...
end
```
Errors:
```
error| unexpected ','
error| unexpected ')'
error| unexpected ')'
error| unexpected keyword_end, expecting end-of-input
```
More on [keyword arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments)

**Comment by lcd047** [comment]
Does #1506 help?

**Comment by zzk** [comment]
Not really. [My zshrc](https://gist.github.com/74f50f2f580e2345c337) and I've linked zshrc to zshenv.
This is what `:echo syntastic#util#system('ruby --version')` is returning:
`ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]`

**Comment by lcd047** [comment]
Well then, fix that, and syntastic will be happy. _shrug_
