### ISSUE TITLE
asm dialect intel and at&t

### ISSUE THREAD

**Issue by SmilePlz** [scrooloose/syntastic#1511]
here http://itmages.ru/image/view/2864124/03db6e95 let g:syntastic_asm_dialect = 'intel'
here http://itmages.ru/image/view/2866531/3062a9be let g:syntastic_asm_dialect = 'at&t'
but it is written in a dialect of intel.

**Comment by lcd047** [comment]
`let g:syntastic_asm_dialect = '<dialect>'` passes `-masm=<dialect>` to `gcc` when checking.  That's all it does, it has no direct meaning to syntastic itself.  On the other hand, `-masm=at&t` is not a valid value for `gcc`, only `att` and `intel` are.

**Comment by SmilePlz** [comment]
Thank you, I really made a mistake. But then I had an error in each line.
Syntastic version: 3.6.0-146 (Vim 704, Linux)
Info for filetype: asm
Global mode: active
Filetype asm is active
The current file will be checked automatically
Available checker: gcc
Currently enabled checker: gcc

**Comment by lcd047** [comment]
If the above doesn't address the problem, please explain what did you do, what did you expect to happen, and what happened instead.  Please describe the problem, rather than expect me to infer from two screenshots what you're trying to do, and what isn't working the way you expect.

**Comment by SmilePlz** [comment]
my setting:
Plug 'scrooloose/syntastic'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_error_symbol = "✗"
let g:syntastic_warning_symbol = "⚠"
let g:syntastic_asm_dialect = 'intel'

filename: 
03.05.01.asm

SyntasticCheck:
Syntastic version: 3.6.0-146 (Vim 704, Linux)
Info for filetype: asm
Global mode: active
Filetype asm is active
The current file will be checked automatically
Available checker: gcc
Currently enabled checker: gcc

example code:
; Найти сумму всех нечетных (s1) и сумму всех четных (s2) целых чисел в диапазоне от 1 до 100.
extern printf
%define MASK 1
%macro  pabc 2          ; a "simple" print macro
        section .text
        mov rdi, fmt4   ; first arg, format
        mov rsi, [%1]   ; second arg
        mov rdx, [%2]   ; third arg
        mov rax, 0      ; no xmm used
        call printf     ; Call C function
%endmacro
section .data
    fmt4 db "sum even = %d, sum not even = %d",10,0

error list:
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|1 error| Error: invalid character (0xd0) in mnemonic
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|2 error| Error: no such instruction: `extern printf'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|4 error| Error: junk at end of line, first unrecognized character is `%'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|6 error| Error: junk at end of line, first unrecognized character is `%'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|6 error| Error: no such instruction: `a "simple"print macro'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|7 error| Error: no such instruction: `section .text'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|8 error| Error: too many memory references for `mov'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|8 error| Error: no such instruction: `first arg,format'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|9 error| Error: invalid char '[' beginning operand 2 `[%1]'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|9 error| Error: no such instruction: `second arg'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|10 error| Error: invalid char '[' beginning operand 2 `[%2]'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|10 error| Error: no such instruction: `third arg'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|11 error| Error: too many memory references for `mov'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|11 error| Error: no such instruction: `no xmm used'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|12 error| Error: junk `function' after expression
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|13 error| Error: junk at end of line, first unrecognized character is `%'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|15 error| Error: no such instruction: `section .data'
/data/tmp/Assembler/Raceev/chapter 03/03.06.01.asm|16 error| Error: no such instruction: `fmt4 db "sum even = %d, sum not even = %d",10,0'

I get an error on each line. please tell me what am I doing wrong

**Comment by lcd047** [comment]
As far as I can tell it's `-masm` as in `-m<machine-option>`, one of the many `-m` options of `gcc`.  It has nothing to do with either `masm` or `nasm`, only `gcc` is involved, run as:
```vim
gcc -x assembler -fsyntax-only -masm=intel file.asm
```
