### ISSUE TITLE
"go build" for the syntax checking of golang is very crude.

### ISSUE THREAD

**Issue by baiyunping333** [scrooloose/syntastic#1513]
"go build" for the syntax checking of golang is very crude, Specially when the project is a little big,you must wait for 3 to 5 second while saving a golang code file. Have a better way?

**Comment by lcd047** [comment]
I'm afraid I don't have any better way, at least not any _practical_ one.  As somebody else used to put it, I'm not a pervert who has a better solution but refuses to share it. :)

**Comment by baiyunping333** [comment]
thank!!:smile:
