### ISSUE TITLE
ghc-mod version 

### ISSUE THREAD

**Issue by atondwal** [scrooloose/syntastic#1514]
I get

```
syntastic: error: checker haskell/ghc_mod: can't parse version string (abnormal termination?)        
```
Running `ghc-mod` doesn't give me the version number
```
:echo system('ghc-mod')
ghc-mod: No command given (try --help)
```
Problem might lie with the fact that I have a git version of ghc-mod, since the current hackage version doesn't compile with ghc7.10.

```
~ ❯❯❯ ghc-mod --version 
ghc-mod version 0 compiled by GHC 7.10.1
```

**Comment by lcd047** [comment]
You could try writing a wrapper like the following and pointing `g:syntastic_haskell_ghc_mod_exec` to it:
```sh
#! /bin/sh
if [ $# -eq 1 -a x"$1" = x--version ]; then
    echo ghc-mod version 5.2.1.2 compiled by GHC 7.6.3
else
    exec ghc-mod "$@"
fi
```
That said however, unreleased versions of the checkers are explicitly not supported by syntastic.  I have enough fun making syntastic keep pace with the released ones.

**Comment by atondwal** [comment]
I tried putting in the script, but it didn't help with the error.

On the other hand, `exec system()` works as expected.

```
:echo system('ghc-mod --version')
```

```
ghc-mod version 5.2.1.2 compiled by GHC 7.6.3
```

**Comment by lcd047** [comment]
> I tried putting in the script, but it didn't help with the error.

What did you do exactly?

**Comment by atondwal** [comment]
```
~ ❯❯❯ echo $PATH
/home/atondwal/bin:/home/atondwal/0-research/weimer/liquid/rolph-haskell/.cabal-sandbox/bin:/opt/ghc/7.8.4/bin:/home/atondwal/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
~ ❯❯❯ cat bin/ghc-mod
#! /bin/sh
if [ $# -eq 1 -a x"$1" = x--version ]; then
    echo ghc-mod version 5.2.1.2 compiled by GHC 7.6.3
else
    exec ~/.cabal/bin/ghc-mod "$@"
fi
~ ❯❯❯ 
```

**Comment by lcd047** [comment]
Don't rely on Vim seeing the `$PATH` you see in a terminal.  Achieving that is possible, but on most environments is far from trivial. :)

What I was suggesting was something like this:

* put the wrapper script in, say, `$HOME/bin/ghc-mod.sh`
* `let g:syntastic_haskell_ghc_mod_exec = $HOME . '/bin/ghc-mod.sh'`

**Comment by atondwal** [comment]
syntastic _does_ execute the right `ghc-mod` script, but the wrapper doesn't fix version error. I think that syntastic is maybe doing something more interesting than calling `ghc-mod --version` to get the version?

**Comment by lcd047** [comment]
Please try it my way before going any further.

**Comment by lcd047** [comment]
Never mind, it's more stupid than that.  The incantation is `ghc-mod version`, rather than `ghc-mod --version`.

**Comment by atondwal** [comment]
Yes, this is after doing it your way.

**Comment by atondwal** [comment]
changed the script to use `version` instead of `version` and everything works great!
