### ISSUE TITLE
Auto Location List should remember your place when you exit and return to the window

### ISSUE THREAD

**Issue by synic** [scrooloose/syntastic#1519]
If you go to the auto location window, go down to the third line and press enter, it will take you to that location in the file.  If you type `CTRL+W J` to go back to the auto location window, your cursor will not be where you left off, you'll be back on the first line.  It should remain where it was before.

This is something I miss from the straight flake8 plugin.  When there's lots of warnings, possibly some you've decided to skip, it can get pretty tedious to have to find the message you really want to fix.

**Comment by lcd047** [comment]
The `loclist` window is managed by Vim, not by syntastic.  A better approach is to navigate through the list without switching focus to the error window, cf. [FAQ](https://github.com/scrooloose/syntastic#faqlnext).

**Comment by synic** [comment]
@lcd047 hrmm, that will probably work, but now I wonder, if there's a way to activate the list without jumping to it, and instead using `:lnext`, etc

**Comment by synic** [comment]
Nevermind. It does that by default.  

Thank you, sir.
