### ISSUE TITLE
Ability to bypass checking of a single RST code blocks

### ISSUE THREAD

**Issue by floatingatoll** [scrooloose/syntastic#1521]
Hi, when writing an RST document with multiple Python code blocks, it doesn't appear to be possible to have Syntastic bypass syntax checking for an intentionally-wrong code block (when, for instance, a bad example must be presented).

Is there a way to tag the RST block somehow, so that syntastic can bypass checking of it?

**Comment by lcd047** [comment]
Once again: syntastic doesn't care about the contents of the files it checks.  What it does is, it runs external checkers against your files, and shows you the results.  That's all it does.  If the checkers you're using can do what you want, syntastic can do it too.  If the checkers can't do that, syntastic can't do it either.  Put another way: it's a question for a Sphinx forum (or a forum for whatever other checker you're using), not for syntastic. _shrug_

**Comment by floatingatoll** [comment]
My apologies, I was unfamiliar and didn't see anything in the FAQ covering that point.
