### ISSUE TITLE
the Plugin can't check syntastic error with the  XXX.h file

### ISSUE THREAD

**Issue by sd886393** [scrooloose/syntastic#1525]
Hi
I have already install this plugin and everything goes well (warn me  while I input :wq)when I writing a C source file.
Today  I 'm writing a  C header file,and there is a obvious syntastic error, but the plugin didn't warn me like before I edited the C source file and nothing happened.
And I check the https://github.com/scrooloose/syntastic/wiki/C%3A---gcc,and I put "let g:syntastic_c_check_header = 1"into the .vimrc file,but nothing change.

![Uploading testc.jpg…]()
![Uploading testh.jpg…]()

**Comment by lcd047** [comment]
Please describe what you did, what did you expect to happen, and what happened instead.  Also, please post a minimal test file that illustrates the problem.

**Comment by lcd047** [comment]
Ok, please feel free to reopen this when you're ready to explain what's wrong.
