### ISSUE TITLE
How to change the let g:syntastic_java_javac_classpath to relative path from Absolute path!

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1529]
in different projects i need to change the g:syntastic_java_javac_classpath in vimrc !
how to change the ages to relative path?

**Comment by lcd047** [comment]
You don't.  Rather, you read the [wiki](https://github.com/scrooloose/syntastic/wiki/Java%3A---javac), and figure out a better way to deal with the problem. :)
