### ISSUE TITLE
make location-list window height configurable

### ISSUE THREAD

**Issue by powerman** [scrooloose/syntastic#153]
Default height for location-list window is 10 lines, which is too much - I prefer 3, and even syntastic/_assets/screenshot_1.png have 5 lines.

Required change is trivial - just add user-configurable param for :lopen at syntastic.vim:336.

Currently one may use this workaround:

```
" set location-list window height to 3 lines
autocmd VimEnter * autocmd BufWritePost *
  \ if exists('b:syntastic_loclist')&&!empty(b:syntastic_loclist)|wincmd p|3 wincmd _|wincmd p|endif
```

**Comment by alphaCTzo7G** [comment]
Thanks superhelful.. the default size may be too large. Perhaps the default height should be set to 5
