### ISSUE TITLE
can this plugin autocompile java file?

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1530]
https://github.com/artur-shaik/vim-javacomplete2/issues/55
some config in my `.vimrc` 
```vim
Plugin 'artur-shaik/vim-javacomplete2'
Plugin 'airblade/vim-rooter'
let g:rooter_patterns = ['Rakefile', 'web.xml']
let g:JavaComplete_LibsPath = 'classes/:lib/:/home/wsdjeg/tools/apache-tomcat-8.0.24/lib'
```
in the WEB-INF dir contains  classes/   lib/   src/ and    web.xml
the plugin `rooter` helps me set the pwd WEB-INF/
all the necessary jar is  included in lib/
java file is included in the src/
class file is included in the classes/
I want to compile the file when save it!
Maybe this function would be the best solution? 
Like add this to vimrc
```vim
let g:javacomplete_compile_on_save = 1  "default is 0
let g:javacomplete_compile_outputdir = 'classes'
```

**Comment by lcd047** [comment]
You don't need syntastic for that.  Set up Vim to compile your project when you run `:make` (in particular, see `:help :make_makeprg` and `:help compiler-select`).  When this is working to your liking, automate it with an `autocmd`:
```vim
autocmd BufWritePost * nested make
```

**Comment by wsdjeg** [comment]
it does not work ,misss the jar in lib/

**Comment by lcd047** [comment]
It's up to you to make it work.  It still has nothing to with syntastic, which is about checking syntax, not about running builds.
