### ISSUE TITLE
syntastic: error: checker javascript/jshint returned abnormal status 1

### ISSUE THREAD

**Issue by fc** [scrooloose/syntastic#1533]
I receive the following error when saving (this is from the debug output):
syntastic: 65.551269: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 65.551920: UpdateErrors (auto): default checkers
syntastic: 65.552383: CacheErrors: default checkers
syntastic: 65.553304: g:syntastic_aggregate_errors = 0
syntastic: 65.553613: getcwd() = '/Users/me/Site/public/assets/js'
syntastic: 65.554173: CacheErrors: Invoking checker: javascript/jshint
syntastic: 65.554885: SyntasticMake: called with options: {'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)', 'defaults': {'bufnr': 3}, 'makeprg': 'jshint --verbose  globals.js | grep -E E[0-9]+.$', 'returns': [0, 2]}
syntastic: 65.989546: checker output: ['']
syntastic: error: checker javascript/jshint returned abnormal status 1
syntastic: 65.990448: javascript/jshint raw: []
syntastic: 65.990944: quiet_messages filter: {}
syntastic: 65.991924: aggregated: {'_sorted': 0, '_name': '', '_owner': 3, '_columns': 1, '_rawLoclist': []}

When I call this:
echo system('jshint --verbose  globals.js | grep -E E[0-9]+.$'):

I get no errors

my vimrc
let g:syntastic_javascript_checkers = ["jshint"]
let g:syntastic_javascript_jshint_args = ""
let g:syntastic_javascript_jshint_tail = "| grep -E E[0-9]+.$"

When I call from the command line I get no errors...

I do not have a .jshintrc

Using the latest version of jshint (2.8.0) and syntastic (3.6.0-151), vim (7.4)

**Comment by fc** [comment]
other syntastic settings I have in vimrc:

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_php_checkers = ["php"]

**Comment by lcd047** [comment]
What happens if you leave alone `g:syntastic_javascript_jshint_args` and `g:syntastic_javascript_jshint_tail`?

**Comment by fc** [comment]
ah, yes, no more 'abnormal normal' errors anymore and it shows the correct output in the quickfix dialogue.  How can I correctly filter the jshint then to only show the errors?

**Comment by lcd047** [comment]
> How can I correctly filter jshint then to only show the errors?

Please see `:help 'syntastic_quiet_messages'`.

> The tail is doing something to the output?

```sh
$ echo foo | grep -E E[0-9]+.$
1
```
The checker expects exit codes 0 or 2.

**Comment by fc** [comment]
For the curious, do this:
let g:syntastic_javascript_jshint_quiet_messages = { "level": "warnings" }

**Comment by lcd047** [comment]
@fc The curious should read the manual, rather than apply any particular canned solution.  Doing that would save everybody's time.
