### ISSUE TITLE
No available checkers

### ISSUE THREAD

**Issue by jrock2004** [scrooloose/syntastic#1537]
When I do a SyntasticInfo, it is howing that there are not active checkers. Before opening I rant npm install -g jslint. 

```
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
```

Could it be cuase I have a custom location where my npm installs global apps? I have them installed in 

```
/home/jcostanzo/.npm-packages/
```

Here is output of info

```
Syntastic version: 3.6.0-153 (Vim 704, Linux)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```

Thanks

**Comment by lcd047** [comment]
> Could it be cuase I have a custom location where my npm installs global apps?

That's the prime suspect, yes.  Syntastic looks for an executable named `jslint` in `$PATH`.  However, the `$PATH` seen by Vim might not be the one you see in a shell.  Run `:echo syntastic#util#system('echo "$PATH"')` from Vim to find out (cf. [FAQ](https://github.com/scrooloose/syntastic#faqinfo)).

**Comment by jrock2004** [comment]
That was it. I had my path setup wrong
