### ISSUE TITLE
SyntasticJavacEditClasspath is not the command?

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1539]
i use .syntastic_javac_config for differdent project,
if i do not add this into vimrc will get the error.
```vim
let g:syntastic_check_on_open = 1
```

**Comment by lcd047** [comment]
Please see #522.  Does that address your problem?

**Comment by lcd047** [comment]
Actually, please update to 1be9077.  It should remove the need to initialize the checker first.

**Comment by wsdjeg** [comment]
Thank you for your work ,the problem has been resolved!
