### ISSUE TITLE
jshint or jsxhint for react

### ISSUE THREAD

**Issue by bfwg** [scrooloose/syntastic#1543]
I'm writing a React Native project. How can I open jshint in syntastic?

The files are in .js format through. 

<img width="639" alt="screen shot 2015-09-08 at 4 46 36 pm" src="https://cloud.githubusercontent.com/assets/12819525/9750160/33e397c0-5649-11e5-8188-a5734a279d96.png">

**Comment by lcd047** [comment]
Please explain what you did, what did you expect to happen, and what happened instead.  No screenshots unless I explicitly ask for them please.

**Comment by bfwg** [comment]
@lcd047 
I expect JSX syntax check to be enabled, how do I do that?

**Comment by lcd047** [comment]
You read the manual and the [relevant wiki entry](https://github.com/scrooloose/syntastic/wiki/JavaScript%3A---jsxhint), then you make the necessary adjustments to your vimrc.

**Comment by bfwg** [comment]
@lcd047 
Thanks! It is working now!
