### ISSUE TITLE
Is there a way to open flow syntax check?

### ISSUE THREAD

**Issue by bfwg** [scrooloose/syntastic#1546]
I'm getting `Expected ')' to match '(' from line ... and instead saw ':'.` 
When I try to write `timeoutID (null: any)`
Is there a way to open syntax check for flow? or even ignore it.
I'm looking for something like 
`let g:syntastic_javascript_checkers = ['flow']` in my vimrc

Thanks

**Comment by lcd047** [comment]
Do you have `flow` installed?  Is `flow` working outside syntastic?  Did you configure your project to use `flow`?

**Comment by bfwg** [comment]
@lcd047 
Yes flow is installed, and when I run `flow check` it is working.
What I want is syntastic to recognize flow's syntax(`var a : string;`) because now it is not and the syntax checker got blocked and stopped at the line which has the flow syntax. 
So if I have another syntax error below that line, if will not show.

Thanks!

**Comment by lcd047** [comment]
Please open a JavaScript file from your project, run `:SyntasticInfo`, and post the output.

**Comment by bfwg** [comment]
`Syntastic version: 3.6.0-147 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: eslint flow jshint jsxhint
Currently enabled checker: jsxhint`

**Comment by lcd047** [comment]
You need to set `g:syntastic_javascript_checkers`.  See `:help :SyntasticCheck`,
`:help 'g:syntastic_<filetype>_checkers'`, and `:help syntastic-aggregating-errors`.

**Comment by bfwg** [comment]
@lcd047  Thank you! It is working now!
