### ISSUE TITLE
Syntastic causes creation of new windows.

### ISSUE THREAD

**Issue by jjpikoov** [scrooloose/syntastic#1551]
When Synastic tells me about errors in my code, it automatically opens new empty window. Changing buffers with :bn :bp makes it happen again and again.

![screenshot from 2015-09-18 16 07 01](https://cloud.githubusercontent.com/assets/3046087/9963637/8b401648-5e2c-11e5-9a7a-fa8ebbaf8f25.png)
![screenshot from 2015-09-18 16 07 23](https://cloud.githubusercontent.com/assets/3046087/9963638/8b406904-5e2c-11e5-9ebf-a2309d22dc79.png)
![screenshot from 2015-09-18 16 08 14](https://cloud.githubusercontent.com/assets/3046087/9963635/8b3dca1e-5e2c-11e5-9d89-7a9c04aebb5e.png)

**Comment by lcd047** [comment]
Do you happen to have `minibufexpl` installed, by any chance?  If you do, please see #1538.

**Comment by jjpikoov** [comment]
I removed minibufexpl plugin and now everything works fine. Thanks for help.
