### ISSUE TITLE
Error when file only contains shebang

### ISSUE THREAD

**Issue by bengadbois** [scrooloose/syntastic#1554]
I created a new file that's just
``` #!/bin/bash/ ```
Fails if a single or line or followed by newlines

Upon saving, get the following error:
![error](http://i.imgur.com/KDHWY5P.png)

Once there's a non-whitespace character, such as:
```
#!/bin/bash/ 
x
```
then it does not throw the error

Syntastic version: 3.6.0-168 (Vim 704, Linux)
Info for filetype: sh
Global mode: active
Filetype sh is active
The current file will be checked automatically
Available checkers: sh shellcheck
Currently enabled checkers: sh shellcheck

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@

**Comment by myint** [comment]
This is a `shellcheck` issue rather than a Syntactic issue. See https://github.com/koalaman/shellcheck/issues/228. (Also, do you mean `#!/bin/bash` rather than `#!/bin/bash/`?

**Comment by bengadbois** [comment]
Correct, I meant ```#!/bin/bash```

Thanks for correctly identifying
