### ISSUE TITLE
Add eslint_d?

### ISSUE THREAD

**Issue by clessg** [scrooloose/syntastic#1556]
https://github.com/mantoni/eslint_d.js/blob/master/plugins/eslint_d.vim

A daemonized version of eslint that makes it considerably faster.

**Comment by lcd047** [comment]
Please see #1553, about 3 posts down from yours.

**Comment by clessg** [comment]
Silly me.

**Comment by mantoni** [comment]
@clessg Fixed up eslint_d to directly work with the existing eslint checker. See the updated docs for details: https://github.com/mantoni/eslint_d.js#editor-integration

**Comment by clessg** [comment]
@mantoni Awesome!
