### ISSUE TITLE
getStatuslineFlag needs a filename for large codebases

### ISSUE THREAD

**Issue by apriendeau** [scrooloose/syntastic#1558]
For example, `vim-go` uses `go build` to send back build errors but it checks every file so it would be useful to have the filename before the line number and have it check for it.

**Current:** [Syntax: line:17 (1)]

**Suggested if filename is sent:** [**filename**: line:17(1)]

**Comment by lcd047** [comment]
Please see commit d73d760.  It adds a number of flags to `syntastic_stl_format`:

* `%ne` - filename of file containing first error
* `%nw` - filename of file containing first warning
* `%N` - filename of file containing first warning or error
* `%pe` - filename with path of file containing first error
* `%pw` - filename with path of file containing first warning
* `%P` - filename with path of file containing first warning or error

They are probably less than useful without some way to control the width of the results, but implementing that properly (that is, taking into account wide characters and the like) is less than trivial.  You can control the width of `%{SyntasticStatuslineFlag()}` in `statusline` though.

**Comment by lcd047** [comment]
Commit e0a3cf7 adds width control to the above flags, namely `%-0{minwid}.{maxwid}{flag}`.
