### ISSUE TITLE
how to support viml check?

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1562]
hi scrooloose
 do you know how to config this plugin ,i want to check vim script ?

**Comment by lcd047** [comment]
Syntastic supports two checkers for VimL, [vimlint](https://github.com/scrooloose/syntastic/wiki/VimL%3A---vimlint) and [vint](https://github.com/scrooloose/syntastic/wiki/VimL%3A---vint).

**Comment by wsdjeg** [comment]
thank i will find how to config
