### ISSUE TITLE
the plugin config doen not work!

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1563]
```vim
NeoBundle 'syngan/vim-vimlint', {
    \ 'depends' : 'ynkdir/vim-vimlparser'}
let g:syntastic_vimlint_options = {                                                                                                              
          \'EVL102': 1 , 
          \'EVL103': 1 , 
          \'EVL205': 1 , 
          \}
NeoBundle 'ynkdir/vim-vimlparser'
NeoBundle 'gcmt/wildfire.vim'
```
but the warning 205 still shown

**Comment by lcd047** [comment]
This seems to be a bug in `vimlint`.  Create a file `test.vim` with contents:
```
let g:foo = '⚠'
```
then run `:echo vimlint#vimlint(expand('%'), {'quiet': 1, 'EVL205': 1})`.

**Comment by lcd047** [comment]
Apparently there's a [similar problem with `EVL105`](https://github.com/syngan/vim-vimlint/issues/48), and as I understand it the root is actually in `vimlparser`.  The bad news is that the problem hasn't been solved in more than an year.

**Comment by lcd047** [comment]
I posted a [bug report](https://github.com/syngan/vim-vimlint/issues/81).
