### ISSUE TITLE
if there is no error ,please do not open the syntastic_auto_loc_list!

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1564]
sometimes there is onle warning for java,the plugin will open the syntastic_auto_loc_list,i want it do not open the list windows when there are only some warning and without errors!
how can i config it,please?

**Comment by lcd047** [comment]
Currently syntastic can't do that.  It is however possible to disable warnings, by setting `g:syntastic_<filetype>_<checker>_quiet_messages` to an apropriate value.  See `:help 'syntastic_quiet_messages'` for details.
