### ISSUE TITLE
Performance issues with eslint

### ISSUE THREAD

**Issue by unphased** [scrooloose/syntastic#1565]
I have not been able to find any configuration that allows me to limit the number of errors and warnings that are produced when using eslint with syntastic. The problem is that sometimes I have javascript files where there is minified copypaste code inside, and these generate enormous quantities of ignorable errors. This would be fine if it did not bring Vim to a crawl. 

Workarounds abound but none seem to be available: 

1. ability to specify specific files to disable syntastic on (relative or absolute path or with a glob or regex matcher)
2. ability to configure eslint to limit to a maximum number of errors and warnings
3. ability to configure syntastic to limit to a maximum number of signs rendered in vim based on the list of errors and warnings

None of these paths seems to lead anywhere.

**Comment by lcd047** [comment]
> ability to specify specific files to disable syntastic on (relative or absolute path or with a glob or regex matcher)

`:help syntastic-filtering-errors`

> ability to configure eslint to limit to a maximum number of errors and warnings

Perhaps ask about this on an `eslint`-related forum?

> ability to configure syntastic to limit to a maximum number of signs rendered in vim based on the list of errors and warnings

For what it's worth, it isn't the number of signs that slow down Vim, but the `echo` notification.  Try `:help 'syntastic_cursor_columns'`, and `:help 'syntastic_echo_current_error'`.

**Comment by unphased** [comment]
I was hoping that I was missing something simple I could use effectively, but looks like i was right... i think the eslint config to limit error count is the best bet. 

`:help syntastic-filtering-errors` shows that i can disable specific types of errors. that is not what I want. i want all the errors i set up my linter to give me, i just need to disable or at least be able to handle certain files.

Thanks for the tips on `syntastic_cursor_columns` and `syntastic_echo_current_error`, these are all features that i would like to keep, of course...

**Comment by lcd047** [comment]
> `:help syntastic-filtering-errors` shows that i can disable specific types of errors.

Should you ever decide to invest a few seconds in _understanding_ what you read, it also tells you how to disable checks for specific files.  There are even multiple ways to do it.

**Comment by unphased** [comment]
My bad... 

To make up for it I have added an answer to [this question](http://stackoverflow.com/questions/20030603/vim-syntastic-how-to-disable-the-checker/32858266#32858266)

**Comment by lcd047** [comment]
Actually, the proper answer to the [SO question](http://stackoverflow.com/questions/20030603/vim-syntastic-how-to-disable-the-checker) is the [one](http://stackoverflow.com/a/20034744) currently marked as accepted: use passive mode.
