### ISSUE TITLE
will the check for java project with pom.xml be faster!

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1566]
i find that the check for java project with pom.xml very slow on the fist time  checking!
i hava set the option that checking on saving file,so when i first time open a file ,edit it ,save it,now the plugin will work,but it is very slow,but if i do not close the vim ,and edit this file ,and save it,the next time checking is very fast!
so i guess on en first time check ,the plugin need time to load the pom.xml and get the classPath! 

can you add some function just like JavaComplete2 ,translate the project's pom.xml to ~/.syntastic/mvnclasspath/Path_to_project_pom.xml,

i think this function will let the firsttime checking be quick

also thank you for this function that autocompile when saving file ,the function help me a lot!

**Comment by lcd047** [comment]
That's not why the `javac` checker is slow.  However, please feel free to prove me wrong by posting a (working) PR.

**Comment by wsdjeg** [comment]
i know ,javac checker is not slow ,i think the first time checking need more time to!
as the wiki show me:
g:syntastic_java_javac_autoload_maven_classpath (Default: 1)
    if enabled, and a file pom.xml is found in the current working directory, maven is used to load Maven project's classpath
 i think this progress need more time ,and if the plugin load the classpath and save it into a new file named "~/.syntastic/mvnclasspath/Path_to_project_pom.xml",just like JavaComplete2 

then the next time to use the plugin will not reload the pom.xml

sorry i really not good at vimL,so i can not give the PR

**Comment by wsdjeg** [comment]
![2015-10-02 22-21-25](https://cloud.githubusercontent.com/assets/13142418/10248725/f45551ca-6953-11e5-89f0-ca3fc0beae3c.png)
![2015-10-02 22-20-47](https://cloud.githubusercontent.com/assets/13142418/10248759/312ffa1e-6954-11e5-901d-782c5b83e7a5.png)

**Comment by lcd047** [comment]
Like I said: that's not why `javac` is slow.  Enable [profiling](https://github.com/scrooloose/syntastic/wiki/Profiling-syntastic) to find the real bottlenecks.

**Comment by wsdjeg** [comment]
i seems nothing wrong with syntastic
https://github.com/wsdjeg/JavaWeb/blob/master/syntastic.log

**Comment by lcd047** [comment]
You have to turn on profiling and trigger the slowdown.  Otherwise you're just profiling the initialisation, which is useless.

**Comment by wsdjeg** [comment]
can you please have a look ,i think i find where the time is gone!
https://github.com/wsdjeg/JavaWeb/blob/master/syntastic.log

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    2   2.688096   0.018620  <SNR>237_GetMavenProperties()
    1   3.002208   0.000409  <SNR>237_GetMavenClasspath()
    1   6.330038   0.000405  SyntaxCheckers_java_javac_GetLocList()
    1   2.688411   0.000233  <SNR>237_MavenOutputDirectory()

**Comment by lcd047** [comment]
This shows that the slowdown comes from running `maven -f pom.xml help:effective-pom` and parsing the output, not from finding the `pom.xml` file.

**Comment by wsdjeg** [comment]
https://github.com/artur-shaik/vim-javacomplete2
this plugin alse need to parsing the pom.xml
but the plugin translate the output into a new file which is show in the above picture,contain all the classpath,

**Comment by lcd047** [comment]
I'm not sure why you think that's relevant to syntastic.  Syntastic does more than parse the classpath out of that command.

**Comment by wsdjeg** [comment]
maybe it is my fault,i will check my vimrc ,thank you
