### ISSUE TITLE
will the plugin support jsp checking?

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1568]
i am useing mvn create javawebApp ,not the java checking auto compile function is ok, i just need jsp checking ,will the plugin support it?

**Comment by lcd047** [comment]
You tell us.  It's up to you to configure the checker to run with the proper flags for your project, and use it only when it makes sense.  You can see how syntastic is calling the checker by enabling debugging (see `:help 'syntastic_debug'`).

**Comment by wsdjeg** [comment]
i really can not config ,i know syna call the cherker and show me the compile info;and i know the plugin call the mvn compile java file and auto set the output dir is target/classes,just the same as mvn itself .so i do not need to delete the output file .the i find the tools compile jsp file is not javac or mvn

**Comment by wsdjeg** [comment]
and i find there is no checkers for jsp in the wiki

**Comment by lcd047** [comment]
There you have it, you found the answer.
