### ISSUE TITLE
function mentioned in the readme is now missing

### ISSUE THREAD

**Issue by shime** [scrooloose/syntastic#1570]
when I try following [the first answer in the FAQ](https://github.com/scrooloose/syntastic#4-faq), Vim trows these errors at me:

    E117: Unknown function: syntastic#util#system
    E15: Invalid expression: syntastic#util#system('echo "$PATH"')

what happened with that function? what can I use as an alternative? 

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 29 2015 16:29:06)
MacOS X (unix) version

Syntastic 3.6.0
```

**Comment by lcd047** [comment]
Right, `syntastic#util#system()` was added after 3.6.0.  Upgrade to master HEAD and you'll have it.  I suppose it's time for a new release...

**Comment by lcd047** [comment]
Ok, [done](https://github.com/scrooloose/syntastic/releases/tag/3.7.0).

**Comment by shime** [comment]
:tada:   turns out I didn't have pathogen installed correctly, sorry for trolling :trollface:

**Comment by lcd047** [comment]
That could be, but still, `syntastic#util#system()` wasn't in the 3.6.0 release. :)
