### ISSUE TITLE
Point syntastic checker at local npm module

### ISSUE THREAD

**Issue by willmcclellan** [scrooloose/syntastic#1571]
We use nvm for node project which means switching node versions frequently so we avoid globally installed modules (with `npm install -g ...`) and install them locally.

Is there anyway to point syntastic at the projects local eslint module instead of a global path?

**Comment by olalonde** [comment]
+1

**Comment by lcd047** [comment]
Normally something like this should work:
```vim
let g:syntastic_javascript_eslint_exec = $HOME . '/bin/eslint'
```
However, there have been reports in the past of it not working on Mac OS-X, and there are persistent rumours that you can only run global mode modules from Vim, at least on some systems.  As far as syntastic is concerned checkers are just executables, it doesn't know (nor cares) about what happens under the hood.  It doesn't do anything special, it just runs checkers with `system()`.  If there is anything that prevents local node modules from running this way, it's between Vim, node, and your shell. _shrug_

**Comment by olalonde** [comment]
I believe parent meant `./node_modules/.bin/eslint` (as installed with `npm install --save-dev eslint` for example).

**Comment by lcd047** [comment]
Whatever the exact path is, my point still stands.

**Comment by wilmoore** [comment]
The following seems to be working for me:

```vim
" after/ftplugin/javascript.vim

" JavaScript Standard Style (standardjs.com)
let b:syntastic_checkers = ['standard']

" Point syntastic checker at locally installed `standard` if it exists.
if executable('node_modules/.bin/standard')
  let b:syntastic_javascript_standard_exec = 'node_modules/.bin/standard'
endif
```

**Comment by lcd047** [comment]
@wilmoore Are you doing that on Mac OS-X?  And that's a less than great way to do it, anyway.

**Comment by wilmoore** [comment]
Hi @lcd047 

> Are you doing that on Mac OS-X? 

Yes.

> And that's a less than great way to do it, anyway.

What would be a better way to do it? I'm open to working alternatives for sure.

**Comment by lcd047** [comment]
> What would be a better way to do it? I'm open to working alternatives for sure.

Err, perhaps try using full paths and `autocmd`s?

**Comment by olalonde** [comment]
I'm using `autocmd FileType javascript let b:syntastic_checkers = findfile('node_modules/.bin/standard', '.;') != '' ? [ 'standard' ] : [ 'eslint' ]`

**Comment by willmcclellan** [comment]
Neither @wilmoore or @olalonde suggestions seemed to work for me, as soon as I uninstalled the global package it stopped working. I think syntastic requires the full path to the executable which has to be on your path?

**Comment by wilmoore** [comment]
> Err, perhaps try using full paths ...

Ideally, what I'm after is to find an executable that is installed relative to the project. If there is a better way to achieve what I am after, would you mind providing an example?

> ... and autocmds?

I could be mistaken (still trying to grasp the ins and out of vimscript) but aren't `autocmds` redundant if I am in a [ftplugin](http://vim.wikia.com/wiki/Keep_your_vimrc_file_clean) file?

**Comment by wilmoore** [comment]
@willmcclellan 

> Neither @wilmoore or @olalonde suggestions seemed to work for me, as soon as I uninstalled the global package it stopped working.

I am not sure what to tell you there, but I was able to test it will the globally installed one existing and not existing and it worked in both cases.

FWIW, here is a link to my dotfiles in case you spot something that may help you:
https://github.com/wilmoore/dotfiles/blob/master/active/.vim/after/ftplugin/javascript.vim

###### SyntasticInfo

```
:SyntasticInfo
Syntastic version: 3.6.0-92 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checker: flow
Currently enabled checkers: -
```

###### Vim Info

```
❯ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  4 2015 02:59:15)
MacOS X (unix) version
Included patches: 1-712
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/Users/wilmoore/.homebrew/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -isystem/Users/wilmoore/.homebrew/include -F/Users/wilmoore/.homebrew/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/Users/wilmoore/.rbenv/versions/2.2.0-dev/lib  -fstack-protector -L/Users/wilmoore/.homebrew/lib  -F/Users/wilmoore/.homebrew/Frameworks -Wl,-headerpad_max_install_names -L/usr/local/lib -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/Users/wilmoore/.homebrew/Cellar/python/2.7.10/Frameworks -framework Python   -lruby-static -framework CoreFoundation -lobjc -L/Users/wilmoore/.rbenv/versions/2.2.0-dev/lib
```

**Comment by lcd047** [comment]
> Ideally, what I'm after is to find an executable that is installed relative to the project.

How should Vim distinguish the root directory of your project from other directories?

> I could be mistaken (still trying to grasp the ins and out of vimscript) but aren't `autocmds` redundant if I am in a [ftplugin](http://vim.wikia.com/wiki/Keep_your_vimrc_file_clean) file?

Some `autocmd`s are redundant, others aren't.  `ftplugin` files are loaded at the wrong time for this, you want something that gets run each time you switch buffers, so that you could, in principle, load files from different projects and check each of them with the appropriate `eslint` (not that you'd need to do that in practice, but it's much cleaner to approach it that way).

**Comment by wilmoore** [comment]
> ftplugin files are loaded at the wrong time for this, you want something that gets run each time you switch buffers

Ah...good point.

**Comment by olalonde** [comment]
Anyone else getting `Undefined variable: g:syntastic_javascript_eslint_exec`?
