### ISSUE TITLE
tslint.conf

### ISSUE THREAD

**Issue by felixSchl** [scrooloose/syntastic#1574]
Is there any way to use `tslint.conf`, similarily to how `.eslintrc` gets used?

**Comment by lcd047** [comment]
Maybe, depending on what you mean by that.

**Comment by felixSchl** [comment]
Well, `tslint -c tslint.config` where `tslint.conf` is expected to be found at the project root. So that tslint uses my rules rather than the defaults

**Comment by lcd047** [comment]
So, what stops you from doing that?

**Comment by felixSchl** [comment]
Well, it's not working, it's not respecting my `tslint.conf`. It may be obvious to you, but it is not to me and I have not found any docs neither in the repo itself nor with `:h syntastic`, so I feel this is a legitimate question to ask. I have read the source code and [I cannot see any trace of `-c` being passed to `tslint.conf`](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/typescript/tslint.vim#L29-L31).

**Comment by felixSchl** [comment]
Ok, it was me being stupid. I referred to the tslint docs again, and the file name has to be "tslint.**json**" and tslint will do the search for the file itself. I am very sorry for the noise, there's absolutely nothing wrong this side of things.

**Comment by lcd047** [comment]
Right: you want to emulate in VimL what `eslint` does by default, but you'd rather not spend a few minutes finding the relevant part of the manual.  Ok, here it is, digested for you from `:help syntastic-config-makeprg`:
```vim
let g:syntastic_typescript_tslint_args = '-c tslint.conf'
```
So, to mimic what `eslint` does, you'd do something like this:
```vim
function! TSLintConfig(dir)
    let config = findfile('tslint.conf', escape(a:dir, ' ') . ';')
    return config !=# '' ? '-c ' . config : ''
endfunction

autocmd BufNewFile,BufReadPre *.ts
    \  let b:syntastic_typescript_tslint_args = TSLintConfig(expand('<amatch>:h'))
```
