### ISSUE TITLE
Throwing in the towel for ghc-mod

### ISSUE THREAD

**Issue by lcd047** [scrooloose/syntastic#1576]
Starting with version 5.4.0, `ghc-mod` wants to be [run from the root directory of the project](https://hackage.haskell.org/package/ghc-mod-5.4.0.0/changelog).  To be precise, it can find the root directory of the project, but it won't `chdir` to that directory itself, it requires the user to do it beforehand.  Syntastic could, in principle, run `ghc-mod root` to find out the root directory, `chdir` to it, and run `ghc-mod` from there, but then it would need to transform the paths in error messages accordingly, or Vim would get confused.  Syntastic is not prepared to cope with this situation, and asking users to run Vim in the roots of their projects just to be able to use the `ghc-mod` checker doesn't seem reasonable.

Consequently, `ghc-mod` versions 5.4.0 and later are no longer supported.  Syntastic's checker `ghc-mod` will continue to run with earlier versions of `ghc-mod`, but the checker itself will be removed from syntastic in a future release.  I'm sorry about that, and I thank you in advance for your understanding.

If you want to take over the maintenance of the `ghc-mod` checker, please follow the instructions for writing an [external checker](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#external).  When you have a working version drop me a note, and I'll remove the existing checker from syntastic and add a link to your project from the `README` file.

In the mean time, please consider using [ghcmod-vim](https://github.com/eagletmt/ghcmod-vim) instead of syntastic for working with `ghc-mod`.  It's written specifically for `ghc-mod`, and it has features syntastic will never have.

**Comment by DanielG** [comment]
This is the soft of thing you should really report upstream. I had no idea people were having such trouble with the rootdir stuff.

So let me get this straight; absolute paths are fine but relative paths have to be relative to the current file, is that right?

**Comment by lcd047** [comment]
@DanielG I'm sorry, but at this point I'm not searching a solution.  If you look at the code, the syntastic checker for `ghc-mod` is a small encyclopaedia of workarounds and special cases.  It has a long, long history at that: the NUL at endlines, printing filenames in UTF-8 regardless of the current locales, changing the way to get program's version at least three times (maybe more, I can't seem to recall right now), and so on.  Most of these are trivial from the point of view of `ghc-mod` users (and authors).  However, they all have something in common: each of them requires some kind of special handling in syntastic.  Assuming the problem above is addressed somehow (by adding an option to resolve paths, or by rolling back to sanity, or whatever), fixing it in syntastic would involve adding yet another special case.  I'm really not looking for ways to spend even more time playing catch with `ghc-mod` development.

Looking at it from the user's perspective, syntastic doesn't add much value to `ghc-mod` anyway.  It isn't aware of cabal, or anything else specific to Haskell.  There are other Vim plugins that do a much better job at integrating `ghc-mod`.  People maintaining those plugins actually use `ghc-mod`, and presumably care about it.  Syntastic never tried to match said plugins in terms of features.  Dropping support for `ghc-mod` from syntastic shouldn't be a huge loss for anybody. _shrug_

Still, as I said: if you (or anybody else) want to take over the maintenance of the checker, feel free to do it.  Let me know when you have something working, and I'll add a link to your project.

**Comment by DanielG** [comment]
Oh I'm not interrested in maintaining it, no. I'm maintaining ghc-mod already keeps me busy ;)

I'm really sorry about all that breakage my recommendation for anyone developing frontends is not to try and support older ghc-mod version and potentially document which version of ghc-mod are supported in older frontend versions.

Anyways if you think no one's actually using syntastic with ghc-mod it's fine I guess.

**Comment by lcd047** [comment]
@DanielG I think you get this backwards.  Support for older versions that's already in place doesn't need any maintenance.  But every time you break backward compatibility, you also break support for _newer_ versions of `ghc-mod` in frontends.  You basically force other people to play catch with you.  Just FYI. _shrug_

**Comment by DanielG** [comment]
I know but ghc-mod never really arrived at a stable state since all of ghc and cabal is constantly in flux ;)

The real problem is it's really hard to judge when the effort to keep backwards compatibility is justified since most frontend developers aren't actually involved in ghc-mod's development. For example with the rootdir stuff: fixing it in ghc-mod directly turned out to be quite a lot of trouble and the thinking was that it's really not that big of a deal to ask fontends to do this but evidently this is not true.

If I had a list of frontends and maintainers to notify about this sort of thing this wouldn't be a big deal.

**Comment by begriffs** [comment]
What about using [vim-rooter](https://github.com/airblade/vim-rooter) to change the vim working directory and modifying ghc-mod to take an option to make it use full file paths in its output? Would that fix things for syntastic?

**Comment by lcd047** [comment]
@begriffs As I said: I'm not looking for solutions.  Sorry about that.

**Comment by begriffs** [comment]
Well thanks for all your previous work! It made my, and many other people's Haskell lives better.

**Comment by hasufell** [comment]
> I know but ghc-mod never really arrived at a stable state since all of ghc and cabal is constantly in flux ;)

I don't understand how that prevents anyone from making a stable "external" API, if someone wanted to. This is something I repeatedly hear in the haskell community and I really do not agree. I think it mostly comes down to the workflow and priorities of library maintainers.

**Comment by sdroege** [comment]
https://github.com/kazu-yamamoto/ghc-mod/issues/665 is closed now, which should make everything work again with newest ghc-mod afaiu

**Comment by ches** [comment]
@sdroege Unfortunately, using latest `ghc-mod` 5.5.0.0 and Syntastic 3.7.0 before the check for latest versions was added, it's still broken: `ghc-mod check --boundary=""` apparently isn't accepted anymore, the option is required to be positioned *before* the `check` command. Small change, but yeah, if it's a breaking scripting API change again then @lcd047 probably isn't going to be inspired to work around it once more… Let us hope [haskell-ide-engine] brings us all a layer of insulation :smile: 

Simple patch for anyone considering maintaining externally (untested in 5.4.0.0 or below…):

```diff
diff --git a/syntax_checkers/haskell/ghc-mod.vim b/syntax_checkers/haskell/ghc-mod.vim
index 0446283..b410d92 100644
--- a/syntax_checkers/haskell/ghc-mod.vim
+++ b/syntax_checkers/haskell/ghc-mod.vim
@@ -56,7 +56,7 @@ endfunction

 function! SyntaxCheckers_haskell_ghc_mod_GetLocList() dict
     let makeprg = self.makeprgBuild({
-        \ 'exe': self.getExecEscaped() . ' check' . (s:ghc_mod_new ? ' --boundary=""' : '') })
+        \ 'exe': self.getExecEscaped() . (s:ghc_mod_new ? ' --boundary=""' : '') . ' check' })

     let errorformat =
         \ '%-G%\s%#,' .
```

[haskell-ide-engine]: https://github.com/haskell/haskell-ide-engine

**Comment by DanielG** [comment]
Passing `--boundary` before the command should be supported in all versions AFAIK so this change doesn't need any version checking at least :)

**Comment by hasufell** [comment]
> is closed now, which should make everything work again with newest ghc-mod afaiu

I don't see any difference. I still have to run from the root dir with ghcmod-5.5.0.0.

**Comment by asivitz** [comment]
Interestingly, for me the boundary check needs to be `-b" "` instead of `--boundary=""`. But after that change it does work fine.

**Comment by lcd047** [comment]
Removed in [syntastic 3.8.0][3.8.0].

[3.8.0]: https://github.com/scrooloose/syntastic/releases/tag/3.8.0
