### ISSUE TITLE
Have checkers but they are not enabled

### ISSUE THREAD

**Issue by jrock2004** [scrooloose/syntastic#1578]
So when I open a js file I am not getting errors. When I run :SyntasticInfo, I see there are available checkers but they are not enabled

```
Syntastic version: 3.7.0-6 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checker: eslint
Currently enabled checkers: -
```

Here is part of my vimrc file for syntastic config

```
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
```

Do I have to manually specify the checker to use for js files?

**Comment by jrock2004** [comment]
So I installed jslint and it loads that, so it must be something with eslint. Maybe an eslint issue?

```
npm install -g jslint
```

**Comment by lcd047** [comment]
Checkers are [not enabled automatically](https://github.com/scrooloose/syntastic#faqinfo).  There are some defaults, but chances are they don't make sense for your particular situation, so you shouldn't rely on them.

**Comment by zzws524** [comment]
Same problem, same solution. At first, the python checker is available, but cannot be enabled. After I "sudo apt-get install pyflakes" , everything works...Of course, I put "set g:syntastic_python_checkers=['pyflakes']" in advance.
