### ISSUE TITLE
tuple unpacking of excess arguments

### ISSUE THREAD

**Issue by lecs** [scrooloose/syntastic#1585]
Hi,
on the following code line:
```python
a, *b = [1, 2, 3, 4, 5]
```
 syntastic complains with the following error: SyntaxError: invalid syntax [E901]
I believe this should be valid python(3), the checker respects other python3-only features.

thx!

:ver
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52
---                                                                                                                        
Syntastic version: 3.6.0-15
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
Available checkers: flake8 pep8 pyflakes python
Currently enabled checkers: python flake8

**Comment by lcd047** [comment]
Please see the [FAQ](https://github.com/scrooloose/syntastic#user-content-faqpython3).  Reading the manual might not be a bad idea, either.
