### ISSUE TITLE
Unable to use happiness with standard javascript checker

### ISSUE THREAD

**Issue by tnguyen14** [scrooloose/syntastic#1588]
I would like to use happiness https://github.com/JedWatson/happiness as my JavaScript checker.

I have the following line in my `.vimrc`:

```vim
let g:syntastic_javascript_checkers = ['standard']
let g:syntastic_javascript_standard_exec = 'happiness'
```

However, it just doesn't work, i.e. it's not available for syntastic. Here's the results of `:SyntasticInfo`

```
Syntastic version: 3.6.0-176 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checker: eslint
Currently enabled checkers: -
```

Running `:SyntasticCheck standard` gives the error `syntastic: warning: checker standard is not available`.

Running `:echo executable('happiness')` returns `1`. 

`happiness` is available on the command line (it is in my `$PATH` and I can run to to lint from the command line).

I am not sure what I am missing here.

**Comment by lcd047** [comment]
The `standard` checker does a version, err, check that can get in the way.  Please upgrade to 9f599a1 and set `g:syntastic_javascript_standard_generic` to 1 (in addition to what you have now).

**Comment by tnguyen14** [comment]
That seems to have solved it. Thanks! :)
