### ISSUE TITLE
g:syntastic_javascript_standard_generic is not defined

### ISSUE THREAD

**Issue by davidosomething** [scrooloose/syntastic#1590]
g:syntastic_javascript_standard_generic is not defined, :SyntasticInfo throws msg
@lcd047 @scrooloose

The current file will be checked automatically
Error detected while processing function SyntasticInfo[2]..96[14]..95[3]..31[3]..SyntaxCheckers_javascript_standard_IsAvailable:
line    1:
E121: Undefined variable: g:syntastic_javascript_standard_generic
E15: Invalid expression: g:syntastic_javascript_standard_generic

**Comment by lcd047** [comment]
Fixed in 03c058e.
