### ISSUE TITLE
support for eclipse project

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1591]
any possble provide support for eclipse project?just need to read the properties from `.classpath`
now the default output directory is the root of the project (vim-rooter)
i want the plugin can read the .classpath file ,here is my helloword project
![2015-11-05 21-50-48](https://cloud.githubusercontent.com/assets/13142418/10970089/4b9f5d86-8407-11e5-9b03-01dde44a1575.png)

**Comment by wsdjeg** [comment]
https://github.com/scrooloose/syntastic/pull/1559

**Comment by lcd047** [comment]
I'm afraid I can't parse what you're saying. _shrug_

**Comment by wsdjeg** [comment]
sorry for my pool english!
i just want use the plugin for auto compile ecplise java project !  i am using vim to create my java project ,when the project is create by maven ,the plugin works well ,and can autocomplile the file into target,but when it has no pom.xml ,the plugin can not read the file named `.classpath ` which is created by eclipse,i hope you can understande

**Comment by lcd047** [comment]
You can set `g:syntastic_java_javac_classpath` in an `autocmd`.

**Comment by wsdjeg** [comment]
but this option can not set the where the javac output,i hope it is same as eclipse,so i can do not open eclipse,just use vim

**Comment by lcd047** [comment]
You can use an `autocmd` to set `g:syntastic_java_javac_classpath`, to the output of an external command.

**Comment by lcd047** [comment]
Also, if you leave `g:syntastic_java_javac_classpath` unset, `javac` will fallback to the value of the environment variable `CLASSPATH` (at least that's what I recall).  Thus it should work if you set the environment variable `CLASSPATH` before running Vim.

**Comment by wsdjeg** [comment]
i will check my old setting ,thank you

**Comment by wsdjeg** [comment]
i have set let g:syntastic_java_javac_classpath="bin",but it does not work,alse compile into the project root directory

**Comment by wsdjeg** [comment]
and i think g:syntastic_java_javac_classpath is not the option for set the outputdir,
javac -d outputdir -cp `g:syntastic_java_javac_classpath`

**Comment by lcd047** [comment]
Ah, the output directory, not the classpath.  You can (ab)use `g:syntastic_java_javac_options` to set it:
```vim
let g:syntastic_java_javac_options = '-Xlint -d /some/path'
```

**Comment by wsdjeg** [comment]
Ah let me have a try

**Comment by wsdjeg** [comment]
i just try with let g:syntastic_java_javac_options = ' -d  bin ' an hour ago but it does not work

**Comment by wsdjeg** [comment]
it does not work `let g:syntastic_java_javac_options = '-Xlint -d bin'`
![2015-11-06 01-03-16](https://cloud.githubusercontent.com/assets/13142418/10975488/2f537e1c-8422-11e5-8816-1bc90452f534.png)

**Comment by lcd047** [comment]
Did you try setting it to a full path?

**Comment by wsdjeg** [comment]
i have setted ,but still does not work
![2015-11-06 01-06-11](https://cloud.githubusercontent.com/assets/13142418/10975581/a4b1f350-8422-11e5-8afa-91a3ff0c9f2b.png)

**Comment by wsdjeg** [comment]
https://github.com/scrooloose/syntastic/blob/50d0315835047c35a1f6f6edf214e612d6eae3dd/syntax_checkers/java/javac.vim#L99-L114

**Comment by lcd047** [comment]
Well then, please set `g:syntastic_debug` to 1, run the checkert, run `:mes`, and post the output.

**Comment by wsdjeg** [comment]
i think it is due to you have use -d out of g:syntastic_java_javac_options,you see, there are two `-d`
"src/com/wsdjeg/testjc/OuterClass.java" 21L, 383C written
syntastic: 14.228614: &shell = '/usr/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shell
slash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 14.230439: UpdateErrors (auto): default checkers
syntastic: 14.231350: CacheErrors: default checkers
syntastic: 14.233363: g:syntastic_aggregate_errors = 0
syntastic: 14.233943: getcwd() = '/home/wsdjeg/workspace/TestJC2'
syntastic: 14.244238: CacheErrors: Invoking checker: java/javac
syntastic: 14.248198: SyntasticMake: called with options: {'postprocess': ['cygwinRemoveCR'], 'errorformat': '%E%f:%l: error: %m,%W%f:%l: warning
: %m,%E%f:%l: %m,%Z%p^,%-G%.%#', 'makeprg': 'javac -Xlint -d /home/wsdjeg/workspace/TestJC2/bin -d . /home/wsdjeg/workspace/TestJC2/src/com/wsdje
g/testjc/OuterClass.java'}
syntastic: 14.820233: getLocList: checker java/javac returned 0

**Comment by lcd047** [comment]
It goes without saying that you shoul also set `g:syntastic_java_javac_delete_output` to 0.

**Comment by wsdjeg** [comment]
i just do not want to delete the output file ,so that let the plugin help me AUTO compile the java file when save,i think i can give you an PR

**Comment by lcd047** [comment]
Did you set `g:syntastic_java_javac_delete_output` to 0?

**Comment by wsdjeg** [comment]
by default it is 0, and i have echo g:syntastic_java_javac_delete_output also show me 0

**Comment by lcd047** [comment]
It isn't 0 by default.  Syntastic won't add the second `-d` if `g:syntastic_java_javac_delete_output` is 0.

**Comment by lcd047** [comment]
Sorry, I now understanbd what's going on.  You have to set both `g:syntastic_java_javac_delete_output` and `g:syntastic_java_javac_autoload_maven_classpath` to 0.

**Comment by wsdjeg** [comment]
![2015-11-06 01-41-38](https://cloud.githubusercontent.com/assets/13142418/10976583/8cf8cbee-8427-11e5-80d1-696b4a419189.png)
i will add this two option in the elseif

**Comment by lcd047** [comment]
Ok, commit cfdcdfa make `g:syntastic_java_javac_delete_output = 0` take effect regardless of `g:syntastic_java_javac_autoload_maven_classpath`.

**Comment by wsdjeg** [comment]
after this comit mvn project does not checked

**Comment by wsdjeg** [comment]
hi @lcd047  if i run mvn clean .the checker will not work ,after run mvm compile it works well

**Comment by wsdjeg** [comment]
i have test this  :
mvn clean
mkdir -p target/classes
then vim src/---------/Hello.java
then the checker works well

**Comment by lcd047** [comment]
I'm afraid I don't understand.  What doesn't work?

**Comment by wsdjeg** [comment]
it can not create the outputdir target/classes ,if has no the  dir ,the checker will not work, if i mkdir -p target/classes ,it works well

**Comment by lcd047** [comment]
Ok, reverting last patch: commit ae7e00a.  One more example showing that this checker has become a labyrinthic mess.  Perhaps somebody that actually cares about Java is willing to maintain it outside syntastic?

**Comment by wsdjeg** [comment]
hi by default 
```vim
if s:has_maven && g:syntastic_java_javac_autoload_maven_classpath
        if !g:syntastic_java_javac_delete_output
            let javac_opts .= ' -d ' . syntastic#util#shescape(s:MavenOutputDirectory())
        endif
        let javac_classpath = s:AddToClasspath(javac_classpath, s:GetMavenClasspath())
    endif
    " }}}2
```
thank you i have find how to config,just add this to my vimrc
if ！filereadable("pom.xml")
let g:syntastic_java_javac_autoload_maven_classpath=0
endif

**Comment by wsdjeg** [comment]
hi @lcd047 here is my config for this plugin,it works well in maven project and eclipse project and the project which has no both pom and .classpath.
only little issue is that:
in the project ,if the default  outputdirectory is not exist,the checker will not work,any possiable,
add this func,
if I set do not delete the outputfile(which means do not use the temp_directory) and the outputdirectory != ' ' ,confirm wether the default outputdirectory exist,if do not exist,create it !

**Comment by lcd047** [comment]
Not possible.  By default syntastic doesn't know, nor care, about `maven`'s output directory.  If you set an explicit output directory it's up to you to create it if needed.

**Comment by wsdjeg** [comment]
sorry i have just read the code of this plugin ,i also find it is  not possible.thank you all the same.do you know javacomplete2, with the help of these two plugin ,I can use vim to finished my java project,
