### ISSUE TITLE
luac checker fails on long paths

### ISSUE THREAD

**Issue by Lekensteyn** [scrooloose/syntastic#1600]
When editing a file at a long path name, syntastic fails to report errors.

The cause is probably that the `luac` checker trims long path names which are not matched fully by vim.

Steps to reproduce it:
```
$ mkdir -p test/with/not/a/very/long/path && cd $_ && echo . > test.lua
$ mkdir ../other && cd $_
$ vim ${PWD%/*}/path/test.lua +SyntasticCheck  # note full path
```

And an example of the `luac`: output:
```
$ luac ${PWD%/*}/path/test.lua
luac: ...ua/src/lua-5.3.1/test/with/not/a/very/long/path/test.lua:1: unexpected symbol near '.'
```

**Comment by lcd047** [comment]
And how would syntastic convince `luac` not to shorten the path in its output?

**Comment by Lekensteyn** [comment]
It does not seem possible from a quick look in the LUA source. The file name is printed as part of a debugging facility and it is always trimmed when the length is too long. Is there a way to convince `%f` to compare the tail of the filenames?

**Comment by lcd047** [comment]
That's handled by Vim, syntastic has no conmtrol over it.  So it's basically garbage in, garbage out. _shrug_

**Comment by Lekensteyn** [comment]
An idea to workaround this issue is to change the directory to the containing directory. `luac` is a simple syntax checker anyway (it tries to compile into byte code). Is that possible?

**Comment by lcd047** [comment]
That isn't a simple change, and syntastic is not prepared to deal with it.  `ghc-mod` is no longer supported for a similar reason (cf. #1576).

**Comment by Lekensteyn** [comment]
Ok, directory changing is ruled out for now.

I looked in the gdb and found that the file name length is restricted in `luaG_addinfo` by `LUA_IDSIZE` which is defined as:
```c
/*
@@ LUA_IDSIZE gives the maximum size for the description of the source
@@ of a function in debug information.
** CHANGE it if you want a different size.
*/
#define LUA_IDSIZE	60
```

No way to change it at runtime. File name aliasing in syntastic is apparently also hard and stdin cannot be used either?

Any way to catch this and report an error? Or maybe just make a note on the wiki and close this issue.

**Comment by lcd047** [comment]
The checker receives the result of `%f`, not the raw output from `luac`.  This can't be changed by adding an explicit parser, but that would be yet another workaround for crap in a third party program's output, that happens once in a blue moon.  Adding a note to the wiki seems to be the easier option.

**Comment by lcd047** [comment]
Reading the input file from `stdin` is possible, and it would solve your problem, but it would break any `require`.  Please report all this upstream.  Syntastic is not the right place to fix meaningless output of `luac`.  I added a note to the [wiki][luac].

[luac]: https://github.com/scrooloose/syntastic/wiki/Lua%3A---luac

**Comment by Lekensteyn** [comment]
Thanks, this note will do. I've updated the wiki with instructions for a workaround (I tried 512 which works). I doubt upstream will change this limit, lua is intended for embedding so the users should modify this configuration as needed/

**Comment by lcd047** [comment]
> I tried 512 which works

Define "works".  Will it work if the path length is 1021?  How about 1533?  Please refrain from offering incomplete solutions in the syntastic's wiki to problems that should be fixed upstream.  If they care to fix the problem, they will.  If they don't care, syntastic won't care to fix it for them either.

> I doubt upstream will change this limit, lua is intended for embedding so the users should modify this configuration as needed/

The proper fix would be to add some runtime option to disable filename shortening.  When / if that happens, I'll consider adding support for it to syntastic.  Until then, as I said, synastic won't care about this issue more than `luac` developers.

**Comment by Lekensteyn** [comment]
"Works" as in less likely to trim the filename. Syntastic is not perfect and neither is lua, both have to make choices. The filename is trimmed due to how error reporting works, it does not store paths of arbitrary length to save memory and reduce complexity (remember its embedding purpose).

For that reason, I don't foresee that luac will gain the ability to store paths of arbitrary length.

**Comment by lcd047** [comment]
Not "arbitrary length", `pathconf(3)` has been part of POSIX for a while.  Equally irrelevant to syntastic either way.
