### ISSUE TITLE
'document' is not defined

### ISSUE THREAD

**Issue by bfwg** [scrooloose/syntastic#1602]
I'm running phantomjs on my node server and syntastic is giving me `'document' is not defined` error.
```js
var phantom = require('phantom');

phantom.create(function (ph) {
  ph.createPage(function (page) {
    page.open("http://www.google.com", function (status) {
      console.log("opened google? ", status);
      page.evaluate(function () { return document.title; }, function (result) {
        console.log('Page title is ' + result);
        ph.exit();
      });
    });
  });
});
```
The code works fine, I just want to know is there a way to ignore this error warning?

Thanks

**Comment by lcd047** [comment]
Syntastic doesn't care about the contents of your files, only external checkers do.  First you need to  find out what checker has produced the error message.  Then you can either (1) understand why said checker complains and change your code to make it happy, (2) configure the checker not to issue the message, or (3) configure syntastic to kill the message.

Relevant to syntastic are (3), and partially (2).  See `:help syntastic-filtering-errors` and `:help syntastic-config-makeprg`.
