### ISSUE TITLE
Is `-masm` option necessary for asm syntax checking?

### ISSUE THREAD

**Issue by carloscai** [scrooloose/syntastic#1611]
Hi, all & @lcd047 . 
**Is `-masm` option necessary for asm syntax checking?**
This option is for x86 ARCH. When I redefine `syntastic_asm_compiler` to a gcc cross compiler (such as arm-none-eabi-gcc  for ARM ARCH), syntastic doesn't work. Because the cross compiler doesn't recognize `-masm` option. If it is not necessary for asm syntax checking, I suggest deleting this option to support more ARCHs.
My temporary solution is create another asm checker `armgcc.vim` from the original file `/syntax_checkers/asm/gcc.vim`,and then add `let g:syntastic_asm_checkers = ['armgcc'] ` to `.vimrc` file.
**Is there another method to achieve this?**  Maybe set a variable `g:main_flags`  with default value '-x assembler -fsyntax-only -masm=', and we could change it in our `.vimrc` file.

**Comment by lcd047** [comment]
> **Is `-masm` option necessary for asm syntax checking?**

It's needed for x86.

> **Is there another method to achieve this?**

Commit dc516ef adds a new option `g:syntastic_asm_generic`.  Set it to 1 to tell syntastic not to add `-masm=...`.

**Comment by carloscai** [comment]
I update the `gcc.vim` file to commit dc516ef version, and add settings as following:
```
let g:syntastic_asm_compiler = 'arm-none-eabi-gcc'
let g:syntastic_asm_generic = 1
```
It could check ARM asm file. Thank you.
