### ISSUE TITLE
Python version detection

### ISSUE THREAD

**Issue by somini** [scrooloose/syntastic#1612]
Right now, the default python checker disregards the python version for the current file.
I've been using this for a while now to automatically configure syntastic to point to the current python version, based on the file shebang.
https://github.com/somini/dotvim/blob/master/ftplugin/python/syntastic_detectversion.vim
It probably needs some `executable()` checks, but I think it can be useful to avoid the manual fiddling when editing files from both versions in the same vim installation.

**Comment by somini** [comment]
Oh, this also solves the 4.2 section in the FAQ.

**Comment by lcd047** [comment]
Your suggestion assumes there are `python` and `python3` binaries, corresponding to Python 2 and Python 3.  This is not true for all systems: some systems have `python2` and `python`, others have `python2` and `python3`, others have versions of Python not based on CPython.

Your suggestion also assumes you always want to check Python 2 files with Python 2, and Python 3 files with Python 3.  This is not the true, there are situations when you want it the other way around.

Also, your suggestion makes a choice that can't be overridden.  A feature that can't be turned off is a bug.

Guessing the user's intentions from a shebang is naive.  You can add something like this to your `vimrc` if it makes your life easier:
```vim
autocmd BufRead *.py    let b:syntastic_python_python_exec = syntastic#util#parseShebang()['exe'] ==# 'python3' ? 'python3' : 'python'
```
Syntastic should _allow_ you to automate some of your choices, and it does.  It should never _make_ choices for you.

**Comment by somini** [comment]
Those are all very good points, I was admittedly addressing my limited experiences, not considering the big picture.

Thank you very much for that tip about using the existing infrastructure to create a clean version of this, I've incorporated it into my personal configuration.

**Comment by nyuszika7h** [comment]
@lcd047

> ```vim
> autocmd BufRead *.py    let b:syntastic_python_python_exec = syntastic#util#parseShebang()['exe']
> ```

This doesn't work for me. I get this error:

```
E119: Not enough arguments for function: syntastic#util#parseShebang
E15: Invalid expression: syntastic#util#parseShebang()['exe']
```

**Comment by lcd047** [comment]
@nyuszika7h Actually, these days the recommended way to deal with multiple versions of Python is to [run Vim in virtualenv](https://github.com/vim-syntastic/syntastic#faqpython).

Also, using `bufnr('')` in an `autocmd` might not work the way you expect (it may not expand to the buffer that triggered the `autocmd`).  You should use `expand('<afile>', 1)` instead.

**Comment by nyuszika7h** [comment]
Ah, thanks for the tip. You may also want to mention [`venv`](https://docs.python.org/3/library/venv.html) in the README, which ships with Python since version 3.3 (usable since 3.4, since 3.3 doesn't ship with `pip` and you won't have it inside your virtual environment).

**Comment by lcd047** [comment]
@nyuszika7h As far as I can tell `venv` doesn't solve the initial problem, namely being able to run checkers under different __versions__ of Python.

**Comment by nyuszika7h** [comment]
I don't see why not. You'd still have to use `virtualenv` for Python 2 (and in case you're still using 3.1 or 3.2, or maybe even 3.3), but it should work fine for different versions of Python 3.3+. Of course, both of these only work with *already installed* Python versions. The alternative is `pyenv` which is a version manager like `rvm`, lets you install versions directly with ease.

**Comment by lcd047** [comment]
> I don't see why not.

@nyuszika7h Because the vast majority of people only care about about differences between Python 2 and Python 3.

> The alternative is `pyenv` which is a version manager like `rvm`, lets you install versions directly with ease.

Which is why `pyenv` and `rvm` _are_ mentioned in the FAQ.  Sadly the way they work makes them less useful for syntastic than viryualenv, but they're good enough for the simple cases.
