### ISSUE TITLE
Puppetlint-vim throws an error for lines longer than 80 characters.  

### ISSUE THREAD

**Issue by plague-doctor** [scrooloose/syntastic#1616]
PuppetLabs style guide website https://docs.puppetlabs.com/guides/style_guide.html#spacing-indentation-and-whitespace states that each line should be no-longer than 140 characters instead of 80 characters. 
Unfortunately puppetlint-vim throws error for lines longer than 80 characters. 
Either please add an optional "--no-80chars-check" to args_after, or just the module by changing 80 to 140 characters limit.
Update: In fact this is a "Warning" not the "Error" but it is equally annoying .

**Comment by lcd047** [comment]
The name you look for is `g:syntastic_puppet_puppetlint_args`.
