### ISSUE TITLE
SBT file is incorrectly treated as Scala file

### ISSUE THREAD

**Issue by jqno** [scrooloose/syntastic#1620]
The Scala plugin that I use, gives SBT files a filetype of `sbt.scala`. Syntastic picks this up as `scala` and attempts to check the SBT file, which gives a false positive on almost every line. SBT files are technically Scala files, but one can't pass it to a Scala compiler directly.

I played around a little, and it looks like Syntastic ignores anything before (and including) the dot, if the filetype contains one (filetype `scala`, `sbt.scala`, and `hello.scala` all resolve to Scala, but `sbtscala` doesn't). I don't know if this is a feature (maybe it's useful for other languages), but is there a way to make an exception for SBT files?

**Comment by lcd047** [comment]
It's a standard Vim feature (well, mostly standard).  See `:h syntastic-composite`.

**Comment by jqno** [comment]
Cool, I didn't know where to look. Thanks for the quick reply!
