### ISSUE TITLE
strange,the plugin does not works with my simple project.

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1625]
here is my repo 
https://github.com/wsdjeg/JavaUtils
only has two java files,but the plugin does not work,i have added echo javac_classpath into javac.vim ,i find the detection of classpath is ok!

**Comment by lcd047** [comment]
What did you do, what did you expect to happen, and what happened instead?

**Comment by wsdjeg** [comment]
sorry maybe itis my fault,
it is not the issue of stc ,
i do not know why this file can be compile without error;
![2015-12-04 20-43-25](https://cloud.githubusercontent.com/assets/13142418/11589961/b136178a-9ac7-11e5-811f-72d244d61153.png)

**Comment by lcd047** [comment]
You can enable debugging to see the raw output from the checker.

**Comment by wsdjeg** [comment]
i have done,i think maybe it is eclipse's feature.
i use javac in command line also show no error ,but in eclipse ,it will show extra semicolon

**Comment by lcd047** [comment]
Nothing to do with syntastic then.

**Comment by wsdjeg** [comment]
yes so close it ,thank you
