### ISSUE TITLE
Typescript cannot use tsconfig.json files

### ISSUE THREAD

**Issue by osdiab** [scrooloose/syntastic#1628]
Running tsc against a specific file causes project flags to be ignored, so that can't be added as an argument; but tsconfig.json would be useful to draw from because it contains all the flags relevant to a particular project. Without it i almost always get spurious compiler errors by running tsc syntax checking.

Maybe this is an issue with tsc itself? I don't see a good way to use tsc for the configuration without running checks on all the files in a project.

**Comment by lcd047** [comment]
> Maybe this is an issue with tsc itself?

It certainly isn't an issue with syntastic.  Syntastic runs `tsc` with the arguments you specify.

**Comment by adikari** [comment]
This does works. However once set it no longer displays the error marker in the editor. If I do `:Errors` then only I can see the actual errors. Would be great if you could suggest on that.

**Comment by lcd047** [comment]
@adikari Please open a __new__ issue.  Explain what you did, what did you expect to happen, and what happened instead.
