### ISSUE TITLE
Warns with old versions of Vim

### ISSUE THREAD

**Issue by bk2204** [scrooloose/syntastic#1629]
At $DAYJOB, we unfortunately have to support CentOS 5, which comes with an old version of Vim, too old for Syntastic.  I deploy an identical home directory configuration, including a Syntastic submodule, across Debian unstable and CentOS 5, 6, and 7.

In commit ffcf625fcb79cf9fc8006ee7cf96b5066c120c65, Syntastic added a warning when a sufficiently old version of Vim is detected that Syntastic won't work. While great in principle, it means that Vim pauses every time I try to start it on CentOS 5, which makes editing files a pain.  It's far preferable to me that it silently fails to work.  Would you accept a patch to add a variable to do so (e.g. g:syntastic_fail_silently)?

**Comment by lcd047** [comment]
Please see [here](https://github.com/scrooloose/syntastic/issues/1497#issuecomment-127746621) for the preferred solution.
