### ISSUE TITLE
parsing go version fails when using a devel build of go

### ISSUE THREAD

**Issue by lucy** [scrooloose/syntastic#1630]
```
syntastic: error: checker output:
go version devel +4a29150 Sat Dec 5 07:45:01 2015 +0000 linux/amd64
syntastic: error: checker go/go: can't parse version string (abnormal termination?)
```

**Comment by lcd047** [comment]
Using development versions of `go` with syntastic is not supported, sorry.  Please see [here](https://github.com/scrooloose/syntastic/issues/1528#issuecomment-138094554) for the reason.  Nothing relevant changed since that post. _shrug_
