### ISSUE TITLE
eslint is not working 

### ISSUE THREAD

**Issue by AndrewKovalenko** [scrooloose/syntastic#1631]
I use nvm, so even despite I installed *eslint* globally, it is located in `/Users/username/.nvm/versions/node/v4.2.1/bin/eslint`

`eslint --version` says v1.10.3
in my .vimrc I specified:
```
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_enable_signs=1
let g:syntastic_auto_loc_list=1
let g:syntastic_disabled_filetypes = ['scss']
```
but it doesn't display any error messages.

`:SyntasticInfo` shows:
```
Syntastic version: 3.7.0-54 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -  
```

but I have no ideas, why it doesn't see eslint

UPD: 
if I set `let g:syntastic_javascript_eslint_exec = '/Users/username/.nvm/versions/node/v4.2.1/bin/eslint'
`
then checker shows:
```
syntastic: error: checker output:
env: node: No such file or directory
syntastic: error: checker javascript/eslint: can't parse version string (abnormal termination?)
```

**Comment by lcd047** [comment]
This is not related to syntastic, it's entirely between Vim, ESLint, node, and your shell.  Open a JavaScript file, run these commands, and look at the output:
```vim
:echo syntastic#util#system('echo "$PATH"')
:echo syntastic#util#system('eslint --version')
```

**Comment by AndrewKovalenko** [comment]
thank you, the issue was really because I specified PATH to node modules in .zshrc
Thank you for your help.

**Comment by simonsmith** [comment]
I'm still seeing this issue, seems like ESLint stopped working recently. The path command shows by current node `bin` directory present

```
/Users/simonsmith/.nvm/versions/node/v5.1.0/bin
```

Likewise the `eslint --version` command outputs `v1.10.3`. I allow `nvm` to set my node path

**Comment by lcd047** [comment]
@simonsmith Please open a JavaScript file, run `:SyntasticInfo`, and post the output.  Then set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output.

**Comment by simonsmith** [comment]
Thanks for the debug tip. I was able to see this error:

```
Error: Cannot read config package: eslint-config-airbnb/base
```

I needed to have that package also installed globally for `eslint` to find it. The reason I didn't see it on the cli is due to using a locally installed `eslint` via `npm run ..`

:+1:

**Comment by tomauty** [comment]
Thanks for posting that @simonsmith. Helped me out :)

**Comment by techyrajeev** [comment]
Installing global `eslint` will not be good solution e.g to use airbnb eslint I will have to install  `eslint-config-airbnb eslint-plugin-import eslint-plugin-react eslint-plugin-jsx-a11y eslint` globally.
 There must be some way to use locally install packages.

**Comment by lcd047** [comment]
@techyrajeev There is: #1692

**Comment by techyrajeev** [comment]
@lcd047 Wow I was looking exactly at the same issue just before you commented. Thanks a lot.

**Comment by simonsmith** [comment]
You might find this useful - https://github.com/mtscout6/syntastic-local-eslint.vim

It also supports stylelint

**Comment by techyrajeev** [comment]
Even after setting that I am not able to get it work.  I am using OH-My-Zsh version of zsh.
Here is the output of `:mes`
syntastic: 2322.478722: &shell = '/bin/sh' (!), &shellcmdflag = '-c', &shellpipe = '2>&1|
 tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shel
lxquote = '', &shellxescape = ''
syntastic: 2322.482829: UpdateErrors (auto): default checkers
syntastic: 2322.486188: CacheErrors: default checkers
syntastic: 2322.490987: g:syntastic_aggregate_errors = 0
syntastic: 2322.492514: getcwd() = '/home/r/Development/web-dev/src'
syntastic: 2322.494514: CacheErrors: Checker javascript/eslint is not available
syntastic: 2322.495884: CacheErrors: no checkers available for javascript
syntastic: 2322.497318: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns':
1, '_rawLoclist': []}    

It saying eslint is not available even though I have installed it in my local directory.

Also set this in my .vimrc

`let g:syntastic_javascript_eslint_exe = 'npm run eslint --'
`
@lcd047  Please help

**Comment by lcd047** [comment]
@techyrajeev Does this ring any bell:
> I am using OH-My-Zsh version of zsh.
[...]
> syntastic: 2322.478722: &shell = '/bin/sh'

**Comment by techyrajeev** [comment]
Syntastic is not using zsh shell at all.  From the readme docs

> Syntastic runs checkers using the shell pointed to by Vim's shell (or by g:syntastic_shell, if set)

**Comment by lcd047** [comment]
@techyrajeev So, what do you conclude, what shell does syntastic gets its `$PATH` from?

**Comment by techyrajeev** [comment]
@lcd047 Syntastic gets its $PATH env variable from the shell set as Vim's shell.
I updated my `.vimrc` and `set shell = /bin/zsh`
But even after setting that I am getting the same error. 
```

syntastic: 138.569030: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote =
 '', &shellxescape = ''
syntastic: 138.576324: UpdateErrors: eslint
syntastic: 138.577823: CacheErrors: eslint
syntastic: 138.580250: g:syntastic_aggregate_errors = 0
syntastic: 138.581316: getcwd() = '/home/rajeev/Development/web-dev/web/src'
syntastic: 138.582690: CacheErrors: Checker javascript/eslint is not available
syntastic: warning: checker eslint is not available                                

```

**Comment by lcd047** [comment]
@techyrajeev Well then, you need to fix this first:

> `syntastic: warning: checker eslint is not available`

You need to either make sure `eslint` version 0.1.0 or later is in (syntastic's idea of) `$PATH`, or point `*_exec` to it.  Setting `*_exe` has no effect on that.

> `let g:syntastic_javascript_eslint_exe = 'npm run eslint --'`

If you named the script `lint` in your `package.json` you need `npm run lint --` here, rather than `npm run eslint --`.

> I updated my `.vimrc` and `set shell = /bin/zsh`

On a side note: you can't have spaces around `=` in `set` commands.  You can only have them in `let`.

**Comment by techyrajeev** [comment]
@lcd047 After continuous failed try I found that if I open gvim from terminal syntastic was working fine but if I opened it from menu or directly open with file name it stopped working.
I had set my .vimrc correctly there were no spaces around =.  
After searching I found this issue [https://github.com/scrooloose/syntastic/issues/1110](1110) and did accordingly but of no use. @simonsmith I am going to install the plugin you mentioned, hope that will help.
@lcd047 Thanks for having patience with me and helping me with this issue.

**Comment by lcd047** [comment]
@techyrajeev When you open gvim "from a menu" your `$PATH` is set by your window manager, not by a login shell.  This is a huge can of worms.  Maybe some Ubuntu-specific forum can clear it up for you.  I'd suggest getting it to work in a terminal first.

What happens when you run gvim "with a filename" depends on the current directory, and on what options you added to `eslint` in `package.json`.  You can see both in the debug logs.

Issue #1110 has nothing to do with your problem, you already have all pieces to get it running.

The plugin mentioned above consists of [two lines](https://github.com/mtscout6/syntastic-local-eslint.vim/blob/master/ftplugin/javascript.vim) that point `exec` to a local binary.  IMO this won't be enough for your situation.  A better approach for you would be to try to understand what's going on, rather than search for other people's solutions to unrelated problems.  But then again, what do I know.

Either way, I believe we're done here, since this is no longer a syntastic problem.
