### ISSUE TITLE
syntastic_aggregate_errors not working

### ISSUE THREAD

**Issue by fdelacruz** [scrooloose/syntastic#1633]
In the shot I have two errors (missing commas) in lines 2 & 3. 
They get checked one at a time despite having set `syntastic_aggregate_errors`. 
The warnings (missing semicolons) get totally ignored.
![shot2](https://cloud.githubusercontent.com/assets/148098/11693663/1d6f633e-9e74-11e5-8d4c-64de37715083.jpg)

This shot is of the warnings mentioned above being aggregated by default. I know there's no relation. I added it I guess for completeness. 
![shot1](https://cloud.githubusercontent.com/assets/148098/11693648/00dfef2c-9e74-11e5-99d2-eb2185f82e90.jpg)

**Comment by lcd047** [comment]
Please open your test file, run `:SyntasticInfo`, and post the output.  Then set `g:syntastic_debug` to 3, run the checker, and again, run `:mes`, and post the output again.

**Comment by fdelacruz** [comment]
Will do as soon as I get off this train..
On Wed, Dec 9, 2015 at 3:58 PM LCD 047 <notifications@github.com> wrote:

> Please open your test file, run :SyntasticInfo, and post the output. Then
> set g:syntastic_debug to 3, run the checker, and again, run :mes, and
> post the output again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scrooloose/syntastic/issues/1633#issuecomment-163389933>
> .
>
-- 
Warm regards,
Francisco De La Cruz
(646)294-2547

Sent from my IPhone

**Comment by fdelacruz** [comment]
`: SyntasticInfo`
![shot2](https://cloud.githubusercontent.com/assets/148098/11699930/defa2f5a-9e94-11e5-96b8-3322954d47da.jpg)

`:mes`
![shot3](https://cloud.githubusercontent.com/assets/148098/11699945/ef2c7018-9e94-11e5-8738-b51ba265032b.jpg)

**Comment by lcd047** [comment]
Ok, now please run this in a terminal:
```sh
cd ~/vim_practice
eslint -f compact copy-paste-demo.js
```

**Comment by fdelacruz** [comment]
![shot5](https://cloud.githubusercontent.com/assets/148098/11700217/81cc7e9e-9e96-11e5-866f-8551333ac109.jpg)

**Comment by lcd047** [comment]
ESLint produces a single message, and syntastic shows it to you.  That's all there is to it: you have a syntax error, and ESLint's parser can't resync after that.

On a side note: `syntastic_aggregate_errors` is about merging errors from _multiple_ checkers.  It isn't particularly useful if you have a single checker enabled.
