### ISSUE TITLE
Don't capture stderr with rubocop

### ISSUE THREAD

**Issue by eapache** [scrooloose/syntastic#1635]
The rubocop plugin is broken on my system because the `parser` gem (which is used by rubocop) sometimes prints a message on stderr, confusing the error format and version check.

AFAIK rubocop prints its actual output on stdout, so if syntastic simply ignored stderr it would fix this problem. I don't know enough about vimscript to know if this is easy to do or not.

(I originally reported this against the parser gem, conversation at https://github.com/whitequark/parser/issues/229)

**Comment by lcd047** [comment]
This is addressed in the [wiki](https://github.com/scrooloose/syntastic/wiki/Ruby%3A---rubocop).
