### ISSUE TITLE
Problem with :E

### ISSUE THREAD

**Issue by noprompt** [scrooloose/syntastic#164]
After installing the plugin I get this funky error when using `:E`:

```
E464: Ambiguous use of user-defined command
```

Incidentally, `:Ex`, `:Exp`, `:Expl`, and so forth all seem to work dandily.

**Comment by bart9h** [comment]
I think it should be `SyntasticErrors`, and if the user wants to shorten it, then she can just call `command Errors SyntasticErrors`. Or make it configurable. I'll use paulgb solution, but I think it is good practice to avoid conflicts with broadly used commands and keys.
