### ISSUE TITLE
Location list is empty unless use Error command

### ISSUE THREAD

**Issue by chemzqm** [scrooloose/syntastic#1642]
This is not bug but an issue confuse me.

I'm working on a plugin to take replace of vim's location list, it get location list info by `getloclist` function.

The problem here is when I save the file, I can see the notification shown, like the sign, the balloon etc,  but location list is actually empty when I use `lopen` command or call `getloclist` function.  The location list would be filled only after I use command `Error`.

Is there any way that I can tell syntastic to fill the location list just after the syntastic check or a function I can call to fill the location list with check result?   I can't use `Error` command to do that as it would show the location list in the window which is not desired.

**Comment by lcd047** [comment]
Please see `:h 'syntastic_always_populate_loc_list'`.  See also `:h syntastic-recommended`, and the [README](https://github.com/scrooloose/syntastic#settings).

**Comment by chemzqm** [comment]
@lcd047 thanks for quick response, but unfortunately it not works, below is my setting:
 ```
let g:syntastic_always_populate_loc_list=1
let g:syntastic_warning_symbol='⚠'
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_check_on_wq = 0
```
I've disabled all other plugins to test, the location list would be empty unless Error is called

I've read the source the of  `plugin/syntastic.vim`
```
        try
            silent lolder
        catch /\m^Vim\%((\a\+)\)\=:E380/
            " E380: At bottom of quickfix stack
            call setloclist(0, [], 'r')
        catch /\m^Vim\%((\a\+)\)\=:E776/
            " E776: No location list
            " do nothing
        endtry
```
It just do nothing :disappointed:

**Comment by lcd047** [comment]
That piece of code is not supposed to update loclist.  It was never supposed to do that.  If you're relying on `SyntasticMake()` to update loclist, it won't work.

**Comment by chemzqm** [comment]
It works after I comment them out, I can get the location list filled after the file saved.
Looks like syntastic tries to avoid conflict with existing location list.

**Comment by lcd047** [comment]
> It works after I comment them out, I can get the location list filled after the file saved.

You're changing code that you don't understand.

> IMO, it's a strange behaviour.

Please show a situation when syntastic doesn't work as documented.

**Comment by chemzqm** [comment]
I just think by setting g:syntastic_always_populate_loc_list=1 should always fill the location list whenever checker find erros, but it's not.
Relax, I'm taking the risk of myself and I can control which plugin use the location list.

**Comment by lcd047** [comment]
> I just think by setting g:syntastic_always_populate_loc_list=1 should always fill the location list whenever checker find erros

[It does](https://github.com/scrooloose/syntastic/blob/48736aa376341518d7bedf3a39daf0ae9e1dcdc0/plugin/syntastic.vim#L362-L364), just not in `SyntasticMake()` as you expect.

**Comment by chemzqm** [comment]
Tks, It did work for me now, don't know what happened :confused:
