### ISSUE TITLE
Opposite of syntastic_auto_loc_list = 2

### ISSUE THREAD

**Issue by jasontibbitts** [scrooloose/syntastic#1647]
I find the opening and closing of the location list kind of distracting, but I also like to have it around to see what I've mistyped.  What I'd really like is to have it open the first time there's an error and then stick around.  The best I can do currently without hacking is to set syntastic_auto_loc_list = 0 and then open it myself once when I find an issue.

This is trivial to implement, but I don't know vim programming very well and the result seems unpleasant.  I can send a pull request if you like, or I'll be happy to implement suggestions for doing this better (and then send a pull request).

```
diff --git a/plugin/syntastic/autoloclist.vim b/plugin/syntastic/autoloclist.vim
index da99dbb..7215229 100644
--- a/plugin/syntastic/autoloclist.vim
+++ b/plugin/syntastic/autoloclist.vim
@@ -20,11 +20,11 @@ endfunction " }}}2
 function! g:SyntasticAutoloclistNotifier.AutoToggle(loclist) abort " {{{2
     call syntastic#log#debug(g:_SYNTASTIC_DEBUG_NOTIFICATIONS, 'autoloclist: toggle')
     if !a:loclist.isEmpty()
-        if syntastic#util#var('auto_loc_list') == 1
+        if syntastic#util#var('auto_loc_list') == 1 || syntastic#util#var('auto_loc_list') == 3
             call a:loclist.show()
         endif
     else
-        if syntastic#util#var('auto_loc_list') > 0
+        if syntastic#util#var('auto_loc_list') > 0 && syntastic#util#var('auto_loc_list') != 3

             "TODO: this will close the loc list window if one was opened by
             "something other than syntastic
```

**Comment by lcd047** [comment]
This is not completely trivial because syntastic still has to do something sensible when `always_populate_loc_list` is unset.  But it happens to work.  Please see dbd7610.

**Comment by jasontibbitts** [comment]
Thanks!
