### ISSUE TITLE
Question: OR in syntax checkers

### ISSUE THREAD

**Issue by SeeThruHead** [scrooloose/syntastic#1652]
currently i have 
```
let g:syntastic_javascript_checkers = ['standard', 'eslint']
```

I've decided to use standard for this project rather than my own eslint that I use in other projects.

I want to disable eslint if standard is found

Currently I get the error Cannot find module 'babel-eslint' since eslint is not installed locally. (I have it set to use local eslint only)

Any ideas?

Sorry if this isn't the best place to ask questions.

**Comment by lcd047** [comment]
Syntastic relies on Vim's `system()` to run checkers.  If you can get this to work, then syntastic will run fine:
```vim
:echo system('/path/to/eslint -f compact /path/to/file.js')
```
That's between Vim, your OS, your shell, `node`, `eslint`, and the modules.  It's easier to achieve on some OSes than on others.  Some people claim you can't run local `node` modules that way, others claim it can be done trivially. :) Either way, it has nothing to do with syntastic.  I'm not particularly knowledgeable about that, so you might need to ask about it on some `node` forums. _shrug_

Once you can get `eslint` to run that way, you can point `g:syntastic_javascript_eslint_exec` to `/path/to/eslint`, and / or use the other standard variables `g:syntastic_javascript_eslint_*` to alter the command line (see `:h syntastic-checker-options`).  To see what syntastic is doing, you can enable debugging: set `g:syntastic_debug` to 1, run the checker, and run `:mes` to see the debugging logs.  But it won't work if you can't get it to run outside syntastic first.
