### ISSUE TITLE
Syntastic warning when JSCS produces no issues

### ISSUE THREAD

**Issue by Swoogan** [scrooloose/syntastic#1653]
If I load a javascript file with JSCS errors, the tools work as expected. However, when I load a file with no issues, I get the following:

    syntastic: warning: checker javascript/jscs: unrecognized error format

I ran it with `let g:syntastic_debug = 3` and I get the following output:

```
syntastic: 13.379388: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 13.379813: UpdateErrors (auto): default checkers
syntastic: 13.380043: CacheErrors: default checkers
syntastic: 13.380483: g:syntastic_aggregate_errors = 0
syntastic: 13.380605: getcwd() = '/home/swoogan/Software/development'
syntastic: 13.380879: CacheErrors: Invoking checker: javascript/jscs
syntastic: 13.381400: SyntasticMake: called with options: {'subtype': 'Style', 'preprocess': 'jscs', 'errorformat': '%f:%l:%c:%m', 'defaults': {'type': 'E'}, 'makeprg': 'jscs --no-colors --reporter json application/application.js', 'returns': [0, 2]}
syntastic: 14.170852: checker output: ['']
syntastic: warning: checker javascript/jscs: unrecognized error format
syntastic: 14.171108: preprocess: []
syntastic: 14.171269: raw loclist: []
syntastic: 14.171440: getLocList: checker javascript/jscs returned 0
syntastic: 14.171544: javascript/jscs raw: []
syntastic: 14.171675: quiet_messages filter: {}
syntastic: 14.171894: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
```

Running the embedded command on the terminal produces no output and a return code of `0`. I'm running with syntastic HEAD and the jscs retrieved with `npm install -g jscs`.

Is there some way to disable warnings if a resolution isn't obvious?

**Comment by gillescastel** [comment]
:+1: When jscs found no errors, there is no output.

**Comment by scottis** [comment]
Looks like this is caused by commit 751afea9e0567fe2b613cddc62aa03d98bee4f43.

I've created pull request scrooloose/syntastic#1654 to remove the warning message.

**Comment by lcd047** [comment]
Minor pilot error, please upgrade to 3280220.

@scottis Commit 751afea is supposed to fix [this problem](http://stackoverflow.com/questions/34445633/jscs-errors-not-appearing-in-syntastic).  Syntastic doesn't have a "real" XML parser, but it can (mostly) parse JSON.  Recent versions of JSCS have a JSON reporter.

> I've created pull request scrooloose/syntastic#1654 to remove the warning message.

The warning is there for a reason: you still want syntastic to tell you if JSCS crashes, rather than try to parse the stack trace as normal errors.
