### ISSUE TITLE
SyntasticInfo shows Xml for ts

### ISSUE THREAD

**Issue by sapond** [scrooloose/syntastic#1655]
Trying to use tslint checkers "tsc" or "tslint" and getting this report on SyntasticInfo for any *.ts file.

```
Syntastic version: 3.7.0-67 (Vim 704, Darwin)
Info for filetype: xml
Global mode: active
Filetype xml is active
The current file will be checked automatically
Available checkers: plutil xmllint
Currently enabled checker: xmllint
```

My config
```
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_typescript_checkers = ['tslint', 'tsc']
let g:syntastic_check_on_open=1
let g:syntastic_enable_signs=1
```

What am I missing?  Thanks.

**Comment by lcd047** [comment]
> `Info for filetype: xml`

Syntastic decides what checkers to run based on Vim filetypes (see `:h filetype`).  Vim doesn't automatically detect TypeScript files, so you need some other Vim plugin to do that for you.  From a quick search, an example of such plugin is [typescript-vim](https://github.com/leafgarland/typescript-vim).

**Comment by janbaer** [comment]
I've the same problem, and I've typescript-vim installed.

**Comment by lcd047** [comment]
@janbaer If it is "the same problem", then you're complaining to the wrong forum.  I suppose we'll never know. :)

**Comment by janbaer** [comment]
In the meantime I found a solution:

```
autocmd BufNewFile,BufRead *.ts setlocal filetype=typescript
```

**Comment by lcd047** [comment]
@janbaer Then please post a PR to typescript-vim.  It has nothing to do with syntastic.
