### ISSUE TITLE
Can't handle traditional UNIX syntax for redirections in zsh.

### ISSUE THREAD

**Issue by botika** [scrooloose/syntastic#1656]
After I upgrade to php 7 returns this error message.
`syntastic: error: your shell /usr/bin/zsh can't handle traditional UNIX syntax for redirections`

This is my zsh --version
`zsh 5.1.1-dev-0 (x86_64-unknown-linux-gnu)`
And my vim --version
`VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 29 2015 00:02:54)`

At last git version of syntastic.
Thanks for your job.

**Comment by lcd047** [comment]
Please open Vim, run the following command, and post the output:
```vim
:echo string([&shell, &shellcmdflag, &shellpipe, &shellquote, &shellredir, &shellslash, &shelltemp, &shellxquote])
```

**Comment by botika** [comment]
This is output:
`['/usr/bin/zsh', '-c', '2>&1| tee', '', '>%s 2>&1', 0, 1, '']`

**Comment by lcd047** [comment]
Please post the output of:
```vim
:echo system('uname')
:echo split(syntastic#util#system('uname'), "\n")[0]
```

**Comment by botika** [comment]
`Linux`
 and 
`Linux`

**Comment by lcd047** [comment]
Ok, let's go back: what did you do to trigger the error message in the first post?

**Comment by botika** [comment]
Already solved mistakenly delete my zshenv, so just look at the history and ~ / .profile was loaded and have the system xdg not find many things. I leave the profile if you is helpful. 
```
# file:     ~/.profile
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:

source /etc/profile

[[ $UID -eq 1000 ]] && PATH="$PATH":"$HOME"/bin:"$HOME"/.node_modules/bin

[[ "$XDG_CACHE_HOME" ]] || export XDG_CACHE_HOME="$HOME"/.cache
[[ "$XDG_CONFIG_HOME" ]] || export XDG_CONFIG_HOME="$HOME"/.config
[[ "$XDG_DATA_HOME" ]] || export XDG_DATA_HOME="$HOME"/.local/share

# setup environment
#export GPGKEY=
#export PRINTER="HP_psc_1200_series"
#export __GL_SHADER_DISK_CACHE="1"
#export __GL_SHADER_DISK_CACHE_PATH="$XDG_CONFIG_HOME/nv/"
export ANDROID_HOME=/opt/android-sdk
export BROWSER="/usr/bin/elinks"
export EDITOR="vim"
export FCEDIT="vim"
export LC_ALL=
export LC_COLLATE="C"
export LESSHISTFILE=-
export LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s"
export LESS=' -R '
export SYSTEMD_PAGER="/usr/bin/less" 
export VISUAL="$EDITOR"

# XDG base conf
source "$(dircolors "$XDG_CONFIG_HOME"/dircolors)" 2&> /dev/null
#export XCOMPOSEFILE="$XDG_CONFIG_HOME"/X11/xcompose
export ATOM_DEV_RESOURCE_PATH="$HOME"/Documents/Builds/workspace/atom
export ATOM_HOME="$XDG_CONFIG_HOME"/atom
export ELINKS_CONFDIR="$XDG_CONFIG_HOME"/elinks
export GIMP2_DIRECTORY="$XDG_CONFIG_HOME"/gimp
export GNUPGHOME="$XDG_CONFIG_HOME"/gnupg
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export IMAPFILTER_HOME=/home/lorenz/.config/imapfilter
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
export IPYTHONDIR="$XDG_CONFIG_HOME"/ipython
export MATHEMATICA_USERBASE="$XDG_CONFIG_HOME"/mathematica
export NMBGIT="$XDG_DATA_HOME"/notmuch/nmbug
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME"/notmuch/notmuchrc
export SOURCE_HIGHLIGHT_DATADIR="$XDG_CONFIG_HOME"/source_highlight
export TERMINFO="$XDG_DATA_HOME"/terminfo 
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
export WINEPREFIX="$XDG_DATA_HOME"/wine
export XAUTHORITY="$XDG_RUNTIME_DIR"/X11/xauthority
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc

# node settings
export npm_config_cache="$XDG_CACHE_HOME"/npm
export npm_config_prefix="$HOME"/.node_modules
export npm_config_userconfig="$XDG_CONFIG_HOME"/npmrc

# ruby settings
if [[ -e /usr/share/chruby ]]; then
    source /usr/share/chruby/{chruby,auto}.sh
    chruby $(<"$XDG_CONFIG_HOME"/ruby-version)
fi

# java settings
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=false'`
```
I do not understand why, and this may affect this plugin.
Thanks for your time. And sorry for my English.

**Comment by lcd047** [comment]
So, you can no longer reproduce the problem?

**Comment by botika** [comment]
Well, I'm trying and I fail, this its unique commands of my vimrc use this env variables, 
```        
let &directory=expand("$XDG_DATA_HOME/vim")

if !isdirectory(expand("$XDG_CACHE_HOME") . "/vim")|call mkdir(expand("$XDG_CACHE_HOME") . "/vim", "p", 0700)|endif
```
My vimrc http://pastebin.com/kcYSFJNJ
I have to fold, keep trying. Sorry.

**Comment by lcd047** [comment]
You have a lot of moving parts there, good luck making sense of them all.  As far as I can tell you managed to trick your shell into returning an error condition when run from Vim.  Feel free to reopen this when / if you can reproduce the problem with all other plugins disabled and a minimal setup, or at least when / if you have conclusive proof the problem is with syntastic and not in your Vim config, or somewhere else.  Otherwise, a forum for your Linux distribution might be a better place to ask. _shrug_

**Comment by Sjlver** [comment]
Just for the record: This happened to me during a system upgrade, when the `zsh` package was updated. During this time, the file `/usr/bin/zsh` (which is a symlink to `/bin/zsh`) was temporarily missing.

Maybe it would help to set the shell to `/bin/zsh` instead of `/usr/bin/zsh`.
