### ISSUE TITLE
Didn't work for sql?

### ISSUE THREAD

**Issue by crazy-canux** [scrooloose/syntastic#1657]
How to make this plugin work for  *.sql files?

**Comment by lcd047** [comment]
What did you try?

**Comment by crazy-canux** [comment]
I think this plugin can check the syntax for sql by default.
But when I write a sql file, it didn't work.

**Comment by lcd047** [comment]
@crazy-canux Few things in life have desirable effects when left to the defaults.  Syntastic is not one of them.  On a more general note: useless description of the problem => useless response. _shrug_
