### ISSUE TITLE
Feature Request: Vim array for g:syntastic_quiet_messages

### ISSUE THREAD

**Issue by MikeDacre** [scrooloose/syntastic#1661]
Right now the regex entry of my g:syntastic_quiet_messages is very long, and keeps getting longer. Would you be interested in potentially adding another entry to the dictionary (e.g. 'pattern_matches') that takes a simple list of strings and does the same thing. My g:syntatic_quiet_messages regex entry has no complex regex, it is just a long pattern grouping:

    \(bad-whitespace\)|\(W0612\)\|\(C901\)\|\(W0611\)\| ...

If you are interested, I can look into adding that myself in a pull request.

**Comment by lcd047** [comment]
It might not be obvious from the manual, but you can already do that:
```vim
let g:syntastic_quiet_messages = {
    \ 'regex': '\mbad-whitespace\|W0612\|C901\|W0611'
    \ }
```
is exactly equivalent to
```vim
let g:syntastic_quiet_messages = {
    \ 'regex': [ 'bad-whitespace', 'W0612', 'C901', 'W0611' ]
    \ }
```
You also don't need `\(...\)` grouping.

**Comment by MikeDacre** [comment]
Great, thank you so much for that clarification.
