### ISSUE TITLE
D syntax checker import fails with DSFML Lib

### ISSUE THREAD

**Issue by afaur** [scrooloose/syntastic#1664]
Since the import checker is hard checking `source` folder, but not `src` folders `syntastic` reports import errors when your code is correct.  When you correct this by being more specific it will pass the syntastic checker, however it will break the build.

Syntactic Version: 
```
Syntastic version: 3.6.0-93 (Vim 704, Darwin)
```
Vim Version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 27 2015 15:03:01)
MacOS X (unix) version
Included patches: 1-769
```

The example library that is trying to be imported is DSFML:
```
-> % pwd
~/.dub/packages/dsfml-2.1.0 
-> % ls
CONTRIBUTING.md     README.md           dub.json            libdsfml_audio.a    libdsfml_network.a  libdsfml_window.a   unittest
License.txt         build.d             libdsfml.a          libdsfml_graphics.a libdsfml_system.a   src
-> % cd src
-> % ls
dsfml 
-> % cd dsfml
-> % ls
audio    graphics network  system   window
-> % cd graphics
-> % ls
blendmode.d      drawable.d       package.d        renderstates.d   shader.d         texture.d        vertexarray.d
circleshape.d    font.d           primitivetype.d  rendertarget.d   shape.d          transform.d      view.d
color.d          glyph.d          rect.d           rendertexture.d  sprite.d         transformable.d
convexshape.d    image.d          rectangleshape.d renderwindow.d   text.d           vertex.d
-> % cat package.d 
/*
DSFML - The Simple and Fast Multimedia Library for D

Copyright (c) 2013 - 2015 Jeremy DeHaan (dehaan.jeremiah@gmail.com)

This software is provided 'as-is', without any express or implied warranty.
In no event will the authors be held liable for any damages arising from the use of this software.

Permission is granted to anyone to use this software for any purpose, including commercial applications,
and to alter it and redistribute it freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software.
If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.

2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.

3. This notice may not be removed or altered from any source distribution
*/

///2D graphics module: sprites, text, shapes, etc.
module dsfml.graphics;

public
{
	import dsfml.window;

	import dsfml.graphics.blendmode;
	import dsfml.graphics.circleshape;
	import dsfml.graphics.color;
	import dsfml.graphics.convexshape;
	import dsfml.graphics.drawable;
	import dsfml.graphics.font;
	import dsfml.graphics.glyph;
	import dsfml.graphics.image;
	import dsfml.graphics.primitivetype;
	import dsfml.graphics.rect;
	import dsfml.graphics.rectangleshape;
	import dsfml.graphics.renderstates;
	import dsfml.graphics.rendertarget;
	import dsfml.graphics.rendertexture;
	import dsfml.graphics.renderwindow;
	import dsfml.graphics.shader;
	import dsfml.graphics.shape;
	import dsfml.graphics.sprite;
	import dsfml.graphics.text;
	import dsfml.graphics.texture;
	import dsfml.graphics.transform;
	import dsfml.graphics.transformable;
	import dsfml.graphics.vertex;
	import dsfml.graphics.vertexarray;
	import dsfml.graphics.view;
}
```

Syntastic says that this is right:
<img width="577" alt="says_right" src="https://cloud.githubusercontent.com/assets/898523/12306979/3def94fe-ba02-11e5-96a0-3a7cbdc8f050.png">

But in fact it does not build:
<img width="878" alt="says_right_but_is_wrong" src="https://cloud.githubusercontent.com/assets/898523/12306986/49103fdc-ba02-11e5-89e0-e10d37edb18d.png">

Where as.. Syntastic says this is wrong:
<img width="578" alt="says_wrong" src="https://cloud.githubusercontent.com/assets/898523/12307103/df1e827c-ba02-11e5-95ce-d6382a06f0cd.png">

But in fact is correct and will build:
<img width="587" alt="says_wrong_but_is_right" src="https://cloud.githubusercontent.com/assets/898523/12307009/6748afca-ba02-11e5-8cc5-59a657898374.png">

I was able to fix this locally, but maybe there is a better solution.  Basically source files for libraries are usually inside `source` or `src` for some libraries.

Here is what change I made locally that I will put in a PR against this issue unless anyone has any other suggestions:
```
(file: syntastic/syntax_checkers/d/dmd.vim)
...
function! SyntaxCheckers_d_dmd_GetLocList() dict
    if !exists('g:syntastic_d_include_dirs')
        let g:syntastic_d_include_dirs = filter(glob($HOME . '/.dub/packages/*', 1, 1), 'isdirectory(v:val)')
        call map(g:syntastic_d_include_dirs, 'isdirectory(v:val . "/source") ? v:val . "/source" : v:val')
        call map(g:syntastic_d_include_dirs, 'isdirectory(v:val . "/src") ? v:val . "/src" : v:val')
        call add(g:syntastic_d_include_dirs, './source')
    endif
...
```
^ Added `/src` as and additional `include_dir` the same way `/source` was above.

Sorry but I was unable to follow the instructions on the contrib guide regarding: `g:syntastic_debug`
I don't know how to set that to a value I tried `:set g:syntastic_debug=1` which failed.  
Update: Wasn't thinking and should have done `:let g:syntastic_debug=1` and that worked but I didn't see anything inside `:mes`

**Comment by lcd047** [comment]
> Since the import checker is hard checking `source` folder, but not `src` folders

According to the [wiki](https://github.com/scrooloose/syntastic/wiki/D%3A---dmd) (and also to the code), that's only a default.  You can override it by setting `g:syntastic_d_include_dirs` to something appropriate for your project.  Since this only depends on your `~/.dub`, you can simply add something like this to your vimrc:
```vim
let g:syntastic_d_include_dirs = filter(glob($HOME . '/.dub/packages/*', 1, 1), 'isdirectory(v:val)')
call map(g:syntastic_d_include_dirs, 'isdirectory(v:val . "/source") ? v:val . "/source" : v:val')
call map(g:syntastic_d_include_dirs, 'isdirectory(v:val . "/src") ? v:val . "/src" : v:val')
call add(g:syntastic_d_include_dirs, './source')
```
However, I seem to recall from an older discussion that adding includes from source packages has negative side effects.  A better way to do it would be to use `dub` to get the list of include directories, but running `dub` is slow, so you'd have to trade between speed at Vim startup and keeping the list of packages up to date.

Either way, it's up to you to set `g:syntastic_d_include_dirs` to a value suitable for your project.

> Sorry but I was unable to follow the instructions on the contrib guide regarding: `g:syntastic_debug`
>I don't know how to set that to a value I tried `:set g:syntastic_debug=1` which failed.  

Vim has variables, and something called "options" (which are a sort of predefined system variables).  Variables are assigned with `let`, options are assigned with `set`.

> Update: Wasn't thinking and should have done `:let g:syntastic_debug=1` and that worked but I didn't see anything inside `:mes`

`:mes` reads Vim logs.  You need to run the checker to produce any logs.

**Comment by lcd047** [comment]
Related older discussion: #960.

**Comment by afaur** [comment]
@lcd047 Thanks for that link I tried searching the issues tracker but didn't find that one.   Sorry about the duplicate issue.
