### ISSUE TITLE
Problem: Syntastic check for clang (LLVM) on windows7 with third party library directory not working.

### ISSUE THREAD

**Issue by Pinaki82** [scrooloose/syntastic#1672]
As I posted this issue already here:
http://vim.1045645.n5.nabble.com/Syntastic-check-for-clang-LLVM-on-windows-with-third-party-libraries-td5726705.html
I'm not rewriting it. I did not get any reply from there so I'm posting this issue here.
But I would like to add a few note.
clang -I"C:\xtralibs\appu" test01.c -o test01.exe
works. But I also tried adding the following lines to my syntasticsetup.vim as:
let g:syntastic_clang_check_config_file = '$HOME/.syntastic_include_dir.txt'
let g:syntastic_clang_check_config_file = '.syntastic_include_dir.txt'
And it does not work.
Again, specifying
let g:syntastic_c_clang_check_args = -IC:\xtralibs\appu 
also not works.

How can I add third party header contained directories to synstastic for checking codes with clang?

**Comment by lcd047** [comment]
`gcc` and `clang_check` are independent to one another, and have different controlling variables.  Setting things up for `gcc` does nothing for `clang_check`, and the other way around.  The variables for `gcc` are documented [here](https://github.com/scrooloose/syntastic/wiki/C%3A---gcc), while those for `clang_check` are [here](https://github.com/scrooloose/syntastic/wiki/C%3A---clang_check) (assuming you're working with C files; C++ has other settings).

The easiest way to check your files with Clang instead of GCC is to point `g:syntastic_c_compiler` to `clang`:
```vim
let g:syntastic_c_compiler = 'clang'
```
With this change, the `gcc` checker will behave essentially the same way as `clang_check` (if you'd have that one configured correctly).

If you want to actually use `clang_check` the way to do it is to move _all_ flags to the config file, one per line:
```
-W
-Wall
-Wextra
-fsized-deallocation
...
-IC:/CODEBL~1/TDM-GC~1/include
-IC:/CODEBL~1/TDM-GC~1/lib/gcc/X86_64~1/51B983~1.0/include
```
-- and then point `g:syntastic_clang_check_config_file` to that:
```vim
let g:syntastic_clang_check_config_file = $HOME . '/.syntastic_include_dir.txt'
```
Please note that:

* you shouldn't add quotes in config files
* using backslashes in paths and passing them to Vim is asking for trouble
* `$HOME` should be expanded by Vim, not by syntastic.

You can then share the same config file with other checkers, such as `clang_tidy`.

To see what's going on you can enable debugging: set `g:syntastic_debug` to 1, run the checker, run `:mes`, and look for `makeprg` in the output.

> let g:syntastic_c_clang_check_args = -IC:\xtralibs\appu

This is not valid Vim syntax.

**Comment by Pinaki82** [comment]
@lcd047 Thanks, So Many Thanks for a quick response.
I was experimenting to get a solution to the problem, accordingly I was experimenting of my own.
Suddenly I found -I"C:\xtralibs\appu"  is the root of all the problems. So I created a file in %USERPROFILE% as '.syntastic_clang_check_config' and removed quotes from the directories as -IC:\xtralibs\appu and it started working. I had to change the syntastic setup as:

syntastic_setup.vim

" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_c_checkers=['gcc', 'cppcheck', 'splint', 'clang_check']
let g:syntastic_cpp_checkers=['gcc', 'cppcheck', 'clang_check']
let g:syntastic_c_compiler_options = '-W -Wall -Wextra -fsized-deallocation -pedantic -ansi -std=c99 -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wzero-as-null-pointer-constant -Wformat=2 -Wformat-security -Wformat-signedness -Wformat-y2k -Wnull-dereference  -Wconversion'
let g:syntastic_cpp_compiler_options = '-W -Wall -Wextra -fsized-deallocation -pedantic -ansi -std=c99 -std=gnu++98 -std=gnu++11 -std=gnu++14 -stdlib=libc++ -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wzero-as-null-pointer-constant -Wformat=2 -Wformat-security -Wformat-signedness -Wformat-y2k -Wnull-dereference  -Wconversion'
let g:syntastic_aggregate_errors = 1
let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_signs=1
" let g:syntastic_cpp_include_dirs = ['libs/dir2/dir3', 'libs/dir2 ]
let g:syntastic_cpp_check_header = 1
let g:syntastic_cpp_remove_include_errors = 1
let g:syntastic_cpp_config_file = $HOME . '/.syntastic_include_dir.txt'
let g:syntastic_cpp_config_file = '.syntastic_include_dir.txt'
let g:syntastic_c_config_file = $HOME . '/.syntastic_include_dir.txt'
let g:syntastic_c_config_file = '.syntastic_include_dir.txt'
let g:syntastic_clang_check_config_file = $HOME . '/.syntastic_clang_check_config'
" let g:syntastic_debug = 1
let g:syntastic_c_check_header = 1
let g:syntastic_cpp_check_header = 1
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Then, I added directories one by one and discovered I need ONE DIRECTORY LEVEL BACK as:
-IC:\xtralibs
-IC:\xtralibs\appu

Then another issue came, the general include directories in the TDM-GCC MinGWw64's folder will cause trouble if you list them, instead they will be added automatically by clang-check if clang finds its brother compiler TDM. So I had to remove all the list of directories located in the TDM's include folder.
Then I added ONE OPTION PER LINE warning flags typically these are:
-W
-Wall
-Wextra
-pedantic
-ansi
Now it works like a charm. Thanks to syntastic, thank you.
Syntastic is really an aeroplane, really a bird. It flies high.

So to cut the long story short. The general solution:
1) Add the COMPILER WARNIING FLAGS , ONE OPTION PER LINE basis.
2) List ONE DIRECTORY LEVEL BACK for the directory you need.
e.g.,
If you need -IC:\xtralibs\appu
write,
-IC:\xtralibs
-IC:\xtralibs\appu
3) Remove every line that points to a directory in the GCC's include folder. I mean if the directory is found by the GCC, don't list it.
4) Never use quotes to list directories like
-I"C:\xtralibs\appu" instead use Short File Name (8.3 Filename) [https://en.wikipedia.org/wiki/8.3_filename] if Possible.


Now I have my settings as:

syntastic_setup.vim

" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_c_checkers=['gcc', 'cppcheck', 'splint', 'clang_check']
let g:syntastic_cpp_checkers=['gcc', 'cppcheck', 'clang_check']
let g:syntastic_c_compiler_options = '-W -Wall -Wextra -fsized-deallocation -pedantic -ansi -std=c99 -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wzero-as-null-pointer-constant -Wformat=2 -Wformat-security -Wformat-signedness -Wformat-y2k -Wnull-dereference  -Wconversion'
let g:syntastic_cpp_compiler_options = '-W -Wall -Wextra -fsized-deallocation -pedantic -ansi -std=c99 -std=gnu++98 -std=gnu++11 -std=gnu++14 -stdlib=libc++ -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wzero-as-null-pointer-constant -Wformat=2 -Wformat-security -Wformat-signedness -Wformat-y2k -Wnull-dereference  -Wconversion'
let g:syntastic_aggregate_errors = 1
let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_signs=1
" let g:syntastic_cpp_include_dirs = ['libs/dir2/dir3', 'libs/dir2 ]
let g:syntastic_cpp_check_header = 1
let g:syntastic_cpp_remove_include_errors = 1
let g:syntastic_cpp_config_file = $HOME . '/.syntastic_include_dir.txt'
let g:syntastic_cpp_config_file = '.syntastic_include_dir.txt'
let g:syntastic_c_config_file = $HOME . '/.syntastic_include_dir.txt'
let g:syntastic_c_config_file = '.syntastic_include_dir.txt'
let g:syntastic_clang_check_config_file = $HOME . '/.syntastic_clang_check_config'
" let g:syntastic_debug = 1
let g:syntastic_c_check_header = 1
let g:syntastic_cpp_check_header = 1
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And I have my '.syntastic_clang_check_config' in the %USERPROFILE% as:

-W
-Wall
-Wextra
-pedantic
-ansi
-IC:\xtralibs
-IC:\xtralibs\appu
-IC:\xtralibs\yxml11
-IC:\WXWIDG~1.2\include\
-IC:\WXWIDG~1.2\include\wx
-IC:\WXWIDG~1.2\include\wx\android
-IC:\WXWIDG~1.2\include\wx\aui
-IC:\WXWIDG~1.2\include\wx\generic
-IC:\WXWIDG~1.2\include\wx\html
-IC:\WXWIDG~1.2\include\wx\meta
-IC:\WXWIDG~1.2\include\wx\msw
-IC:\WXWIDG~1.2\include\wx\persist
-IC:\WXWIDG~1.2\include\wx\private
-IC:\WXWIDG~1.2\include\wx\propgrid
-IC:\WXWIDG~1.2\include\wx\protocol
-IC:\WXWIDG~1.2\include\wx\ribbon
-IC:\WXWIDG~1.2\include\wx\richtext
-IC:\WXWIDG~1.2\include\wx\stc
-IC:\WXWIDG~1.2\include\wx\univ
-IC:\WXWIDG~1.2\include\wx\unix
-IC:\WXWIDG~1.2\include\wx\xml
-IC:\WXWIDG~1.2\include\wx\xrc
-IC:\xtralibs\GTK_-B~1.1-2
-IC:\xtralibs\GTK_-B~1.1-2\include
-IC:\xtralibs\GTK_-B~1.1-2\include\atk-1.0
-IC:\xtralibs\GTK_-B~1.1-2\include\atk-1.0\atk
-IC:\xtralibs\GTK_-B~1.1-2\include\cairo
-IC:\xtralibs\GTK_-B~1.1-2\include\FONTCO~1
-IC:\xtralibs\GTK_-B~1.1-2\include\FREETY~1
-IC:\xtralibs\GTK_-B~1.1-2\include\FREETY~1\freetype
-IC:\xtralibs\GTK_-B~1.1-2\include\gail-1.0
-IC:\xtralibs\GTK_-B~1.1-2\include\gail-1.0\LIBGAI~1
-IC:\xtralibs\GTK_-B~1.1-2\include\GDK-PI~1.0
-IC:\xtralibs\GTK_-B~1.1-2\include\GDK-PI~1.0\GDK-PI~1
-IC:\xtralibs\GTK_-B~1.1-2\include\glib-2.0
-IC:\xtralibs\GTK_-B~1.1-2\include\glib-2.0\gio
-IC:\xtralibs\GTK_-B~1.1-2\include\glib-2.0\glib
-IC:\xtralibs\GTK_-B~1.1-2\include\glib-2.0\gobject
-IC:\xtralibs\GTK_-B~1.1-2\include\gtk-2.0
-IC:\xtralibs\GTK_-B~1.1-2\include\gtk-2.0\gdk
-IC:\xtralibs\GTK_-B~1.1-2\include\gtk-2.0\gtk
-IC:\xtralibs\GTK_-B~1.1-2\include\libpng14
-IC:\xtralibs\GTK_-B~1.1-2\include\pango-1.0
-IC:\xtralibs\GTK_-B~1.1-2\include\pango-1.0\pango
-IC:\xtralibs\GTK_-B~1.1-2\include\pixman-1


Thanks, Have a Good Day.
