### ISSUE TITLE
Word with non-ascii not recorded into autocomplete

### ISSUE THREAD

**Issue by Darksonn** [scrooloose/syntastic#1673]
In my LaTeX document, if I type a word such as `ligevægt`, and begin typing it again, `ligevægt` is not suggested.

Steps to reproduce:

    touch tmp.tex
    vim tmp.tex

Now paste ligevægt into the first line, and type a newline. Try starting to type the word. Notice how nothing is suggested.

Now find an empty line and paste in a word with just ascii characters. For example cakecakecake would do. On another empty line try starting to type cakecakecake, and see how it's suggested.

I would have expected ligevægt to be suggested, just like cakecakecake was.

I tried a few other characters, I was unable to find a non-ascii character exhibiting the desired behaviour. The characters I tried was `æøåöł`.

**Comment by lcd047** [comment]
I'm afraid you're on the wrong track here, syntastic has nothing to do with autocomplete.  Perhaps post to `vim_users` instead?
