### ISSUE TITLE
Reset errorformat to its previous value

### ISSUE THREAD

**Issue by jmirabel** [scrooloose/syntastic#1676]
Dear syntastic developers,

I'm not sure whether my question is a feature request or an issue.

syntastic set the `errorformat` according to the checker to be used. Is there a reason for the `errorformat` not being reset to its previous value after having run the check ? If no, is there an easy way of doing so ?

VIM version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:40:46)
Included patches: 1-52
```
syntastic version: `3.7.0-62 (Vim 704, Linux)`

**Comment by lcd047** [comment]
Syntastic [already restores `errorformat`](https://github.com/scrooloose/syntastic/blob/48736aa376341518d7bedf3a39daf0ae9e1dcdc0/plugin/syntastic.vim#L579-L580).  If you're seeing a different behaviour there is something else at play.  You can see where `errorformat` was last set with this command:
```vim
:verbose set errorformat?
```
