### ISSUE TITLE
phpmd does not use g:syntastic_phpmd_rules

### ISSUE THREAD

**Issue by tomsteg** [scrooloose/syntastic#1677]
The phpmd syntax checker does not use the variable g:syntastic_phpmd_rules.
With the variable documented somewhere it would be possible to use own rules.

**Comment by lcd047** [comment]
> The phpmd syntax checker does not use the variable g:syntastic_phpmd_rules.

What gave you the idea that it should?

> With the variable documented somewhere it would be possible to use own rules.

Perhaps read the manual and use `g:syntastic_php_phpmd_args` for that purpose?

**Comment by tomsteg** [comment]
to g:syntastic_phpmd_rules I found something in a gitlab site 
https://git.crystax.net/mirror/vim-syntastic/blob/e0b8e87c939b96d7cc2548edb177021d4f9e27bf/syntax_checkers/php/php.vim

I also tried to use g:syntastic_php_phpmd_args , but without any positive result

Please can you tell me, where in the code of https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/php/phpmd.vim
is g:syntastic_php_phpmd_args used? 
Maybe I can learn here something.

**Comment by lcd047** [comment]
> to g:syntastic_phpmd_rules I found something in a gitlab site

That file is three years old.  Syntastic has changed in the mean time.

> I also tried to use g:syntastic_php_phpmd_args , but without any positive result

What did you do, what did you expect to happen, and what happened instead?

> Please can you tell me, where in the code of https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/php/phpmd.vim
 is g:syntastic_php_phpmd_args used?

You'll have to trust the manual: setting `g:syntastic_php_phpmd_args` adds options to `phpmd`.

To see what syntastic is doing (assuming a reasonably recent version of syntastic), set `g:syntastic_debug` to 1, run the checker, run `:mes`, and look for `makeprg` in the output.

**Comment by tomsteg** [comment]
I put in my .vimrc

    let g:syntastic_php_phpmd_args = "/Users/thomassteglich/Websites/Test.git/library/requests/phpmd-rules.xml"
    let g:syntastic_php_checkers = ['php', 'phpcs', 'phpmd']

and got the following debug result:

```
syntastic: 349.588725: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shellt
emp = 1, &shellxquote = ''
syntastic: 349.589054: UpdateErrors: phpmd
syntastic: 349.589359: CacheErrors: phpmd
syntastic: 349.589803: g:syntastic_aggregate_errors = 0
syntastic: 349.589935: getcwd() = '/Users/thomassteglich/Websites/Test.git'
syntastic: 349.590238: CacheErrors: Invoking checker: php/phpmd
syntastic: 349.590674: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%E%f:%l%\s%#%m', 'makeprg': 'phpmd /Users/thomassteglich/Website
s/Test.git/library/requests/phpmd-rules.xml library/requests/Elaine/ElaineController.class.php text codesize,design,unusedcode,naming'}
syntastic: 349.641989: getLocList: checker php/phpmd returned 1
```

Like that phpmd does not find any errors.

When I do not use g:syntastic_php_phpmd_args
I get errors, but from the wrong rulesets:

```
syntastic: 53.268012: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shellte
mp = 1, &shellxquote = ''
syntastic: 53.268366: UpdateErrors: phpmd
syntastic: 53.268668: CacheErrors: phpmd
syntastic: 53.269238: g:syntastic_aggregate_errors = 0
syntastic: 53.269389: getcwd() = '/Users/thomassteglich/Websites/Test.git'
syntastic: 53.269680: CacheErrors: Invoking checker: php/phpmd
syntastic: 53.270108: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%E%f:%l%\s%#%m', 'makeprg': 'phpmd library/requests/Elaine/Elaine
Controller.class.php text codesize,design,unusedcode,naming'}
syntastic: 53.678348: getLocList: checker php/phpmd returned 2
```

**Comment by tomsteg** [comment]
When I use on the command line the following expression, I get the correct error messages:

    phpmd ElaineController.class.php text /Users/thomassteglich/Websites/Test.git/library/requests/phpmd-rules.xml

**Comment by lcd047** [comment]
Well, the key is still in the manual.  You need to use `g:syntastic_php_phpmd_post_args` to pass the rule file after the filename, instead of `codesize,design,unusedcode,naming`:
```vim
let g:syntastic_php_phpmd_post_args = $HOME . '/Websites/Test.git/library/requests/phpmd-rules.xml'
```

**Comment by tomsteg** [comment]
So my mistake was to forget the post in g:syntastic_php_phpmd_post_args.
Now everything is fine. 
If I had a closer look to the code of phpmd.vim, I should have known.
Sorry.

**Comment by lcd047** [comment]
> If I had a closer look to the code of phpmd.vim, I should have known.

It's unlikely you'd have infer that from looking at `phpmd.vim`.  To understand what's going on you'd have to read `makeprgBuild()` code in `plugin/syntastic/checker.vim`, and its dependencies thereof, and then look at `phpmd.vim`.  Alternatively, youcould have read the ~20 relevant lines in the manual, and think for a minute about what you're doing. _shrug_
