### ISSUE TITLE
Location size doesn't automatically adjust to content size

### ISSUE THREAD

**Issue by olalonde** [scrooloose/syntastic#1678]
<img width="658" alt="screenshot 2016-01-28 01 10 57" src="https://cloud.githubusercontent.com/assets/416585/12639968/5169a802-c55c-11e5-8dcf-7b12aa0aeb31.png">

I'm not sure if this is something syntastic can "fix" but there's a lot of wasted screen estate when the location list opens up for only 2 lines. it would be nice if it would automatically adjust to fit the size of the content.

**Comment by lcd047** [comment]
Syntastic uses variable `g:syntastic_loc_list_height` (defaulting to 10) to sets the height of the error window.  To make it adjust automatically to the number of issues found, you can use the undocumented callback `SyntasticCheckHook()`.  This function is called with an argument pointing to the final list of errors, so you can add something like this to your vimrc:
```vim
function! SyntasticCheckHook(errors)
    if !empty(a:errors)
        let g:syntastic_loc_list_height = min([len(a:errors), 10])
    endif
endfunction
```
Please note however that Vim options `winheight` and `winminheight` also affect the final result.

**Comment by olalonde** [comment]
@lcd047 thanks! that seemed to work

**Comment by ds-cbo** [comment]
Could this be added to either the Recommended Settings or FAQ? I just installed Syntastic and this was the first thing that bugged me.

**Comment by lcd047** [comment]
@ds-cbo It isn't a recommended setting. _shrug_ Also, you should probably consider using [ALE][ALE] instead of syntastic these days.

[ALE]: https://github.com/dense-analysis/ale
