### ISSUE TITLE
Feature request, independent file type

### ISSUE THREAD

**Issue by aemonge** [scrooloose/syntastic#1680]
Hi !! due to a lack of my proyect organization, i have to code my Javascript files in HTML. So I know jshint and jscs can handle HTML correctly, but lot's of my plugins can't.

So I had to force the *.html files to be `:set filetype=javascript`, but now jshint and jscs complains about the <html> tags.

So It would be awesome if syntastic had a way to set *.html files to filetype=html overwrittin my own default crappy setting.

**Comment by lcd047** [comment]
Syntastic already has this: `:h 'syntastic_filetype_map'`.  But jshint and jscs don't care about Vim filetypes.

**Comment by aemonge** [comment]
Thanks !!!!

**Comment by aemonge** [comment]
Ohhh nevermind !!! I figure it out, I was reading wrong the :h 

**.vimrc**
```
if expand("<afile>:e") ==? 'html'
  set filetype=javascript
  let g:syntastic_filetype_map = { "javascript": "html" }
endif
```

**Comment by lcd047** [comment]
If that works, it does so by accident. :) Try something like this instead:
```vim
autocmd BufRead,BufNewFile *.html set filetype=javascript | let g:syntastic_filetype_map={"javascript":"html"}
```

**Comment by aemonge** [comment]
I'll do so !!!

Thanks !!!
