### ISSUE TITLE
fish shell supports Unix redirections now

### ISSUE THREAD

**Issue by fibo** [scrooloose/syntastic#1681]
Hi,

at the time of this writing fish shell supports Unix redirectinos so [syntastic doc](https://github.com/scrooloose/syntastic/blob/master/doc/syntastic.txt#L885-L893) should by updated.

Tell me if you agree, I can do a pr updating that part of documentation if you want.

However, setting `let g:syntastic_shell = "/bin/sh"` is still required for vi <7.4 as you can see here: https://github.com/fish-shell/fish-shell/issues/2701

**Comment by lcd047** [comment]
> Tell me if you agree

I don't.  Syntastic needs more than just UNIX redirections, it pretty much assumes Bourne `sh`.  Some checkers would still fail with `shell` pointing to `fish`.  The same is true for `csh`, anf `tcsh`.

**Comment by fibo** [comment]
Right, at the end the suggested solution was to set

.   set shell=/bin/sh

on top of vimrc
