### ISSUE TITLE
Options to easily turn on and off.

### ISSUE THREAD

**Issue by KyleRoberts2a** [scrooloose/syntastic#1683]
It would surely be lovely if there was an easy option to turn syntastic on and off.  While I know there is :SyntasticToggle.  When once does that if syntastic is off it does nothing. I would expect toggle to turn it off when on and on when off.  

How could one do this as a temporary work around?

Thanks a lot :)

**Comment by lcd047** [comment]
There can't be any such things as "on" and "off" states.  `:SyntasticToggle` toggles between active and passive states.  In the active state checks are run whenever you save a file (and also when you open one, depending on `syntastic_check_on_open`).  In the passive state syntastic doesn't "do" anything, checks are run only when you explicitly call `:SyntasticCheck`.  There's also `:SyntasticReset` to clear the list of errors, and you can re-instate the list of errors by running the checks again.  This the only approach that makes sense given Vim's API. _shrug_

**Comment by KyleRoberts2a** [comment]
Thank you so much. I appreciate it. I suppose I was just looking for a way
to turn the left colmn off and on again.

**Comment by lcd047** [comment]
The left column is called "signs", and is managed by Vim, not by syntastic.  There is no on / off switch for signs (see `:h signs`).  Now, is it possible to implement such a switch in VimL?  The answer is yes and no.  It's possible to implement a switch to hide the current signs, and later show the same signs.  It isn't possible to prevent plugins to place new signs while they are supposed to be off, nor is it possible to update the hidden list automatically.  Either way, managing signs would be out of scope for syntastic.

**Comment by KyleRoberts2a** [comment]
Thanks LCD.  How would one just turn off syntastic and then turn of back
on? Maybe I want to use another plugin that uses signs like git gutter.

I guess now If I do :SyntasticToggle it turns the signs off and checking
off. But if I toggle back on well they don't come back.

**Comment by lcd047** [comment]
Reading the manual can save you a lot of time.
