### ISSUE TITLE
Unknown function: syntastic#util#system

### ISSUE THREAD

**Issue by W-M-D** [scrooloose/syntastic#1684]
line   58:
E117: Unknown function: syntastic#util#system
E116: Invalid arguments for function split(syntastic#util#system('uname'), "\n")[0]
E15: Invalid expression: split(syntastic#util#system('uname'), "\n")[0]

**Comment by W-M-D** [comment]
VIM version info

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 19 2015 02:52:16)
Included patches: 1-658
Compiled by neophobia@Main
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2    -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu/ -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions

**Comment by lcd047** [comment]
This looks like a broken installation.  What did you do, what did you expect to happen, and what happened instead?

**Comment by W-M-D** [comment]
I have installed syntastic for vim on previous systems using this version of vi before. The prompt shows every time i open vim.

**Comment by lcd047** [comment]
You can either explain how did you install syntastic, or trace down the differences between your previous system and the current one, whatever these might be.  I can't help you with the latter.  I _might_ be able to give you some hints about what's going on if you give me enough details to make sense of what you actually did.

**Comment by W-M-D** [comment]
Reinstalled vim from debian unstable. fixed.

**Comment by timblaktu** [comment]
FWIW I'm seeing this error when I `:echo syntastic#util#system('echo "$PATH"')`. I'm on raspberry pi 3 (raspbian), using these package versions:

`(ansible-testing) pi@tblack-pi:~/Source/ansible $ dpkg -l | grep vim                                                                   ii  vim                                   2:7.4.488-7+deb8u3                        armhf        Vi IMproved - enhanced vi editor      ii  vim-addon-manager                     0.5.3                                     all          manager of addons for the Vim editor  ii  vim-common                            2:7.4.488-7+deb8u3                        armhf        Vi IMproved - Common files            ii  vim-runtime                           2:7.4.488-7+deb8u3                        all          Vi IMproved - Runtime files           ii  vim-syntastic                         3.5.0-1                                   all          Syntax checking hacks for vim `

This felt like an installation problem, but I have purged all vim packages, cleaned and updated apt, then reinstalled ONLY vim and vim-syntastic via apt, which produced the packages listed above.

**Comment by lcd047** [comment]
It _is_ an installation problem.  I'm afraid I know nothing about raspbian, so please take it with the maintainer of your `vim-syntastic` for your distribution.
