### ISSUE TITLE
XML does not validate schemas

### ISSUE THREAD

**Issue by maxbucknell** [scrooloose/syntastic#1685]
Hi,

I'm looking to migrate back to vim in my day job, and this is going to be a feature that I need. A naïve solution would be to find the schema from the XML and pass it to `xmllint`, but I'd say it's worth having a lookup table before that, as well. so that URNs can be resolved into actual locations (something like `g:schema_locations`, if needed. If nothing is set in the table, we can just try to load a file, and silently do nothing if we can't resolve it (or warn?)

I'm happy to do some preliminary work on this, it seems like something I'm capable of, and I'm highly motivated to do it.

**Comment by lcd047** [comment]
You can use `g:syntastic_xml_xmllint_args` to pass optionms to `xmllint`, f.i.:
```vim
let g:syntastic_xml_xmllint_args = '--schema /path/to/schema.xsd'
```
You can see the exact command line formed by syntastic in the debug logs: set `g:syntastic_debug` to 1, run the checker, run `:mes`, and look for `makeprg`.
