### ISSUE TITLE
Windows/UNIX slash inconsistencies causing errors running Syntastic

### ISSUE THREAD

**Issue by alberdingk-thijm** [scrooloose/syntastic#1686]
Encountered a bug running Syntastic on my Python code that has, I suspect, more to do with my configuration than Syntastic.

On a Windows machine running the Windows 64-bit VIM in Git Bash, Syntastic reports a Python open() error where the Windows backslashes have been lost while trying to open compile.py when Syntastic attempts to run (e.g. when saving the file):
F:\Python35\python.exe: can't open file 'C:UsersTimvimfilesbundlesyntasticsyntax_checkerspythoncompile.py"
I'm not sure if there is a way to pad the path in the Syntastic code to keep from losing the backslashes or not, as I assume Git Bash has lost them somewhere, or if another solution exists.
Thanks.

EDIT: Same problem occurred when opening vim in cmd.exe.

**Comment by lcd047** [comment]
I'm afraid I know preciously little about Windows and nothing about Git Bash, but these should be relevant: `:h syntastic-shellslash` and `:h 'syntastic_shell'`.

**Comment by alberdingk-thijm** [comment]
Thanks a lot, @lcd047! Turns out having shellslash off was causing the issue. Looks like syntastic is working now.
