### ISSUE TITLE
Cygwin, incorrect path for tmp directory (while using javac.vim)

### ISSUE THREAD

**Issue by WooterTheTroubleshooter** [scrooloose/syntastic#1687]
Before I found this issue I have been trying to get the javac checker working with my cygwin environment, after some searching I found an old issue related to the javac checker with some information to debug syntastic.

The following command was shown for syntasticMake: (abbreviated & truncated to show relevant information only)
> 'makeprg': 'javac -Xlint -d /tmp/vim-syntastic-6240-Nq3Wr88V ''C:/cygwin64/home/Wouter/projec
ts/...

After trying to execute the command manually I have gotten the following error:
> javac:  directory not found: /tmp/vim-syntastic-5232-OkBjTTAa

Looking through the javac.vim I have noticed that some paths in are corrected for cygwin. After finding the function that generates the tmp directory, and analysing the code. I think I have found the issue. [util.vim:54](https://github.com/scrooloose/syntastic/blob/master/autoload/syntastic/util.vim#L54)

I have used the following code, which I have placed in my .vimrc to test the environment statement in the function "syntastic#util#tmpdir()". The echo below is executed on my cygwin environment.
> if (has('unix') || has('mac')) && executable('mktemp')
>     echo "unix or mac"
> endif

Since the environment statement is true, the tempdir is now no longer empty, the cygwin specific line: [util.vim:66](https://github.com/scrooloose/syntastic/blob/master/autoload/syntastic/util.vim#L66)
will not be executed and the path will no longer be escaped.
Also judging by the format of the directory name "/tmp/vim-syntastic-5232-OkBjTTAa" matches the statement on [util.vim:57](https://github.com/scrooloose/syntastic/blob/master/autoload/syntastic/util.vim#L57)

Edit: Additional information: By disabling the output directory deletion switch for the javac.vim, the tmpdir call is avoided and could be considered a workaround for the problem: [javac.vim:103](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/java/javac.vim#L103)

**Vim Version:**
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct  8 2015 00:46:23)
> Inclusief 'patches': 1-801, 803-808, 810-891
> Gecompileerd door <cygwin@cygwin.com>
> Enorme versie without GUI.  Features included (+) or not (-):
> +acl             +cindent         +conceal         +digraphs        +farsi           +gettext         +libcall         +mksession       +mouse_netterm   -mzscheme        +profile         +scrollbind      +syntax          +textobjects     +visualextra     -X11
> +arabic          -clientserver    +cryptv          -dnd             +file_in_path    -hangul_input    +linebreak       +modify_fname    +mouse_sgr       +netbeans_intg   +python/dyn      +signs           +tag_binary      +title           +viminfo         -xfontset
> +autocmd         +clipboard       +cscope          -ebcdic          +find_in_path    +iconv           +lispindent      +mouse           -mouse_sysmouse  +path_extra      +python3/dyn     +smartindent     +tag_old_static  -toolbar         +vreplace        -xim
> -balloon_eval    +cmdline_compl   +cursorbind      +emacs_tags      +float           +insert_expand   +listcmds        -mouseshape      +mouse_urxvt     +perl/dyn        +quickfix        -sniff           -tag_any_white   +user_commands   +wildignore      -xsmp
> -browse          +cmdline_hist    +cursorshape     +eval            +folding         +jumplist        +localmap        +mouse_dec       +mouse_xterm     +persistent_undo +reltime         +startuptime     -tcl             +vertsplit       +wildmenu        -xterm_clipboard
> ++builtin_terms  +cmdline_info    +dialog_con      +ex_extra        -footer          +keymap          +lua/dyn         -mouse_gpm       +multi_byte      +postscript      +rightleft       +statusline      +terminfo        +virtualedit     +windows         -xterm_save
> +byte_offset     +comments        +diff            +extra_search    +fork()          +langmap         +menu            -mouse_jsbterm   +multi_lang      +printer         +ruby/dyn        -sun_workshop    +termresponse    +visual          +writebackup     -xpm
>    system vimrc file: "$VIM/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>   fall-back for $VIM: "/etc"
>  f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
> Compilatie: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/vim/vim-7.4.891-1.x86_64/build=/usr/src/debug/vim-7.4.891-1 -fdebug-prefix-map=/usr/src/ports/vim/vim-7.4.891-1.x86_64/src/vim74=/usr/src/
> debug/vim-7.4.891-1 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
> Linking: gcc   -L. -fstack-protector  -L/usr/local/lib -Wl,--as-needed -o vim.exe        -lm -lelf    -lncursesw -liconv -lintl   -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.
> 22/x86_64-cygwin-threads/CORE -lperl -lpthread -ldl -lcrypt

**SyntasticInfo:**
> Syntastic version: 3.7.0-80 (Vim 704, CYGWIN_NT-10.0)
> Info for filetype: java
> Global mode: active
> Filetype java is active
> The current file will be checked automatically
> Available checker: javac
> Currently enabled checker: javac

**Comment by lcd047** [comment]
Thank you for getting to the root of this.  Please try d8af502.

**Comment by WooterTheTroubleshooter** [comment]
Thanks for the fast reply, I will try this when I get home.

**Comment by WooterTheTroubleshooter** [comment]
It's working as expected now:
> 'javac -Xlint -d ''C:/cygwin64/tmp/vim-syntastic-5856'' ''C:/cygwin64/home/Wouter/projects...
