### ISSUE TITLE
HLint not working

### ISSUE THREAD

**Issue by afonsojoao96** [scrooloose/syntastic#1688]
Hi there, i've installed `hlint` in my Ubuntu 14.04 machine (with `apt-get install hlint`, not cabal), however when i edit a haskell file it does not perform syntax check.

Running `:SyntasticInfo` i get:
```
Syntastic version: 3.7.0-81 (Vim 704, Linux)
Info for filetype: haskell
Global mode: active
Filetype haskell is active
The current file will be checked automatically
Available checker: hlint
Currently enabled checker: hlint
```
So i assume that Syntastic knows that i've hlint installed and working.
`:SyntasticCheck` does nothing with a file containing obvious errors.

Hlint is working good when i run it through my terminal.
Vim version: 7.4

Any thoughts about that?

**Comment by lcd047** [comment]
> when i edit a haskell file it does not perform syntax check.

Please open your test file, set `g:syntastic_debug` to 3, run the checker, then run `:mes` and post the output.

**Comment by afonsojoao96** [comment]
Wow it is now working, i simply ran:
`let g:syntastic_debug=3` followed by
`:mes`
and now it highlights the errors!
Thanks dude
