### ISSUE TITLE
Errors when running source % in vimrc

### ISSUE THREAD

**Issue by TheSuitIsNotBlack** [scrooloose/syntastic#1689]
I'm installing easymotion in vim, and when I run source %, the colors completely change from my dark scheme to a light scheme and I get the following two errors:

```
E121: Undefined variable: #warningmsg#
E15: Invalid expression: pyeval('powerline.new_window()')%#warningmsg#%{SyntasticStatuslineFlag()}%*%#w
arningmsg#%{SyntasticStatuslineFlag()}%*%#warningmsg#%{SyntasticStatuslineFlag()}%*
```

This has happened a couple times to me now, and as far as I can tell it only happens when I'm in a split screen. When it's only a single window it works fine.

**Comment by lcd047** [comment]
The part relevant to syntastic: you're running `powerline`.  With `powerline` you aren't supposed to mess with `statusline` directly, so the manipulations described by `:h syntastic-statusline-flag` don't apply.  `powerline` has a predefined segment for syntastic, and you can use that to configure syntastic's `statusline` flag if you need to.  So remove the `set statusline+=...` lines, and see `:h syntastic-powerline`.

This also explains (in a roundabout way) why you get errors only in a split screen: you're probably using a plugin manager that does lazy initialisations, and said initialisations are run in the wrong order in splits.  As I said, the problem should go away if you remove the `set statusline+=...` lines.

The colour scheme and `easymotion` have nothing to do with syntastic.  And running `source %` from your vimrc is asking for trouble (this is a well-known Vim problem).
