### ISSUE TITLE
Javascript Standard doesn't work

### ISSUE THREAD

**Issue by nicknikolov** [scrooloose/syntastic#1690]
Sorry if I've missed something stupid. 
I installed Syntastic using Vundle.
This is my vimrc
```
let g:syntastic_javascript_checkers = ['standard']
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
```

This is what I get from SyntacticInfo

Syntastic version: 3.7.0-84 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -

Thanks!

**Comment by lcd047** [comment]
The first entry in the [FAQ](https://github.com/scrooloose/syntastic#faqinfo) has some pointers.

**Comment by nicknikolov** [comment]
Ahh, I forgot that standard is installed locally, not globally. Sorry!
