### ISSUE TITLE
Can't Close Location List With :bd

### ISSUE THREAD

**Issue by amadeus** [scrooloose/syntastic#1699]
I tried searching to see if this has been reported before, but I have not found anything.

Not sure if this is a vim issue or something with Syntastic. When I attempt to close the Location List with `:bd` the Location List appears to get closed, but then immediately gets recreated again.

However, if I perform `:lcl` from the main file buffer then the Location List closes just fine.

It should be assumed that the Location List has items in it.

**Comment by lcd047** [comment]
Right, the useful information about syntastic is scattered across the manual, the wiki, and the FAQ.

Please see the last item in the [FAQ](https://github.com/scrooloose/syntastic#faqbdelete).
