### ISSUE TITLE
Include errors although g:syntastic_cpp_remove_include_errors=1

### ISSUE THREAD

**Issue by SpectreJan** [scrooloose/syntastic#1702]
Hi,
I have encountered a problem where VIM/Syntastic would show the error that the included files could not be found, even if g:syntastic_cpp_remove_include_errors was set to 1.
vimx 7.4 (GTK support) from the Fedora 23 packages.
Syntastic Version and Checkers can be seen in the picture below.
![syntastic_version](https://cloud.githubusercontent.com/assets/6916046/13179244/4fdc9354-d723-11e5-9eef-e7fcd38c8e02.png)

In this picture one can see that the error is shown.
![syntastic_bug](https://cloud.githubusercontent.com/assets/6916046/13179190/1bf1c492-d723-11e5-9419-faec0912a350.png)

I put together a minimalistic .vimrc I used for the tests:
[vimrc.txt](https://github.com/scrooloose/syntastic/files/138181/vimrc.txt)

Another thing I noticed is that sometimes the errors are correctly hidden if I start vim directly in the directory of the source file. But if I open the file in another directory, say: vim path/to/file/some.cc or via NerdTree the errors are still shown. When I created three new files in different directories, all of them would show the include errors.

**Comment by lcd047** [comment]
Please open your test file, run `:SyntasticInfo`, and post the output (doing that in the quickfix window as you did above is useless, sorry).  Then set `g:syntastic_debug` to 3, run the checker, run `:mes`, and again, post the output.

**Comment by lcd047** [comment]
On a side note: `g:syntastic_cpp_remove_include_errors` removes messages about errors in header files.  In your example above the error is in the main file, not in a header (`#include` pointing to a missing file).

**Comment by SpectreJan** [comment]
Oh yeah, after reading the checker wiki again I also realize that it does not what I thought it did (removing errors about header not found). My mistake, sorry. I guess then it is time to do things right and add the appropriate include paths.
 
I also just saw my mistake with the quickfix window *facepalm*. I guess the Issue can be closed then.

Thanks anyway,
Jan

**Comment by lcd047** [comment]
Missing `#include` files are fatal errors for most compilers, you probably won't get any useful diagnostics if you ignore the messages.

Anyway, you probably wanty to write a [config file](https://github.com/scrooloose/syntastic/wiki/Configuration-Files) based on your `Makefile` and point `g:syntastic_cpp_config_file` to it.  Or use a checker that knows about compilation databases and related tricks.

**Comment by SpectreJan** [comment]
Thanks for the tipp!
