### ISSUE TITLE
Python: shows only the first error of many

### ISSUE THREAD

**Issue by for-coursera** [scrooloose/syntastic#1703]
After running a check and opening the location list with `:Errors` only the first of two errors is shown (note the second one on the line 24):

![](http://i.imgur.com/YIcPccC.png)

Here's the `:SyntasticInfo` output:

    Syntastic version: 3.7.0-86 (Vim 704, Darwin)
    Info for filetype: python
    Global mode: active
    Filetype python is active
    The current file will be checked automatically
    Available checkers: flake8 pep8 pyflakes python
    Currently enabled checkers: python flake8

**Comment by lcd047** [comment]
Syntastic doesn't know, or care, about syntax checks.  What syntastic does is, it delegates the checks to external programs, and shows you the results in a window.  In your particular case, do you get more than one error when you try to run the script in a terminal?
