### ISSUE TITLE
Make syntastic run for only certain filetypes

### ISSUE THREAD

**Issue by sid-kap** [scrooloose/syntastic#1705]
I apologize if this is in the documentation and I overlooked this, but is there a way to make Syntastic run ONLY on filetypes that I specify? I searched the documentation but I could not find this. 

If someone can help me with this, I would love to put this back into the documentation so that other users can find this more easily.

**Comment by lcd047** [comment]
Please see `:h 'syntastic_mode_map'` and `:h :SyntasticToggleMode`.
