### ISSUE TITLE
Some bleeding around signs and highlighting (when paired with signify plugin?)

### ISSUE THREAD

**Issue by mtglsk** [scrooloose/syntastic#1706]
Here is a screenshot:

![syntastic-bleeding](https://cloud.githubusercontent.com/assets/10101321/13231143/a9927490-d9a8-11e5-9f4c-316408fe2b1b.png)

Those `j` don't exist in the file and they dissapear on `^L`.

How to reproduce (hopefully):

1. Go on a highlighted line like above.
2. Insert a blank line with `o`.
3. Exit insert mode.
4. Save.
5. Press j.

I have signify plugin installed which might be caused by it or maybe syntastic. It also only happens if you do such actions fast.

**Comment by lcd047** [comment]
Syntastic has no control over this kind of things, and, while I haven't looked at signify, I'm willing to bet the same holds true for signify.  The most likely candidate for a problem is the `terminfo` / `termcap` entry for your `TERM`, or a bug in Vim.  Please see #822 for more details.
