### ISSUE TITLE
get error when save markdown files;

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/syntastic#1709]
when I am use neovim ,and if I save this markdown file,will get this error;
the file is 
https://github.com/Neovim-cn/Neovim-cn.gitgub.io/blob/master/translation/vim_diff.md
```
"translation/vim_diff.md" 247L, 8003C written                                                                                                          
Error detected while processing function <SNR>129_BufWritePostHook[3]..<SNR>129_UpdateErrors:                                                          
line   44:                                                                                                                                             
E685: Internal error: get_tv_string_buf()                                                                                                              
Press ENTER or type command to continue      
```

**Comment by lcd047** [comment]
Please upgrade to the latest version of syntastic (make sure it's unmodified), and try to reproduce the problem with __plain Vim__, and with __all other plugins disabled__.

**Comment by wsdjeg** [comment]
I am using the latest version of syntastic and vim also and neovim.
test with only one plugin .only neovim show me this issues.but with other markdown file there is no error,only the link I show you above

**Comment by lcd047** [comment]
Please try to reproduce the problem with plain Vim.  Neovim "should work", but is not supported (not by myself that is).  Please report the problem to neovim developers if you can't reproduce it with plain Vim.

**Comment by wsdjeg** [comment]
ok thanks,I think maybe it is an issue of neovim, after update neovim ,all filetype get this error

**Comment by wsdjeg** [comment]
@lcd047 I got it it is due to this option `"let g:syntastic_always_populate_loc_list = 1`

**Comment by lcd047** [comment]
When `always_populate_loc_list` is off syuntastic doesn't call the relevant function.  As far as I can tell there's no reason for said function to raise an error though.  So yes, this is probably a bug in neovim.

**Comment by wsdjeg** [comment]
thanks a lot ,I have report it to neovim repo.
