### ISSUE TITLE
iabbrev

### ISSUE THREAD

**Issue by gerases** [scrooloose/syntastic#1710]
Hi,

I love the plugin but I have a small issue. It seems that if a line is highlighted with an error, `iabbrev`iations stop working on that line. Anywhere above or below are OK but not on the line itself. Any idea what could be causing it?

I'm specifically using these settings:

```
let g:syntastic_enable_perl_checker = 1
let g:syntastic_perl_checkers = [ 'perl', 'podchecker', 'perlcritic' ]
set statusline+=%{SyntasticStatuslineFlag()}
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_aggregate_errors = 1
let g:syntastic_html_checkers=['']
let g:syntastic_java_checkers=['']
```

**Comment by lcd047** [comment]
This is not related to syntastic, syntastic has nothing to do with anything related to insert mode, or with abbreviations.  If anything it looks like a bug in Vim.  Rule out conflicts with other plugins first, then run Vim with a clean config:
```sh
vim -i NONE -u NONE -N -X --noplugin
```
Then add highlighting with `matchadd()`.  If you can trigger the problem with this setup, post a bug report to `vim_dev`.

**Comment by gerases** [comment]
Thanks much for the tips. I will diagnose the way you suggested.
