### ISSUE TITLE
Eslint is not working

### ISSUE THREAD

**Issue by segmentationfaulter** [scrooloose/syntastic#1717]
I am unable to check my JS code using eslint, there are many errors with my test javascript file which should be reported but nothing is reported, here is a screenshot of running `SyntasticInfo`:

http://imgur.com/Un36gHf

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, then post the output (__not__ a screenshot of it please).

**Comment by nybblr** [comment]
Same issue here, I'm using ESLint 2.2.0.

```
syntastic: 128.820029: &shell = '/usr/local/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellr
edir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 128.820553: UpdateErrors: eslint
syntastic: 128.820896: CacheErrors: eslint
syntastic: 128.821702: g:syntastic_aggregate_errors = 0
syntastic: 128.821872: getcwd() = '/Users/jonathan/Development/Work/milegacy'
syntastic: 128.822160: CacheErrors: Invoking checker: javascript/eslint
syntastic: 128.822617: SyntasticMake: called with options: {'postprocess': ['guards'], 'errorformat': '%E%f: line %l\, col %c\,
 Error - %m,%W%f: line %l\, col %c\, Warning - %m', 'makeprg': '/Users/jonathan/Development/Work/milegacy/node_modules/.bin/esl
int -f compact ember-cli-build.js'}
syntastic: 129.646814: checker output: ['']
syntastic: 129.647396: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern':
'', 'text': ''}]
syntastic: 129.647716: postprocess: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern':
'', 'text': ''}]
syntastic: 129.647972: getLocList: checker javascript/eslint returned 0
syntastic: 129.648141: javascript/eslint raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', '
pattern': '', 'text': ''}]
syntastic: 129.648411: quiet_messages filter: {}
syntastic: 129.648794: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
```

I overrode the eslint_exec to be the local eslint, but get the same issues using the globally installed eslint.

**Comment by lcd047** [comment]
> syntastic: 129.646814: checker output: ['']

Well, there's your problem.  What happens if you run this in a terminal:
```
cd /Users/jonathan/Development/Work/milegacy
/Users/jonathan/Development/Work/milegacy/node_modules/.bin/eslint -f compact ember-cli-build.js
```

**Comment by segmentationfaulter** [comment]
Here is my `:mes` output:

`Messages maintainer: Bram Moolenaar <Bram@vim.org>                                                                              
"app.js" 60L, 1441C
syntastic: 0.037648: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash
 = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 0.038232: UpdateErrors (auto): default checkers
syntastic: 0.038552: CacheErrors: default checkers
syntastic: 0.039211: g:syntastic_aggregate_errors = 0
syntastic: 0.039392: getcwd() = '/home/saqib/test'
syntastic: 0.277523: CacheErrors: Invoking checker: javascript/eslint
syntastic: 0.278266: SyntasticMake: called with options: {'postprocess': ['guards'], 'errorformat': '%E%f: line %l\, col %c\, Error - %m,%W%f: lin
e %l\, col %c\, Warning - %m', 'makeprg': 'eslint -f compact app.js'}
syntastic: 0.561944: checker output: ['/usr/lib/node_modules/eslint/lib/config/config-file.js:332', '            throw e;', '            ^', '', '
Error: Cannot read config package: eslint-config-airbnb', 'Error: Cannot find module ''eslint-config-airbnb''', 'Referenced from: /home/saqib/test
/.eslintrc.json', '    at Function.Module._resolveFilename (module.js:339:15)', '    at Function.Module._load (module.js:290:25)', '    at Module.
require (module.js:367:17)', '    at require (internal/module.js:16:19)', '    at loadPackage (/usr/lib/node_modules/eslint/lib/config/config-file
.js:168:16)', '    at loadConfigFile (/usr/lib/node_modules/eslint/lib/config/config-file.js:212:18)', '    at load (/usr/lib/node_modules/eslint/
lib/config/config-file.js:385:18)', '    at /usr/lib/node_modules/eslint/lib/config/config-file.js:326:36', '    at Array.reduceRight (native)', '
    at applyExtends (/usr/lib/node_modules/eslint/lib/config/config-file.js:309:28)', '']
syntastic: 0.563091: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/usr/lib
/node_modules/eslint/lib/config/config-file.js:332'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': ''
, 'text': '            throw e;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '
    ^'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}, {'lnum': 0, 'bufnr': 0, 'col':
 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Error: Cannot read config package: eslint-config-airbnb'}, {'lnum': 0, 'b
ufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Error: Cannot find module ''eslint-config-airbnb'''}, {'l
num': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Referenced from: /home/saqib/test/.eslintrc.js
on'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Function.Module._resolveFilena
me (module.js:339:15)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Function.Mo
dule._load (module.js:290:25)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at Mod
ule.require (module.js:367:17)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at re
quire (internal/module.js:16:19)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at
loadPackage (/usr/lib/node_modules/eslint/lib/config/config-file.js:168:16)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1,
'type': '', 'pattern': '', 'text': '    at loadConfigFile (/usr/lib/node_modules/eslint/lib/config/config-file.js:212:18)'}, {'lnum': 0, 'bufnr':
0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at load (/usr/lib/node_modules/eslint/lib/config/config-file
.js:385:18)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    at /usr/lib/node_modules
/eslint/lib/config/config-file.js:326:36'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text':
'    at Array.reduceRight (native)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    a
t applyExtends (/usr/lib/node_modules/eslint/lib/config/config-file.js:309:28)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -
1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 0.564526: postprocess: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '/usr/lib
/node_modules/eslint/lib/config/config-file.js:332'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': ''
, 'text': '            throw e;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '
    ^'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}, {'lnum': 0, 'bufnr': 0, 'col':
-- More --
`

**Comment by nybblr** [comment]
My bad, I pasted the `mes` output after removing my intentional issues =) I tweaked my config a bit more and got it working:

```vimscript
let s:eslint_path = system('PATH=$(npm bin):$PATH && which eslint')
let g:syntastic_javascript_eslint_exec = substitute(s:eslint_path, '^\n*\s*\(.\{-}\)\n*\s*$', '\1', '')

function! HasConfig(file, dir)
    return findfile(a:file, escape(a:dir, ' ') . ';') !=# ''
endfunction

autocmd BufNewFile,BufReadPre *.js  let b:syntastic_checkers =
    \ HasConfig('.eslintrc', expand('<amatch>:h')) ? ['eslint'] :
    \ HasConfig('.jshintrc', expand('<amatch>:h')) ? ['jshint'] :
    \     ['standard']
```

So it uses my local version of eslint (with the babel plugin) instead of global.

**Comment by lcd047** [comment]
> I overrode the eslint_exec to be the local eslint, but get the same issues using the globally installed eslint.

@nybblr Then please see #1692.  And next time please refrain from hijacking other people's thread, thank you.

**Comment by lcd047** [comment]
> syntastic: 0.561944: checker output: ['/usr/lib/node_modules/eslint/lib/config/config-file.js:332', '            throw e;', '            ^', '', '
Error: Cannot read config package: eslint-config-airbnb', 'Error: Cannot find module ''eslint-config-airbnb''', 

@segmentationfaulter Fix the problem, and try again.  Repeat until this no longer crashes:
```vim
:echo system('eslint -f compact app.js')
```

**Comment by segmentationfaulter** [comment]
thank you for the help, it was some issue with airbnb config file.
