### ISSUE TITLE
eslint not in available checkers

### ISSUE THREAD

**Issue by bigsley** [scrooloose/syntastic#1718]
Syntastic info yields:
```
Syntastic version: 3.7.0-93 (Vim 704, Darwin)
Info for filetype: javascript.jsx.components
Global mode: active
Filetype javascript.jsx.components is active
The current file will be checked automatically
Available checkers: javascript/jshint javascript/jsxhint
Currently enabled checkers: - 
```

However, eslint is in the path syntastic checks -- why isn't it getting picked up as an available checker?

**Comment by lcd047** [comment]
Please read the [first entry](https://github.com/scrooloose/syntastic#faqinfo) in the FAQ.  If that still doesn't ring any bell, please enable debugging and post a debug trace.
