### ISSUE TITLE
using package, some commands are not in the current script

### ISSUE THREAD

**Issue by xoit** [scrooloose/syntastic#1721]
I use this plugin and it helps a lot.

When I use package to include some existing functions.

the plugin report some command could not found. Can I avoid this?

**Comment by lcd047** [comment]
Please explain what you did, what did you expect to happen, and what happened instead.

**Comment by xoit** [comment]
I am using tcl to develop some automatic testbench.

And in tcl script, I also use package to include some existing procedures.

The plugin report an warning, said that, unknown command.
But all these command is in the package files.

What I want is to including these files, so that plugin could recognize the procedure and these warning's gone.

**Comment by lcd047** [comment]
Syntastic runs `nagelfar` to check TCL files.  You can enable debugging (see `:h syntastic-config-debug`) to find out the exact command run by syntastic.  You can then use `g:syntastic_tcl_nagelfar_args` to pass more options to `nagelfar`.  If you need help beyond that, you should probably ask on a TCL forum.  I know very little about TCL, and nothing about `nagelfar`.
