### ISSUE TITLE
Error while running jscs

### ISSUE THREAD

**Issue by robh-scribestar** [scrooloose/syntastic#1722]
This used to work but since updating syntastic (using vundle) when running jscs through syntastic it always displays: 
`Syntastic: warning: checker javascript/jscs: unrecognized error format`

I've tried updating jscs to the latest version (2.11) still no joy. When setting `syntastic_debug = 3` it is trying to run `jscs --no-colors --max-errors -1 --reporter json "path/to/file.js"` which returns `Reporter "null" doesn't exist` and if I get rid of the reporter option (by running on the command line) it outputs `'maxErrors' option requires number or null value`

Any ideas what I'm missing?

**Comment by lcd047** [comment]
Please post the debug log.

**Comment by robh-scribestar** [comment]
![image](https://cloud.githubusercontent.com/assets/8612512/13666415/5ad5553a-e6a9-11e5-8912-9b3b7a9b31b1.png)

**Comment by robh-scribestar** [comment]
checking out syntastic to commit dbd761006f67f409e51fc4e4ae87 has fixed it for me for the moment looks like 751afea9e0567fe2b613cddc62aa03d98bee4f43 introduced the problem I'm having

**Comment by lcd047** [comment]
Well then, please report the problem to jscs developers.  It has nothing to do with syntastic.

> checking out syntastic to commit  dbd7610  has fixed it for me for the moment

Sadly, the older version was broken in other ways.  Syntastic can't really parse XML, but it can parse JSON.

> looks like 751afea  introduced the problem I'm having

No.  The problem you're having is jscs not behaving as advertised.  Fix the crash, and syntastic should (re-)start working. _shrug_

**Comment by willsALMANJ** [comment]
I don't know if this will help anyone else, but I was having this problem with `jscs`. I tried specifying the full path to the json report file (`lib/reporters/json.js` in the `jscs` install directory) and that worked. After that, `jscs -r json` started working (i.e. without the full path) and so worked with Syntastic. I'm not sure why.
