### ISSUE TITLE
Add an option to specify .yamllint config file location

### ISSUE THREAD

**Issue by vaijab** [scrooloose/syntastic#1723]
It would be great if there was a way to specify `yamllint -c ${HOME}/.yamllint` configuration file location. The way yamllint works is that it expects to find `.yamllint` file in current directory, otherwise it just uses default configuration, unless `-c /path/to/yamllint` is specified.

**Comment by lcd047** [comment]
Try this:
```vim
let g:syntastic_yaml_yamllint_args = '-c ' . shellescape($HOME . '/.yamllint')
```

**Comment by vaijab** [comment]
@lcd047 awesome! Thanks.
