### ISSUE TITLE
syntastic balloon_eval

### ISSUE THREAD

**Issue by lanox** [scrooloose/syntastic#1724]
Hi 

Sorry this potential could be silly question, but does balloon_eval work in terminal ?
I was reading http://vimdoc.sourceforge.net/htmldoc/debugger.html#balloon-eval but doesn't mention anything about gvim ro vim in terminal.

I was trying to install it with brew reinstall vim --with-balloon_eval but it will not install and gives me no errors.

Thanks

**Comment by lcd047** [comment]
> does balloon_eval work in terminal ?

No, balloons are tooltips implemented and handled by GUIs, not by Vim itself.  This is mentioned in `:h +balloon_eval`.
