### ISSUE TITLE
Compiling Conditional Go files

### ISSUE THREAD

**Issue by dadgar** [scrooloose/syntastic#1727]
Go lets you have compile flags or suffixes on files that gate on what platform they are built on. You can see a description [here](http://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool).

You can force the go tool chain to compile specific OS/Architecture using environment variables:
`GOOS=windows go build foo_windows.go` would compile this even if you are on linux or a mac. It would be nice to incorporate this as it means when you are developing on a project that targets many operating systems, syntactic is disabled on certain files essentially. Would be cool for Neomake as well

**Comment by lcd047** [comment]
If go were an usual checker, you would just set `exe` and `fname` and all would be fine.  Sadly, go is at best a weird checker.  For the environment variable, it will probably work if you `export` it from your shell's profile:
```sh
GOOS=windows
export GOOS
```
For the modified filename you could try something like this:
```vim
autocmd BufRead,BufNewFile *.go
    \ let b:syntastic_go_go_build_args=expand('<amatch>:p:r', 1) . '_windows.go'
```
I can't comment on Neomake.
