### ISSUE TITLE
Pylint import errors

### ISSUE THREAD

**Issue by carlitux** [scrooloose/syntastic#1732]
Pylint raises errors when can't import a package, and most of the packages there are on virtualenv. There is a way to integrate with https://github.com/jmcantrell/vim-virtualenv?

**Comment by lcd047** [comment]
This has been discussed in the past, and the conclusion was syntastic can't work with vim-virtualenv, because of a limitation of vim-virtualenv (or perhaps a limitation of Vim).  However, you can just install pylint in virtualenv, and run Vim from virtualenv.
