### ISSUE TITLE
Support &. with Ruby 2.3

### ISSUE THREAD

**Issue by sachin21** [scrooloose/syntastic#1735]
I encountered syntax error when executed `:w` with syntastic but my syntax is all is well because I executed ruby -c target.rb and it returned `Syntax OK` 
The cause of the error is `obj&.foo`.
`&.` is feature of ruby2.3 and it was released. https://bugs.ruby-lang.org/issues/11537

### My environment is
```
vim: VIM - Vi IMproved 7.4
syntastic: 3.7.0
ruby: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
```

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, run the checker, then run `:mes`, and look for `makeprg` in the output.  Run that command in a terminal, then run it from `system()` inside Vim.  See also the output of `:echo syntastic#util#system('echo "$PATH"')`.

**Comment by sachin21** [comment]
I see. :smile: Thanks.
