### ISSUE TITLE
ESlint is available but won't enable

### ISSUE THREAD

**Issue by WilsonChiang** [scrooloose/syntastic#1736]
`:SyntasticInfo` returns the following

```
Syntastic version: 3.7.0-105 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: eslint flow
Currently enabled checkers: -
```

I have eslint enabled as follows:

```let g:syntastic_javascript_checkers = ['eslint']```

Seems to work fine if i run it manually, but it won't automatically enable eslint for my js files.

ie, `:SyntasticCheck eslint` works fine.

**Comment by lcd047** [comment]
Do you have another plugin that can disable syntastic checkers (f.i. Eclim)?  Can you reproduce the problem with all other plugins disabled?

**Comment by VitorHP** [comment]
I'm facing a similar issue. If I open vim directly on a javascript file, eslint does not run and I get the following result from `SyntasticInfo javascript`:

> Syntastic version: 3.6.0-67 (Vim 704, Linux)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
Available checkers: -
Currently enabled checkers: -

If before entering a javascript file, I run `SyntasticInfo javascript`, then it shows eslint both available and enabled as following:

> Syntastic version: 3.6.0-67 (Vim 704, Linux)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
Available checker: eslint
Currently enabled checker: eslint

after that, if I enter a javascript file, eslint runs as expected.

this is the config I have in my .vimrc for syntastic:

```vim
let s:eslint_path = system('PATH=$(npm bin):$PATH && which eslint')
let b:syntastic_javascript_eslint_exec = substitute(s:eslint_path, '^\n*\s*\(.\{-}\)\n*\s*$', '\1', '')
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
```

**Comment by lcd047** [comment]
@VitorHP Please read `:h b:`, then think for a minute what "current buffer" is at the time vimrc is executed.  If you still have questions after that, please explain what you're trying to do, and why the straightforward way doesn't work for you:
```vim
let g:syntastic_javascript_eslint_exec = '/path/to/eslint'
```

**Comment by VitorHP** [comment]
@lcd047 Alright. Problem solved. Kudos for the way of letting me discover the problem by myself.
