### ISSUE TITLE
Can't enable available checker?

### ISSUE THREAD

**Issue by DavidAwad** [scrooloose/syntastic#1744]
Not sure why but I can't get this to work. 
I have pep8 installed and in the `$PATH` but syntastic won't apply checks? It's available but it's not running it to report syntax errors. 

This is the relevant part of my vimrc

```vimscript
let g:syntastic_python_checkers = ['pep8']
let g:syntastic_c_checkers = ['gcc', 'make'] 
let g:syntastic_ruby_exec = '~/.rvm/rubies/ruby-2.0.0-p0/bin/ruby'
```

Here's the relevant portion of `:SyntasticInfo`
```
Syntastic version: 3.6.0-57 (Vim 704, Darwin)
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
Available checkers: pep8 python
Currently enabled checkers: -
```

running `:SyntasticCheck` doesn't do anything either. I feel like it's a simple fix but I don't see what it is. Thanks!

**Comment by lcd047** [comment]
Do you have other plugins that mess with syntastic configuration, such as Eclim or YouCompleteMe?  Your version of syntastic is pretty old, more recent versions can detect that kind of problems (well, most of them) and warn you about it.

**Comment by DavidAwad** [comment]
okay well at least I'm not crazy. let me try updating it and get back to you

**Comment by DavidAwad** [comment]
Alright, running `:PluginUpdate` isn't getting me any progress, same problem. However I do have YCM installed and working. I know the two might conflict. 

How can I force an update of syntastic to see the updated error messages? (because tbh I love syntastic too much to let it go)

**Comment by lcd047** [comment]
> How can I force an update of syntastic to see the updated error messages?

`:PluginUpdate` sounds like a Vundle command.  I'm afraid my knowledge about Vundle is mostly theoretical, so perhaps ask on some Vundle-related forum?  Syntastic itself doesn't really care how you install it.

**Comment by Someguy123** [comment]
@DavidAwad did you ever get this fixed? I'm having the same problem with ESLint

**Comment by lcd047** [comment]
@Someguy123 Please open a __new__ issue.  Explain what you did, what did you expect to happen, and what happened instead.

**Comment by Someguy123** [comment]
lcd047: Turns out I'm an idiot.

I had `js_checkers` instead of `javascript_checkers` (Got confused by my previous attempt at using `jsx_checkers`, which didn't work so I had to switch to ESLint)
