### ISSUE TITLE
Can't disable echo to command window

### ISSUE THREAD

**Issue by MichielDerhaeg** [scrooloose/syntastic#1746]
If an error is takes up 2 lines or more, vim requires me to press ENTER to continue
every time i move on a line with an error, which is extremely annoying.
So i put ``let g:syntastic_echo_current_error = 0`` in my vimrc but it doesn't have any effect.
Am i doing something wrong?

**Comment by lcd047** [comment]
Syntastic doesn't normally produce the kind of error messages that may require you to press ENTER, and when it does, it has no way to control them.  Can you reproduce the problem with syntastic disabled?  Can you reproduce it with syntastic enabled and all other plugins disabled?

**Comment by MichielDerhaeg** [comment]
![ss](https://cloud.githubusercontent.com/assets/6206753/14496097/5c84b822-0192-11e6-9379-3a0ba74dcf03.png)
It still happens when i disable everything except syntastic, i even commented out everything in my vimrc.

**Comment by lcd047** [comment]
Please open your test file, run `:SyntasticInfo`, and post the output.

**Comment by MichielDerhaeg** [comment]
```
Syntastic version: 3.7.0-118 (Vim 704, Linux)
Info for filetype: haskell
Global mode: active
Filetype haskell is active
The current file will be checked automatically
Available checkers: hdevtools hlint
Currently enabled checker: hdevtools
```

**Comment by lcd047** [comment]
Ok, now please open the same file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output.

**Comment by MichielDerhaeg** [comment]
```
syntastic: 19.957531: UpdateErrors (auto): default checkers
syntastic: 19.958124: CacheErrors: default checkers
syntastic: 19.959444: g:syntastic_aggregate_errors = 0
syntastic: 19.959804: getcwd() = '/home/michiel'
syntastic: 19.960459: CacheErrors: Invoking checker: haskell/hdevtools
syntastic: 19.961807: SyntasticMake: called with options: {'postprocess': ['compressWhitespace'], 'err
orformat': '%-Z %#,%W%f:%l:%v: Warning: %m,%W%f:%l:%v: Warning:,%E%f:%l:%v: %m,%E%>%f:%l:%v:,%+C  %#%m
,%W%>%f:%l:%v:,%+C  %#%tarning: %m,', 'defaults': {'vcol': 1}, 'makeprg': 'hdevtools check /home/michi
el/test.hs'}
syntastic: 20.003964: checker output: ['/home/michiel/test.hs:4:12:', '    Couldn''t match expected ty
pe ‘Int’ with actual type ‘[Char]’', '    In the expression: "hello"', '    In an equation for ‘someFu
nc’: someFunc = "hello"', '']
syntastic: 20.043547: raw loclist: [{'lnum': 4, 'bufnr': 1, 'col': 12, 'valid': 1, 'vcol': 0, 'nr': -1
, 'type': 'E', 'pattern': '', 'text': '^@    Couldn''t match expected type ‘Int’ with actual type ‘[Ch
ar]’^@    In the expression: "hello"^@    In an equation for ‘someFunc’: someFunc = "hello"'}]
syntastic: 20.043985: postprocess: [{'lnum': 4, 'bufnr': 1, 'col': 12, 'valid': 1, 'vcol': 1, 'nr': -1
, 'type': 'E', 'pattern': '', 'text': 'Couldn''t match expected type ‘Int’ with actual type ‘[Char]’ I
n the expression: "hello" In an equation for ‘someFunc’: someFunc = "hello"'}]
syntastic: 20.044195: getLocList: checker haskell/hdevtools returned 1
syntastic: 20.044349: haskell/hdevtools raw: [{'lnum': 4, 'bufnr': 1, 'col': 12, 'valid': 1, 'vcol': 1
, 'nr': -1, 'type': 'E', 'pattern': '', 'text': 'Couldn''t match expected type ‘Int’ with actual type
‘[Char]’ In the expression: "hello" In an equation for ‘someFunc’: someFunc = "hello"'}]
syntastic: 20.044595: quiet_messages filter: {}
syntastic: 20.045200: aggregated: {'_sorted': 0, '_name': 'hdevtools (haskell)', '_owner': 1, '_column
s': 1, '_rawLoclist': [{'lnum': 4, 'bufnr': 1, 'col': 12, 'valid': 1, 'vcol': 1, 'nr': -1, 'type': 'E'
, 'pattern': '', 'text': 'Couldn''t match expected type ‘Int’ with actual type ‘[Char]’ In the express
ion: "hello" In an equation for ‘someFunc’: someFunc = "hello"'}]}
```

**Comment by lcd047** [comment]
Ok, please open the file again, and post the output of:
```vim
echo syntastic#util#system('hdevtools check /home/michiel/test.hs')
```

**Comment by MichielDerhaeg** [comment]
```
/home/michiel/test.hs:4:12:
    Couldn't match expected type ‘Int’ with actual type ‘[Char]’
    In the expression: "hello"
    In an equation for ‘someFunc’: someFunc = "hello"
```

**Comment by lcd047** [comment]
Well I'm afraid I still don't see how your error message can possibly be produced by syntastic.  For one, message `loc - (1 of 1)` is not printed by either syntastic, Vim core, or hdevtools.  The most likely explanation is that disabling everything but syntastic is not as thorough as you seem to believe. :)

Please disable everything except syntastic again, open your test file, run the checker, run `:verbose set rtp` and post the output.  Then run `:autocmd` and post the output (warning: lots of junk).

**Comment by MichielDerhaeg** [comment]
Will do.

I've noticed that enabling either of these two options causes the issue.
```vim
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
```
If i disable both, it will no longer ask me to press ENTER but still show the message.

**Comment by lcd047** [comment]
What version of Vim are you running?

**Comment by MichielDerhaeg** [comment]
``:verbose set rtp`` helped my find the issue, I installed eclim systemwide with my package manager.
Uninstalling this has solved my issue. Eclim was the culprit.

**Comment by MichielDerhaeg** [comment]
Thank's for the help :)
