### ISSUE TITLE
gjslint javascript checker uses `--nodebug_indentation` flag by default?

### ISSUE THREAD

**Issue by hoylemd** [scrooloose/syntastic#1747]
I found this was causing a difference between the errors reported by syntastic and those by my CI server, even with the same configuration file.  Isn't it too prescriptive to assume that all users want this flag on by default?

**Comment by lcd047** [comment]
The move to `args_before` and `args_after` happened two years ago, and you're the first to complain about it. :) Please see 40b1295.
