### ISSUE TITLE
scalastyle being quiet, not showing any warnings

### ISSUE THREAD

**Issue by shichao-an** [scrooloose/syntastic#1749]
I installed scalastyle and change .vimrc like this:

```
let g:syntastic_scala_scalastyle_jar = '/usr/local/Cellar/scalastyle/0.8.0/libexec/scalastyle_2.11-0.8.0-batch.jar'
let g:syntastic_scala_scalastyle_config_file = '/usr/local/etc/scalastyle_config.xml'
```

However, when I updated a file, there was no output in the location window. Running the jar file from the command-line did show a lot of warnings. So I look at the source code at [syntax_checkers/scala/scalastyle.vim](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/scala/scalastyle.vim#L46), and found it is set to "quite mode".

```vim
    let makeprg = self.makeprgBuild({
        \ 'exe_after': ['-jar', expand(g:syntastic_scala_scalastyle_jar, 1)],
        \ 'args_before': ['-q', 'true', '-c', expand(g:syntastic_scala_scalastyle_config_file, 1)] })
```
Removing `'-q', 'true'` will work.

Is there any reason why it is set to this? If it's not set to this on purpose, can we remove this quiet option so that I can get the warnings in the location window?

**Comment by lcd047** [comment]
> Is there any reason why it is set to this?

Not really.  Congratulations, you're the first to use this checker in the past year or so. :) Please see commit 3f320d0.

**Comment by shichao-an** [comment]
Thanks!
