### ISSUE TITLE
Flow is slow... Can we use flow check-contents instead?

### ISSUE THREAD

**Issue by tribou** [scrooloose/syntastic#1754]
Using the flow checker is very slow in the current implementation.

```
syntastic: 732.390310: CacheErrors: Invoking checker: javascript/flow
syntastic: 732.391940: SyntasticMake: called with options: {'preprocess': 'flow', 'error
format': '%f:%l:%c:%n: %m,%f:%l:%c: %m', 'defaults': {'type': 'E'}, 'makeprg': 'flow che
ck --show-all-errors --json helpers/file.js'}
syntastic: 737.981168: getLocList: checker javascript/flow returned 0
```

```bash
time flow check --show-all-errors --json helpers/file.js
{"flowVersion":"0.23.0","errors":[],"passed":true}
real	0m4.852s # <--- ouch
user	0m1.944s
sys	0m0.952s
```

I noticed that it had to be changed back in e39f636e288fdf5b8adf0bb51babd0d1a0f7baa4 because of a bug.  However, I'm hoping we can find a better solution that may be faster.

My initial thought is that we could somehow pipe the contents of the current file into `flow check-contents` which seems to be much faster.  I did notice that the initial call to `flow check-contents` had to initialize the flow server (which I'm guessing is the reason for increased speed in subsequent calls), and I didn't know if that would cause an issue for syntastic.

```bash
time cat helpers/file.js | flow check-contents --show-all-errors --json
Launching Flow server for /Users/tribou/dev/project
Spawned flow server (child pid=9858)
Logs will go to /private/tmp/flow/zSUserszStribouzSdevzSproject.log
{"flowVersion":"0.23.0","errors":[],"passed":true}
real	0m4.935s
user	0m0.115s
sys	0m0.059s
```

Subsequent calls like this complete very quickly:

```bash
time cat helpers/file.js | flow check-contents --show-all-errors --json
{"flowVersion":"0.23.0","errors":[],"passed":true}
real	0m0.153s
user	0m0.094s
sys	0m0.036s
```

My vimscript-fu is weak, but would there be an easy way to accomplish this method of flow checking?

```
Syntastic version: 3.7.0-126 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: eslint flow
Currently enabled checkers: eslint flow
```

**Comment by lcd047** [comment]
Please refer to #1649.  If the problem has been fixed in `flow` and you can point me to a (released) version that includes the fix, I'll make the necessary adjustments to syntastic.  Otherwise I'd rather stay with `flow check`, which has proved to be safe.

However, you can set `g:syntastic_javascript_flow_exe` to `flow check-contents` (or whatever) if you want to play with it:
```vim
let g:syntastic_javascript_flow_exe = 'flow check-contents'
```
The checker has been written the way it is specifically to allow people to do that.  Just don't complain here if the problem hasn't been fixed and it bites you. _shrug_

**Comment by tribou** [comment]
@lcd047 I think flow has fixed the original issue.  After a few basic tests, this appears to work now:

flow version: `0.31.0`

```vim
let g:syntastic_javascript_checkers = ['eslint', 'flow']
let g:syntastic_javascript_flow_exe = 'flow'
```

After the flow server initialization on the first check (still unfortunately VERY slow), the subsequent checks now are incredibly fast.

**Comment by lcd047** [comment]
Nope, still the same problem:
```
Started a new flow server: -{"flowVersion":"0.31.0","errors":[],"passed":true}
```

**Comment by tribou** [comment]
It looks like that only happens on the first save.  After the first save on a new project directory (flow initialization), I'm not getting any errors when using the flow checking upon save with Syntastic.  For me, that's a much better experience than having it run `flow check` on each save which is unusable IMO.

Is there an easy way to run `flow start` in the background upon opening vim in a dir with a `.flowconfig` and `flow stop` on closing vim?  (The `flow stop` needs to happen anyway in the current state as it leaks flow processes running in the background upon closing vim.)

**Comment by lcd047** [comment]
Please refer to #1649 for the description of the problem, and to my first message above for a workaround.  Nothing has changed in the mean time from the point of view of syntastic.

**Comment by tribou** [comment]
Would the [`--quiet` option](https://github.com/scrooloose/syntastic/issues/1649#issuecomment-180066192) satisfy this?

**Comment by lcd047** [comment]
I believe I already answered that question, in the message following the one you quoted.

**Comment by tribou** [comment]
You said "it might be useful for other reasons." Could you please clarify?

**Comment by lcd047** [comment]
As I said:

> A `--quiet` option might be useful for other reasons, but for the purpose of syntastic, a "not a `tty`" test would be enough.

A "not a `tty`" test would solve the problem.  A `--quiet` option would also solve the problem.  A `--quiet` option might also be useful for other things that might need to parse the output of `flow` in a meaningful way.

**Comment by tribou** [comment]
Thanks!  Submitted facebook/flow#2329 to track this.
