### ISSUE TITLE
CheckStyle warnings not showing in gutter

### ISSUE THREAD

**Issue by Qix-** [scrooloose/syntastic#1760]
I've been pulling my hair out over this for about 3 hours now, trying to debug it. I can't for the life of me figure it out.

I've disabled all plugins other than syntastic.

I'm trying to use CheckStyle with some java and while `:SyntasticCheck` shows the location list when warnings occur, nothing shows up in the gutter.

I know other languages work since flake8 (pyflakes) shows issues in the gutter just fine; it's just this checker.

```
:let g:syntastic_debug = 1
:SyntasticCheck
:mes
```
```
syntastic: 390.561257: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &sh
ellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 390.562000: UpdateErrors: default checkers
syntastic: 390.562283: CacheErrors: default checkers
syntastic: 390.563087: g:syntastic_aggregate_errors = 0
syntastic: 390.563411: getcwd() = '/src/snip'
syntastic: 390.563893: CacheErrors: Invoking checker: java/checkstyle
syntastic: 390.564862: SyntasticMake: called with options: {'subtype': 'Style', 'preprocess': 'checkstyle', 'errorformat': '%f:%t:%l:%c:%m'
, 'makeprg': 'java -cp /Users/junon/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclim.jdt_2.5.0/lib/checkstyle-6.17-all.jar com.p
uppycrawl.tools.checkstyle.Main -c .checkstyle.xml -f xml /src/snip/src/com/snip/snip/snip/Main
.java'}
syntastic: 391.079312: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &sh
ellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 391.079789: UpdateErrors (auto): default checkers
syntastic: 391.080001: _skip_file: skipping checks
syntastic: 391.083282: getLocList: checker java/checkstyle returned 1
syntastic: 391.085801: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &sh
ellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 391.086299: UpdateErrors (auto): default checkers
syntastic: 391.086490: _skip_file: skipping checks
syntastic: 391.089523: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &sh
ellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 391.089985: UpdateErrors (auto): default checkers
syntastic: 391.090165: _skip_file: skipping checks
syntastic: 391.092202: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &sh
ellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 391.092634: UpdateErrors (auto): default checkers
syntastic: 391.092812: _skip_file: skipping checks
```

As mentioned earlier, warnings show up in the location list window just fine - it's clear it's running CheckStyle. Line numbers and expected warnings/errors all check out. However the gutter just isn't showing them and this is a huge downer since I rely on that for quick development loops.

---

The problem gets even worse :(

Even in active mode, the loc list isn't brought up when the buffer is saved to disk. Manually issuing `:SyntasticCheck` performs the check correctly, but the second the buffer is saved again the loc list clears itself.

This is nearly unusable and the syntastic source is so cryptic I can't figure out how I'd even begin to fix it. One thing I noticed is that `errorformat` matches a bunch of colon delimited information but the output format of the command is `-f xml`. Not entirely sure how syntastic pulls in error information but it just doesn't seem right at all.

Here are the relevant pieces of configuration:

```viml
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_python_flake8_args = "--ignore=E501"

let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = ' -std=c++11 -stdlib=libc++'
let g:syntastic_cpp_check_header = 1
let g:syntastic_cpp_clang_tidy_post_args = ""

let g:syntastic_java_checker = "checkstyle"
let g:syntastic_java_checkstyle_classpath = "/Users/junon/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclim.jdt_2.5.0/lib/checkstyle-6.17-all.jar"
let g:syntastic_java_checkstyle_conf_file = ".checkstyle.xml"
```

Even removining the `auto_loc_list` and `always_populate_loc_list` entries above, the result is still the same, though sans loc list.

`check_on_wq` had absolutely no effect.

---

So I poked around a bit and noticed this:

```
:SyntasticInfo
```
```
Syntastic version: 3.7.0-130 (Vim 704, Darwin)
Info for filetype: java
Global mode: active
Passive filetype: java
Filetype java is passive
The current file will not be checked automatically
Available checkers: checkstyle javac
Currently enabled checker: checkstyle
Checkers for filetype java possibly disabled by Eclim
```

- Why is Java passive to begin with?
- Why would Eclim be disabling this check?

---

EDIT: alright, the following line enabled checks upon `:wq`:

```
let g:EclimFileTypeValidate = 0
```

However still no gutter indicators.

I'd like to mention I'm turning to syntastic to do this since CheckStyle silently fails in eclim and nothing ever outputs back in Vim.

Side note: getting the following super annoying warning upon opening java files:

```
syntastic: warning: variable g:syntastic_java_checker is deprecated
```

What other choice do I have? It defaults to `javac` which is useless to me.

---

More potentially helpful information

```
g:syntastic_enable_signs #1
g:syntastic_enable_balloons #1
g:syntastic_enable_highlighting #1
```

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output.

> `let g:syntastic_java_checkstyle_conf_file = ".checkstyle.xml"`

You probably need a full path here, or otherwise make sure you have a `.checkstyle.xml` in (Vim's idea of) current directory when you run the checks.  Use an `autocmd` if you need to set it per project.

**Comment by Qix-** [comment]
@lcd047 I did. Check first post. Also that parameter is fine; as I mentioned it's linting correctly.

**Comment by lcd047** [comment]
`3 != 1`

**Comment by Qix-** [comment]
Aha, sorry. 

```
"src/com/snip/snip/snip/Main.java" 23L, 358C written
syntastic: 10753.773953: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 10753.775900: UpdateErrors (auto): default checkers
syntastic: 10753.776947: CacheErrors: default checkers
syntastic: 10753.779392: g:syntastic_aggregate_errors = 0
syntastic: 10753.780041: getcwd() = '/src/snip'
syntastic: 10753.781334: CacheErrors: Invoking checker: java/checkstyle
syntastic: 10753.784192: SyntasticMake: called with options: {'subtype': 'Style', 'preprocess': 'checkstyle', 'errorformat': '%f:%t:%l:%c:%m', 'makeprg': 'java -cp /Users/junon/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclim.jdt_2.5.0/lib/checkstyle-6.17-all.jar com.p
uppycrawl.tools.checkstyle.Main -c .checkstyle.xml -f xml /src/snip/src/com/snip/snip/snip/Main.java'}
syntastic: 10759.641947: checker output: ['<?xml version="1.0" encoding="UTF-8"?>', '<checkstyle version="6.17">', '<file name="/src/snip/src/com/snip/snip/snip/Main.java">', '<error line="7" column="24" severity="error" message="snip" source="com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenTextCheck"/>', '</file>', '</checkstyle>', 'Checkstyle ends with 1 errors.', '']
syntastic: 10759.644552: preprocess: ['/src/snip/src/com/snip/snip/snip/Main.java:e:7:24:snip']
syntastic: 10759.778448: raw loclist: [{'lnum': 7, 'bufnr': 1, 'col': 24, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'e', 'pattern': '', 'text': 'snip'}]
syntastic: 10759.784412: getLocList: checker java/checkstyle returned 1
syntastic: 10759.784987: java/checkstyle raw: [{'lnum': 7, 'bufnr': 1, 'col': 24, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'e', 'pattern': '', 'subtype': 'Style', 'text': 'snip'}]
syntastic: 10759.786220: quiet_messages filter: {}
syntastic: 10759.787842: aggregated: {'_sorted': 0, '_name': 'checkstyle (java)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 7, 'bufnr': 1, 'col': 24, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'e', 'pattern': '', 'subtype': 'Style', 'text': 'snip!'}]}
```

**Comment by lcd047** [comment]
The logs show syntastic working just fine.  What happens if you run `:Errors` after running the checks?

**Comment by Qix-** [comment]
@lcd047 Woah, weird. Just running `:Errors` fixed it.

<img width="187" alt="screen shot 2016-05-03 at 12 55 14 am" src="https://cloud.githubusercontent.com/assets/885648/14977545/a100a6be-10c9-11e6-9314-19bc04bbdd14.png">

**Comment by lcd047** [comment]
Then you have another plugin that messes up with syntastic's results.  Can you reproduce the problem with __all__ other plugins disabled?

**Comment by Qix-** [comment]
@lcd047 yes - the entirety of the first post was written with *just* syntastic enabled.

> I've disabled all plugins other than syntastic.

**Comment by lcd047** [comment]
Nope, you still had Eclim.

**Comment by Qix-** [comment]
@lcd047 Eclim isn't a plugin. That's a jarfile that is invoked as an external linter by syntastic.

**Comment by lcd047** [comment]
> `let g:syntastic_java_checker = "checkstyle"`

By the way, this should be
```vim
let g:syntastic_java_checkers = [ "checkstyle" ]
```
The `*_checker` form hasn't been supported in a few years.

**Comment by Qix-** [comment]
@lcd047 :+1: thank you so much
