### ISSUE TITLE
Syntastic making files everytime a file is opened

### ISSUE THREAD

**Issue by fourblank** [scrooloose/syntastic#1761]
This isn't much of an issue but rather my lack of knowledge. In my vimrc, I have check_on_open = 1 with syntastic_c_checkers set to ['gcc' , 'make']. Is there a way to stop syntastic from making my first target within makefile everytime I open a file?

**Comment by lcd047** [comment]
The `make` checker runs `make -sk`, thus no, it isn't possible.
