### ISSUE TITLE
Disable syntastic in modeline?

### ISSUE THREAD

**Issue by jasontibbitts** [scrooloose/syntastic#1764]
I hate to ask a question here, but I just can't figure it out.

I suspect the answer is "it's not possible", but I have a few files which I know will have errors and so syntastic shouldn't check them.  The filetype is correct I would still like them to be highlighted and indented as normal, I just don't want syntastic to yell at me when I open them.

Unfortunately you can't set syntastic_skip_checks=1 in a modeline.  I guess technically syntastic could look through the file for some magic disabling sigil at the end of the modeline or something, but I don't think anything like that currently exists.

**Comment by lcd047** [comment]
You can't do it with a `modeline`, but you can achieve essentially the same thing with an `autocmd`.  Something like this:
```vim
let stfu = [
    \ '/path/to/file1',
    \ '/path/to/file2',
    \ '/path/to/file3' ]
autocmd BufReadPre * let b:syntastic_skip_checks = index(stfu, expand('<amatch>', 1)) >= 0
```
Depending on your version of Vim, you might need a `BufReadPost` instead of `BufReadPre` (and then you may or may not be able to disable syntastic in a `check_on_open`).

If you prefer to base this on some kind of flag in the files rather than on filenames you could populate `stfu` with a `systemlist()` calling a script like this:
```sh
find /some/path -type f -name '*.py' | \
while read -r fname; do
    tail -5 "$fname" | grep -qw some_keyword && printf '%s\n' "$fname"
done
```
Other approaches are possible too, but they aren't necessarily better.

**Comment by jasontibbitts** [comment]
Yeah, that's the only thing I could think of as well.  Unfortunately that's just really suboptimal.  An autocmd that actually looks in the file for a sigil is probably the best way for me to go.  Then I could do:
```
# vim: set filetype=spec: disable_syntastic
```
But I'll have to learn a while lot more about vimscript before I get to the point where I can write that.

**Comment by lcd047** [comment]
Well, you can do it like this:
```vim
function! GetSigil() 
    let end = line('$') 
    return end >= 1 && match(getline( max([end - 5, 1]), end ), '\m^# vim:.*: disable_syntastic\>') >= 0
endfunction

augroup syntastic_haters
    autocmd!
    autocmd BufReadPost * let b:syntastic_skip_checks = GetSigil()
augroup END
```
But this won't work if you have `syntastic_check_on_open` set, since the `autocmd` gets to run too late.

Or you can do it like this:
```vim
augroup syntastic_haters
    autocmd!
    autocmd BufReadPre *
        \ call system("tail -5 " . shellescape(expand('<amatch>', 1)) .
        \     " | grep -q '^# vim:.*: disable_syntastic'") |
        \ let b:syntastic_skip_checks = !v:shell_error
augroup END
```
But this runs an an external command for each and every file open.  Like I said: not necessarily better. _shrug_
