### ISSUE TITLE
rst2pseudoxml not showing in available checkers

### ISSUE THREAD

**Issue by shichao-an** [scrooloose/syntastic#1765]
When editing a rst file, `SyntasticInfo` shows:

```
Syntastic version: 3.7.0-133 (Vim 704, Darwin)
Info for filetype: rst
Global mode: active
Filetype rst is active
The current file will be checked automatically
Available checkers: rstcheck sphinx
Currently enabled checkers: -                      
```

Setting `let g:syntastic_rst_checkers = ['rst2pseudoxml']` does not work.

**Comment by lcd047** [comment]
Do you have `rst2pseudoxml` installed?

**Comment by shichao-an** [comment]
Yes. I have `rst2pseudoxml.py` installed.

**Comment by lcd047** [comment]
Please run this from Vim and post the output:
```vim
:echo executable('rst2pseudoxml.py')
```

**Comment by shichao-an** [comment]
It shows "1".

It comes with the docutils Python package and is located at `/usr/local/bin/rst2pseudoxml.py`.

**Comment by lcd047** [comment]
Please upgrade syntastic to d69c878, then open your test file, set `g:syntastic_debug` to 33, run `:SyntasticInfo`, and post the output.

**Comment by shichao-an** [comment]
```
Syntastic version: 3.7.0-134 (Vim 704, Darwin)
Info for filetype: rst
Global mode: active
Filetype rst is active
The current file will be checked automatically
Available checkers: rstcheck sphinx
Currently enabled checkers: -
```

**Comment by lcd047** [comment]
You need to set `g:syntastic_debug`  to 33 before running `:SyntasticInfo`.  The output is useless otherwise.

**Comment by shichao-an** [comment]
Yes, I did run `let g:syntastic_debug=33`. And `let g:syntastic_debug` shows `g:syntastic_debug    #33`.

**Comment by lcd047** [comment]
Please quit Vim, then open your test file again, run `:SyntasticInfo` (ignore the output), then run `:verbose scriptnames` and post the output.

**Comment by shichao-an** [comment]
I think I found the problem. when I run `:verbose scriptnames`, I found there is .vimrc in my project directory which contains a line `let g:loaded_syntastic_rst_rst2pseudoxml_checker = 0` (I totally forgot that I created this file). I remove that file, and it works!. Sorry about that!

BTW, now I set `let g:syntastic_debug=33` and run `:SyntasticInfo` it shows:

```
Syntastic version: 3.7.0-134 (Vim 704, Darwin)
Info for filetype: rst
Global mode: active
Filetype rst is active
The current file will be checked automatically
Available checkers: rst2pseudoxml rstcheck sphinx
Currently enabled checker: rst2pseudoxml  
```
