### ISSUE TITLE
Recent vim changes seem to make loclist jumps go to wrong line

### ISSUE THREAD

**Issue by novas0x2a** [scrooloose/syntastic#1768]
Sorry that this bug isn't great, I'm having a hard time tracking down what could have broken this. What I know so far is if I upgrade from vim 7.4.1583 to 7.4.1821, the loclist error references end up pointing to the wrong line (so hitting enter on them goes to the wrong line). This is with 
```vimscript
let g:syntastic_check_on_open=0
let g:syntastic_auto_loc_list=1
let g:syntastic_python_checkers=['pylint']
let g:syntastic_enable_highlighting = 1
```
And specifically with the pylint checker, although I suspect that doesn't matter. [Here's](http://ftp.vim.org/pub/vim/patches/7.4/README) what changed between, there are a few quickfix/loclist-related changes, but I'm not familiar enough with the mechanism there to be more helpful :\

**Comment by novas0x2a** [comment]
As I bisect, I realized that I was missing what was actually happening- when i hit enter on the line, i get the error message `E926: Current location list was changed` and the cursor just doesn't move (i.e. it's not that the locline points to the wrong line).

I'm currently bisecting, so hopefully i'll have an exact patch reference soon.

**Comment by novas0x2a** [comment]
Okay, bisection complete. [7.4.1640](http://ftp.vim.org/pub/vim/patches/7.4/7.4.1640) Is the first one that breaks.

**Comment by novas0x2a** [comment]
.... Okay, apparently I was running an ancient version of syntastic. Running syntastic master, this is no longer a problem.

**Comment by lcd047** [comment]
> Okay, bisection complete. [7.4.1640](http://ftp.vim.org/pub/vim/patches/7.4/7.4.1640) Is the first one that breaks.

Yeah, I could have saved you the time of doing the bisection and point you to #1127.

> Running syntastic master, this is no longer a problem.

It's still a problem, it just doesn't happen as often.  Vim's API doesn't permit avoiding all problematic cases.

Vim patch 1640 is, well, not that great.  I suggested a much simpler approach that would have avoided the problem in the first place, but it looks like nobody has bothered to take the time to understand what I'm saying.  I'll probably have to drop `check_on_open` when running the forthcoming Vim 8. _shrug_
