### ISSUE TITLE
Using errorformat and makeprg from another plugin

### ISSUE THREAD

**Issue by camilstaps** [scrooloose/syntastic#1771]
There is a vim-clean plugin with an errorformat and makeprg for the [Clean](http://clean.cs.ru.nl/Clean) programming language. What would be the steps to take to use the same errorformat and makeprg with syntastic?

It is obviously possible to copy the code, but that wouldn't be maintainable.

The compiler plugin in vim-clean I'm referring to is here: https://github.com/timjs/vim-clean/blob/timjs-syntax/compiler/cpm.vim

**Comment by lcd047** [comment]
> What would be the steps to take to use the same errorformat and makeprg with syntastic?

Syntastic doesn't use `makeprg`.  But you could still read the [checker guide](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide), write a checker for syntastic using a similar command line than `vim-clean`, and re-use the `errorformat`.

> It is obviously possible to copy the code, but that wouldn't be maintainable.

Well, sorry about that.  As we found out the hard way, `makeprg` simply can't be configured to work reliably with the kind of command lines used by syntastic, and the kind of filenames people insist to throw at it. :) Maybe the format of errors produced by your Clean compiler doesn't change often enough to be such a burden though.

**Comment by camilstaps** [comment]
Okay, will do this then and open a PR. Thanks for the quick support!
