### ISSUE TITLE
How to disable when using vim-fugitive or other plugins 

### ISSUE THREAD

**Issue by joseche** [scrooloose/syntastic#1775]
Using the default config, syntastic will open when using :Gstatus or other commands from vim-fugitive. 

How can I disable syntastic temporarily ?

**Comment by lcd047** [comment]
Please explain what you did, what did you expect to happen, and what happened instead.  State your OS, your versions of Vim, syntastic, and fugitive, the kind of file that triggers the problem, your syntastic setup (in view of the [recommended settings](https://github.com/scrooloose/syntastic#settings), "default config" can mean a few different things), and your fugitive setup.  Can you reproduce the problem with all other plugins disabled except syntastic and fugitive?

**Comment by joseche** [comment]
When I am reviewing my changes and for example I do :Gdiff I need to
disable Syntastic's window so I can compare both files. Other plugins like
Tabgar, etc... allow you to close their window, this is very useful and I
will say necessary.

How to reproduce:

Open a version controlled file, make changes and then run :Gdiff, the
screen will have the comparison of the changes and below that the syntastic
segment which at that moment is unnecessary and taking important space of
the screen.


Vim version: 7.4.1724
OS: osx 10.11.5
Syntastic: 3.7.0-137
Fugitive: 2.2

Syntastic default configuration:

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0





On 19 May 2016 at 22:39, LCD 047 <notifications@github.com> wrote:

> Please explain what you did, what did you expect to happen, and what
> happened instead. State your OS, your versions of Vim, syntastic, and
> fugitive, the kind of file that triggers the problem, your syntastic setup
> (in view of the recommended settings
> <https://github.com/scrooloose/syntastic#settings>, "default config" can
> mean a few different things), and your fugitive setup. Can you reproduce
> the problem with all other plugins disabled except syntastic and fugitive?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scrooloose/syntastic/issues/1775#issuecomment-220515577>
>



-- 
No quiero creer, quiero saber.
   - Carl Sagan

**Comment by lcd047** [comment]
I'm afraid I'm still not sure what you're saying here.  Syntastic has `:SyntasticToggleMode` to toggle automatic checking, and it has `:SyntasticReset` to reset the error list after checking.  They are both documented.  Also, buffers in a `:Gdiff` have the `diff` variable set, and syntastic doesn't run checks if it can detect `diff` mode.  So, what _exactly_ did you do, what did you expect to happen, and what happened instead?

**Comment by lcd047** [comment]
I take it you have it figured out eventually?  If you haven't, feel free to reopen this when you're ready to disclose more details.
