### ISSUE TITLE
Rubocop not running

### ISSUE THREAD

**Issue by BBCMarkMcDonnell** [scrooloose/syntastic#1779]
Hi,

Here is my `.vimrc` file: https://github.com/Integralist/dotfiles/blob/master/.vimrc#L122

I have Syntastic installed (latest version) and it appears to work fine with other languages, but with Ruby it's not picking up any Rubocop errors in code that definitely has errors (I know this because when I run rubocop in my shell it picks up the errors).

I've recently followed the instructions here: https://github.com/scrooloose/syntastic/wiki/Ruby%3A---rubocop about setting `rbenv shell` version to avoid the parser error. But that made no difference to whether Syntastic could locate the Rubocop binary

I also found this file in Syntastic: https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/ruby/rubocop.vim and when I run `:echo loaded_syntastic_ruby_rubocop_checker` I see `1` is returned.

Any help in narrowing down where the problem could be would be greatly appreciated.

Thanks

**Comment by lcd047** [comment]
Does the [first entry in the FAQ](https://github.com/scrooloose/syntastic#faqinfo) answer your question?

**Comment by BBCMarkMcDonnell** [comment]
I'm afraid not.

Running the PATH checker reveals:

```
/Users/M/.pyenv/shims:/Users/M/.rbenv/shims:/Users/M/Projects/golang/bin:/Users/M/dotvim/voom:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin                                                                             
```

If I look inside `/Users/M/.rbenv/shims` I can see Rubocop.

**Comment by lcd047** [comment]
Please pay particular attention to the second paragraph.

**Comment by BBCMarkMcDonnell** [comment]
Aha! OK that was it. Apologies @lcd047 

```
Syntastic version: 3.7.0-139 (Vim 704, Darwin)                                                                                                                                                                                         
Info for filetype: ruby                                                                                                                                                                                                                
Global mode: active                                                                                                                                                                                                                    
Filetype ruby is active                                                                                                                                                                                                                
The current file will be checked automatically                                                                                                                                                                                         
Available checkers: jruby mri rubocop                                                                                                                                                                                                  
Currently enabled checker: mri
```

I can see that it's available but not been set to be used.

I need to implement it with:

```
let g:syntastic_ruby_checkers = ['rubocop', 'mri', 'jruby']
```

**Comment by githorse** [comment]
This works. However, some file types don't require me to explicitly enable each checker. For instance, in a `.sh` file, `SyntasticInfo` says:

```
Syntastic version: 3.8.0-26 (Vim 800, Darwin, GUI)
Info for filetype: sh
Global mode: active
Filetype sh is active
The current file will be checked automatically
Available checkers: sh shellcheck
Currently enabled checkers: sh shellcheck  
``` 

I haven't set `g:syntastic_sh_checkers =` anywhere. Is there some reason Rubocop has to be added explicitly? Is that a Rubocop thing or a Syntastic thing I'm not getting?

**Comment by lcd047** [comment]
> I haven't set `g:syntastic_sh_checkers =` anywhere.

This has been discouraged for the last 5+ years.  Then again, it's your time.

> Is there some reason Rubocop has to be added explicitly?

Running `rubocop --version` used to take ~5 seconds on OS-X.  No idea if this was fixed in the mean time.
