### ISSUE TITLE
How can I find out which validator is being called?

### ISSUE THREAD

**Issue by bgshacklett** [scrooloose/syntastic#1780]
I'm having some trouble with the YAML checker right now (major performance hit in certain situations), and I want to verify which validator is being called. Is there a command to do this?

**Comment by lcd047** [comment]
By default this is shown on the status bar of the error window:
![2016-05-26-181050_398x191](https://cloud.githubusercontent.com/assets/1281736/15579626/16faa034-236e-11e6-9ffe-4bfa96e14ef4.png)
See also `:h :SyntasticInfo`, and `:h syntastic-config-debug`.
