### ISSUE TITLE
Cannot change python interpreter

### ISSUE THREAD

**Issue by xucuncicero** [scrooloose/syntastic#1787]
os: win10
vim: gvim 7.4.1848
syntastic: current latest version.
python: I installed python 2.7 in `c:\python27` first and then python 3.5 in `c:\python35-32`

Problem:

I have this setting in my _vimrc:
`let g:syntastic_python_checkers = ['pylint']`
now the default interpreter/checker for python is python 3/pylint.

I want to change it to python 2/pylint, so add this:
`let g:syntastic_python_python_exec = 'c:/Python27'`
But this doesn't work at all.

Another way of setting(In powershell, `py -2 -m pylint *.py` works fine):
`let g:Syntastic_python_pylint_exec = 'py'`
`let g:Syntastic_python_pylint_args = ['-2', '-m', 'pylint']`
Still not work.

**Comment by xucuncicero** [comment]
OK, figured it out myself, we need these 2 sentence:
`let g:syntastic_python_checkers = ['pylint']`
`let g:syntastic_python_pylint_exe = 'py -2 -m pylint'`

**Comment by lcd047** [comment]
Setting the `exe` works, but only for `pylint`.  The general solution is to use something like [virtualenv](https://virtualenv.pypa.io/en/stable/) or [pyenv](https://github.com/yyuu/pyenv), create environments for Python 2 and Python 3, install the checekrs you want, and run Vim from said environments.  (I have no idea how you might do that from Windows, but I trust it's possible...)

> `let g:syntastic_python_python_exec = 'c:/Python27'`

On a side note: you need to point the `exec` to the checker's binary, not to its base directory.

> In powershell

You might also want to read `:h syntastic-powershell`.

**Comment by xucuncicero** [comment]
@lcd047 point the `exec` to the checker's binary takes no effect, too. I don't know why.

> You might also want to read `:h syntastic-powershell`

here I just run commands in system environment, which involves nothing with syntastic, but it did remind me of using vim from powershell.

Thanks for your suggestion, I might find out how to integrate gvim with virtualenv.

**Comment by lcd047** [comment]
> point the `exec` to the checker's binary takes no effect, too. I don't know why.

I didn't say it would solve your problem in this particular situation.  `g:syntastic_python_python_exec` only has effect on the `python` checker, it has nothing to do with the `pylint` checker.  No, what I'm saying is, pointing `exec` to a directory has no chance to work, for _any_ checker.
