### ISSUE TITLE
Gtk-WARNING **: unable to find signal handler for object(GtkWindow:0x9a50800) with func(0x81be470) and data(0x9b01640)

### ISSUE THREAD

**Issue by shaildev123** [scrooloose/syntastic#1800]
Getting Error in gvim after configuring syntastic plugin.
My gvim version is 7.3

Could you please help me in this.?

**Comment by lcd047** [comment]
Please see #787.

**Comment by shaildev123** [comment]
Thank you so much for your prompt response.
I just scrolled down the issue no 787. Should i update my vim version number?. The current version is 7.3

**Comment by lcd047** [comment]
I'd say you should upgrade Vim itself rather than just the version number. :smile: But yes, upgrading to a recent version is supposed to help.
