### ISSUE TITLE
[Ruby on Rails] File to import not found or unreadable: bootstrap-sprockets.

### ISSUE THREAD

**Issue by HaleTom** [scrooloose/syntastic#1801]
In my `app/assets/stylesheets/custom.css.scss` I have a line:
```
@import "bootstrap-sprockets";
```
Everything gets shown in my browser just fine, so it seems that Syntastic doesn't know about paths like Rails does, highlighting a syntax error:
```
File to import not found or unreadable: bootstrap-sprockets.
```

I've googled around and many answers say to prepend a commented `*= require` line, but the [bootstrap-sass documention ](https://github.com/twbs/bootstrap-sass) says not to do this:

```Do not use *= require in Sass or your other stylesheets will not be able to access the Bootstrap mixins or variables.```

How do I get rid of this supposed reported "error"?

**Comment by lcd047** [comment]
Please see #1799.
