### ISSUE TITLE
[d] should find dub directory up in the tree

### ISSUE THREAD

**Issue by wilzbach** [scrooloose/syntastic#1804]
The D support in Syntastic works nicely, but I often are inside a `dub` directory when opening a file with Vim thus the imports aren't recognized.
It would be nice if the plugin would thus check up the tree until a `dub.json` is found. Is there a "syntastic" approach to this?

Just in case I described the issue confusingly, here's an image:

![image](https://cloud.githubusercontent.com/assets/4370550/16542205/cd6dc3b6-409f-11e6-8095-1d8f51165185.png)

**Comment by lcd047** [comment]
> It would be nice if the plugin would thus check up the tree until a `dub.json` is found.

This is exactly what is supposed to happen with recent versions of syntastic (and `dub` 0.9.24 or later).  If it doesn't, than please provide evidence: set `g:syntastic_debug` to 33, run the checker, and post the logs.

**Comment by lcd047** [comment]
I take it the problem went away somehow?  Feel free to re-open this if it didn't, and you're ready to disclose details.
