### ISSUE TITLE
Not working on Ubuntu

### ISSUE THREAD

**Issue by mafrosis** [scrooloose/syntastic#1805]
Apologies for having to ask, but I really can't figure this one out. Please could you take a look at my problem as posted on superuser?

http://superuser.com/questions/1095023/syntastic-not-working-on-ubuntu

I'm not sure where to go next with debugging this, so any pointers on a "syntastic debug mode" or similar would be very helpful!

**Comment by lcd047** [comment]
Right, I suppose this should be in the FAQ: to work with multiple versions of Python, install `virtualenv`, `pyenv`, or similar, activate the relevant environment, install the checkers you plan to use, set `g:syntastic_python_checkers` accordingly, and run Vim from the environment.

If this doesn't solve your problem then please explain what you did, what did you expect to happen, and what happened instead.  Post a minimal file that illustrates the problem, enable debugging, and post the logs.

**Comment by mafrosis** [comment]
Yes apologies for the link to SU. It seemed unnecessary to copy/paste that content in here..

I have a standard dotfiles setup - same config on OSX, Debian & now Ubuntu. Syntastic is not showing any errors in a broken Python file on Ubuntu. The same setup works on OSX/Debian.

Using `test.py`, which contains only a single line:

    import json

`:SyntasticInfo` output is the same on OSX/Ubuntu/Debian:

    Syntastic version: 3.7.0-157 (Vim 704, Linux)
    Info for filetype: python
    Global mode: active
    Passive filetypes: java sass scss
    Filetype python is active
    The current file will be checked automatically
    Available checkers: pyflakes python
    Currently enabled checkers: pyflakes python

`:SyntasticCheck` does nothing, likewise `:Errors`.

I forcefully show errors by running `:echo system('pyflakes test.py')` in vim, which produces:

    test.py:1: 'json' imported but unused

My syntastic `.vimrc` config is (from my [dotfiles](https://github.com/mafrosis/dotfiles/blob/master/vim/.vimrc#L157)):

    let g:syntastic_python_checkers = ['pyflakes', 'python']
    let g:syntastic_python_pyflakes_exe = 'python3 -m pyflakes'
    let g:syntastic_python_flake8_args='--ignore=E501'
    let g:syntastic_mode_map = { 'mode': 'active',
						       \ 'active_filetypes': [],
						       \ 'passive_filetypes': ['java', 'sass', 'scss'] }

You mention "enable debugging" above - is that syntastic debugging? How can I enable that?

**Comment by lcd047** [comment]
> Yes apologies for the link to SU. It seemed unnecessary to copy/paste that content in here..

For one, GitHub doesn't index posts on SO...

> let g:syntastic_python_pyflakes_exe = 'python3 -m pyflakes'

From my answer above:

> Right, I suppose this should be in the FAQ: to work with multiple versions of Python, install `virtualenv`, `pyenv`, or similar, activate the relevant environment, install the checkers you plan to use, set `g:syntastic_python_checkers` accordingly, and run Vim from the environment.

Try this first.

> I can show errors by running `:echo system('pyflakes test.py')` in vim, which produces:

This is not directly relevant, since you have `exe = 'python3 -m pyflakes'`.  So try `:echo system('python3 -m pyflakes test.py')` instead.

> You mention "enable debugging" above - is that syntastic debugging? How can I enable that?

This is explained in the manual: `:h syntastic-config-debug`.

So, please try this:

* upgrade syntastic to the latest master HEAD
* install `pyflakes` in `virtualenv` and run Vim from the environment, as I said above
* if you still have problems: open your test file, set `g:syntastic_debug` to 3, run `:SyntasticCheck pyflakes`, then run `:mes` and post the output.

**Comment by mafrosis** [comment]
Thanks for your comments. It came down to the `g:syntastic_python_pyflakes_exe` config - somehow my ubuntu box had pyflakes installed for python2, but not python3.. Your suggestion of running the following fixed things for me:

    :echo system('python3 -m pyflakes test.py')

Thank you for sparing some time for this!
