### ISSUE TITLE
g:syntastic_always_populate_loc_list=1 seems to be not working

### ISSUE THREAD

**Issue by chubin** [scrooloose/syntastic#1806]
I have
~~~~
let g:syntastic_always_populate_loc_list = 1
~~~~
in my `~/.vimrc`, but it obviously doesn't work.
If I run `:Errors` manually, I can use `:lnext` and `:lprev`,
but if I don't, they do not work.

**Comment by chubin** [comment]
Strange. I've installed vim-unimpaired, and it works now. But it didn't work before. Should I close the issue?

**Comment by lcd047** [comment]
That particular piece of code hasn't changed in a few years, and you're the first to complain about it.  Feel free to re-open this if you can find a way to reproduce the problem though.
