### ISSUE TITLE
Add ability to change the CWD for specific checkers.

### ISSUE THREAD

**Issue by sanscore** [scrooloose/syntastic#1808]
My issue is specifically with the Python checker `pylint` which only checks for its `pylintrc` configurations inside the CWD. For `pylint`, you could also provide a configuration with the `--rcfile=<file>` option, but there's no way to make this generic to work with any project. What would work better is the ability to change the CWD to the file's directory **only** to run `pylint` so I can take advantage of its discovery algorithm. The CWD for the greater vim process should not be affected.

Examples from the commandline.

What I want:
```sh
$ pwd
/home/jdoe/work/py-project/test

$ ls pylintrc
pylintrc

$ pylint test_py_project.py
...
Your code has been rated at 10.00/10
```

What I don't want:
```sh
$ cd ..

$ pwd
/home/jdoe/work/py-project/

$ ls pylintrc
ls: pylintrc: No such file or directory

$ ls test/pylintrc
pylintrc

$ pylint test/test_py_project.py
...
Your code has been rated at 8.75/10
```

## Special Comment

I would argue that this is something that the `pylint` project should fix in their discovery algorithm, but from my experience with that community, I'll just state that isn't likely to happen anytime soon.

**Comment by lcd047** [comment]
> For `pylint`, you could also provide a configuration with the `--rcfile=<file>` option, but there's no way to make this generic to work with any project.

Sure you can, people do it all the time for [other checkers](https://github.com/scrooloose/syntastic/issues/1739#issuecomment-206292156).

**Comment by sanscore** [comment]
@lcd047, very interesting. thanks for the snippet. Would you like for me to  try to incorporate into syntastic? Or, do you think this is a solution for individual use cases?

**Comment by lcd047** [comment]
> Would you like for me to try to incorporate into syntastic?

Sorry, but no.  If `pylint` people don't care about fixing usability problems in their project, then neither do I.  There are currently 217 checkers in syntastic, keeping things clean and maintainable is far more important than adding workarounds for everything people might ever run into.

> Or, do you think this is a solution for individual use cases?

Syntastic is a development tool, and the kind of trick I mentioned in the other thread is basic Vim gymnastics.

**Comment by sanscore** [comment]
W4M. Thanks for the trick.

**Comment by vitaly** [comment]
the proposed trick doesn't work if I actually need to run from the project root and not just pass some configuration file. How can I run the syntax check from the vim's current directory, and not form the checked file's directory?

**Comment by lcd047** [comment]
> How can I run the syntax check from the vim's current directory, and not form the checked file's directory?

@vitaly That's what happens for the vast majority of the checkers.  So you'll have to provide more details if you want a more meaningful answer.  What checker are you using, what are you trying to do, and how does syntastic prevent you from doing it?
