### ISSUE TITLE
Is it possible to make the split smaller when there are fewer errors?

### ISSUE THREAD

**Issue by zacps** [scrooloose/syntastic#1812]
For example:
![2016-07-13-220211_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9827696/16799554/7f710f2a-4945-11e6-97cf-6056298606cb.png)
How can I make the errors window automatically resize to the height of the errors?

**Comment by lcd047** [comment]
Please see #1678.

**Comment by zacps** [comment]
Thanks, sorry I missed that when searching.
