### ISSUE TITLE
Support tsconfig.json for tsc checker

### ISSUE THREAD

**Issue by kazimuth** [scrooloose/syntastic#1816]
Typescript projects have a standard configuration file called [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html), which documents compiler options and the files to compile.
Often typescript has invisible dependencies between files, particularly type declaration files.

If I have:
`src/lotsofdeclarations.d.ts`:
```typescript
declare module 'bananas' {
    export var count: number;
}
```
`src/code.ts`:
```typescript
import {count} from 'bananas';
console.log(count);
```

Calling `tsc --noEmit src/code.ts`, as syntastic currently does, will give the error `error TS2307: Cannot find module 'bananas'`.
If I have a `tsconfig.json` that specifies the files, though, then I can call just `tsc --noEmit`, or `tsc --noEmit -p tsconfig.json`, and it will compile fine.
This will, unfortunately, build the whole project, and there doesn't seem to be any way to not build the whole project, since the dependencies are invisible.
Note that the error can be avoided by including reference tags in the source code:
`src/code.ts`:
```typescript
///<reference path="./lotsofdeclarations.d.ts"/>
import {count} from 'bananas';
console.log(count);
```
Now everything will just work. This is discouraged by tools like [typings](https://github.com/typings/typings), though.
It might make sense to at least include an option to have the tsc checker search for tsconfig.json.

**Comment by lcd047** [comment]
Please see question 4.14 in the [FAQ][FAQ], and #1811.

[FAQ]: https://github.com/scrooloose/syntastic#faqconfig
