### ISSUE TITLE
Syntastic can't find checkers possible %PATH% problem?

### ISSUE THREAD

**Issue by Bombastrelopas** [scrooloose/syntastic#1818]
Shell: Cmder
OS: Windows 10
Syntastic: Latest version

The debug output when I open a file:

> syntastic: 0.091268: &shell = 'C:\Windows\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '(', &shellxescape = '"&|<>()@^'
syntastic: 0.093202: UpdateErrors (auto): default checkers
syntastic: 0.094495: CacheErrors: default checkers
syntastic: 0.096148: g:syntastic_aggregate_errors = 0
syntastic: 0.096810: getcwd() = 'C:\Users\ioann\Desktop'
syntastic: 0.112020: CacheErrors: Checker cs/mcs is not available
syntastic: 0.112804: CacheErrors: no checkers available for cs

When I run the `:echo syntastic#util#system('echo %PATH%')`
I get:

```
\NVIDIA was unexpected at this time.ATH%')
Error detected while processing function syntastic#util#system:
line   10:
E484: Can't open file C:\Users\ioann\AppData\Local\Temp\VIo4EB0.tmp
-1
```

My _vimrc settings:
```
syntax on

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_debug = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
set noshellslash

```

NOTES: Same outputs if I switch from cmder to command prompt.

**Comment by lcd047** [comment]
It looks like your `system()` can't run programs.  But I'm afraid my last contact with the Windows world was with Windows 3.1 in 1993, so I'm afraid I won't be of much use helping you fix the problem. _shrug_
