### ISSUE TITLE
Not-so-cool gutter highlighting

### ISSUE THREAD

**Issue by light2yellow** [scrooloose/syntastic#1819]
I'm using `flattened`, which is almost a `solarized` clone. There were a lot of talks about `solarized`, but now the issue seems to be with `syntastic`, because `vim-gitgutter` highlights perfectly. You can find `vim-gutter`'s highlighting [here](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/highlight.vim).
![screenshot_2016-07-19_21-29-16](https://cloud.githubusercontent.com/assets/10786469/16963681/e6ebf0a0-4df7-11e6-96ba-04b25991a901.png)

**Comment by lcd047** [comment]
Syntastic lets you define the colours for the signs (see `:h syntastic-error-signs`), and the sign characters (cf. `:h syntastic_error_symbol`).

If that doesn't address your problem then please explain what you did, what did you expect to happen, and what happened instead.  Don't expect me to infer that from some names, a screenshot, and a link to an unrelated plugin.

**Comment by light2yellow** [comment]
Thank you for the anwer. [Here's an issue on solarized page](https://github.com/altercation/solarized/issues/252). But I don't suffer from such a problem. Instead, syntastic detects background color but my intention is that it should detect another one, which is brighter (idk how to call it) on the provided screenshot. I know I can change the colors by myself, but:
* I don't know how to fill in this brighter color (also need to detect it first, but it's easy), my colorscheme's related string is `hi  ColorColumn ctermbg=0  guibg=#073642  gui=NONE` and `vim-gutter` somehow manages to deal with it in the right way. The colors it offers are:
```
TERMCOL   HEX     RGB
-------   ------- -----------
black     #073642   7  54  66
red       #dc322f 220  50  47
green     #859900 133 153   0
yellow    #b58900 181 137   0
blue      #268bd2  38 139 210
magenta   #d33682 211  54 130
cyan      #2aa198  42 161 152
white     #eee8d5 238 232 213

brblack   #002b36   0  43  54
brred     #cb4b16 203  75  22
brgreen   #586e75  88 110 117
bryellow  #657b83 101 123 131
brblue    #839496 131 148 150
brmagenta #6c71c4 108 113 196
brcyan    #93a1a1 147 161 161
brwhite   #fdf6e3 253 246 227
```
* possibly more people would like to have consistent gutter color
Thus your help is needed in both situations.

**Comment by lcd047** [comment]
Please read this carefully: syntastic __doesn't change any colours__.  It uses the highlight groups mentioned in the manual.  __It's up to you__ to change the colours for said groups.

**Comment by light2yellow** [comment]
Understood now. Successfully changed the `Syntastic..Sign`s, thanks again. Just didn't realize that I can change not only the symbol's color, but the color under the symbol too.

**Comment by cythb** [comment]
https://github.com/jumski/vim-colors-solarized/commit/54864d547cb54177e3a00d1166637c1fddddfad5
