### ISSUE TITLE
Syntastic and .html.erb checking

### ISSUE THREAD

**Issue by HaleTom** [scrooloose/syntastic#1820]
Is there a way to use
* [rails-erb-lint](https://rubygems.org/gems/rails-erb-lint/versions/1.1.6)
* [rails-erb-check](https://github.com/jugyo/rails-erb-check)
* something else

with syntastic and get any indication about the validity of the .html.erb file?

I'm trying with: `let g:syntastic_eruby_ruby_exec=['rails-erb-check']` but get:

    Error detected while processing function <SNR>66_BufWritePostHook..<SNR>66_UpdateErrors..<SNR>66_CacheErrors..30..21:
    line    1:
    E730: using List as a String
    Press ENTER or type command to continue

**Comment by lcd047** [comment]
As far as I can tell `rails-erb-lint` and `rails-erb-check` return only a `valid` / `invalid` status for each file.  Why would you need syntastic to deal with that?

As for `g:syntastic_eruby_ruby_exec`, (1) you has to set that to a string, not a list, (2) that string has to point to the `ruby` executable, and (3) pointing it to something else than the `ruby` executable won't automatically add support for unknown checkers. _shrug_
