### ISSUE TITLE
syntastic : error: checker haskell/ghc_mod returned abnormal status 1 

### ISSUE THREAD

**Issue by arey0pushpa** [scrooloose/syntastic#1821]
Saving a haskell file gives:

 syntastic: error: checker haskell/ghc_mod returned abnormal status

My config :  

 mokambo 05:15 PM ~/try_haskell/48hours.hs  ghc-mod version
 ghc-mod version 5.5.0.0 compiled by GHC 7.8.4

As you have previously stated :
Please open a Haskell file, set g:syntastic_debug to 3, run the checker, run :mes, and post the output.

I'm Getting : 
http://pastebin.com/yHDqzanR

Kindly help 

Thanks

**Comment by lcd047** [comment]
Please read #1576.  Come back here if you still have questions.
