### ISSUE TITLE
can't parse version string for python2

### ISSUE THREAD

**Issue by RTNelo** [scrooloose/syntastic#1823]
When I use syntastic on .py files I always get the error message like this:

> syntastic: error: checker output:
> syntastic: error: checker python/python: can't parse version string (abnormal termination?)

I found that the SyntasticCheck.getVersion in file plugin/syntastic/checker.vim use syntastic#util#system to get the version string, which just use system to get the stdout of the command.

What's more, my python2 output version string to stderr if I use the --version option. (However, python3 output it to stdout.) So I change the code in SyntasticChecker.getVersion from
`let version_output = syntastic#util#system(command)`
to
`let version_output = syntastic#util#system(command . " 2>&1")`
to fix my problem.

So, is this a real bug in syntastic, or just something wrong with my python? (It seems that there is no issue about the problem before?)

Please forgive me for my poor english.

**Comment by lcd047** [comment]
If you have this problem and adding `2>&1` solves it, then either

1. you messed with `shellredir`,
2. you're using an unsupported shell, or
3. your Vim is broken.

To find out which it is, please open a Python file, set `g:syntastic_debug` to 1, run `:SyntasticCheck python`, run `:mes`, and post the output.

**Comment by RTNelo** [comment]
@lcd047 
At last I got this message of the command :mes without changing the .vim file back to the original version.

`syntastic: 4.676387: &shell = '/usr/bin/fizsh', &shellcmdflag = '-c', &shellpipe = '| tee', &shellquote = '', &shellredir = '>', &shell
slash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 4.677797: UpdateErrors: default checkers
syntastic: 4.678454: CacheErrors: default checkers
syntastic: 4.679885: g:syntastic_aggregate_errors = 0
syntastic: 4.680255: getcwd() = '/home/rtnelo'
syntastic: 4.681187: CacheErrors: Invoking checker: python/python
syntastic: 4.683202: SyntasticMake: called with options: {'errorformat': '%E%f:%l:%c: %m', 'makeprg': 'python2 /home/rtnelo/.vim/bundle
/syntastic/syntax_checkers/python/compile.py project/Beryllium/model.py', 'env': {'TERM': 'dumb'}, 'returns': [0]}
syntastic: 4.727028: system: command run in 0.043001s
syntastic: 4.727858: getLocList: checker python/python returned 0
syntastic: 4.728356: getLocList: checker python/python run in 0.046920s
syntastic: 4.728874: CacheErrors: Checker python/flake8 is not available
syntastic: 4.729183: CacheErrors: Checker python/pylint is not available
`

**Comment by lcd047** [comment]
> &shell = '/usr/bin/fizsh'

Please read `:h syntastic-fizsh`.

**Comment by RTNelo** [comment]
@lcd047 Thank you very much. It fixed my problem. Sorry for disturbing you.
