### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by aidylewis** [scrooloose/syntastic#1824]
OS X 10.9.5
Vim 7.4

I am getting some strange rendering issues with syntastic. I have just opened the file and navigated up and down. The parentheses after line 15 are not actually there (there is no line numbering and if I save this file, they'll disappear). Also the status bar has an extra blank line there. If I remove syntastic, the Vim rendering is fine.

![screen shot 2016-07-25 at 17 51 30](https://cloud.githubusercontent.com/assets/6703997/17109683/efacaa5c-5290-11e6-8f0d-422b1e434f9a.png)

**Comment by lcd047** [comment]
This problem might have been triggered by syntastic (for some roundabout reasons), but it isn't caused by syntastic.  Syntastic has absolutely no control over low-level rendering.  Please see my comments at #822.
