### ISSUE TITLE
Twig linted as HTML with Plugin 'evidens/vim-twig' installed

### ISSUE THREAD

**Issue by rodrigoaguilera** [scrooloose/syntastic#1825]
While developing with vim plugin for Drupal we ran into an issue.
https://www.drupal.org/node/2773013

With tidy and 'evidens/vim-twig' installed the twig files in drupal are reporting HTML/tidy errors because the plugin sets the filetype to also HTML for highlighting.

Since I assume tidy doesn't have an option for stripping all the twig bits before linting, Can it be possible to suppress the html errors for twig files?

is 'evidens/vim-twig' doing it wrong for setting the filetype to html?

**Comment by lcd047** [comment]
> Can it be possible to suppress the html errors for twig files?

As you probably know, error messages are produced by the checkers, not by syntastic.  Now, syntastic supports a single checker for `twig`, namely [twig-lint][twig-lint].  Whether this can be coerced to ignore HTML problems is a question for the [`twig-lint` issue tracker][twig-lint-tracker].

Actually, you could also remove the offending messages on syntastic side, by setting `g:syntastic_twig_twig_lint_quiet_messages` (see `:h 'syntastic_quiet_messages'` for details).  But it's of course better if `twig-lint` doesn't generate these messages to begin with.

> is 'evidens/vim-twig' doing it wrong for setting the filetype to html?

It's a common approach when dealing with templates.  In this case syntastic runs the checkers for both filetypes, but you can disable this behaviour by setting `syntastic_filetype_map`:
```vim
let g:syntastic_filetype_map = { 'html.twig': 'twig' }
```
This basically tells syntastic that the `html.twig` filetype is an alias for `twig`.  See `:h syntastic-composite` for details.

[twig-lint]: https://github.com/asm89/twig-lint
[twig-lint-tracker]: https://github.com/asm89/twig-lint/issues

**Comment by rodrigoaguilera** [comment]
Is not twig-lint errors that are reported wrong on twig files. these syntax reports come from tidy.
I guess tidy alredy ignores js blocks inside html. It should do something similar for twig.

The syntastic_filetype_map solution is great!

I think it should be somehow automatically managed by evidens/vim-twig so twig files are only linted for twig. If this is the plugin saying "hey, this is HTML too" it should be in charge of letting syntastic know that is not checked as HTML.

The ideal solution will be to check only the syntax for the HTML parts of a twig file but I don't know how this is achievable.

**Comment by lcd047** [comment]
> The ideal solution will be to check only the syntax for the HTML parts of a twig file but I don't know how this is achievable.

It isn't (achievable, that is).  All checkers for templates have this problem, and sadly syntastic can't do anything to solve it.  The "naive" approach to remove everything between the template markers doesn't work, since it changes the line numbers for errors and the like.  This _has_ to be addressed on the checkers' side (in your case in `tidy`), but very few checkers are willing to even consider that. _shrug_

**Comment by rodrigoaguilera** [comment]
I see that some forks of the plugin have this problem solved
https://github.com/juanolon/vim-twig/commit/cb75fae2dfe5918597dd4762202a085f48d29df8
I'll check later.

**Comment by lcd047** [comment]
Like I said: you can just set `g:syntastic_filetype_map` as above, and not care about the composite filetype.

**Comment by rodrigoaguilera** [comment]
Thank you for your help!
