### ISSUE TITLE
Add support for checkpatch.pl "CHECK" messages

### ISSUE THREAD

**Issue by vivien** [scrooloose/syntastic#1828]
In addition to *ERROR* and *WARNING* messages, checkpatch.pl has a *CHECK* message type, e.g.:

```
CHECK: Comparison to NULL could be written "name"
#98: FILE: net/dsa/dsa.c:98:
+		if (name != NULL) {
```

Cc: @daniel-walker @d-k-c

**Comment by lcd047** [comment]
No.  Informational messages are deliberately left out.  Besides, syntastic supports only errors and warnings.

**Comment by vivien** [comment]
I understand your concern about the message semantic, however checkpatch is a bit different. I don't know why they have a *CHECK* type, but the related messages are definitely syntax checking issues. Examples of such messages are:

- "Alignment should match open parenthesis"
- "Please use a blank line after function/struct/union/enum declarations"
- "Please don't use multiple blank lines"
- "Concatenated strings should use spaces between elements"
- etc.

**Comment by lcd047** [comment]
Those are style issues rather than syntax errors.
