### ISSUE TITLE
checkpatch.pl checks more filetypes, must be global

### ISSUE THREAD

**Issue by vivien** [scrooloose/syntastic#1829]
In addition to the *c* filetype, *./scripts/checkpatch.pl* supports other filetypes such as:

- *cpp* (`.h` files)
- *make* (Makefile files)
- *kconfig* (Kconfig files)
- *dts* (`.dts` and `.dtsi` files)
- *diff* (`.patch` files, usually results of `git format-patch`)

The only nitpick here is that *checkpath.pl* must be called **without** the `--file` option to check `.patch` files.

Cc: @daniel-walker @d-k-c

**Comment by lcd047** [comment]
If you post a PR I'll consider it.

**Comment by vivien** [comment]
I didn't dig that much in the code yet and thus I'm not sure how to handle such "global" checkers, as well as the `.patch` case without the need for the `-f` option.

**Comment by lcd047** [comment]
You won't be able to handle the `.patch` case.  Syntastic can't check `diff` files, for reasons that have to do with conflicts with `vimdiff`, and with the incompleteness of Vim's API.

That said, I'm working on a patch that would make it possible to run checkers of "foreign" filetypes against any file, and that would address your problem.  I'm afraid I can't give you any ETA for it though.

**Comment by vivien** [comment]
That'll indeed fix the `diff` filetype case. What about having a "global" checker, registered for different filetypes? Can Syntastic handle that?

**Comment by lcd047** [comment]
There is no such thing as a "global" checker, there are only checkers associated to concrete filetypes.  There are redirection mechanisms (they are explained in the [guide](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#duplicates)), but that's about all.  If you want generic checkers you should consider using compiler sets (see `:h :compiler`).  Syntastic comes from there, and is moving in the opposite direction. _shrug_

**Comment by lcd047** [comment]
It's now possible to run checkers of "foreign" filetypes against any file.  Commit adf899f.
