### ISSUE TITLE
The location list can not be closed automitically

### ISSUE THREAD

**Issue by FuDesign2008** [scrooloose/syntastic#1835]
The following configuration for Syntastic is in my `.vimrc`

```viml
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
```

1. Open file `a.js`  which has `jshint` errors, the location list will be shown in vim.  
1. Execute`vsplit` command, there will be two buffer windows: `left` and `right`. 
1. Move cursor to `right` buffer window and execute `:e b.js`. The file `b.js` has no `jshint` errors
1. Go back to `left` buffer window and execute `:close`. The `left` buffer window will be closed, but the location list can NOT be closed automatically. 

I think the location list should be closed automatically when the `left` buffer window is closed.

There is another similar problem.

1.  Open file `a.js` which has no `jshint` errors
1.  Execute command `:vert diffsplit b.js`. The file `b.js` has `jshint` errors
1.  Then location list for `b.js` will be shown.  

I found following code in `plugin/syntastic.vim` 

```vml
" Skip running in special buffers
function! s:_skip_file() abort " {{{2
    let fname = expand('%', 1)
    let skip = s:_is_quitting(bufnr('%')) || get(b:, 'syntastic_skip_checks', 0) ||
        \ (&buftype !=# '') || !filereadable(fname) || getwinvar(0, '&diff') ||
        \ getwinvar(0, '&previewwindow') || s:_ignore_file(fname) ||
        \ fnamemodify(fname, ':e') =~? g:syntastic_ignore_extensions
    if skip
        call syntastic#log#debug(g:_SYNTASTIC_DEBUG_TRACE, '_skip_file: skipping checks')
    endif
    return skip
endfunction " }}}2

```

If the vim is in diff mode ( `getwinvar(0, '&diff')` ), the syntax check will be skipped. Can Syntastic add support for the diff mode when executing `:vert diffsplit b.js` command ?

**Comment by lcd047** [comment]
> Go back to `left` buffer window and execute `:close`. The `left` buffer window will be closed, but the location list can NOT be closed automatically. 

It __is__ closed automatically if you `:quit` the buffer rather than just `:close` the window.

> I think the location list should be closed automatically when the `left` buffer window is closed.

As far as I can tell there is no safe way to do that (i.e. fixing it would break other scenarios).  If you do find a solution that doesn't break anything feel free to post a PR though.

> Then location list for `b.js` will be shown.

That's the expected behaviour, the list of errors is associated to the buffer, not to the window.  Run `:SyntasticReset` to get rid of it.

> Can Syntastic add support for the diff mode when executing `:vert diffsplit b.js` command ?

No, for many reasons.  This has been discussed a few times in the past, but the limitations in Vim's API haven't changed. _shrug_

**Comment by FuDesign2008** [comment]
@lcd047  Thanks for your nice response! 

I write a simple [plugin](https://github.com/FuDesign2008/diffsplit.vim) that wraps `diffsplit` command to avoid the problem.

**Comment by FuDesign2008** [comment]
Hello @lcd047 , the `timer_start` can make syntastic to add support the diff mode when executing `:vert diffsplit b.js` command.

There is a commit of fix: https://github.com/FuDesign2008/syntastic/commit/b3c2e44b62c0baad4a28f5619923941b91dc9568

**Comment by lcd047** [comment]
Actually, your patch has nothing to do with syntastic checking `diff` files.

**Comment by FuDesign2008** [comment]
@lcd047 

The `UpdateErrorsWhenBufReadPost` will not be called when the `BufReadPost` event, it will be called  `50` ms later than `BufReadPost` event.

During the `50` ms,  the built-in `&diff` option will be set  by Vim.

So when executing commands like `:dffsplit`,   the `s:_skip_file()` function can get the right value of `&diff`.

**Comment by lcd047** [comment]
Like I said: there are many other problems with checking `diff` files.  Syntastic doesn't check them for reasons that have nothing to do with closing windows.

**Comment by FuDesign2008** [comment]
@lcd047  Do you mean: Syntastic does not checking `diff` files ?   

I  go along with  Syntastic does not checking `diff` files.

When opening file, Syntastic detect built-in `diff` option,  but can NOT get the right value. 

When executing `:diffsplit somefile`on MacVim 

1. At point of `BufReadPost` ,  the result of   `getwinvar(0, '&diff')` will be  `0`
1. 50 ms later,  the result of   `getwinvar(0, '&diff')` will be  `1`
