### ISSUE TITLE
statusline is reset when vimrc is reloaded with syntastic recommended settings

### ISSUE THREAD

**Issue by go2null** [scrooloose/syntastic#1838]
My `.vimrc` has the [recommended](https://github.com/scrooloose/syntastic#settings) settings.
I also have `vim-airline` installed

However, when `.vimrc` is reloaded, my `statusline` gets reset and `airline` is removed.
There is also an [issue](https://github.com/vim-airline/vim-airline/issues/988) opened on vim-airline`.

**Comment by lcd047** [comment]
Please read :h syntastic-statusline-flag`, in particular the last paragraph.  In this particular case, `airline` should support syntastic's status line flag out of the box, provided that you leave alone `statusline`.

**Comment by hungle88** [comment]
@go2null : Not sure if you've found a solution but this is how I fixed this.
```
map <leader>vr :source ~/.vimrc<CR> :AirlineRefresh <CR>
```
Hope this helps!

**Comment by lcd047** [comment]
@hungle88 There wouldn't be anything to fix if you left alone `statusline`.

**Comment by hungle88** [comment]
@lcd047 Unfortunately, that not seems to be the case. I tried to comment out all the `statusline` settings and keep only the recommended settings as follow
```
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
```
but when I sourced the ~/.vimrc file, the `statusline` would just blacked out, like @go2null mentioned above:

>  However, when `.vimrc` is reloaded, my `statusline` gets reset and `airline` is removed.
There is also an issue opened on vim-airline`.

**Comment by lcd047** [comment]
@hungle88 The recommended settings __don't apply__ if you're using other plugins that change the status line.  This is explicitly stated in the manual: `:h syntastic-statusline-flag`.  Just __delete__ these lines from your vimrc:
```vim
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
```

**Comment by chrisbra** [comment]
@lcd047  airline maintainer here: What would you suggest, to have a better support for airline?

**Comment by lcd047** [comment]
@chrisbra Perhaps add a note to the manual that the recommendation to set `statusline` for syntastic doesn't apply.  There is nothing else to improve, `airline` works fine with syntastic out of the box.

**Comment by chrisbra** [comment]
@lcd047 thanks and done.

**Comment by vegangaro** [comment]
Sorry the necro,

Deleting those recommend commands helps but in my case was not their fault but reloading vimrc from inside itself that turn off airline!
