### ISSUE TITLE
Can not check go files.

### ISSUE THREAD

**Issue by heramerom** [scrooloose/syntastic#1841]
Hi:
My vim can't check go files. I don't know why.
```
:SyntasticInfo
```
output
```
Syntastic version: 3.7.0-180 (Vim 704, Darwin)
Info for filetype: go
Global mode: active
Filetype go is active
The current file will be checked automatically
Available checkers: go gofmt golint gometalinter govet
Currently enabled checkers: -
```
I don't know how to config. Can you help me?
Thank you very much!

**Comment by lcd047** [comment]
Please consider installing [vim-go][vim-go] insetad.  If you still want to enable syntastic for Go, then read the answer to the first question in the [FAQ][FAQ] (in particular the second paragraph), and act accordingly.

[vim-go]: https://github.com/fatih/vim-go
[FAQ]: https://github.com/scrooloose/syntastic#faqinfo

**Comment by heramerom** [comment]
I have a try. Thank you.

**Comment by heramerom** [comment]
![image](https://cloud.githubusercontent.com/assets/4046709/17663774/a807e0ee-6321-11e6-93a0-f12037a1b4ee.png)

Maybe I found the reason. I update the golang with dev version. It was not work. but before. it work  well.

**Comment by lcd047** [comment]
Syntastic relies on version strings to find out if a given option of `go` can be used or not.  And since it isn't possible to tell whether version "31ad583" came before or after something like "1.5", syntastic only works with release versions of Go. _shrug_
