### ISSUE TITLE
STL file not found

### ISSUE THREAD

**Issue by kobecsb** [scrooloose/syntastic#1847]
When using syntastic and ycm in C++. A simple example code is like:

```
#include <vector>

template <typename T>
using matrix = std::vector<std::vector<T>>;

struct TreeNode {
    int val;
    TreeNode *left;
    TreeNode *right;
    TreeNode(int x) : val(x), left(NULL), right(NULL) {}
};
```
It says "error| fatal error: 'vector' file not found". How can I fix this please?

**Comment by lcd047** [comment]
Please open your test file, run `:SyntasticInfo`, and post the output.

**Comment by kobecsb** [comment]
The outputs like below:

Syntastic version: 3.7.0-190 (Vim 704, Linux)
Info for filetype: cpp
Global mode: active
Filetype cpp is active
The current file will be checked automatically
Available checkers: clang_check gcc
Currently enabled checker: gcc


Thank you

**Comment by lcd047** [comment]
To _see_ how syntastic runs `gcc`: enable debugging (cf. `:h syntastic-debug`).  To _change_ the way syntastic runs `gcc`: set the checker options appropriately (cf. `:h syntastic-cpp-gcc`).
