### ISSUE TITLE
stylelint with syntastic does not catch errors

### ISSUE THREAD

**Issue by richtong** [scrooloose/syntastic#1849]
This is probably a configuration error, so needs to be documented, but how do you use stylelint with syntactic. I have done

```
npm install -g stylelint stylelint-default-config
```
And added the appropriate .stylelintrc to extend to it, so when I try an obviously css bad file like

```
a {
  d:
```

The command line stylelint finds it and prints the errors, but when I go to syntasticInfo for that file I see that stylelint is detected 

But no errors are generated. Is there another step? Normally when it sees it the path it detects and works.

**Comment by lcd047** [comment]
Please open your test file, run `:SyntasticInfo`, and post the output.

**Comment by richtong** [comment]
Ok, good thing I looked at this, I don't understand syntastic well enough, but somewhere in your documentation, you should add the need to update .vimrc to see stylelint. The complet steps to install for syntastic are assuming you want it as your global default and you are on a mac. For ubuntu the path is /usr/lib/node_modules/

```
npm install -g stylelint stylelint-default
echo '{"extends" : "/opt/local/lib/node_modules/stylelint-config-standard"}' > ~/.stylelintrc
echo 'g:syntastic_css_checkers = ['stylelint']' > ~/.vimrc
```

**Comment by aaron-goshine** [comment]
``` if [[ $OSTYPE =~ darwin ]]; then NODE_ROOT=/opt/local; else NODE_ROOT=/usr; fi
npm install -g stylelint stylelint-default
echo extends : $NODE_ROOT/lib/node_modules/stylelint-config-standard > ~/.stylelintrc
echo g:syntastic_css_checkers = [\'stylelint\'] > ~/.vimrc ```
there was a typo in the script  the a `t` was left off
