### ISSUE TITLE
your shell /bin/bash can't handle traditional UNIX syntax for redirection

### ISSUE THREAD

**Issue by her** [scrooloose/syntastic#1850]
Hello, 

I'm on FreeBSD trying to get syntastic to work, it works great on other systems I use, but FreeBSD is being stubborn. 

`
.vimrc
set shell=/bin/csh
`

`
root@mb ~# echo $SHELL
/bin/csh
`

I've done some searching on this and found a previous issue [here](https://github.com/scrooloose/syntastic/issues/803)

But I've tried this and still no luck... Any suggestions? 

Thanks, and thanks again for syntastic!

**Comment by lcd047** [comment]
Please read `:h syntastic-csh`.

**Comment by her** [comment]
Thank you @lcd047 

I'm a silent lurker to your many, many, responses to these issues and you're brilliant! 

I'll go read now.

**Comment by her** [comment]
I set 

`let g:syntastic_shell = "/bin/sh"`

and

`.vimrc set shell=/bin/sh`

But still, 

> your shell /bin/bash can't handle traditional UNIX...

I'm just kind of puzzled here because it almost seems like this has *nothing to do with Syntastic* and more like *vim is ignoring my shell settings*

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 1, run the checker, run `:mes`, and post the output.

**Comment by her** [comment]
Okay it's fixed, I had duplicate conflicting shell settings 

`let g:syntastic_shell = "/bin/sh"`
`let g:syntastic_shell = "/bin/bash"`

*blushing*

Thank you for helping me get that sorted it out. I'll close this issue now. Have a wonderful weekend and thank you again for syntastic!
