### ISSUE TITLE
Please add PHP7 support 

### ISSUE THREAD

**Issue by NextSeason** [scrooloose/syntastic#1852]

**Comment by lcd047** [comment]
What happens when you try to use the existing `php` checker with PHP 7?

**Comment by NextSeason** [comment]
@lcd047 

I got some error messages if the php coding include some syntax only be supported in php7

for example : 

The code ```use NS\{ Router, Controller };```  will get error message  ```error | parse error, expecting `"identifier( T_STRING )"'
The code ```$x = $list[ 0 ] ?? true``` will get error message ```error | parse error```

Is there any way to fix error messages like these ?

**Comment by lcd047** [comment]
Did you point `g:syntastic_php_php_exec` to a PHP 7 executable?

**Comment by NextSeason** [comment]
@lcd047 

I think i did not. 
Do you mean I can add ```g:syntastic_php_php_exec = something``` in .vimrc to solve the problem ?
Thanks for your reply.

**Comment by lcd047** [comment]
Syntastic itself doesn't care about the syntax of your files.  It just runs third-party linters, and show their output to you in a window.  Now, if your `php` checker points to an old PHP binary, you'll get errors about new PHP 7 construct.  If you point `g:syntastic_php_php_exec` to the PHP 7 binary it _might_  solve your problem, provided that you configure it correctly.  Read the manual to find out how to do that, and feel free to re-open this if you find an actual problem in syntastic.

**Comment by NextSeason** [comment]
@lcd047 Thank you very much. It's working well after I point ```g:syntastic_php_php_exec``` to my php7 binary file.
