### ISSUE TITLE
Add an option to display signs for errors only

### ISSUE THREAD

**Issue by Coacher** [scrooloose/syntastic#1853]
Hello.

I like signs for errors because they show where important problems are without jumping through loclist.
Given that signs consume some vertical space and that sometimes warnings cannot be avoided I'd like to have the ability to display signs for errors only.

If I manually undefine syntastic's warning signs, I get errors when syntastic reruns checkers.

**Comment by Coacher** [comment]
For clarity, I'd like to see warnings elsewhere, e.g. in loclist, but not in signs.

**Comment by lcd047** [comment]
> If I manually undefine syntastic's warning signs, I get errors when syntastic reruns checkers.

This is what `syntastic_quiet_messages` is for:
```vim
let g:syntastic_quiet_messages = { "!level": "errors" }
```

> For clarity, I'd like to see warnings elsewhere, e.g. in loclist, but not in signs.

This is not going to happen, sorry.  Syntastic works with a single `loclist`, and it has several mechanisms (named "notifiers" in the manual) to display it.  This is a desgn decision.

You can however disable signs when there are no errors.  Something like this:
```vim
function! SyntasticCheckHook(errors)
    let g:syntastic_enable_signs = len(filter(copy(a:errors), 'v:val["type"] ==? "E"')) != 0
endfunction
```

You'll still see signs for warnings, but only when there are errors amlong with them.

**Comment by Coacher** [comment]
> You can however disable signs when there are no errors. Something like this: ...

Thanks for the idea, but this hook works globally. This leads to inconsistencies when one buffer has no errors, while the other one has some. I see that there are no per-buffer controls atm.
Could you please add `b:syntastic_enable_signs`?

**Comment by Coacher** [comment]
Hmm, `syntastic#util#var` actually checks for `b:` variant, but it isn't mentioned in docs.
Still, there are stale signs left behind.

**Comment by lcd047** [comment]
That wouldn't work, and you just found out why.  Only highlighting is updated per buffer, everything else is global and managed by Vim, not by syntastic.  Well, your expectation is not realistic to begin with.
