### ISSUE TITLE
Filetype set in modeline not respected for checkers

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [scrooloose/syntastic#1855]
So, I have a `.mustache` file with this as the first line:

    // vim: ai:sts=3:sw=3:filetype=javascript

Syntastic, however, treats it as an HTML file; giving me a ton of HTML-related errors for “unescaped `&amp;`'s”. This is fixed if I `:SyntasticReset`; but it'd be ideal if Syntastic picked up on the filetype-change-immediately-after-opening caused by the modeline.

**Comment by lcd047** [comment]
Syntastic doesn't try to detect the `filetype`, it just uses the one it finds in place.  It's up to you to set the `filetype` correctly (and fix whatever it's setting it incorrectly).  Fortunately you can use `verbose set` to find out where an option was last set:
```vim
:verb set ft
```

**Comment by ELLIOTTCABLE** [comment]
Er, it's set correctly, Syntastic just isn't respecting it (because it's set belatedly, presumably, by the modeline.)

Like I said, `:SyntasticReset` causes it to recognize the correct filetype, and then respect it.

**Comment by lcd047** [comment]
Like I said: syntastic uses whatever it finds there.  It doesn't question why the filetype is set as it is, nor does it try to guess a better one.  It just uses whatever it's given to it by Vim.  Now, if syntastic sees a different `filetype` than the one you set in your `modeline` but only on the first run, then you're probably running Neovim (as far as I can tell Vim itself doesn't do that), and you just found a bug in it.

**Comment by ELLIOTTCABLE** [comment]
Errrr, nope, definitely vim:

```
> mvim --version   
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 30 2016 22:43:55)
MacOS X (unix) version
Included patches: 1-1831
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +fullscreen      -mzscheme        +textobjects
+channel         -gettext         +netbeans_intg   +timers
+cindent         -hangul_input    +odbeditor       +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +transparency
+cmdline_compl   +job             +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          -xpm
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.12/Frameworks -I/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/Cellar/python/2.7.12/Frameworks -L/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/opt/lua/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.12/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby    
```

I guess: tl;dr “what you're saying happening isn't happening” feels like a little bit of an … unnecessary … response; and I would much prefer “what's happening is due to a limitation of vim / is desired behaviour / is outside the scope of this project”, y'know?

But that aside, I'm not at all sure that my diagnosis is correct, either … do you have any ideas as to how I can debug this? (If it *is* what I suspect: I totally get where you're coming from, that you only check once, and use whatever you find … but I *would* like to point out that changing the `filetype` isn't exactly an edge-case in vim-land, and propose that perhaps some sort of `ft`-change-detection might be a worthwhile feature?)

**Comment by lcd047** [comment]
> I guess: tl;dr “what you're saying happening isn't happening” feels like a little bit of an … unnecessary … response;

Let's see what I wrote:

> as far as I can tell Vim itself doesn't do that, at least not in recent versions

So how did you go from "as far as I can tell Vim itself doesn't do that" to "[it] isn't happening"?

> do you have any ideas as to how I can debug this?

One way to start: disable syntastic, and add this to your vimrc:
```vim
function! ShowFt(where, fname)
    echomsg a:where . ': ' . a:fname . ': ft = ' . &filetype
    verbose set filetype
endfunction

autocmd BufReadPost  * call ShowFt('BufReadPost', expand('<afile>', 1))
autocmd BufWritePost  * call ShowFt('BufWritePost',  expand('<afile>', 1))
```

> but I *would* like to point out that changing the `filetype` isn't exactly an edge-case in vim-land, and propose that perhaps some sort of `ft`-change-detection might be a worthwhile feature?

There's an army of plugins that set `filetype`.  As far as I know, none of them tries to monitor files for _changes_ in `filetype`.  Anyway, like I said: syntastic _uses_ the `filetype`.  It never tries to _change_ it.  That's the first design assumption of syntastic, that the `filetype` is set correctly, and that it doesn't change under its feet.

**Comment by lcd047** [comment]
Never mind, I figured out why this happens.  I'll try to find a workaround, hopefully in a few days.

**Comment by ELLIOTTCABLE** [comment]
Yikes!

I'm sorry if I came off confrontational; I also maintain software, and know how shitty it can be. Again: I'm very okay if the fix is out-of-scope or not related.

Let me know if you still want me to run any debugging or verbose-mode stuff. And no hurry! o7

**Comment by lcd047** [comment]
No, I understand exactly what's going on, it's a bug in syntastic that affects `check_on_open`.  Sadly that was introduced as a fix for another bug, related to handling multiple files. :smile:

**Comment by lcd047** [comment]
Please try d50e8c0.  It's a nontrivial change to the most fragile part of syntastic, so expect new bugs.
