### ISSUE TITLE
Balloon conflict with tsuquyomi

### ISSUE THREAD

**Issue by Torwori** [scrooloose/syntastic#1857]
https://github.com/Quramy/tsuquyomi/issues/83

Setting `let g:syntastic_enable_balloons = 0` doesn't allow tsuquyomi to set balloonexpr, causing no ballons to work. :balloon::disappointed:

**Comment by lcd047** [comment]
Syntastic has its own balloon mechanism which works fine with both builtin and external checkers, as long as `g:syntastic_enable_balloons` is set to 1.  Once you set it to 0, syntastic no longer tries to do anything with balloons.  Whether tsuquyomi can or can't do anything useful with balloons after you set `g:syntastic_enable_balloons` to 0, has nothing to do with syntastic.

I can only speculate that tsuquyomi would have to provide a syntastic notifier for that to work, but adding third party notifiers isn't part of syntastic's public API (and there is currently no plan to go there).  So basically you're on your own.  Sorry about that.

**Comment by Torwori** [comment]
Ah, bummer. Thanks for the quick response.

**Comment by szurcher** [comment]
The response is incorrect. Syntastic very much DOES do something with balloons even if `g:syntastic_enable_balloons` is set to 0. Specifically, this line:
`        set noballooneval`
https://github.com/vim-syntastic/syntastic/blob/master/plugin/syntastic/balloons.vim#L41

I haven't traced why or how it's called, but it definitely is called, and it is called _after_ the user's vimrc has run.  So, Syntastic is turning off ballooneval for everyone!

You can see it was syntastic that did the deed by:
1) Make sure you have ballooneval set in your vimrc
2) Open a file in your balloon_eval having vim program
3) Type `:4verbose set beval?`

As a bandaid in my local copy of Syntastic, I've changed this line:
`    if has('balloon_eval')`
https://github.com/vim-syntastic/syntastic/blob/master/plugin/syntastic/balloons.vim#L38
as follows:
`if self.enabled() && has('balloon_eval')`
to match up with this similar line in the refresh function:
`    if self.enabled() && !a:loclist.isEmpty()`
https://github.com/vim-syntastic/syntastic/blob/master/plugin/syntastic/balloons.vim#L26
I have no idea if this is a good or proper solution, but it did make Syntastic stop clobbering my balloon setting!
