### ISSUE TITLE
Syntatstic stopped working on open/save

### ISSUE THREAD

**Issue by nshibalov** [scrooloose/syntastic#1860]
Hi, I have a problem with latest Syntastic on Windows 10 x64, when I open or save file check doesn't start:
```
syntastic: 3.121826: UpdateErrors (auto): default checkers
syntastic: 3.127981: _skip_file: skipping checks
```

I have found that this is because of changes in last [commit](https://github.com/scrooloose/syntastic/commit/d50e8c0f6b1e6352b97d4176d19c53a96d1d64ec#diff-85cd52db4286b8a8afdba6693f9638a4), where **syntastic#util#fname2buf** was added. This function (as I understand) expands fname to absolute file name and because of that **bufnr** returns **-1**. If I change code to:
```
" Returns the buffer number of a filename
function! syntastic#util#fname2buf(fname) abort " {{{2
    " comment on next line:
    " return bufnr('^' . escape( fnamemodify(a:fname, ':p'), '\$.*~[' ) . '$')
    return bufnr(a:fname)
endfunction " }}}2
```
Everything starts to work. I can imagine that this may not be the best solution, so ask for your help.

PS: Check on open (with **let g:syntastic_check_on_open = 1**) still not working, but **:w** and **:SyntaticCheck** works.

I use latest Vim without Cream (https://sourceforge.net/projects/cream/files/Vim/7.4.2066):
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 17 2016 19:50:24)
MS-Windows 32-bit GUI version
Included patches: 1-2066
Compiled by digitectNO@SPAMdancingpaper.com:http://SteveHallArchitecture.com
Huge version with GUI.  Features included (+) or not (-):

++builtin_terms +acl +arabic +autocmd +balloon_eval +browse +byte_offset +channel +cindent +clientserver +clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments +conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con_gui +diff +digraphs -directx -dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path +find_in_path +float +folding -footer +gettext/dyn -hangul_input +iconv/dyn +insert_expand +job +jumplist +keymap +langmap +libcall +linebreak +lispindent +listcmds +localmap +lua/dyn +menu +mksession +modify_fname +mouse +mouseshape +multi_byte_ime/dyn +multi_lang -mzscheme +netbeans_intg +num64 -ole +packages +path_extra +perl/dyn +persistent_undo -postscript +printer +profile +python/dyn +python3/dyn +quickfix +reltime +rightleft +ruby/dyn +scrollbind +signs +smartindent +startuptime +statusline -sun_workshop +syntax -tag_any_white +tag_binary +tag_old_static -tcl -termguicolors -termresponse +textobjects -tgetent +timers +title +toolbar +user_commands +vertsplit +viminfo +virtualedit +visual +visualextra +vreplace +wildignore +wildmenu +windows +writebackup -xfontset -xim -xpm_w32 -xterm_save 

   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
    system menu file: "$VIMRUNTIME\menu.vim"

Compilation: i686-pc-mingw32-gcc -Iproto -DWIN32 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=i686 -Wall -I/cygdrive/c/strawberry/perl/lib/Core -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL="perl518.dll" -I/cygdrive/c/PROGRA~2/Lua/5.1/include -I/cygdrive/c/PROGRA~2/Lua/5.1 -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL="lua51.dll" -DFEAT_RUBY -I /cygdrive/c/Ruby22/lib/ruby/2.2.0/i386-mingw32 -I /cygdrive/c/Ruby22/include/ruby-2.2.0 -I /cygdrive/c/Ruby22/include/ruby-2.2.0/i386-mingw32 -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL="msvcrt-ruby220.dll" -DDYNAMIC_RUBY_VER=22 -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL="python27.dll" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL="python33.dll" -O3 -fomit-frame-pointer -freg-struct-return -s

Linking: i686-pc-mingw32-gcc -Iproto -DWIN32 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=i686 -Wall -I/cygdrive/c/strawberry/perl/lib/Core -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL="perl518.dll" -I/cygdrive/c/PROGRA~2/Lua/5.1/include -I/cygdrive/c/PROGRA~2/Lua/5.1 -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL="lua51.dll" -DFEAT_RUBY -I /cygdrive/c/Ruby22/lib/ruby/2.2.0/i386-mingw32 -I /cygdrive/c/Ruby22/include/ruby-2.2.0 -I /cygdrive/c/Ruby22/include/ruby-2.2.0/i386-mingw32 -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL="msvcrt-ruby220.dll" -DDYNAMIC_RUBY_VER=22 -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL="python27.dll" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL="python33.dll" -O3 -fomit-frame-pointer -freg-struct-return -s -mwindows -o gvim.exe -lkernel32 -luser32 -lgdi32 -ladvapi32 -lcomdlg32 -lcomctl32 -lversion -lwsock32 -lole32 -luuid      
```

**Comment by lcd047** [comment]
What is the value of `fname` for the failing filenames?  Please add something like this to the beginning of the function to find out:
```vim
echomsg string(a:fname) . ' -> ' . bufnr('^' . escape( fnamemodify(a:fname, ':p'), '\$.*~[' ) . '$')
```

**Comment by nshibalov** [comment]
I changed function to:
```
" Returns the buffer number of a filename
function! syntastic#util#fname2buf(fname) abort " {{{2
    " return bufnr('^' . escape( fnamemodify(a:fname, ':p'), '\$.*~[' ) . '$')
    echomsg string(a:fname) . ' -> ' . bufnr('^' . escape( fnamemodify(a:fname, ':p'), '\$.*~[' ) . '$')
    echomsg '^' . escape( fnamemodify(a:fname, ':p'), '\$.*~[' ) . '$'
    return bufnr(a:fname)
endfunction " }}}2
```
Result is:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
'' -> -1
^d:\\my\\networm\\home\\vimfiles\\bundle\\syntastic-master\\autoload\\syntastic\\$
"~\vimfiles\bundle\syntastic-master\autoload\syntastic\util.vim" [unix] 558L, 17757C
'util.vim' -> -1
^d:\\my\\networm\\home\\vimfiles\\bundle\\syntastic-master\\autoload\\syntastic\\util\.vim$
"util.vim" 558 lines --0%--
```

`:set shellslash?` returns `noshellslash`

**Comment by lcd047** [comment]
Please try 287aeeb.

**Comment by nshibalov** [comment]
Thank you, now when you save the file check is performed.
But still when opening file check does not occur (with let **g:syntastic_check_on_open = 1**).
Should I close issue and create new?

**Comment by lcd047** [comment]
The issues are related.  Where do you set `g:syntastic_check_on_open`?

**Comment by nshibalov** [comment]
In my _vimrc file:
```
" Syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_debug = 0
let g:syntastic_enable_balloons = 0
let g:syntastic_enable_signs = 1
let g:syntastic_aggregate_errors = 1
```

**Comment by lcd047** [comment]
So, does this problem also go away if you just return `bufnr(a:fname)` in the function `syntastic#util#fname2buf()` above?

**Comment by fooby** [comment]
Hi, I installed syntastic today on a new windows vim install and also found this out. I did some digging over the last hour or two and found some info which might help.

To start with, I created a file in the following location: D:\devel\projects\personal\blah\hello.js

(note: shellslash is set to 0)

When saving, it doesn't trigger the check. The log output shows:

    "hello.js" 1L, 6C written
    syntastic: 11.586220: &shell = 'C:\WINDOWS\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellr
    edir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '(', &shellxescape = '"&|<>()@^'
    syntastic: 11.589622: UpdateErrors (auto): default checkers
    syntastic: 11.591871: _skip_file: skipping checks


However, when calling SyntasticCheck, it does work:

    syntastic: 13.500825: &shell = 'C:\WINDOWS\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellr
    edir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '(', &shellxescape = '"&|<>()@^'
    syntastic: 13.503060: UpdateErrors: default checkers
    syntastic: 13.505976: CacheErrors: default checkers
    syntastic: 13.508856: g:syntastic_aggregate_errors = 0
    syntastic: 13.510758: getcwd() = 'D:\devel\projects\personal\blah'
    syntastic: 13.935926: system: command run in 0.407299s
    syntastic: 13.937283: CacheErrors: Invoking checker: javascript/eslint
    syntastic: 13.939856: SyntasticMake: called with options: {'postprocess': ['guards'], 'errorformat': '%E%f: line %l\, col %c\, Error -
     %m,%W%f: line %l\, col %c\, Warning - %m', 'makeprg': 'eslint -f compact hello.js'}
    syntastic: 14.793836: system: command run in 0.849024s

    (further syntastic output but basically everything works here)

Next I tried the VIM debugger. And tracked the error down to syntastic#util#fname2buf at: https://github.com/scrooloose/syntastic/blob/d50e8c0f6b1e6352b97d4176d19c53a96d1d64ec/autoload/syntastic/util.vim#L276 from the commit d50e8c0f6b1e6352b97d4176d19c53a96d1d64ec a few days earlier.

fname2buf is called from BufReadPostHook to resolve the buf number, but instead it's resolving to -1 which causes problems down the track.

Here's a short debugging session. Beginning with:

    debug :w

    Entering Debug mode.  Type "cont" to continue.
    cmd: w
    "hello.js" 2L, 12C written
    BufWritePost Auto commands for "*"
    cmd: call s:BufWritePostHook(expand('<afile>', 1))
    >s
    function <SNR>22_BufWritePostHook
    line 1: let buf = syntastic#util#fname2buf(a:fname)
    >s
    function <SNR>22_BufWritePostHook[1]..syntastic#util#fname2buf
    line 1: return bufnr('^' . escape( fnamemodify(a:fname, ':p'), '\$.*~[' ) . '$')

Ok, here I've stepped into syntastic#util#fname2buf. I'll execute the same line here as in the function to see what would be returned:

    >echo a:fname
    hello.js
    >echo bufnr('^' . escape( fnamemodify(a:fname, ':p'), '\$.*~[' ) . '$')
    -1

bufnr returns -1, meaning it didn't find the filename? So I checked what's being passed as the argument:

    >echo escape( fnamemodify(a:fname, ':p'), '\$.*~[' )
    D:\\devel\\projects\\personal\\blah\\hello\.js

I suspected the backslashes introduced via escape() might have been the problem, so I tried bufnr again without escape(). First, double check what value I'm about to pass to bufnr:

    >echo fnamemodify(a:fname, ':p')
    D:\devel\projects\personal\blah\hello.js

Then execute bufnr():

    >echo bufnr('^' . fnamemodify(a:fname, ':p') . '$')
    1

Returned 1, so it works! To conclude, the escaping of the backslashes and the dot is causing bufnr to fail:

    >echo bufnr('^D:\\devel\\projects\\personal\\blah\\hello\.js$')
    -1
    >echo bufnr('^D:\devel\projects\personal\blah\hello.js$')
    1

Decided to check whether escaping the backslashes or the dot specifically caused the problem:

    >echo bufnr('^D:\\devel\\projects\\personal\\blah\\hello.js$')
    -1
    >echo bufnr('^D:\devel\projects\personal\blah\hello\.js$')
    -1        

It's both...escaping either of them interferes with bufnr.

Anyway, I'm not sure how important escaping is with bufnr but looking it up it appears that bufnr uses the "file-pattern" expression instead of a regexp, so that the characters requiring escaping would be different in any case. So either changing the escaped characters or removing the escaping would seem to work.

Just to get things working quickly for myself, I'm currently running a modified fname2buf in autoload/syntastic/util.vim without the escape():

    " Returns the buffer number of a filename
    function! syntastic#util#fname2buf(fname) abort " {{{2
        return bufnr('^' . fnamemodify(a:fname, ':p') . '$')
    endfunction " }}}2

You might still want some sort of escaping, it's up to you I suppose.

**Comment by nshibalov** [comment]
> So, does this problem also go away if you just return bufnr(a:fname) in the function syntastic#util#fname2buf() above?

No, the problem remains.

**Comment by lcd047** [comment]
@fooby Please read the thread you're posting to before interjecting, thank you.

**Comment by lcd047** [comment]
@nshibalov Please set `g:syntastic_debug` to 8 in your vimrc, then open a file that should trigger `check_on_open`.  There should be a few messages in the message log, run `:mes` and post the output.

**Comment by nshibalov** [comment]
With `g:syntastic_check_on_open = 1`:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
syntastic: 0.066640: autocmd: BufEnter, buffer -1 = '', &buftype = ''
syntastic: 0.067348: autocmd: VimEnter, buffer 1 = '', &buftype = ''
"d:\my\networm\dev\python\mts4\mts4.py" [unix] 137L, 5138C
syntastic: 0.255754: autocmd: BufReadPost, buffer 2 = 'mts4.py'
"mts4.py" 137 lines --0%--
```
With `g:syntastic_check_on_open = 0`:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
syntastic: 0.074994: autocmd: BufEnter, buffer -1 = '', &buftype = ''
syntastic: 0.075685: autocmd: VimEnter, buffer 1 = '', &buftype = ''
"d:\my\networm\dev\python\mts4\mts4.py" [unix] 137L, 5138C
"mts4.py" 137 lines --0%--
```

**Comment by lcd047** [comment]
Did you open this file from the command line, or with `:r mts4.py`?

**Comment by nshibalov** [comment]
From the command line. With `:e`, and `:tabnew` check is perfomed.

**Comment by nshibalov** [comment]
Sorry, with `:e`, and `:tabnew` check is perfomed if before already was check either with `:SyntaticCheck` or `:w`.

**Comment by lcd047** [comment]
So the first log above is the result of `vim mts4.py`?  The file `mts4.py` is buffer 2, what is buffer 1?

Please note that when opening multiple files from the command line the buffer is checked only when you switch to its window.

**Comment by nshibalov** [comment]
Ok, i figured it out. I have a hotkey in my file manager to open file with `gvim.exe --remote-tab-silent` and the option `--remote-tab-silent` is the problem. If I run `gvim.exe mts4.py`, or in empty `gvim.exe` session I use commands `:e`, `:tabnew` everything works as it should.

Previous outputs was for `gvim.exe --remote-tab-silent mts4.py`.
Messages for `gvim.exe mts4.py` with `g:syntastic_check_on_open = 1`:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"mts4.py" [unix] 139L, 5142C
syntastic: 0.253544: autocmd: BufReadPost, buffer 1 = 'mts4.py'
syntastic: 0.255114: autocmd: BufEnter, buffer 1 = 'mts4.py', &buftype = ''
syntastic: 0.257611: autocmd: VimEnter, buffer 1 = 'mts4.py', &buftype = ''
```

**Comment by lcd047** [comment]
Please try the new master HEAD.

**Comment by nshibalov** [comment]
Thank you, now everything works.
