### ISSUE TITLE
rubocop checker not found

### ISSUE THREAD

**Issue by red8888** [scrooloose/syntastic#1864]
Windows 10
vim 7.4
syntastic 3.7.0-213
ruby 2.1.8p440 (2015-12-16 revision 53160) [i386-mingw32]

I'm using the version of ruby that comes with chefdk.

Did the following to install rubocop and confirm where rubo and ruby are located:

```
gem install rubocop
gem install gem-path
gem path rubocop
C:/Users/ME/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.42.0
Get-Command ruby
C:\opscode\chefdk\embedded\bin\ruby.exe

```

In my _vimrc
```
let g:syntastic_mode_map = { 'mode': 'active',
    \ 'active_filetypes': [],
    \ 'passive_filetypes': [] }

let g:syntastic_ruby_checkers = ['rubocop']
let g:syntastic_ruby_rubocop_exec='C:\opscode\chefdk\embedded\bin\ruby.exe C:\Users\ME\AppData\Local\chefdk\gem\ruby\2.1.0\gems\rubocop-0.42.0\bin\rubocop'
```

I open a ruby file, write some bad code, and save, but I get no error checking from syntastic it just saves the file like normal and running SyntasticCheck rubocop returns "...checker rubocop is not found"

This is the output of SyntasticInfo when a ruby file is open: 
![image](https://cloud.githubusercontent.com/assets/6265399/18226422/4a65bbd6-71d7-11e6-8581-822b060ff741.png)

`echo syntastic#util#system('echo "$PATH"')`

![image](https://cloud.githubusercontent.com/assets/6265399/18226407/f6601720-71d6-11e6-834b-1732e65ec637.png)

`:echo syntastic#util#system('rubocop --version')
`![image](https://cloud.githubusercontent.com/assets/6265399/18226401/c4326fe6-71d6-11e6-85f5-3c8483e4229e.png)

I just tried to get ruby-lint working and having errors with that as well. It sees ruby-lint but when I do a syntax check I see this:
![image](https://cloud.githubusercontent.com/assets/6265399/18227862/b31dd4d6-7201-11e6-9cb2-cecb406ec9e4.png)

**Comment by lcd047** [comment]
> `C:/Users/ME/AppData/Local/chefdk/gem/ruby/2.1.0/gems/rubocop-0.42.0`
> `C:\opscode\chefdk\embedded\bin\ruby.exe`

Please read `:h syntastic-shellslash`.

> `let g:syntastic_ruby_rubocop_exec='C:\opscode\chefdk\embedded\bin\ruby.exe C:\Users\ME\AppData\Local\chefdk\gem\ruby\2.1.0\gems\rubocop-0.42.0\bin\rubocop'`

`*_exec` is supposed to point to a path, not to a command.  It should also be consistent with the current value of `shellslash`.

> `echo syntastic#util#system('echo "$PATH"')`

I presume that would be something like `:echo syntastic#util#system('echo %PATH%')` on Windows.

> `:echo syntastic#util#system('rubocop --version')`

You need to fix this first.  If Vim can't run commands, syntastic won't work.  What shell are you using?

**Comment by red8888** [comment]
Thanks for getting back to me

I'm using powershell, I have this in my vimrc
```
	set shell=powershell
	set shellcmdflag=-command
```

In powershell to echo the path I would do this `echo $env:Path`
But this gives me an error:
`:echo syntastic#util#system(echo $env:Path)`
![image](https://cloud.githubusercontent.com/assets/6265399/18234115/e14e57d8-72c7-11e6-9428-403958e59795.png)

I tried using set shellslash and change the path to forward slashes, but doesn't seem to make a difference

**Comment by lcd047** [comment]
> I'm using powershell

Please read `:h syntastic-powershell`.

**Comment by red8888** [comment]
god what a waste of time I can't believe I didn't find that info sooner with all the googling I've been doing trying to solve this problem. totally works with the default shell on windows.
