### ISSUE TITLE
python syntastic not hide error after fix this error

### ISSUE THREAD

**Issue by vasyapupkin123456** [scrooloose/syntastic#1870]
If cheked too many blank lines - I fix blank line, but error too many blank lines (6) [E303] showing.

**Comment by vasyapupkin123456** [comment]
Ok, another error this bug too...
If I write print('aaa') and remove ). Syntastic show me error| unexpected EOF while parsing, but if I write ) and write file - syntastic not hide error.

**Comment by lcd047** [comment]
> If cheked too many blank lines - I fix blank line, but error too many blank lines (6) [E303] showing.

Please read `:h syntastic-aggregating-errors`.

> If I write print('aaa') and remove ). Syntastic show me error| unexpected EOF while parsing, but if I write ) and write file - syntastic not hide error.

Please read `:h 'syntastic_auto_loc_list'`.

**Comment by vasyapupkin123456** [comment]
In my option: let g:syntastic_auto_loc_list=1 i.e automatically opened when errors are
detected, and closed when none are detected, but autoclose when no error - not working. I downgrade syntastic and this work correctly

**Comment by lcd047** [comment]
What did you do exactly?  What version of Vim and what version of syntastic are you using?

**Comment by vasyapupkin123456** [comment]
debian jessi: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:07)
syntastic - git version on this repo. Downgrade version vim-scripts/syntastic.

Options:
" Syntastic
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_signs=1
let g:syntastic_quiet_messages = {'level': 'warnings'}
let g:syntastic_auto_loc_list=1 " auto open error window when errors
let g:syntastic_check_on_open=1 " check for errors on file open
" let g:syntastic_error_symbol='✗'
let g:syntastic_error_symbol = "☠"
let g:syntastic_warning_symbol = "⚠"
let g:syntastic_style_error_symbol = "☢"
let g:syntastic_style_warning_symbol = "☹"

let g:syntastic_ignore_files = ['\m\c\.sma$']
" let g:syntastic_python_python_exec = '/usr/bin/python'
" :let g:syntastic_python_checkers=['python']
" let g:syntastic_python_python_exec = '.env/bin/python'
let g:syntastic_python_python_exec = 'python'
let g:syntastic_python_checkers = ['python','flake8']
" let g:syntastic_python_checker_args='--ignore=E501'
" let g:syntastic_python_flake8_args='--ignore=E501,F401,E128,F841,F821,E114,E116,E111' " disable check long str(for 2 spaces)
let g:syntastic_python_flake8_args='--ignore=E501,F401,E128,F841,F821,E114,E116' " disable check long str

**Comment by lcd047** [comment]
What version of Vim are you using?  There's a patchlevel beyond 7.4.  Also, what did you do __exactly__?

**Comment by lcd047** [comment]
Never mind, I can reproduce the problem.  I'll try to find a solution.

**Comment by lcd047** [comment]
This should be fixed in 8ab26a2.
