### ISSUE TITLE
Syntastic reports no errors (custom linter)

### ISSUE THREAD

**Issue by atsepkov** [scrooloose/syntastic#1873]
I'm not sure where the issue is, whether it's on my end or something with syntastic, so I apologize if I'm opening a spurious bug. My use case is running my own linter (source code for plugin: https://github.com/atsepkov/vim-rapydscript/blob/master/syntax_checkers/rapydscript/rapydscript.vim) for my own language (https://github.com/atsepkov/RapydScript). My syntastic portion of vimrc looks like this:

```
Bundle 'scrooloose/syntastic'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
"let g:syntastic_enable_signs=1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_rapydscript_checkers = ['rapydscript']
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '⚠'
```

But when I open the relevant file (rapydscript), nothing gets reported, the same file when analyzed by `rapydscript --lint` in bash shows a bunch of errors in the following format (which I believe matches the format expected by errorformat, unless I misunderstand it):

```
src/output.pyj:2457:12:E:AST_Node:undefined symbol: "AST_Node" [undef]
src/output.pyj:2458:5:E:basic_sourcemap_gen:"basic_sourcemap_gen" is defined but not used [unused-local]
```

As a test I've also tried syntastic with JavaScript + JSHint and it works as expected. Running `:SyntasticInfo` after loading a rapydscript file shows the following:

```
Syntastic version: 3.7.0-224 (Vim 704, Darwin)
Info for filetype: rapydscript
Global mode: active
Filetype rapydscript is active
The current file will be checked automatically
Available checker: rapydscript
Currently enabled checker: rapydscript
```

Setting `g:syntastic_debug=33`, then running `:SyntasticCheck` and `:mes` shows the following:

```
syntastic: 112.806790: g:syntastic_version = '3.7.0-224 (Vim 704, Darwin)'
syntastic: 112.806929: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shell
xquote = '', &shellxescape = '', &autochdir = 0
syntastic: 112.807395: UpdateErrors: default checkers
syntastic: 112.807656: CacheErrors: default checkers
syntastic: 112.808222: g:syntastic_aggregate_errors = 0
syntastic: 112.808345: $TERM = 'xterm-256color-italic'
syntastic: 112.808435: $PATH = '/Users/alexander.tsepkov/.rbenv/shims:/Users/alexander.tsepkov/.rbenv/shims:/Users/alexander.tsepkov/.npm/bin:/Users/alexander
.tsepkov/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin'
syntastic: 112.808552: getcwd() = '/Users/alexander.tsepkov/work/personal/RapydScript'
syntastic: 112.808836: CacheErrors: Invoking checker: rapydscript/rapydscript
syntastic: 112.809559: SyntasticMake: called with options: {'errorformat': '%f:%l:%c:%t:%m', 'makeprg': 'rapydscript --lint src/output.pyj'}
syntastic: 113.487291: system: command run in 0.677297s
syntastic: 113.499133: getLocList: checker rapydscript/rapydscript returned 1
syntastic: 113.501269: getLocList: checker rapydscript/rapydscript run in 0.692302s
```

I'm not seeing anything in the debug data that gives me a hint about what's going on. Anyone more familiar with Syntastic can recommend how to go about debugging this further?

Thanks

**Comment by lcd047** [comment]
A few notes:

* Don't change `g:syntastic_extra_filetypes` in the checker's file.  The checker gets read too late for `g:syntastic_extra_filetypes` to be of any use.  I added a note to that effect to the [guide][guide].
* You can delete the `IsAvailable()` function, the default does that for you.
* `e['vcol']` should be already 0 when you use `%c` in `errorformat`.
* Passing a `highlightname` field between `GetLocList()` and `GetHighlightRegex()` won't work.  I suggest deleting the `GetHighlightRegex()`  function and doing something like this instead:
```vim
for e in loclist                                                                                                                
    let parts = matchlist(e['text'], '\v^([^:]*)\:(.*)')
    if len(parts) > 2 
        let e['hl'] = '\V' . (parts[1] ==# ';' ? ';' : '\<' . escape(parts[1], '\') . '\>')
        let e['text'] = parts[2]
    endif
endfor
```
As for why your checker doesn't work, try setting `g:syntastic_debug` to 3.  Setting it to 33 is useless in this context, since you aren't logging anything checker-specific.

[guide]: https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#external

**Comment by atsepkov** [comment]
Thanks for the feedback. And your suggestion helped me understand what the problem was, it works now. With debug flag of 3 I saw that the message format isn't what I expected:

```
syntastic: 17.716723: g:syntastic_version = '3.7.0-224 (Vim 704, Darwin)'
syntastic: 17.716881: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellx
quote = '', &shellxescape = '', &autochdir = 0
syntastic: 17.717417: UpdateErrors: default checkers
syntastic: 17.717703: CacheErrors: default checkers
syntastic: 17.718638: g:syntastic_aggregate_errors = 0
syntastic: 17.718911: getcwd() = '/Users/alexander.tsepkov/work/personal/RapydScript'
syntastic: 17.719507: CacheErrors: Invoking checker: rapydscript/rapydscript
syntastic: 17.720520: SyntasticMake: called with options: {'errorformat': '%f:%l:%c:%t:%m', 'makeprg': 'rapydscript --lint src/output.pyj'}
syntastic: 18.474820: system: command run in 0.753820s
syntastic: 18.475144: checker output: ['src/output.pyj:ERR:undef:51:14: undefined symbol: "defaults"', 'src/output.pyj:ERR:undef:129:19: undefined symbol: "to
_ascii"', 'src/output.pyj:ERR:undef:137:14: undefined symbol: "make_string"', 'src/output.pyj:ERR:undef:146:19: undefined symbol: "to_ascii"', 'src/output.pyj
:ERR:undef:151:15: undefined symbol: "repeat_string"', 'src/output.pyj:ERR:undef:162:12: undefined symbol: "print_"', 'src/output.pyj:ERR:undef:165:28: undefi
ned symbol: "makePredicate"', 'src/output.pyj:ERR:unused-local:186:12: "might_need_semicolon" is defined but not used', 'src/output.pyj:ERR:undef:187:12: unde
fined symbol: "maybe_newline"', 'src/output.pyj:ERR:undef:200:19: undefined symbol: "last_char"', 'src/output.pyj:ERR:undef:201:45: undefined symbol: "is_iden
tifier_char"', 'src/output.pyj:ERR:unused-local:218:8: "last" is defined but not used', 'src/output.pyj:ERR:undef:221:38: undefined symbol: "print_"', 'src/ou
tput.pyj:ERR:unused-local:224:8: "might_need_space" is defined but not used', 'src/output.pyj:ERR:undef:228:12: undefined symbol: "print_"', 'src/output.pyj:E
RR:undef:228:19: undefined symbol: "make_indent"', 'src/output.pyj:ERR:undef:234:18: undefined symbol: "next_indent"', 'src/output.pyj:ERR:unused-local:239:8:
... the rest omitted for brevity ...
```

I had an older version of linter from npm, which global path was referencing instead of the most up-to-date one, the older version used a different error format. I will also update my syntax file per your suggestions. On a related note:

- Is this (the inconsistent error format) something syntastic can detect and warn about at load time or would it not be worth it? I guess this is a one-time issue for most linters.
- Could I submit rapydscript linter to be part of syntastic core, seeing how coffeescript and typescript is already there and we occupy a similar niche?

Thanks

**Comment by lcd047** [comment]
> Is this (the inconsistent error format) something syntastic can detect and warn about at load time or would it not be worth it? I guess this is a one-time issue for most linters.

The short answer is no.  There is a field named `valid` in `loclist` errors, that gets set to 0 for lines in the linter's output that can't get matched by `errorformat`.  However, that field can be set to 0 by syntastic itself, for many other reasons.  You can't imagine how "creative" the error formats can be across linters, and how wrong parsing them with `errorformat` actually is. _shrug_

> Could I submit rapydscript linter to be part of syntastic core

You may, but (1) I would include it only if I can actually test it myself.  The problem above seems to imply there's a version check missing.  And (2) you actually care about this thing.  For me it would be just the 220th checker in syntastic, for a language about which I know only the name. _shrug_

**Comment by atsepkov** [comment]
>You may, but (1) I would include it only if I can actually test it myself. The problem above seems to imply there's a version check missing. And (2) you actually care about this thing. For me it would be just the 220th checker in syntastic, for a language about which I know only the name. shrug

For number 1, would the procedure below be good enough?
```
npm install -g rapydscript
create a file that triggers a couple warnings, a couple errors (I can provide exact source)
add the above g:syntastic_rapydscript_checkers and setf rapydscript, :w to trigger linting
```
For version check, I've already added and tested the following, works like a charm:
```
function! SyntaxCheckers_rapydscript_rapydscript_IsAvailable() dict
    if !executable(self.getExec())
        return 0
    endif
    return syntastic#util#versionIsAtLeast(self.getVersion(), [0, 5, 7])
endfunction
```

For number 2, I completely understand your point of view. I've been building this for 4 years, and I write my own projects using it and while the user community is small, it's not going anywhere, project got 1500 downloads over the last week. With recent improvements to JavaScript standards, the project (and it's ability to automatically optimize user code) is becoming even more relevant in my work. Likewise, there are open-source projects relying on it, such as http://www.glowscript.org

Here is the latest gist of the code: https://gist.github.com/atsepkov/b84be11302fb3a8a04961d9ef953863a

Should I do a pull request?

**Comment by lcd047** [comment]
> For number 1, would the procedure below be good enough?

Sure.

> For version check, I've already added and tested the following

Ok.

> Here is the latest gist of the code: https://gist.github.com/atsepkov/b84be11302fb3a8a04961d9ef953863a

Two problems with this:

* syntastic only supports errors and warnings, not info messages.  That's essentially a legacy limitation, but it's way too late to fix it now.  I believe what happens if you leave `errorformat` like this info messages are turned into errors.
* Comma as a separator in `errorformat` is much less reliable than colon.  The reasons for this are complicated, and have to do with the way Vim sets `isfname`, and the way filenamed are matched by `errorformat`.  There isn't much you (or syntastic) can do about it though.  Just beware that files with names containing certain characters will never be matched on some systems.  Feel free to send hate mail to `vim_dev` about that.

> Should I do a pull request?

If you do, please add:

* a license to the checker file
* an entry to the manual
* an entry for `rapydscript` to the registry
* a note to README that RapydScript is a supported language.
