### ISSUE TITLE
Set up checkers' path

### ISSUE THREAD

**Issue by Henrique1792** [scrooloose/syntastic#1874]
Good evening =)

I got an issue with syntastic - the $PATH isn't pointing to the right place - and I cannot use any checker due to it.
How can I change that value?

Thanks =)

**Comment by lcd047** [comment]
Setting `$PATH` correctly is between your Vim, your shell, and your OS.  It has nothing to do with syntastic.

What OS are you using, and what shell?  Are you using terminal Vim or GVim?  How did you conclude your `$PATH` is not right?

**Comment by Henrique1792** [comment]
OS: debian jessie
Shell: terminator/gnome-shell
Using terminal version

I concluded  it after looking around and many people had the same issue.
 ECHO $PATH and loc at README file have a matching output.

Also: I have checkers installed and none of them are sat like available.

Maybe it's not related, but I didn't found anything to solve anywhere else.

**Comment by lcd047** [comment]
Then please back up une step and explain what did you do, what did you expect to happen, and what happened instead.  Please provide only concrete, actionable information (i.e. reporting about other people's problems is useless).

**Comment by Henrique1792** [comment]
Right after regular installation and default configuration (using README) - any checker was available. I've checked .vim/plugged/syntastic/syntastic_checkers and they were there.
SyntasticInfo returned a simple dash, like no checker was installed.
Due to a post (which I lost the link, unfortunately) - and FAQ on README - I looked for $PATH issues and it actually doesn't make sense.

Anyway, I got another issue with my system and had to format it.

But please, take a look at default $PATH - I didn't change anything from default configuration, and it messed up.
Thanks.

**Comment by lcd047** [comment]
Syntastic __uses__ the `$PATH` provided by your shell, Vim, etc.  Syntastic doesn't __change__ `$PATH`.
