### ISSUE TITLE
Consider Supporting Vim 8 Jobs

### ISSUE THREAD

**Issue by maxbucknell** [scrooloose/syntastic#1876]
I couldn't find any issue about this already.

Is there a plan to support the jobs feature in Vim 8? I had to turn off Syntastic for many files, because the linting process takes too long. If it could be architected in such a way as to not block `:w`, I would love to start using it again.

The [release notes][1] for the jobs feature specifically state:

> Vim can now start a job, communicate with it and stop it.  This is very useful
to run a process for completion, syntax checking, etc.

So it seems that it's a feature match made in heaven. If there is no plan, please let me know, because I might have a go at it.

[1]: https://github.com/vim/vim/blob/master/runtime/doc/version8.txt#L56

**Comment by lcd047** [comment]
Please see #699.
