### ISSUE TITLE
Doesn't seem to work with html tidy on Mac OS X El Capitan

### ISSUE THREAD

**Issue by arooni** [scrooloose/syntastic#1878]
Seeing 
syntastic: warning: variable g:syntastic_html_checker is deprecated
Error detected while processing function <SNR>63_VimEnterHook[14]..<SNR>63_UpdateErrors[15]..<SNR>63_CacheErrors[22]..341[17]..348:
line    1:
E730: using List as a String
Press ENTER or type command to continue
Error detected while processing function <SNR>63_VimEnterHook[14]..<SNR>63_UpdateErrors[15]..<SNR>63_CacheErrors:
line   22:
E712: Argument of extend() must be a List or Dictionary
Press ENTER or type command to continue

when I try to vim foo.html

Here are my relevant lines in my .vimrc file 

" Recommneded settings via https://github.com/scrooloose/syntastic
set statusline+=%#warningmsg#

" Turn off style messages
"let g:syntastic_quiet_messages = { "!level":  "errors" }
let g:syntastic_loc_list_height=1

set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_error_symbol = "✗"
let g:syntastic_warning_symbol ="⚠"

" Syntax checkers
let g:syntastic_css_checkers = ['csslint']
let g:syntastic_html_checker = ['tidy']

" From https://github.com/vim-ruby/vim-ruby/issues/166
" We like fish but need a POSIX compatible shell
set shell=/bin/bash

Here is me setting syntastic_debug =1 and opening the file in question:

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"current.html" 514L, 62071C
syntastic: 0.216403: g:syntastic_version = '3.7.0-225 (Vim 704, Darwin)'
syntastic: 0.216676: &shell = '/bin/bash' (!), &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &shellxescape =
 '', &autochdir = 0
syntastic: 0.217337: UpdateErrors (auto): default checkers
syntastic: 0.217712: CacheErrors: default checkers
syntastic: 0.218643: g:syntastic_aggregate_errors = 0
syntastic: 0.218991: getcwd() = '/Users/david/workspace'

Please let me know if you need anything else.  You've got a great tool here; excited to get it working.

**Comment by lcd047** [comment]
> syntastic: warning: variable g:syntastic_html_checker is deprecated

Fix this first.

**Comment by arooni** [comment]
And that made it work!  

Moving 
let g:syntastic_html_checker = ['tidy'] 

to

let g:syntastic_html_checkers = ['tidy']

Fixed it!  

Now if I could just speed up editing this 61K HTML file I'd be all set.  But I don't think that's a syntastic issue; more of a why is this HTML 61K issue :P
