### ISSUE TITLE
how to remove the green bar ?

### ISSUE THREAD

**Issue by chaos5958** [scrooloose/syntastic#1880]
The green bar in the below image is shown when I type the command like ":SyatasticCheck".
But how can I remove this bar when I wanna hide it? 
Is it also possible to remove both of this bar and the error-showing window (which can be closed by the command "lcose") by one command? 

Thanks :)

![selection_001](https://cloud.githubusercontent.com/assets/15246011/18941276/9f2bb034-85c4-11e6-8f54-0355c388fdc5.png)

**Comment by lcd047** [comment]
> But how can I remove this bar when I wanna hide it?

With Vim 8.0 or later: `:h 'signcolumn'`.  With an older Vim: upgrade to Vim 8.0 or later.

> Is it also possible to remove both of this bar and the error-showing window (which can be closed by the command "lcose") by one command?

`:h :SyntasticReset`
