### ISSUE TITLE
The function SyntasticStatuslineFlag() is a known function.

### ISSUE THREAD

**Issue by z1003031335** [scrooloose/syntastic#1882]
set statusline+=%{SyntasticStatuslineFlag()}

**Comment by lcd047** [comment]
Please explain (preferably in fully formed English sentences) what did you do, what did you expect to happen, and what happened instead.

**Comment by z1003031335** [comment]
@lcd047 Sorry,i assumed that it is a simple problem,so i didn't give a detailed description.The plugin vim-airline uses this function before syntastic being loaded,causing the problem.The problem has been solved by me.
