### ISSUE TITLE
Stucked every time with java in the following situation

### ISSUE THREAD

**Issue by yafngzh** [scrooloose/syntastic#1886]
vim version: 
![image](https://cloud.githubusercontent.com/assets/5991357/19116958/e53f2670-8b49-11e6-9185-0a8a856d3c82.png)

When I did as follows, vim stucked.
https://spring.io/guides/gs/rest-service/#initial
After I cleaned this plugin, it worked well.

I checked the progress of vim, found out it stucked here,
![image](https://cloud.githubusercontent.com/assets/5991357/19116589/a56ded34-8b48-11e6-8dd1-d89c844c8aa2.png)

**Comment by lcd047** [comment]
Please explain (preferably without screenshots) what you did, what did you expect to happen, and what happened instead.  Also please explain why you think this has anything to do with syntastic.  Please note that "it no longer happens when I remove syntastic" is not really a logical explanation.

**Comment by yafngzh** [comment]
It stucked each time when I **_used ":w"_** in vim. Syatastic would check the grammer at this time right? I also made some experiments to verify my suppose. For example, set the option ---- let g:syntastic_check_on_open=1,  it stucked when I opened the file;  clean syntastic plugin, it works well.  Besides even there exists errors in my file (official code, probabely not), are there any options,such as timeout, to avoid stucking? Syntastic helped me a lot, thanks for helping me solve the problem!

**Comment by lcd047** [comment]
There could be many reasons for syntastic getting stuck, ranging from you using the wrong `shell`-related options, to the command line being chopped off by Vim, to `javac` running into various limits.  What checker are you using?  Does it work for a minimal "hello, world" project?  Did you enable debug (`:h syntastic-debug`) to find out what's actually going on?

The `javac` checker in syntastic is fragile for many reasons, the main one being that `javac` itself is hostile to being run on command line.  You really should be using something like Eclim for anything more complicated than toy projects.
