### ISSUE TITLE
Can't Enable Python Checkers

### ISSUE THREAD

**Issue by clarkpede** [scrooloose/syntastic#1887]
No matter what I do, I can't get any of the python checkers to be enabled by default.  When I run ":SyntasticCheck" on a python file, no checks are performed.  But when I run ":SyntasticCheck python", ":SyntasticCheck flake8", or ":SyntasticCheck pyflakes", Syntastic works as expected.

When I run ":SyntasticInfo" in a python file, I get:

Syntastic version: 3.7.0-230 (Vim 704, Linux)
Info for filetype: python
Global mode: active
Passive filetype: fortran
Filetype python is active
The current file will be checked automatically
syntastic: 48.765158: system: command run in 0.747605s
syntastic: 48.793992: system: command run in 0.021185s
Available checkers: flake8 pep8 pycodestyle pyflakes pylint python
Currently enabled checkers: -
syntastic: 48.795908: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = '

As you can see, there are no "currently enabled checkers." I've tried a dozen different ways to enable python checkers in my .vimrc file, and nothing worked.

Here's the relevant lines from my .vimrc:
```
" Syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_mode_map = {
    \ "mode": "active",
    \ "active_filetypes": ["python", "cpp"],
    \ "passive_filetypes": ["fortran"] }
let g:syntastic_debug = 1
let g:syntastic_python_checkers='flake8'
let g:syntastic_fortran_compiler = 'mpif90'
let g:syntastic_cpp_compiler = 'g++'
let g:syntastic_cpp_compiler_options = ' -std=c++11'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_error_symbol='✗'
let g:syntastic_warning_symbol='⚠'
```

I do not have eclim or youcompleteme currently installed.

I know at least flake8 and pyflakes are in the "~/.local/bin/" folder, which vim sees on the path.  I checked the path using:
:echo syntastic#util#system('echo "$PATH"')

**Comment by lcd047** [comment]
> `let g:syntastic_python_checkers='flake8'`

Fix this first.  It's supposed to be a __list__, not a single string.  I'm actually surprised you didn't get an exception for it.

**Comment by clarkpede** [comment]
Okay, I figured it out.  If the first definition I enter when I start up vim is:
`let g:syntastic_python_checkers='flake8'`
And then I try to change it within vim to a list, it gives me the error:
E706: Variable type mismatch for: g:syntastic_python_checkers

But, if I start up vim with the following:
`let g:syntastic_python_checkers=['flake8']`
And I try to change it within vim to a string, it gives the same error.  

Basically, Vim seems to assume that the variable type of syntastic_python_checkers must be whatever it initially was when Vim started.  An exception occurs if you try to change it from one type of variable to another, but not if you start out with the wrong variable type. In fact, I tested, and you can even start up vim with a dictionary defintion:
`let g:syntastic_python_checkers= {'cell':5551017346, 'home':5558038728,'work':'?'}`
without it complaining, even though this is obviously an invalid setting.

**Comment by lcd047** [comment]
> So changing the settings, closing Vim, and then restarting it works. But I had gotten stuck trying to change the setting and simply ":source %" to update the Vim setting.

Older Vim versions insisted that once assigned, a variable can't change its type.  This limitation has been removed in Vim 8.0.  You could still have avoided it, by running `:unlet g:syntastic_python_checkers` before assigning the new value.

Also, this is one of the reasons why `:source`-ing your vimrc to update settings seldom works as expected.

> I tested, and you can even start up vim with a dictionary defintion:

Yeah, syntastic falls back to a pre-defined value if the `*_checkers` you provide is not meaningful.  Checking all user variables for sanity would be nice.  It would also take a few weeks to code, and it would slow down the core to maybe half the current speed. _shrug_
