### ISSUE TITLE
Issues in opening latex documents

### ISSUE THREAD

**Issue by tjansson60** [scrooloose/syntastic#1889]
When opening a latex very simple latex document

```latex
\documentclass[]{article}
\end{document}
```

I get the following error:
```vim
test.tex" 2L, 41C
Error detected while processing function <SNR>25_VimEnterHook..<SNR>25_UpdateErrors..38..syntastic#util#getbufvar..<SNR>27__getbufvar_dumb:
line    2:
E735: Can only compare Dictionary with Dictionary

Press ENTER or type command to continue
Error detected while processing function <SNR>25_VimEnterHook..<SNR>25_UpdateErrors..38..syntastic#util#getbufvar..<SNR>27__getbufvar_dumb:
line    2:
E15: Invalid expression: a:0 && ret ==# ''
Press ENTER or type command to continue
```

The problem did came after I updated the plugin yesterday. I have updated this morning again, but the problem is still there. 

Kind regards
Thomas Jansson

**Comment by tjansson60** [comment]
When I reverted back to 36ead6d (syntastic 3.6.0) the problem is gone.

**Comment by lcd047** [comment]
Right.  Please upgrade to 0a606ae and try again.

**Comment by tjansson60** [comment]
I have just checked with 0a606ae and the problem is gone now. Thanks for the help.
