### ISSUE TITLE
How to check code for kernel module ?

### ISSUE THREAD

**Issue by Arondight** [scrooloose/syntastic#1894]
I add

```vimrc
let g:syntastic_c_include_dirs = ['/usr/lib/modules/4.7.6-1-ARCH/build/include', '/usr/lib/modules/4.7.6-1-ARCH/build/arch/x86/include/']
```

then syntastic can find header files, but I get thousand errors after that about declaration.

Thanks for any help.

**Comment by lcd047** [comment]
Somebody wrote a sort of recipe, mentioned at #1383.  IMO a better approach would be something like this:

* read the manual until you're confident you understand how syntastic works and what it can do
* read `:h syntastic-c-gcc`
* duplicate in syntastic the setup you're using to _build_ the modules.

That's all there is to it.  It's rather long and not particularly user-friendly, but it isn't _conceptually_ complicated.
