### ISSUE TITLE
Weird characters (^[[>1;4590;0c) shown in buffer

### ISSUE THREAD

**Issue by frbor** [scrooloose/syntastic#1896]
When editing clojure and python code weird characters (^[[>1;4590;0c) are inserted on some of the lines:

![vim8_characters](https://cloud.githubusercontent.com/assets/2320183/19379052/6b0920c4-91f0-11e6-8370-e526f83cf510.png)

The characters are only "visually" - they are not inserted in the actual file.

Other have seen the same issue (fisadev/vim-isort#13) related to the [isort plugin](https://github.com/fisadev/vim-isort/), but I do not have that installed.

A workaround for me when using syntastic is to resize the terminal as the characters are then removed. 
In addition, if disable syntastic in vimrc (`g:syntastic_check_on_open=0`), the characters are not shown. Running `:SyntasticCheck` also removes the characters.

I do not know whether this is a bug related to syntastic or vim, but since the problem is removed by disabling syntastic I have reported it here.

Syntastic version: 3.7.0-237 (Vim 800, Linux)
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
Available checkers: flake8 pyflakes pylint python
Currently enabled checker: pylint

**Comment by lcd047** [comment]
Syntastic has no control over low level redraws.  The problem may be _triggered_ by syntastic for some reasons, but it can't be _solved_ from within syntastic.  Please see #822 for a more detailed discussion. _shrug_
