### ISSUE TITLE
Syntastic causes E926 in vim 8.0.32

### ISSUE THREAD

**Issue by jpmv27** [scrooloose/syntastic#1898]
I use syntastic along with plugin vim-easygrep. The latter is configured to report its results in the location list.

Everything works well in vim 7.4.2191.

Since upgrading to 8.0.32, some searches with easygrep fail due to an E926 exception. If I disable syntastic, the problem with easygrep goes away.

The problem only happens if I have `g:syntastic_check_on_open=1` configured. Easygrep must be configured to automatically jump to the first match.

If I repeat the same easygrep search after the failure the first time, then it works as expected. A different easygrep search may or may not succeed.

After a failed easygrep search, :Errors displays a location list with the easygrep results. I get the expected syntastic results in the loclist after running :SyntasticCheck and :Errors again.

Any thoughts?

**Comment by jpmv27** [comment]
I can get the problem to disappear by commenting out the highlighted line below

```
function! s:BufEnterHook(fname) abort " {{{2
    let buf = syntastic#util#fname2buf(a:fname)
    call syntastic#log#debug(g:_SYNTASTIC_DEBUG_AUTOCOMMANDS,
        \ 'autocmd: BufEnter, buffer ' . buf . ' = ' . string(a:fname) . ', &buftype = ' . string(&buftype))
    if buf > 0 && getbufvar(buf, '&buftype') ==# ''
        let idx = index(reverse(copy(s:_check_stack)), buf)
        if idx >= 0
            if !has('vim_starting')
                call remove(s:_check_stack, -idx - 1)
                "call s:UpdateErrors(buf, 1, [])    <--- this line
            endif
        elseif &buftype ==# ''
            call s:notifiers.refresh(g:SyntasticLoclist.current())
        endif
    elseif &buftype ==# 'quickfix'
        " TODO: this is needed because in recent versions of Vim lclose
        " can no longer be called from BufWinLeave
        " TODO: at this point there is no b:syntastic_loclist
        let loclist = filter(copy(getloclist(0)), 'v:val["valid"]')
        let owner = str2nr(getbufvar(buf, 'syntastic_owner_buffer'))
        let buffers = syntastic#util#unique(map(loclist, 'v:val["bufnr"]') + (owner ? [owner] : []))
        if !empty(get(w:, 'syntastic_loclist_set', [])) && !empty(loclist) && empty(filter( buffers, 'syntastic#util#bufIsActive(v:val)' ))
            call SyntasticLoclistHide()
        endif
    endif
endfunction " }}}2

```

**Comment by jpmv27** [comment]
I can reproduce the problem a different way. If Easygrep is configured not to automatically jump to the first match, then the exception happens when a result is selected from the loclist and the corresponding file is opened

**Comment by jpmv27** [comment]
Tested some older versions of vim and this problem started with 7.4.2299, with which I believe you are familiar: [](https://groups.google.com/forum/#!topic/vim_dev/4GKEpx8bvzM)

**Comment by lcd047** [comment]
> The latter is configured to report its results in the location list.

This combination was actually never supposed to work.  As of Vim 8.0, there is _still_ no way to tell, given a random `loclist`, which plugin has created it, nor is there any way to state ownership of a `loclist`.  Now, syntastic takes great care to minimise its interaction with the `loclist` stack, just to avoid situations like this.  But ultimately two (or more) plugins fighting for the same `loclist`s are going to run into conflicts.  Just configure your EasyGrep to use `quickfix` lists instead.

> Since upgrading to 8.0.32, some searches with easygrep fail due to an E926 exception.

E926 is a bug introduced by 7.4.1640.  If you have a `loclist` set up by an `autocmd` and you jump to an entry from it, then any `autocmd`s on open for the file you're jumping to are run before the jump.  If you have another plugin setting `autocmd`s on open, you lose.  At the time I suggested an approach that would have avoided this behaviour, but nobody was convinced there was a problem in the first place. _shrug_

> I can get the problem to disappear by commenting out the highlighted line below

Yeah, if you disable syntastic the problem goes away, you already said that. :)

> Tested some older versions of vim and this problem started with 7.4.2299

The interaction of the 7.4.1640 bug with the 7.4.2299 boobytrap is complicated.  Tracing this to the roots would involve understanding said bugs, understanding how both syntastic and EasyGrep work, and spending a few days validating various hypotheses.  I'm not familiar with the EasyGrep code, and I really don't have time for this kind of legwork.  It isn't at all clear there's a problem in syntastic, as opposed to a bug in Vim and / or in EasyGrep.  Also, you can avoid the problem with a saner setup (i.e. by making EasyGrep use `quickfix` lists).  So my "solution" is to add a note to that effect to the manual: 167a062.  Sorry about that. _shrug_

**Comment by jpmv27** [comment]
Thanks for your reply. What has me confused is that it is my understanding that Syntastic doesn't touch the location list unless the `:Errors` command is used. So I don't understand how the two plugins are "fighting" over the location list.

**Comment by lcd047** [comment]
"Doesn't touch the location list" is a simplification.  What's going on is that syntastic creates a `loclist` to parse errors from checkers, then discards it.  It does that from an `autocmd` on open.  If there's another `autocmd` on open that creates a `loclist`, there's a race condition that can make syntastic use the wrong `loclist`.  Since Vim 7.4.2299 this race condition is more probable than before.  As I said, the race condition can't be avoided, because there is no way to establish ownership over `loclist`s.  Actually, using `loclist`s, `errorformat`, and friends has been syntastic's biggest design mistake.

Then again, I didn't really try to understand how EasyGrep works, so I don't have the entire picture.  You'd think that after 5+ years at this I've seen every possible way syntastic can crash.  Yet every few weeks somebody still comes up with a scenario that I haven't thought of.  So please, if you have a better solution, please feel free to post a PR. _shrug_

**Comment by jpmv27** [comment]
Thanks again. In the discussion about 7.4.2299, I saw that you mentioned this process, but I didn't quite understand it. This clears it up.

Regards, and thanks for your work on this very useful plugin. Couldn't live without it any more.

**Comment by jpmv27** [comment]
This is the work-around I am experimenting with. I have disabled `syntastic_check_on_open` and I'm doing this instead. Seems to work OK after an extensive 5 minutes of testing :-)

```
function! TestIt() abort
    if !exists('b:did_it')
        let old_list = getloclist(0)
        SyntasticCheck
        call setloclist(0, old_list, 'r')
        let b:did_it = 1
    endif
endfunction
autocmd CursorHold * call TestIt()

```

**Comment by jpmv27** [comment]
Sorry to bother you again, but I am just reading/learning about the "stack" of quickfix and location lists.
When creating the loclist to parse errors from checkers, it seems that Syntastic overwrites the current loclist if there is one. Perhaps that's a limitation of the checkers? I'm curious why not create a new loclist and then `:lolder` to restore the loclist that was there before?

**Comment by lcd047** [comment]
> When creating the loclist to parse errors from checkers, it seems that Syntastic overwrites the current loclist if there is one.

Please provide evidence for your claim.

**Comment by jpmv27** [comment]
That's what I was seeing two days ago. Since then I have updated vim version and syntastic version and I am no longer seeing that behaviour. Hence why I deleted the comment.
