### ISSUE TITLE
Perl6 PM Files

### ISSUE THREAD

**Issue by dataf3l** [scrooloose/syntastic#1901]
when I save a perl6 file with a pm extension, syntastic doesn't recognise the file as perl6, but as perl, which is less than awesome :(

**Comment by lcd047** [comment]
Syntastic relies on `filetype`s to do its job.  It doesn't try to _infer_ said `filetype`s though, it just assumes that job has already been done when it gets to see the files.  Now, if Vim's builtin `filetype` detection doesn't work the way you want it, you can install some language-specific plugin to improve detection (if there is such a thing), or you can explicitly set the `filetype` for each file in `modeline`s.  Either way it's up to you to fix it, syntastic itself doesn't try to second-guess what the correct `filetype` might be.
