### ISSUE TITLE
CUDA chekcer

### ISSUE THREAD

**Issue by elsdrium** [scrooloose/syntastic#1902]
I just want to replace the default checker nvcc with clang for better C++ advice. But it seems not configurable at CUDA checker? Thanks.

**Comment by lcd047** [comment]
It can be done with recent versions of syntastic.  You can add `cpp/gcc` as a checker for `cuda`,  the configure `gcc` to run CLang and produce CUDA code.  Something like this (not tested):
```vim
let g:syntastic_cuda_checkers = ['cpp/gcc']
let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = '--cuda-gpu-arch=sm_35'
```
