### ISSUE TITLE
Handlbars file checker include html/tidy, which throws error

### ISSUE THREAD

**Issue by tnguyen14** [scrooloose/syntastic#1904]
For a handlebars file, I see the following `SyntasticInfo`:

```
Syntastic version: 3.7.0-235 (Vim 800, Darwin, GUI)
Info for filetype: html.handlebars
Global mode: active
Filetype html.handlebars is active
The current file will be checked automatically
Available checkers: handlebars/handlebars html/eslint html/jshint html/tidy html/validator html/w3
Currently enabled checkers: html/tidy handlebars/handlebars
```

This is causing errors to be thrown for legitimate handlebars syntax. Should html/tidy be disabled for handlebars files?

**Comment by lcd047** [comment]
Please read `:h syntastic-composite`.

**Comment by tnguyen14** [comment]
Thanks. I resolved this by doing so

```
let g:syntastic_filetype_map = { "html.handlebars": "handlebars"}
```

For some reason, setting that causes the syntax highlighting to be off, and syntax such as `{{> partial}}` is marked as invalid (the `>` character is highlighted in red).

**Comment by lcd047** [comment]
Syntastic has nothing to do with syntax highlighting.

**Comment by tnguyen14** [comment]
Hmm. Yeah, weird why that was the case. When closing the buffer and re-open it, it works fine.
