### ISSUE TITLE
Syntastic overrides let g:syntastic_python_checker = 'flake8 --ignore=E501'

### ISSUE THREAD

**Issue by stantonk** [scrooloose/syntastic#204]
No matter where I try to put:

let g:syntastic_python_checker = 'flake8 --ignore=E501'

Syntastic always overrides it to:

let g:syntastic_python_checker = flake8

What do I have to do to get it to obey mine? The only way I can get it to work is either entering it after I've already opened MacVim...

**Comment by omsobliga** [comment]
` let g:syntastic_python_flake8_args='--ignore=E501'`

**Comment by aswin-raghavan** [comment]
The better solution is to create a file called `flake8` in your home directory with the default args for all calls to flake8.
