### ISSUE TITLE
Freezes terminal

### ISSUE THREAD

**Issue by y** [scrooloose/syntastic#205]
I experience random freezes of my terminal when using syntastic under console mode vim with iTerm on Mac OS X. It happens when the syntax check is performed (for any syntax) and an error/warning is found, but before the signs appear and the Errors window opens. When it happens, my screen won't refresh and the keys I hit are simply echoed to the screen. I either have to reset the terminal or press some random sequence of C-l, Esc, Ret for the display to refresh. I also experience this when removing all other plugins.

The only syntastic options I set are:

```
let g:syntastic_auto_loc_list = 1
let g:syntastic_enable_balloons = 0
```

And the only display-related settings in my .vimrc are:

```
set  ttyfast
set lazyredraw
```

My vim:

```
$ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Mar  7 2012 14:19:07)
MacOS X (unix) version
Included patches: 1-244, 246-462
Compiled by y@localhost
Huge version without GUI.  Features included (+) or not (-):
+arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset +cindent 
-clientserver +clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
+conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path 
+find_in_path +float +folding -footer +fork() +gettext -hangul_input +iconv 
+insert_expand +jumplist +keymap +langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
+mouse_dec -mouse_gpm -mouse_jsbterm +mouse_netterm -mouse_sysmouse 
+mouse_xterm +mouse_urxvt +multi_byte +multi_lang -mzscheme +netbeans_intg 
+path_extra +perl +persistent_undo +postscript +printer +profile -python 
-python3 +quickfix +reltime +rightleft -ruby +scrollbind +signs +smartindent 
-sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
-toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
-xterm_clipboard -xterm_save 
system vimrc file: "/opt/local/etc/vimrc"
    user vimrc file: "$HOME/.vimrc"
    user exrc file: "$HOME/.exrc"
fall-back for $VIM: "/opt/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -I/opt/local/include -DMACOS_X_UNIX -no-cpp-precomp  -pipe -O2 -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: /usr/bin/clang   -L/opt/local/lib -arch x86_64 -L/usr/local/lib -o vim       -lncurses -liconv -lintl -framework Cocoa    -L/opt/local/lib -fstack-protector  -L/opt/local/lib/perl5/5.12.3/darwin-multi-2level/CORE -lperl -lm -lutil -lc       
```

**Comment by nathanisaac-s** [comment]
I am experiencing this issue in gvim and vim under vim 7.4 on a vanilla Linux kernel at 3.18.6-1 every time I attempt to make an edit on a scala file in an sbt project. Gvim needs a kill -9 (no other signal works) or a kill signal from X to respond. Vim on the command line will respond to an `:q` after a Ctrl-C

here's the relevant tail on my log from `vim -V9`:

    Calling shell to execute: "(fsc -Ystop-after:parser /home/nathan/code/scalatowebscale/src/main/scala/PostPipeline.scala) >/tmp/vQO7DKN/1 2>&1"
    error list 1 of 1; 0 errors
    Calling shell to execute: "(scalac -Ystop-after:parser code/scalatowebscale/src/main/scalaPostPipeline.scala) >/tmp/vQO7DKN/2 2>&1"
    error list 1 of 2; 0 errors
    <calatowebscale/src/main/scala/PostPipeline.scala" 76L, 2131C written

    Executing QuitPre Auto commands for "*"
    autocommand call s:QuitPreHook()

and in .viminfo:

    # File marks:
    '0  17  16  ~/code/scalatowebscale/src/main/scala/PostPipeline.scala
    
    # Jumplist (newest first):
    -'  17  16  ~/code/scalatowebscale/src/main/scala/PostPipeline.scala
    -'  1  0  ~/code/scalatowebscale/src/main/scala/PostPipeline.scala
    
    # History of marks within files (newest to oldest):
    
    > ~/code/scalatowebscale/src/main/scala/PostPipeline.scala
           "       17      16
            ^       17      17
            .       17      16
            +       17      16


This looks like it's either an issue with scalac or fsc and/or the way syntastic calls it.

**Comment by lcd047** [comment]
Please run these in a terminal:
```sh
$ fsc -Ystop-after:parser /home/nathan/code/scalatowebscale/src/main/scala/PostPipeline.scala
$ scalac -Ystop-after:parser code/scalatowebscale/src/main/scalaPostPipeline.scala
```
If neither of them freezes, please open Vim and run these in Vim:
```vim
: echo system('fsc -Ystop-after:parser /home/nathan/code/scalatowebscale/src/main/scala/PostPipeline.scala')
: echo system('scalac -Ystop-after:parser /home/nathan/code/scalatowebscale/src/main/scala/PostPipeline.scala')
```
If neither freezes again, please read the first section in [this guide](https://github.com/scrooloose/syntastic/blob/master/CONTRIBUTING.md#bugreps) and open a new issue.

**Comment by nathanisaac-s** [comment]
It looks like fsc hangs, but strace (ha ha only serious) shows that it still responds to interrupts:

    22:24:41 wait4(-1, 0x7fff7b5998e0, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
    22:24:55 --- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=8907, si_uid=1000} ---

scalac works okay.

    >>> scalac -Ystop-after:parser src/main/scala/PostPipeline.scala 
    >>> echo $?
    0

This really looks more like an fsc issue that I can reproduce but haven't isolated, and it's coincidental that syntastic calls it.
