### ISSUE TITLE
Syntastic does not find linter in certain conditions

### ISSUE THREAD

**Issue by neilhwatson** [scrooloose/syntastic#2193]
I have two hosts using the same user vimrc and other vim files. I've configured Syntastic to use yamllint for yaml files. Host A works, but host B doesn't. A check returns this:

```
Syntastic version: 3.7.0 (Vim 800, Linux)
Info for filetype: yaml
Global mode: active
Filetype yaml is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```

Why is yamllint not listed as a checker? Yamllint is in the PATH and works in the shell. Both hosts are Debian. Vim files are here: https://github.com/neilhwatson/nustuff/tree/master/vim

**Comment by lcd047** [comment]
Please read the first entry in the [FAQ][FAQ].

[FAQ]: https://github.com/vim-syntastic/syntastic#faqinfo

**Comment by neilhwatson** [comment]
Yes, I have read that. The PATH is good, yamllint is in the right place. ```:echo g:syntastic_yaml_checkers``` returns ```['yamllint'] ```

**Comment by lcd047** [comment]
Well for some reasons either your Vim's `$PATH` is not what you think it is,  your Vim can't find `yamllint` in said `$PATH` (permission problems along the way?), or your Vim doesn't think `yamllint` is executable.  That's all there is to it.

**Comment by neilhwatson** [comment]
```:echo syntastic#util#system('echo "$PATH"')```

Returns:

```/home/nwatson/bin:/home/nwatson/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games```

And there is yamllint:

```
:!ls -l /usr/bin/yamllint
-rwxr-xr-x 1 root root 387 Nov  7  2016 /usr/bin/yamllint

:!yamllint --version
yamllint 1.5.0
```

So it's visible, in the path, and executable.

**Comment by lcd047** [comment]
Please open a `yaml` file and post the output of `:echo executable('yamllint')`.

**Comment by neilhwatson** [comment]
1

**Comment by lcd047** [comment]
Right: from your first post, you're using syntastic 3.7.0, while according to the [Changelog][Changelog] `yamllint` was added in 3.8.0.

[Changelog]: https://github.com/vim-syntastic/syntastic/wiki/Changelog
