### ISSUE TITLE
Empty available checkers

### ISSUE THREAD

**Issue by Sunno** [scrooloose/syntastic#2225]
Hello, I wasn't able to use the plugin since all available checkers are empty, I tried with python, js and css and nothing appears in the available checkers section when I type `SyntasticInfo`, I already installed flake8, pylint in my virtualenv and set the `g:syntastic_python_checkers` variable and nothing, it's always empty.

**Comment by lcd047** [comment]
What OS are you using and what version of Vim?  Please post the output of `vim --version`.
