### ISSUE TITLE
Syntastic is unable to recognize HTML templates and throws syntax errors

### ISSUE THREAD

**Issue by distracteddev** [scrooloose/syntastic#240]
If the following is found in the head element of a HTML page, Syntastic will complain about the html tags not being allowed within the tag. Can we some how modify the HTML checker to either detect the scripts type attribute and simply not parse the following. Or, if possible, parses it using a handlebars syntax checker? (if one exists). 

Code placed in comment below since code-formatting was being fussy.

**Comment by KaoruDev** [comment]
@rafi thx! this worked for my ejs files:

```
let g:syntastic_html_tidy_ignore_errors = [
     \   '<img> escaping malformed URI reference'
     \ ]
```

**Comment by ldong** [comment]
```
// add this
let g:syntastic_html_tidy_ignore_errors = [ '<template> is not recognized!' ]
```

Source: https://gist.github.com/khanghoang/345cd55541eb00952fe4
