### ISSUE TITLE
Only the first line of multiline Haskell errors is displayed

### ISSUE THREAD

**Issue by nponeccop** [scrooloose/syntastic#317]

**Comment by expipiplus1** [comment]
I'm still seeing this behavior with Vim 7.4, latest ghc-mod and syntastic.
I notice that syntastic sets -b to "" for the ghc-mod checker. As far as I can tell this is causing all the lines to become concatenated.
If I change the separator to "\n" then only the first line is displayed. Is syntastic unable to display multi-line error messages?

**Comment by lcd047** [comment]
@expipiplus1 Please open a new issue.  Explain what you did, what you expected to happen, and what happened instead.  If you have a test file that can be used to reproduce the problem, post that too.

**Comment by nomeata** [comment]
@expipiplus1, see #1700 for a related bug.
