### ISSUE TITLE
:lnext with only one issue in the location list gives "E553 No more items"

### ISSUE THREAD

**Issue by sgronblo** [scrooloose/syntastic#32]
Version 1.2.0

The issue should be clear from the title

**Comment by HaleTom** [comment]
Based on @lcd047's code above I made the following to not produce a ugly multi-line erorr message if there are no entries in the location list:

```viml
" Allow :lprev to work with empty location list, or at first location
function! <SID>LocationPrevious()
  try
    lprev
  catch /:E553:/
    lfirst
  catch /:E42:/
    echo "Location list empty"
  catch /.*/
    echo v:exception
  endtry
endfunction

" Allow :lnext to work with empty location list, or at last location
function! <SID>LocationNext()
  try
    lnext
  catch /:E553:/
    lfirst
  catch /:E42:/
    echo "Location list empty"
  catch /.*/
    echo v:exception
  endtry
endfunction
```

**Comment by HaleTom** [comment]
Actually, [this](http://stackoverflow.com/questions/27198612/vim-location-list-how-to-go-to-first-location-if-at-last-location/27204000#27204000) is an even better solution (but consider adding `echo "List empty"` rather than an null catch.

**Comment by timblaktu** [comment]
For those stumbling on this behavior, maybe the solutions is "don't do that" - see [this workflow/workaround](https://stackoverflow.com/a/15417309).
