### ISSUE TITLE
Jump between errors?

### ISSUE THREAD

**Issue by vkuznet** [scrooloose/syntastic#341]
Hi,
I found this plugin very useful, but it has one limitation. How can user jump between errors/warnings (basically between signs)? If file is long it would be convenient to have such functionality and I wonder if it can be implemented.
Thanks,
Valentin

**Comment by daGrevis** [comment]
Well it works fine now. :dancer:

**Comment by fweep** [comment]
Even with `g:syntastic_always_populate_loc_list = 1`, the location list isn't populated until calling `Errors`.

**Comment by lcd047** [comment]
@fweep Please open a __new__ issue.  Explain what you did, what did you expected to happen, and what happened instead.

**Comment by brandonsturgeon** [comment]
This only works for errors, what about warnings?

**Comment by lcd047** [comment]
@brandonsturgeon Congratulations: you won the "Thread necromancer of the year" award.
