### ISSUE TITLE
Haskell: Add cabal paths to ghc-mod based checker

### ISSUE THREAD

**Issue by NicolasT** [scrooloose/syntastic#408]
When working on a project using *cabal* or *cabal-dev*, it's often useful to pass some include paths to GHC, similar to what *cabal* would do, e.g. when using *hsc2hs*.

The *ghcmod-vim* plugin contains some support for this, see https://github.com/eagletmt/ghcmod-vim/blob/master/autoload/ghcmod.vim#L381 ("ghcmod#build_command"). I hacked this into *syntax_checkers/haskell/ghc-mod.vim*, and it seems to work, although it looks like #219 is biting me as well now.

**Comment by ches** [comment]
OP can confirm, but I believe this can be closed as no longer relevant: `cabal-dev` is essentially obsoleted by native sandbox support in current `cabal` versions, and ghc-mod and thus Syntastic's checker for it work seamlessly with these sandboxes.
