### ISSUE TITLE
Disabling pylint errors breaks syntastic

### ISSUE THREAD

**Issue by meunierd** [scrooloose/syntastic#414]
```
let g:syntastic_python_checker_args='-d E1101'
```

...although it appears to work properly when disabling some warnings: (W0232, W0142)

**Comment by bgenchel** [comment]
none of these fixes have actually worked. where are you supposed to write these lines? In the checker files? because I've been writing them in my .vimrc...

**Comment by lcd047** [comment]
@bgenchel Well, you can either (1) install a version of syntastic from 2013, apply the above recipes, and see if they solve your problem; or (2) you can upgrade to the latest version of syntastic, read the manual, read Pylint's manual, and open a new issue if you still can't get it to work.

**Comment by fuyw** [comment]
Another solution is to add `no-member` to the `disable` part in `.pylintrc`

```bash
pylint --generate-rcfile > ~/.pylintrc
```
