### ISSUE TITLE
Ignore Python Warnings/Errors

### ISSUE THREAD

**Issue by jbremer** [scrooloose/syntastic#448]
I'm sure I'm missing something, but I've tried modifying the code (which usually works fine for me..) and checking the docs/googling, but I can't seem to find how to disable certain warnings/errors.

For example, I'd like to disable the "E225 missing whitespace around operator" error, because, well, it irritates me, and I don't want to follow this rule.

Looking forward to some help here. Or some documentation on a _.syntastic_python_config_ file would be nice as well! (Note that I'm running the _flake8_ syntax checker here.)

Regards,
Jurriaan

**Comment by sirusdas** [comment]
Currently this only seems working for me...
let g:syntastic_python_checkers=['flake8 --ignore=E225,E501,E302,E261,E262,E701,E241,E126,E127,E128,W801','python3']

**Comment by lcd047** [comment]
@sirusdas That's exactly equivalent to
```vim
let g:syntastic_python_checkers = ['python3']
```
You can save a lot of time reading the manual instead of experimenting with random changes. _shrug_

**Comment by sirusdas** [comment]
My apologies, @lcd047.
1. Did you mean that now 'flake8' is working with syntastic? if i use below lines

`let g:syntastic_python_checkers=['flake8 --ignore=E225,E501,E302,E261,E262,E701,E241,E126,E127,E128,W801','python3']`

the below code is not working for me

    let g:syntastic_python_checker_args = '--ignore=E225'

and even tried below code 
`let g:syntastic_python_checker_args = '--ignore=E225,W291,W292,W293,E211,E201,E202,E203'
 taking reference from: https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes`

But it seems i am missing somethings. Your help or a link will be highly appreciated!
I am very new to VIM and its Plug-ins.

**Comment by lcd047** [comment]
@sirusdas Sadly, syntastic is probably not the best place to start if you're new to Vim.  Consider using Vim without _any_ plugins for a while, until you get familiar with the main builtin features.
