### ISSUE TITLE
syntastic_python_checkers not chainable

### ISSUE THREAD

**Issue by joaopimentel** [scrooloose/syntastic#558]
While flake8 gives errors of PEP8 style (which are desirable), it does not check, for example, for invalid imports ("from sys import foo" only gives "'foo' imported but unused", if in fact you don't use 'foo')

pylint, on the other hand, gives "no name 'foo' in module 'sys'", but does not give errors for PEP8 style.

Both

```
let g:syntastic_python_checkers = ['pylint']
```

and 

```
let g:syntastic_python_checkers = ['flake8']
```

Correctly select the intended checker, but both

```
let g:syntastic_python_checkers = ['pylint', 'flake8'] 
```

and 

```
let g:syntastic_python_checkers = ['flake8', 'pylint']
```

seems to favor flake8: only flake8 errors show up. At least on my environment flake8 is used if I don't define syntastic_python_checkers.

Is there a way to show the errors from both checkers? 
From the docs, the php checkers seem to be chainable. Are the python checkers supposed to be chainable as well?

**Comment by tony** [comment]
@scrooloose Is this still the behavior in 2016?

**Comment by lcd047** [comment]
@tony `:h syntastic-aggregating-errors`, since December 2013...
