### ISSUE TITLE
How to skip angularJS tag and empty element in html 

### ISSUE THREAD

**Issue by ghost** [scrooloose/syntastic#612]
I want to skip these errors since it makes no sense for me. Is there anyway I can do this ? 

![Screen Shot 2013-04-11 at 13 45 35](https://f.cloud.github.com/assets/2028062/367151/64a42968-a29d-11e2-855e-223b0c4555c1.png)

**Comment by carusog** [comment]
@JaimeBeneytez Thanks for the quick fix. Still using it? 
In any case, saving the edited `.vimrc` file with it raises an error for the double quotes in `"lacks "action"`.

**Comment by JaimeBeneytez** [comment]
Hi @carusog.

Sorry, my fault, I didn't pay much attention and the GitHub editor was correctly parsing the text of the answer removing the slash to scape the character `\"`.

this is my configuration and still working fine for me:

`
let g:syntastic_html_tidy_ignore_errors=[" proprietary attribute " ,"trimming empty \<", "inserting implicit ", "unescaped \&" , "lacks \"action", "lacks value", "lacks \"src", "is not recognized!", "discarding unexpected", "replacing obsolete "]
`

Thank you
