### ISSUE TITLE
New option: g:syntastic_ignore_files

### ISSUE THREAD

**Issue by lcd047** [scrooloose/syntastic#646]
List of regexps, specifying files that should neither be checked, nor included in error lists.  This is useful for ignoring errors in system headers, or third-party files that are not under user's control (see #378). Patch 8d47df6, in branch modemap_ignore.

I also have a different solution to this, implementing `active_filenames` and `passive_filenames` patterns as alternatives to `active_filetypes` and `passive_filetypes`, but I don't like the complexity added to the user interface, and also my clunky Engrish is not up to the task of documenting it. :)

**Comment by acumon** [comment]
This is super useful to me.
