### ISSUE TITLE
Finding the Java classpath through an Ant config file

### ISSUE THREAD

**Issue by taq** [scrooloose/syntastic#819]
I was wondering if it will be a good idea to try to automatically find the classpath to use with the Java compiler in an Ant config file.

I often have some build.xml files on my projects with path elements inside of them labeled "compile.path". As we already have a global var `syntastic_java_javac_config_file`, we could have a `syntastic_java_ant_compile_id` or something like that to find and join the paths on a `LoadClasspathFromAntFile` function.

What you guys think about that?

**Comment by Svtter** [comment]
Thanks, it worked!

- By the way, I've tried your method but it didn't work before.  = =
- But this time, I restart my vim and now it worked. 

I really appreciate your patience and support. @troydm
