### ISSUE TITLE
Problem with screen refresh

### ISSUE THREAD

**Issue by surfmikko** [scrooloose/syntastic#822]
Syntastic noobie here, so firstly A big thank you for a great plugin! :)

For me the problem is that occasionally Syntastic causes edit window to corrupt. This happens when saving file and start typing before syntactic went trough checking and refreshing screen.

This can be reproduced by saving bigger file on slightly laggy virtual machine, when saving big enough file and immediately try navigating to line with "j" / "k". For example just press down "j" for a while and editing window gets garbled.

So after saving you can have one or two lines offset between in-memory buffer and what is displayed on screen. Then with fast fingers you jsut edit or delete the wrong line.

Garbled window gets redrawn fine with :redraw! or ^L.

I have tried altering the g:syntastic_full_redraws settings, but no change in behaviour.

---

let g:syntastic_python_pylint_args='-d W0232 -f parseable -r n -i y'

let g:syntastic_check_on_open=0
let g:syntastic_aggregate_errors=0

let g:syntastic_enable_highlighting = 0
let g:syntastic_echo_current_error=1

let g:syntastic_enable_balloons = 0
let g:syntastic_auto_jump=0

let g:syntastic_full_redraws=1

---

Centos 6.3:

$ vim --version
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Apr  5 2012 10:17:30)
Included patches: 1-411
Modified by bugzilla@redhat.com
Compiled by bugzilla@redhat.com
Huge version without GUI.  Features included (+) or not (-):
+arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
+cryptv +cscope +cursorshape +dialog_con +diff +digraphs -dnd -ebcdic 
+emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path +find_in_path 
+float +folding -footer +fork() +gettext -hangul_input +iconv +insert_expand 
+jumplist +keymap +langmap +libcall +linebreak +lispindent +listcmds +localmap 
+menu +mksession +modify_fname +mouse -mouseshape +mouse_dec +mouse_gpm 
-mouse_jsbterm +mouse_netterm -mouse_sysmouse +mouse_xterm +multi_byte 
+multi_lang -mzscheme -netbeans_intg -osfiletype +path_extra +perl +postscript 
+printer +profile +python +quickfix +reltime +rightleft -ruby +scrollbind 
+signs +smartindent -sniff +startuptime +statusline -sun_workshop +syntax 
+tag_binary +tag_old_static -tag_any_white -tcl +terminfo +termresponse 
+textobjects +title -toolbar +user_commands +vertsplit +virtualedit +visual 
+visualextra +viminfo +vreplace +wildignore +wildmenu +windows +writebackup 
-X11 -xfontset -xim -xsmp -xterm_clipboard -xterm_save 
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall  -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64  -D_FORTIFY_SOURCE=1    -D_REENTRANT -D_GNU_SOURCE  -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE  -I/usr/include/python2.6 -pthread  
Linking: gcc   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -o vim       -lselinux  -lncurses -lacl -lgpm   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lutil -lc -L/usr/lib64/python2.6/config -lpython2.6 -lutil -lm -Xlinker -export-dynamic

**Comment by nmschulte-aviture** [comment]
Drat!  I just started using Syntastic (and a whole slew of other nice plugins, finally), and I'm running into this issue left and right!  My fingers and habits are just too fast for this, I suppose.  To be clear, I'm running into redraw issues due to typing immediately after a save, as the OP describes.

(this is Vim from Debian Sid):

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 13 2015 05:48:14)
Included patches: 1-712
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     +tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1  
Linking: gcc   -L. -Wl,-z,relro -L/build/ruby2.1-_39Jjj/ruby2.1-2.1.5/debian/lib -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.20/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.1 -lpthread -lgmp -ldl -lcrypt -lm    
```

**Comment by lcd047** [comment]
@nmschulte-aviture I'm afraid the situation hasn't changed in the mean time.  Sorry about that.  Syntastic still has no control over any of the above.  Not sure what else I could tell you.

**Comment by nmschulte-aviture** [comment]
@lcd047, understood entirely.  I was more posting here that a more recent of Vim/stack still has not resolved the issue.  Being more deliberate with my saving, as well as the hint about CTRL+L for redraw, is my solution.

**Comment by msabramo** [comment]
Another possibility is to use the GUI vim instead of a terminal one. Could even modify your vimrc so that it only activates syntastic when in GUI mode.

**Comment by manishtoons** [comment]
same issue with me, hitting Ctrl+L is correcting the buffer's visual issue

**Comment by lcd047** [comment]
@manishtoons Same solution for you then: reporting the issue upstream might help, for suitable values of "upstream". _shrug_

**Comment by motizuki** [comment]
I had this issue using Vim 7.4+ with vim-tmux-navigator plugin.
By pressing <ctrl-j>, (to move to the tmux pane below) while syntastic is scanning a file the window gets garbled.
In order to solve this issue (nasty workaround), I've chained a redraw in the tmuxnavigatedown binding like that:
`nnoremap <silent> <c-j> :TmuxNavigateDown<cr>:redraw!<cr>
`
Cheers,

**Comment by opendevnet** [comment]
For posterity if anyone else is trying to solve this frustrating issue (decades of typing <kbd>ctrl</kbd>+<kbd>l</kbd> don't make it more pleasant) I used autocommand and bound `:redaw!`to as many events and file types as I could in order to force a "fix".  

It probably slowed things down a bit, but the machine had 16 cores and 64G of RAM so I didn't notice. I began narrowing down the events that triggered the screen scrambling (QuickFixCmd was notorious) but never seriously debugged this; there is some good advice on how to do that in this thread.

Using the `:au` command's "events" subsystem was just a way to overcome what seemed to be some kind of timing issue for screen redrawing (alluded to in https://github.com/scrooloose/syntastic/issues/699) but one which probably lives deeper down in ncurses or terminfo.

Thanks for Syntastic. 

```
"  force  a :redraw! on "events" that scramble the screen with
"  syntax highlighting enabled.

set ttyfast
au FileWritePost * :redraw!
au TermResponse * :redraw!
au TextChanged * :redraw!
au QuickFixCmdPre * :redraw!
au QuickFixCmdPost * :redraw!

```

**Comment by lcd047** [comment]
@opendevnet 
> Using the  :au  command's "events" subsystem was just a way to overcome what seemed to be some kind of timing issue for screen redrawing 

No.  That was your way of brute forcing around the fact that the order of execution of `autocmd`s is not well-defined.  So some of your `redraw!`s are actually run before the events they are supposed to fix. :smile:

This is such a waste of time and energy.  Here's a more rational approach:

1. If you're having redraw problems in gVim, report them to `vim_dev`.
2. If you're having redraw problems in terminal Vim running in any other terminal than `xterm`, try to reproduce them with (a recent version of) plain `xterm`.  If you can't, then report the problems to the developers of your fancy terminal.
3. If you're having redraw problems in terminal Vim running in `xterm` then report them to the maintainers of your distribution, as they most likely have messed up your `termcap` / `terminfo`.

Try this before spending your time brute-forcing `redraw`.

**Comment by dhinus** [comment]
@motizuki good workaround. I had to modify it slightly to include it in my `.vimrc`:
```
autocmd VimEnter * nnoremap <silent> <c-j> :TmuxNavigateDown<cr>:redraw!<cr>
```
Without `autocmd VimEnter *`, the custom mapping was overwritten by the default mapping included in the vim-tmux-navigator plugin, as plugins are loaded after the `.vimrc` file.

**Comment by niloct** [comment]
> @opendevnet
> 
> > Using the  :au  command's "events" subsystem was just a way to overcome what seemed to be some kind of timing issue for screen redrawing
> 
> No. That was your way of brute forcing around the fact that the order of execution of `autocmd`s is not well-defined. So some of your `redraw!`s are actually run before the events they are supposed to fix. 😄
> 
> This is such a waste of time and energy. Here's a more rational approach:
> 
> 1. If you're having redraw problems in gVim, report them to `vim_dev`.
> 2. If you're having redraw problems in terminal Vim running in any other terminal than `xterm`, try to reproduce them with (a recent version of) plain `xterm`.  If you can't, then report the problems to the developers of your fancy terminal.
> 3. If you're having redraw problems in terminal Vim running in `xterm` then report them to the maintainers of your distribution, as they most likely have messed up your `termcap` / `terminfo`.
> 
> Try this before spending your time brute-forcing `redraw`. It isn't a complete algorithm, but IMO it does cover the most common causes.

I can confirm that syntastic has the issue on this thread, when vim is running inside a docker container. Thanks for your checklist \o/
