### ISSUE TITLE
Syntastic doesn't recognize C++11

### ISSUE THREAD

**Issue by rafee** [scrooloose/syntastic#826]
I am using Fedora 19, gcc 4.8.1. My compiler supports C++11, the code compiles fine. But syntastic can't recognize C++11 code.
I set the following lines in my .vimrc,

let g:syntastic_cpp_compiler="g++"
let g:syntastic_cpp_compiler_options="-std=c++11 -stdlib=libc++"

**Comment by ulidtko** [comment]
This is so freaking annoying.

Why do I even have to fiddle with all these greasy vimscript config variables to support a **6 year old** C++ feature. Darn.

**Comment by lcd047** [comment]
@ulidtko Feel free to use some less greasy linter instead of syntastic.  It's that easy.
