### ISSUE TITLE
LESS include paths

### ISSUE THREAD

**Issue by johngeorgewright** [scrooloose/syntastic#862]
Hey there,

A nice option might be to configure LESS include paths. Currently all my LESS files have errors as VIM doesn't know where to import files from.

Ta,
John

**Comment by metal3d** [comment]
Nice ! but maybe a modeline should help. Different project hasn't the same include path to load.

**Comment by mazlix** [comment]
Agree that may be useful, but a workaround is to use a local `.vimrc`

**Comment by metal3d** [comment]
Right. I did it

**Comment by lcd047** [comment]
You can't set variables from modelines, presumably for security reasons.  This is a limit imposed by Vim, not by syntastic.  You can however run `autocmd`s per project.  See the [FAQ][cfg] for an example.

[cfg]: https://github.com/scrooloose/syntastic#faqconfig
