### ISSUE TITLE
Pylint version checking not working 

### ISSUE THREAD

**Issue by timc3** [scrooloose/syntastic#865]
When using syntastic commit bdc4b0f1772cb13b034029d706095c66f5f51d43 

Version of Pylint is 1.0.0 and Vim is 7.3 (actually MacVim version) on OSX 10.9 I get the error

```
syntastic: error: checker python/pylint: can't parse version string (abnormal termination?)
```

Other issues that seem to talk about this are closed and marked fixed, but it doesn't seem to me seem to say that this issue is fixed, but it doesn't seem to be.

**Comment by laerus** [comment]
message:
```
Syntastic version: 3.7.0-237 (Vim 800, Linux, GUI)
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
syntastic: error: checker output:
Python 3.4.2
syntastic: error: checker python/pylint: can't parse version string (abnormal termination?)
Available checkers: flake8 pyflakes python
Currently enabled checkers: flake8 python
```

vimrc:
```
let g:syntastic_python_python_exec = "/usr/bin/python3"
let g:syntastic_python_checkers = ['flake8', 'pylint', 'python']
let g:syntastic_python_pylint_exec = 'python3'
let g:syntastic_python_pylint_args = ['-m', 'pylint']
let g:syntastic_python_flake8_exec = 'python3'
let g:syntastic_python_flake8_args = ['-m', 'flake8']
```

debian-stable/vim8

installed pylint through `python3 -m pip install pylint` so it's not a dist package.
maybe a pylint bug or something wrong with my syntastic configuration,
flake8 works great.

**Comment by lcd047** [comment]
> `let g:syntastic_python_pylint_exec = 'python3'`
> `let g:syntastic_python_pylint_args = ['-m', 'pylint']`

That won't work, and you just found out why:

> `syntastic: error: checker python/pylint: can't parse version string (abnormal termination?)`

The point being, `python --version` output has a different format that `pylint --version`.

Leave `g:syntastic_python_python_exec` alone, and run Vim from `virtualenv`.

**Comment by MulticsYin** [comment]
change two line:
change
`let g:syntastic_python_pylint_exec = 'python3'
let g:syntastic_python_pylint_args = ['-m', 'pylint']`
to
`let g:syntastic_python_pylint_exec = 'pylint'
let g:syntastic_python_pylint_args = ['--help-msg', 'pylint']`

**Comment by lcd047** [comment]
@MulticsYin You're welcome to make your own life as hard as you want.  The easy (and recommended) way is still the one mentioned above: leave out all those settings, and run Vim from `virtualenv`. _shrug_
