### ISSUE TITLE
Vim slow when saving SASS/SCSS files

### ISSUE THREAD

**Issue by gcollura** [scrooloose/syntastic#898]
I don't know how to explain properly but when Syntastic is enabled in active mode, every time I try to save a scss/sass file (it happens with both filetypes) Vim hangs few seconds (~3-4 sec). If I toggle Syntastic with `:SyntasticToggleMode` and I set it to passive, files are saved instantly.
It happens only with these two filetypes, I also work with c, c++, js, php, css and I never had an issue.
I don't know how to debug vim times properly, if you need more information just ask me, I'd be happy to help and improve my bug report.
Vim version: 7.4 patch 52
OS: ubuntu 14.04 trusty

Thanks for your amazing plugin and your support,
Giulio

**Comment by vinchi777** [comment]
@JiriChara  :+1:
