### ISSUE TITLE
Syntastic fails with pylint on OS X 10.9

### ISSUE THREAD

**Issue by shkodrang** [scrooloose/syntastic#902]
Pylint seems to crash when Syntastic attempts to invoke it to check a python source file.

With the following in .vimrc:

let g:syntastic_python_checkers=['pylint']
let g:syntastic_always_populate_loc_list=1
let g:syntastic_debug=1

I am getting the following debug output when saving Python files:

syntastic: 1.561945: &shell = '/bin/bash', &shellcmdflag = '-c', &shellxquote = '', &shellredir = '>%s 2>&1', &shellslash = 0
syntastic: 1.562269: g:syntastic_aggregate_errors = 0
syntastic: 1.821157: CacheErrors: Invoking checker: pylint
syntastic: 1.821678: SyntasticMake: called with options: {'postprocess': ['sort'], 'errorformat': '%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#', 'makeprg': 'pylint --msg-template="{path}:{line}: [{msg_id
}] {msg}" -r n backup_project.py'}
syntastic: 2.133238: getLocList: checker python/pylint returned 1

Running pylint on the Python source file works just fine and produces the expected output.

It would be amazing if someone could look into this, since my Vim-scripting foo is pretty much nonexistent and the only other viable option - python-mode - segfaults on me on some Python files, and pyflakes is deprecated.

**Comment by sengaya** [comment]
I can confirm this bug with OS X 10.10 and the following Terminal settings: Profiles --> Advanced --> Text encoding --> Unicode (UTF-8) and "Set locale environment variables on startup" activated

This will set ```$LC_CTYPE``` to ```UTF-8```. ```$LC_MESSAGES```, ```$LC_ALL``` and ```$LANG``` are not set. With these pylint won't work. To work around this issue I could either unset ```$LC_CTYPE``` (by unchecking "Set locale environment variables on startup" or by running ```unset LC_CTYPE```) or set ```LC_CTYPE=en_US.UTF-8```.

I hacked a quick fix into ```syntastic.vim``` (basically unsetting ```$LC_CTYPE```) and it seems to work, at least in my environment. I can submit a pull request if you're interested.

**Comment by lcd047** [comment]
@sengaya:  Sorry, but no.  This would break valid locale configurations on other systems.  Write a wrapper if you must, and point `g:syntastic_python_pylint_exec` to it.  Perhaps something like this:
```sh
#! /bin/sh
unset LC_CTYPE
exec pylint "$@"
```

**Comment by teferi** [comment]
Hi all! I'm still having this problem on the latest MacOSX. I have locale set to 

    $ locale
    LANG="ru_RU.UTF-8"
    LC_COLLATE="ru_RU.UTF-8"
    LC_CTYPE="ru_RU.UTF-8"
    LC_MESSAGES="ru_RU.UTF-8"
    LC_MONETARY="ru_RU.UTF-8"
    LC_NUMERIC="ru_RU.UTF-8"
    LC_TIME="ru_RU.UTF-8"
    LC_ALL="ru_RU.UTF-8"


I've "fixed" it by not setting LC_ALL to empty. I wonder why do you have to do it? You still set messages to 'C', so everything should be in english, shouldn't it? 
Btw setting LC_ALL to C also fixes the problem. 


Also, on related not man locale states, that
`LANG         Used as a substitute for any unset LC_* variable.  If LANG is unset, it will act as if set to "C".  If any of LANG or LC_* are set to invalid values, locale acts as if
                  they are all unset.`
Although setting LANG to '' doesn't do the trick.

**Comment by lcd047** [comment]
@teferi  Different systems have different priorities for locale variables.  For example:

* On Linux:
```
$ LANG=ru_RU LC_ALL=pt_BR LC_MESSAGES=se_SE locale
LANG=ru_RU
LC_CTYPE="pt_BR"
LC_NUMERIC="pt_BR"
LC_TIME="pt_BR"
LC_COLLATE="pt_BR"
LC_MONETARY="pt_BR"
LC_MESSAGES="pt_BR"
LC_PAPER="pt_BR"
LC_NAME="pt_BR"
LC_ADDRESS="pt_BR"
LC_TELEPHONE="pt_BR"
LC_MEASUREMENT="pt_BR"
LC_IDENTIFICATION="pt_BR"
LC_ALL=pt_BR
```
* On OpenBSD:
```
$ LANG=ru_RU LC_ALL=pt_BR LC_MESSAGES=se_SE locale
LANG=ru_RU
LC_COLLATE="C"
LC_CTYPE="pt_BR"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_MESSAGES="C"
LC_ALL=pt_BR
```
Setting `LC_ALL` to empty and `LC_MESSAGES` to `C` seems to cover _most_ cases.  Your example above seems to show it doesn't cover them all. _shrug_

**Comment by joest67** [comment]
https://github.com/scrooloose/syntastic/wiki/Python%3A---pylint Fix it

**Comment by lcd047** [comment]
@joest67 Fix it how?

**Comment by joest67** [comment]
@lcd047  add follows

```bash
LC_CTYPE=en_US.UTF-8
export LC_CTYPE
```

**Comment by lcd047** [comment]
As far as I can tell, it's already there...
