### ISSUE TITLE
How to disable unused variable highlight in cpp?

### ISSUE THREAD

**Issue by pinkfrog9** [scrooloose/syntastic#939]
Hi.
I am using writing cpp in Youcompleteme and syntastic.
Seems like syntastic has undergone a huge update recently. It begins to highlight my unused cpp variables.
I tried setting
let g:syntastic_quite_messages = {"level": "warnings", "type": "style"}

but with no success.

**Comment by raffylopez** [comment]
If you're using a recent version of YCM (which doesn't use syntastic, as mentioned, and has its own diagnostics ui), you may want to go to your .ycm_extra_conf.py file, and disable the '-Wall' compiler option. This should disable warnings for unused variables.
