### ISSUE TITLE
Explicitly setting g:syntastic_python_python_exe results in abnormal status 1

### ISSUE THREAD

**Issue by miham** [scrooloose/syntastic#943]
If I explicitly set python checker executable (needed for python 3 support, but for the purpose of this bug report I stuck with default python):

```
let g:syntastic_python_checkers = ['python']
let g:syntastic_python_python_exe = 'python'
```

and then save a Python file containing `printa 'foo'` (notice the extra a after print), I get the following output (if g:syntastic_debug=0 I get only last line) and no sign is placed by the line with syntax error:

```
"test.py" 1L, 13C written
syntastic: 1.398878: &shell = '/bin/bash', &shellcmdflag = '-c', &shellxquote = '', &shellredir = '>%s 2>&1', &shellslash = 0
syntastic: 1.399064: g:syntastic_aggregate_errors = 0
syntastic: 1.556888: CacheErrors: Invoking checker: python
syntastic: 1.557305: SyntasticMake: called with options: {'errorformat': '%E%f:%l:%c: %m', 'makeprg': 'python test.py', 'returns': [0]}
syntastic: error: checker python/python returned abnormal status 1
```

If I comment out line `let g:syntastic_python_python_exe = 'python'` from vimrc, it works as expected and the output is

```
"test.py" 1L, 13C
"test.py" 1L, 13C written
syntastic: 1.025945: &shell = '/bin/bash', &shellcmdflag = '-c', &shellxquote = '', &shellredir = '>%s 2>&1', &shellslash = 0
syntastic: 1.026125: g:syntastic_aggregate_errors = 0
syntastic: 1.184561: CacheErrors: Invoking checker: python
syntastic: 1.184971: SyntasticMake: called with options: {'errorformat': '%E%f:%l:%c: %m', 'makeprg': 'python /home/miha/Dropbox/dotfiles/.vim/bundle/syntastic/syntax_checkers/python/compile.py test
.py', 'returns': [0]}
syntastic: 1.206749: getLocList: checker python/python returned 0
```

The difference is in the SyntasticMake line and I guess that is the reason for this bug.

**Comment by alphaCTzo7G** [comment]
What is the difference between using "python" vs "pylint" vs "flake8" as a checker? Typically I see people use flake8. 

If I use python as a checker, does syntastic basically run the program through python and output the errors?

**Comment by lcd047** [comment]
> What is the difference between using "python" vs "pylint" vs "flake8" as a checker?

The `python` checker tries to compile the current file.  The `pylint` checker runs `pylint` against your file, while `flake8` runs `flake8` against your file.

> If I use python as a checker, does syntastic basically run the program through python and output the errors?

It runs [this script](https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/python/compile.py), and it shows you the errors if any.  It's just syntax checking with the current Python interpreter, nothing more, nothing less.
