### ISSUE TITLE
GHC-mod

### ISSUE THREAD

**Issue by zackp30** [scrooloose/syntastic#973]
GHC-mod doesn't seem to work, I get this:

```
syntastic: error: checker haskell/ghc_mod: can't parse version string (abnormal termination?)        
```

**Comment by sgnl** [comment]
Hi, I am learning haskell and I cam getting the error message

syntastic: error: checker haskell/ghc_mod: can't parse version string (abnormal termination?)

`ghc-mod --version` returns `ghc-mod version 5.2.1.2 compiled by GHC 7.8.3`
`:echo split(system('ghc-mod'), '\n')` returns `[ghc-mod: No command given (try --help)]`
`:echo filter(split(system('ghc-mod'), '\n'), 'v:val =~# ''\m^ghc-mod version''')` returns `[]`
`:echo system('ghc-mod')` returns `ghc-mod: No command given (try --help)`

After I tried the series on commands.

`:echo &shell` returned nothing at all so i set my shell with `set shell=/bin/sh`
`:echo &shellcmdflag` returned `-c`
`:echo &shellquote` returned nothing at all
`:echo &shellxquote` returned nothing at all
`:echo &shellredir` returned `>%s 2>&1`
`:echo &shellslash` returned `0`
