### ISSUE TITLE
JSCS Syntax Checker

### ISSUE THREAD

**Issue by dejanr** [scrooloose/syntastic#974]
I am gettings this, when i have jscs configured and i open files inside project i dont have .jscs.conf configured. It should be silent, like jshint is working.

![pgb85h3xmv-3000x3000](https://f.cloud.github.com/assets/18490/2050347/78d168f2-8a72-11e3-9e3d-e26c8bb16377.png)

**Comment by kennykaye** [comment]
@dejanr This is a stop-gap solution I cobbled together:

```vim
" jscs returns exit code when no config file is present.
" only load it when appropriate
function JavascriptCheckers()
  if filereadable(getcwd() . '/.jscsrc')
    return ['jshint', 'jscs']
  else
    return ['jshint']
  endif
endfunction
```
```vim
let g:syntastic_javascript_checkers=JavascriptCheckers()
```

**Comment by lcd047** [comment]
Or just put a default `.jscsrc` in your home directory for JSCS to fallback to (assuming, of course, that your projects live in a subdirectory of your `$HOME`).  According to the [JSCS docs](http://jscs.info/overview.html):

> If there is no `--config` option specified, `jscs` it will consequentially search for `jscsConfig` option in  `package.json` file then for `.jscsrc` (which is a just JSON with comments) and `.jscs.json` files in the current working directory then in nearest ancestor until it hits the system root.

**Comment by dejanr** [comment]
thanks @kennykaye i had something similar in mean while. As of recently i dont use jshint and jscs anymore, i moved to eslint. Not sure if this behavior still occurs.

But i think default lint behavior should be:

- check local env file -> lint file if config found
- check global env file -> lint file if config found
- ignore linting when config not found found

And this is what @lcd047 is referring to, but i think it didn't worked for me as expected.

**Comment by lcd047** [comment]
It didn't work for you as expected by you.  It did work as expected by the authors of JSCS. :)

Perhaps you guys could redirect a fraction of the energy you invest in coming up with ideas for workarounds in syntastic towards actually fixing the problem at the source, in this case in JSCS?  Just a thought.

**Comment by dejanr** [comment]
jscs works fine, if you try and run jscs outside of vim, it works as expected.

The error is being thrown in this plugin, and the plugin is not working properly.

But good luck with it @lcd047, the way you do hostile handling :bomb:

**Comment by lcd047** [comment]
@dejanr If you can show a case where jscs works outside Vim but not when called from syntastic, please file a bug report.  Also, it would be great if you could do that while refraining from name calling, thank you. :)

**Comment by coolaj86** [comment]
@kennykaye Thanks for the example. I extended it to check parent directories:

https://coolaj86.com/articles/jscs-jscsrc-vim-syntastic-and-you/

```
function! JavascriptLinter(curpath)
  let parent=1
  let local_path=a:curpath
  let local_jscs=local_path . '.jscsrc'

  while parent <= 255
    let parent = parent + 1
    let local_path = local_path . "../"
    let local_jscs = local_path . '.jscsrc'
    if filereadable(local_jscs)
      return ['jscs']
    endif
  endwhile

  unlet parent local_jscs

  return ['jshint']
endfunction
let g:syntastic_javascript_checkers=JavascriptLinter(getcwd() . "/")
```

If there's a newer, better way to do this, I'd love to know about it.

**Comment by lcd047** [comment]
> If there's a newer, better way to do this, I'd love to know about it.

If you insist doing it this way: yes, there is (although, given the above exchange, you'll probably hate to hear that from me) :
```vim
autocmd FileType javascript let b:syntastic_checkers = findfile('.jscsrc', '.;') != '' ? ['jscs'] : ['jshint']
```
This actually works even when you switch projects from inside Vim.
