### ISSUE TITLE
location list filtering

### ISSUE THREAD

**Issue by amigrave** [scrooloose/syntastic#977]
Hi folks,

I'm using latest macvim with latest syntastic. I'd like to always see the errors AND warnings signs on the left bar but I'd like to put an extra focus on errors by allowing the location-list to automatically open on errors. Problems is that if I use `syntastic_auto_loc_list = 1`, the location list will open on errors, warnings, style errors and style warnings while I want this to happen only on errors.

Is this actually possible ?

**Comment by jf87** [comment]
Is this still the not possible? I would like to achieve exactly the same as @amigrave 
Cheers!

**Comment by lcd047** [comment]
@jf87 No, it still isn't possible.  Syntastic has a number of notification mechanisms, and all these mechanisms use the same list of issues.  There is no plan to change this in the foreseeable future.

**Comment by jf87** [comment]
Ok, no problem. Thanks for the quick reply and for the great work :-)
