### ISSUE TITLE
scss_lint not working

### ISSUE THREAD

**Issue by medihack** [scrooloose/syntastic#988]
I disabled the `scss` checker and enabled the `scss_lint` checker (by using `let g:syntastic_scss_checkers = ['scss_lint']` in my .vimrc) as the `scss` checker shows errors when using `@import`  in a Rails app, cause of the sprocket pipeline.
Unfortunately `scss_lint` does not work in vim (nothing is checked). `scss-lint` works correctly when called from the command line.

**Comment by maximeparisse** [comment]
I'm pretty new into vim and even linuxm sorry if i miss something really simple but i can't manage to make scss_lint works with syntastic.

I installed the latest scss_lint gem and add in my .vimrc
`let g:syntastic_scss_checkers = ['scss_lint']`

But when i open an .scss file i get :
`syntastic: warning: checker scss/scss_lint: unrecognized error format`

When i do an `:SyntasticInfo` i get :
```
Syntastic version: 3.7.0-137 (Vim 704, Linux)
Info for filetype: scss
Global mode: active
Filetype scss is active
The current file will be checked automatically
Available checkers: sass scss_lint
Currently enabled checker: scss_lint
```

Can you guide me how i can make it works ?
