### ISSUE TITLE
Currently enabled checkers emptied when relevant filetype is detected

### ISSUE THREAD

**Issue by waiting-for-dev** [scrooloose/syntastic#989]
I have a fresh new Synastic installation, pointing to current master branch (commit c10aa8d6d54d23b). I'm using VIM 7.4.169 on Debian 3.2.54-2 x86_64 GNU/Linux.

In my .vimrc I have following syntastic configuration:

    let g:syntastic_mode_map = { 'mode': 'active',
             \ 'active_filetypes': ['php', 'ruby'], }

If I open a blank file and I do `:SyntasticInfo php` I get:

    Syntastic: active mode enabled
    Syntastic info for filetype: php
    Available checker(s): php phpcs
    Currently enabled checker(s): php phpcs

And if I run `:SyntasticInfo ruby` I get:

    Syntastic: active mode enabled
    Syntastic info for filetype: ruby
    Available checker(s): mri rubocop
    Currently enabled checker(s): mri

Great. Everything as expected.

If now I open a php file and run again `:SyntasticInfo php`, I get empty enabled checkers:

    Syntastic: active mode enabled
    Syntastic info for filetype: php
    Available checker(s): php phpcs
    Currently enabled checker(s):

If in the same php file I run `:SyntasticInfo ruby` everything is correct:

    Syntastic: active mode enabled
    Syntastic info for filetype: ruby
    Available checker(s): mri rubocop
    Currently enabled checker(s): mri

It is the same case for a ruby file with `:SyntasticInfo ruby`

    Syntastic: active mode enabled
    Syntastic info for filetype: ruby
    Available checker(s): mri rubocop
    Currently enabled checker(s):

and `:SyntasticInfo php`:

    Syntastic: active mode enabled
    Syntastic info for filetype: php
    Available checker(s): php phpcs
    Currently enabled checker(s): php phpcs

It seems that when the relevant filetype is detected, enabled ckeckers for that filetype are emptied. Once that enabled checkers for a filetype are emtied, they persist for others buffers that are open in the same session, even if they have another filetype.

The, doing `SyntasticCheck` does nothing...

However, Syntastic works, for example, in a javascript file without problems...

I have disabled all other plugins and the error doesn't disappear.

**Comment by lcd047** [comment]
This is well understood now: Eclim messes with syntastic variables.  As of 7b67345, syntastic tries to detect this and add a warning when running `:SyntasticInfo`.
